### ISSUE TITLE
Problem With Filtered Reads DADA2

### ISSUE THREAD

**Issue by enriqueza** [benjjneb/dada2#1013]
Hello, I am following the DADA2 tutorial to filter and trim my reads from some bacterial sequences. My advisor had originally used a tool called " trim-omatic" to trim the reads, and I put in what I thought would be good parameters for the filtering, however, afterwards I found that almost half the length was filtered out. 

 <out_1 <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(290, 250), maxN=0,  maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)>

This is the code I had used from the tutorial. I was wondering if there might be some better settings for me to use with the truncLen and/or maxEE and trunQ so that it doesn't cut out as much? I saw that there was a software that helps you figure out the best settings, but I am working with a pc and not a mac so I am using docker toolbox and not docker and am not sure if it would work. If you have any suggestions, I would appreciate it. Thank you!

**Comment by benjjneb** [comment]
It is generally not recommended to pre-filter the reads with other software, especially software that is creating length variation.

As is shown in the tutorial, you will want to pick your `truncLen` parameters based on the quality profile plots and the length of your sequenced amplicon. You want to cut off low quality read tails, while retaining enough sequence length so that the reads still overlap enough to be merged.

If your primers were sequenced, you can use `trimLeft=c(FWD_PRIM_LEN, REV_PRIM_LEN)` to remove them. Otherwise, don't use `trimLeft`.
