### ISSUE TITLE
dada and removeBimeraDenovo pooled mode, DADA2 1.14

### ISSUE THREAD

**Issue by mcamarareis** [benjjneb/dada2#1042]
Hi Ben,

First thank you for making available this great tool.

I've used DADA2 1.14 to denoise my microbiome data (V4-V5 regions of 16S rRNA).
I've used dada pooled mode (I saw that it improved detection of rare ASVs) but for chimera detection I kept the removeBimeraDenovo "consensus" mode.
After reading more about it, it seems that it would have been better to use "pooled" mode for the chimera detection also (I still have to test it though), but I only found old discussions about the topic.
I would like to know if this is still valid for the newer versions of dada2 that we should use pooled mode for both denoising and chimera detection?
If so, maybe something to consider would be to add a remark at the tutorial to remind inexperienced users (like me) to take this in account when using pooled mode?

Thank you in advance.

**Comment by benjjneb** [comment]
Yes, it is still the case that if you did pooled denoising, you should also do pooled chimera removal.

**Comment by and3k** [comment]
It would also be helpful to mention this here https://f1000research.com/articles/5-1492. In the article dada is used in pooled mode, but removeBimeraDenovo isn’t.

**Comment by mcamarareis** [comment]
Hi Ben,

Thank you for your answer.

I'm coming back with some results of the comparison that I did.
As I mentioned, I've compared dada default and pooled mode before choosing which one to use to analyze my data. Like in this document (https://benjjneb.github.io/dada2/pool.html) I've used the default chimera removal for both.

This in green is what I obtained for number of ASVs and reads.
![image](https://user-images.githubusercontent.com/54186891/85148622-a4c93900-b250-11ea-98e8-2baf6f9cf0e6.png)

I obtained about 2X more ASVs using dada pooled.

After your answer, I tested dada and chimera removal pooled, and I found actually less ASVs than using the default dada and chimera.

I was wondering if you already had similar results when doing this kind of comparison. 
Based in what I've read, I was expecting to have more ASVs using pooled mode (even tough I knew that I could detect more chimeras).
The primers were already removed and I didn't have major loss of reads in any step of the pipeline.

Thank you very much.

**Comment by mcamarareis** [comment]
> Yes, it is still the case that if you did pooled denoising, you should also do pooled chimera removal.

**Comment by mcamarareis** [comment]
I've closed the issue by mistake, I reopened to follow the discussion.

**Comment by benjjneb** [comment]
In short, the results you present here are not surprising to me. 

Longer form: Pooled denoising is better at picking up rare study-wide ASVs, especially those that appear in a few samples at like 1 read each. Chimeras very often show up with exactly this abundance-prevalence pattern, i.e. very low abundance per-sample but often in multiple samples. Pooled chimera removal is better at identifying and removing exactly those sorts of rare chimeras. In a big picture sense, this is because there is a conceptual match between the denoising and the chimera removal, both are operating on the study as a whole. When denoising is pooled but chimera removal is consensus (which operates on a per-sample basis, then makes a consensus "vote" across samples to flag and remove chimeras), chimeras that might clearly be flagged in the whole study pooled can not be flagged because in a sample or two their putative "parents" weren't high enough abundance to call that ASV a chimera in that sample.

On a raw # of ASVs/reads level, this means that pooled chimera removal acting on pooled-denoised samples will remove significantly more ASVs, but not that many more reads, which is what you are seeing. This basic idea is also consistent with the similarity between the default-both and pooled-both total ASV numbers. Default-both tends to just not identify those rare chimeras described above, while pooled-both detects and removes them, so they numbers end up similar.

> Based in what I've read, I was expecting to have more ASVs using pooled mode (even tough I knew that I could detect more chimeras).

Usually I do see more ASVs in pooled/pooled mode, but often that difference is small, at least in the human microbiome type samples I've explored this way. So maybe the direction you are seeing isn't what I would have guessed, but the similarity isn't surprising to me. The one thing you may want to consider is using a higher `minFoldParentOverAbundance` threshold for the pooled chimera removal. This modulates how much more abundant the putative "parents" of a chimera should be then the chimera itself, and the default value is tuned for the default methods. There is some support in a preprint by Robert Edgar that the value should be higher for pooled chimera remova, maybe like `8`. See the "chimera filtering" section here: https://www.biorxiv.org/content/10.1101/081257v1.full

**Comment by mcamarareis** [comment]
"Default-both tends to just not identify those rare chimeras described above, while pooled-both detects and removes them, so they numbers end up similar."

It's interesting that the total number of ASVs is similar, but the number of ASVs per sample seems to increase anyway in pooled/pooled mode (specially in the samples on the right, which are environmental). I think that could be related to the fact that non-chimeric ASVs that appeared in only one sample are now identified in more samples, does it make sense? I say that because the number of singletons also decreased between default mode (291) and pooled/pooled mode (90).

[200621_comparing_modes.pdf](https://github.com/benjjneb/dada2/files/4831138/200621_comparing_modes.pdf)

About minFoldParentOverAbundance. If I understood correctly, this parameter should be increased to allow more ASVs passing the chimera removal because they are probably false positives? 

Thank you for all the clear explanations.

**Comment by benjjneb** [comment]
> About minFoldParentOverAbundance. If I understood correctly, this parameter should be increased to allow more ASVs passing the chimera removal because they are probably false positives?

"false positives" in the sense of potentially being incorrectly flagged as chimeras. And yes, especially in pooled mode it might make sense to increase the parameter for that reason.

**Comment by mcamarareis** [comment]
> "false positives" in the sense of potentially being incorrectly flagged as chimeras. And yes, especially in pooled mode it might make sense to increase the parameter for that reason.

Yes, that's what I meant. Indeed I had some more ASVs remaining after chimera removal (142) by using  minFoldParentOverAbundance = 8. By curiosity I've checked these ASVs using Decipher chimera detection and 71 were flagged as chimeric, but they are mainly low abundance ASVs. From those that are not chimeric, I had some assigned to quite important bacterial groups. So it seems to make sense to keep these results and apply abundance filter to remove these possibly chimeric ones.

Thank you very much for you patience.

**Comment by pdhrati02** [comment]
@benjjneb 
Hi, I have been reading about the minFoldParentOverAbundance parameter and based on your comments I do understand that using minFoldParentOverAbundance = 8 is a good and safe option. Usin this also helped me to reduce loss as chimeras. However my question is how do we decide if we need to increase this number further?
In my case, I had 3 separate runs which I processed and then merged their seqtabs and then performed chirmera removal. 

The results are as follows:
st.all <-  mergeSequenceTables(st1, st2, st3)
> dim(st.all)
[1]   208 38666

seqtab <- removeBimeraDenovo(st.all, method="consensus", multithread=TRUE)
> dim(seqtab)
[1]  208 5243
> seqtab_8 <- removeBimeraDenovo(st.all, method="consensus",minFoldParentOverAbundance=8, multithread=TRUE)
> dim(seqtab_8)
[1]  208 8833
> sum(seqtab_8)/sum(st.all)
[1] 0.9596458
> seqtab_16 <- removeBimeraDenovo(st.all, method="consensus",minFoldParentOverAbundance=16, multithread=TRUE)
> dim(seqtab_16)
[1]   208 11447
> sum(seqtab_16)/sum(st.all)
[1] 0.9607661

Thank you in advance
Best
DP

**Comment by benjjneb** [comment]
It looks like there is relatively little difference at the total reads level between 8 and 16, so I would be comfortable just going ahead with 8.

**Comment by pdhrati02** [comment]
Thank you very much for your quick response.
