### ISSUE TITLE
better handle "Invalid derep$uniques vector. Names must be sequences made up only of A/C/G/T."

### ISSUE THREAD

**Issue by elsherbini** [benjjneb/dada2#106]
I'm running into an issue where the `dada` function complains about the derepped sequences.

This could be a bug: I haven't found an example of a sequence containing a non ACGT character in any of the files. 

But even if there is such a sequence, it'd be nice to handle this better, maybe by chucking it out with a warning rather than failing. In my case, it failed after doing inference successfully on the forward reads, which took over 24 hours since I had pooled the samples.

Here is an example that shows the issue:

```
filtRs <- readRDS("debug_filtRs.rds")
sample.names <- readRDS("./debug_samples.rds")
derepRs <- derepFastq(filtRs, verbose=TRUE)
names(derepRs) <- sample.names
dadaRs <- dada(derepRs, err=NULL, selfConsist=TRUE) # throws error

filtFs <- readRDS("debug_filtFs.rds")
derepFs <- derepFastq(filtFs, verbose=TRUE)
names(derepFs) <- sample.names
dadaFs <- dada(derepFs, err=NULL, selfConsist=TRUE) # works
```

[folder containing necessary files](https://drive.google.com/open?id=0B8zpZcbxw7kdRGVFNlEwRGRXZjQ)

**Comment by benjjneb** [comment]
Q: Did you perform any filtering of these sequences you are processing?

**Comment by elsherbini** [comment]
Yes, 3 filtering steps:
1. I trimmed the primer, and any sequence that didn't match the primer was thrown out
2. I trimmed low quality tails, basically from the end of the read chucking out continuous sequence that had a quality of less than 5
3. I trimmed all the reads to be 110 bases long, and threw out reads that were shorter than that.

But I guess this means it's possible that crappy reads are still present, if they happened to have at least one higher quality position (>6)  further than 110 bases into the read.

**Comment by benjjneb** [comment]
The issue will probably be solved if you use the dada2 filtering function (`fastqPairedFilter`).

The DADA2 pipeline currently requires three things that aren't always enforced by other filtering protocols, no Ns, global trimming to the same length, and matched ordering between the filtered forward and reverse reads. `fastqPairedFilter` takes care of all those requirements.

While just culling sequences with Ns might solve the specific error you are seeing now, if the forward/reverse files were filtered independently then the later `mergePairs` step will break.

Also, and because this happens to me as well, I recommend saving your progress after major chunks of your workflow. This is easy to add to your scripts:

```{r}
saveRDS(dadaFs, "path/to/dadaFs.rds")
```

You can read it back in later  via:

```{r}
dadaFs <- readRDS("path/to/dadaFs.rds")
```

**Comment by elsherbini** [comment]
I was also "intersecting" the forward and reverse reads, so all the reads were match ordered, and any without a pair were thrown out, so the mergePairs step should have been fine. 

Ok, I'll try using the fastqPairedFilter function on my already filtered data, just to see if it resolved the issue. But I think I've met all the requirements (I cant find any Ns or other non ACGT characters, I have match ordered sequences, and I truncated sequences to all the same length).

**Comment by benjjneb** [comment]
Just took a look at your data. These 3 reverse files have reads with Ns in them:

`t28.5_11Ba.r.fq`, `t4.5_7-c.r.fq`, `t4.5_7Pb.r.fq`

If you clean that up, and you enforced the ordering and did truncation as you described, you should be good to go even w/o using `fastqPairedFilter`. Prob easiest to just use it though.

**Comment by elsherbini** [comment]
I appreciate you taking a look. Not sure why my regex didn't catch them.

**Comment by lebetimonas** [comment]
I'm experiencing the same problem, except that I get the error for my forward reads, rather than the reverse reads. AND I am using fastqPairedFilter with the default settings. I've used dada2 for several different projects and this is the first time I've encountered this error. I can't find any Ns in my sequences---I used fastqc on both my original reads and the filtered reads and see no Ns. Any idea what's wrong with the F reads?

path <- "~/Documents/LKL_amplicons/paired_reads"
fns<- list.files(path)
fns
fastqs <- fns[grepl(".fastq$", fns)]
fastqs <- sort(fastqs)
fnFs <-fastqs[grepl("_R1",fastqs)]
fnRs <-fastqs[grepl("_R2",fastqs)]
sample.names <- sapply(strsplit(fnFs, "_"), '[',1)
fnFs <- file.path(path,fnFs)
fnRs <- file.path(path,fnRs)
plotQualityProfile(fnFs[[1]])
plotQualityProfile(fnRs[[1]])

filt_path <- file.path(path, "filtered")
if(!file_test("-d", filt_path)) dir.create(filt_path)
filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))
# Filter
for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    maxN=0, maxEE=c(2,5), truncQ=2, rm.phix=TRUE,
                    compress=TRUE, verbose=TRUE)
}


derepFs <- derepFastq(fnFs, verbose=TRUE)
derepRs <- derepFastq(fnRs, verbose=TRUE)
# Name the derep-class objects by the sample names
names(derepFs) <- sample.names
names(derepRs) <- sample.names
derepFs[[1]]
dadaFs <- dada(derepFs, err=NULL, selfConsist = TRUE)
**Error in dada(derepFs, err = NULL, selfConsist = TRUE) : 
  Invalid derep$uniques vector. Names must be sequences made up only of A/C/G/T.**


[paired_reads.zip](https://github.com/benjjneb/dada2/files/1253241/paired_reads.zip)

**Comment by benjjneb** [comment]
You've got a small bug in the script that is probably resposnsible:

```
derepFs <- derepFastq(fnFs, verbose=TRUE)
derepRs <- derepFastq(fnRs, verbose=TRUE)
```

You've read in the unfiltered files (i.e. `fnFs` instaed of `filtFs`) which presumably still have some Ns in them.

Also, this command might work better for the sample.names: `sample.names <- sapply(strsplit(basename(fnFs), "_"), '[',1)`

**Comment by lebetimonas** [comment]
Thanks! That fixed it. It certainly helps to use the filtered samples!

**Comment by nick-youngblut** [comment]
>You've read in the unfiltered files (i.e. fnFs instaed of filtFs) which presumably still have some Ns in them.

Processing the standard Mother MiSeq_SOP reads will generate this error, if the user doesn't want to filter/trim the reads prior to running `learnErrors()`. It would be helpful to include this warning in the tutorial.

**Comment by benjjneb** [comment]
@nick-youngblut The error message is reasonably informative "Invalid derep$uniques vector. Sequences must be made up only of A/C/G/T." That seems good enough to me combined with the text in the tutorial, e.g. "DADA2 requires no Ns" in the filtering and trimming section?

**Comment by nick-youngblut** [comment]
I didn't see the text in the tutorial. My bad
