### ISSUE TITLE
makeSequenceTable did not properly assign dimnames in one sample case

### ISSUE THREAD

**Issue by ETaSky** [benjjneb/dada2#1068]
Hello,
I am reporting that makeSequenceTable does not put the sample name in its output if there is only one sample.
For example, I have a zymo mock community that is sequenced from one run that is different from my other samples, so I have to analyze this sample separately. It works fine up until, I try to merge the seqtab of the zymo sample with my other samples. The reason is below:
```
> seqtab_zymo <- makeSequenceTable(mergers_zymo)
> str(seqtab_zymo)
int [1, 1:761] 4048 3427 3320 3177 2733 2716 2580 1497 416 387 ...
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : chr [1:761] "TAGGGAATCTTCCGCAATGGGCGAAAGCCTGACGGAGCAACGCCGCGTGAGTGATGAAGGTCTTCGGATCGTAAAACTCTGTTATTAGGGAAGAACATATGTGTAAGTAAC"| __truncated__ "TAGGGAATCTTCCGCAATGGACGAAAGTCTGACGGAGCAACGCCGCGTGAGTGATGAAGGTTTTCGGATCGTAAAGCTCTGTTGTTAGGGAAGAACAAGTACCGTTCGAAT"| __truncated__ "TAGGGAATCTTCCACAATGGGCGCAAGCCTGATGGAGCAACACCGCGTGAGTGAAGAAGGGTTTCGGCTCGTAAAGCTCTGTTGTTAAAGAAGAACACGTATGAGAGTAAC"| __truncated__ "TGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAAGGTGTTGTGGTTAATA"| __truncated__ ...

# the following step would fail
> seqtab_v3v4 <- mergeSequenceTables(seqtab_jw, seqtab_zymo)
Error in mergeSequenceTables(seqtab_jw, seqtab_zymo) : 
  Some sequence tables found invalid
In addition: Warning message:
In FUN(X[[i]], ...) : Row (sample) names are missing.
```
It looks like the sample name is missing from `attr(seqtab_zymo, "dimnames")[[1]]`. A workaround is to manually give it the name, e.g. `attr(seqtab_zymo, "dimnames")[[1]] <- "Zymo_F_filt.fastq.gz"` then it works fine.

```
> attr(seqtab_zymo, "dimnames")[[1]] <- "Zymo_F_filt.fastq.gz"
> seqtab_v3v4 <- mergeSequenceTables(seqtab_jw, seqtab_zymo)
```

**Comment by benjjneb** [comment]
Can you inspect the names of the previous 1-sample objects to see if they have the sample names?

`names(mergers_zymo)` and `names(dadaFs_zymo)` (or whatever the correct variable name is there).

**Comment by ETaSky** [comment]
@benjjneb Sorry for the oversight, I thought I did. No, the dada output is a single dada class, not a list, so does not have the name, and the mergePairs output is a data.frame, and therefore does not have the name either.

**Comment by benjjneb** [comment]
Unfortunately this is an annoying behavior, but it's not likely to get fixed in the near future.

`makeSequenceTable` just propagates names from the previous objects. When processing multiple samples, the `dadaFs` or `mergers` objects are lists with an entry for each sample, with the sample name as the corresponding name in the list. When its a single sample, there is no list, its just the base `dada-class` or `data.frame` object, and thus has no sample name attached.

This is actually a pretty normal R behavior, returning different objects when a single argument is processed versus a vector of arguments. But it's an annoying one that creates these sorts of single-sample edge cases.

**Comment by ETaSky** [comment]
Thanks. This is not a big deal and the workaround seems simple enough. People just need to be aware and pay attention to it.
