### ISSUE TITLE
learnErrors issue: kmer size of input sequence not large enough

### ISSUE THREAD

**Issue by prasm** [benjjneb/dada2#1073]
Hello, 
I'm using the DADA2 tutorial for processing 16S amplicon data. After removing the synthetic sequences from the samples (primers, adaptors, barcodes etc.), I tried to find the error rates of the samples but keep running into this error:

Error in dada_uniques(names(drpi$uniques), unname(drpi$uniques), names(drpi$uniques) %in%  : 
  Input sequences must all be longer than the kmer-size (5).

This is the order in which I removed the synthetic sequences: Filtered for N -> Primers -> Adaptors -> Pad and linker -> Barcodes
I am only able to find the error rates for the N filtered samples; for the primer removed samples onward, the error appears. The barcode removed samples retain about 85% of the original samples. 
I'm not sure how to move past this error, and would appreciate any help with this issue.

**Comment by benjjneb** [comment]
Are you using an external program to remove the synthetic sequences?
This is probably resulting in some sequences being too short to be processed, perhaps because they also do default quality filtering (which you should turn off if you can).

You can add a final `filterAndTrim` step a the end to clear those out. By default it will remove any sequences <20 nts. You should also consider truncating to a fixed length and doing quality filtering in `filterAndTrim` as well.
