### ISSUE TITLE
Combining ASV and Taxonomy tables

### ISSUE THREAD

**Issue by hpremathilake** [benjjneb/dada2#1076]
Hi,
I have a large dataset to analyze. I'm thinking of breaking it down into segments, analyze it, and later combine the ASV and Taxonomy tables (from the different analysis attempts into a single large ASV and Taxomonoy table), since I'm trying to do the analysis on my PC until I get my HPCC account setup. 

Hence, I want to know whether this method is technically correct? 

Thank you.
Best,
Hasitha.

**Comment by benjjneb** [comment]
Yes you can do that.

In an ideal world you perform chimera removal and taxonomy assignment on the whole dataset together to avoid any stochastic differences between chunks though. You might be surprised on what you can run on your laptop. But yes there will be datasets that get too big for that on a laptop.

**Comment by hpremathilake** [comment]
Thank you for the prompt response, Benjamin.
Attached are the error plots generated for the data. Do you think the predicted and actual error rates overlap enough?
I have seen better fitting graphs in my previous analyses. Hence, thought of getting your opinion on this.
 
[F_errors.pdf](https://github.com/benjjneb/dada2/files/4927723/F_errors.pdf)
[R_errors.pdf](https://github.com/benjjneb/dada2/files/4927724/R_errors.pdf)

**Comment by benjjneb** [comment]
It's probably fine. These error model behavior is being seen when the underlying sequencing data is using "binned" quality scores. It's not ideal, but is unlikely to affect results much since very few quality scores occur in that dip in the error model (they are outside the binned values).

More discussion of this here, and a suggested fix to enforce monotonicity as well: https://github.com/benjjneb/dada2/issues/791
