### ISSUE TITLE
QIIME and DADA pipelines result in different presence percentages of OTUs/ASVs across samples

### ISSUE THREAD

**Issue by mvelg** [benjjneb/dada2#1077]
We have performed a comparison of different 16S sequences processing pipelines using your R package DADA2 and software QIIME on two datasets. We have processed both datasets with four different pipelines briefly described below:

 

QIIME - UCLUST open-reference OTU picking.
DADA2 - global denoising and VSEARCH open-reference picking.
DADA2 - denoising by plate and VSEARCH open-reference picking.
DADA2 - no denoising (no dada) and VSEARCH open-reference picking.
 
We have observed that the tables obtained with the different pipelines are completely different and it has an impact on different subsequent statistical analyses. In the attached images you can see how pipelines resulted in different presence percentages of OTUs/ASVs across samples in both datasets (attached images).

![PigDataset97clustering](https://user-images.githubusercontent.com/68416846/87758466-ccd69880-c80c-11ea-9775-bec3849c906c.png)
![RabbitDataset97clustering](https://user-images.githubusercontent.com/68416846/87758469-cd6f2f00-c80c-11ea-9f1c-dfeb646a11e2.png)
![RabbitDataset99clustering](https://user-images.githubusercontent.com/68416846/87758473-ce07c580-c80c-11ea-8b55-73e0ecd36347.png)

QIIME and DADA2 pipelines lead to completely different tables regarding the distribution of OTUs/ASVs presence across samples in both datasets. While most OTUs obtained with QIIME pipeline are present in all samples, most OTUs obtained with DADA2 denoising pipelines are only present in approximately 10% of the samples. These important differences in OTU distributions have strong consequences on latter classification and prediction results.

 
Do you have any thoughts on why are we obtaining such different final tables regarding the sequences distribution across samples in both datasets?

**Comment by and3k** [comment]
Hi!

Not a DADA2 author, but I am also curious about these results :)

A few comments:

1. I am generally not surprised that OTU and ASV numbers differ between the methods. We observe this all the time, but a lot of the differences are with the rare OTUs/ASVs
1. did you use UCLUST or UPARSE? UCLUST is _not_ suitable for OTU generation: https://drive5.com/usearch/manual/uclust_algo.html
1. did you run DADA2 in pooled mode or not?
1. you talk about OTUs and VSEARCH open-reference picking in regards to DADA2, which makes no sense to me 😅 could you maybe explain more about the methods?
1. could you show the results from the "latter classification and prediction"?
1. have you also tried some of the really robust CODA methods for analysing your count tables, like, e.g. http://mixomics.org/mixmc/

Thank you! :)

**Comment by mvelg** [comment]
Hi :)

1. I agree. Neither are we surprised that the number of OTU and ASV differ between methods, but we are concerned about the distribution of OTUs/ASVs presence/frecuency across samples in both datasets. With QIIME pipeline we observed that most OTUs obtained are present in all samples. However, most OTUs obtained with DADA2 denoising pipelines are only present in approximately 10% of the samples (higher sparsity). We have observed that in both datasets analyzed.

2. In the QIIME pipeline we followed the clustering strategy pick_open_reference_otus.py with UCLUST algorithm. Do you recommend USEARCH or VSEARCH instead UCLUST?

3. We didn’t run the pooled mode.

4. Yes. When I talk about that regarding DADA2 I mean that the 100% ASV tables (with unique sequences) generated with DADA2 are in a second step clustered into 97% OTUs or 99% ASVs through QIIME2 plugin qiime vsearch cluster-features-open-reference.

5. Sure, I attach a PDF file with a largest summary of the pipelines compared and the subsequent analyses with the OTU/ASV tables generated by each pipeline.

6. In the attached summary you can see the analyses we have performed aiming to compare the different tables. For both datasets we have compared the total number of OTUs/ASVs obtained with different 16S processing pipelines, the presence percentages of OTUs/ASVs across samples, the total number of different genera (and how many sequences could be annotated at this level), some alpha diversity metrics and the microbial classification and prediction power of each table. Some of the analyses were indeed done with mixomics. 


Thank you for your comments!
[PipelinesComparison_Summary_GitHub.pdf](https://github.com/benjjneb/dada2/files/4937943/PipelinesComparison_Summary_GitHub.pdf)

**Comment by benjjneb** [comment]
The figures are very small/low-res thus difficult to read.

I think the comparison you want to focus on is the usearch vs. vsearch comparison in which no DADA2-denoising is performed. It is better to have fewer moving parts in these comparisons, and this qualitative difference in prevalance patterns you are observing seems to exist in the usearch vs. vsearch results.

So then, why would that be? Looking at your pipelines comparison, it seems that you performed filtering and trimming differently between the QIIME1 pipeline and the "DADA2" pipeline.  What I'd try first is to use the same filtering/trimming on each, and see if that leads to results looking similar again.

A concern there is that if filtering/trimming is incorrect, perhaps because in the "DADA2" filtering the primers and sample barcode were not removed, then you can get this kind of effect, where OTUs are sample-specific because the primers/barcodes are being included in the sequences.

It would be also helpful to know what fractino of reads is passing through these steps.

Overall though: Try to isolate one difference between "pipelines" at a time to make progress. When there are multiple differences, it can be confusing to know which one is relevant.
