### ISSUE TITLE
Pooling Samples Results in decreased ASVs

### ISSUE THREAD

**Issue by jp589** [benjjneb/dada2#1081]
Hello,

I am doing analyses using DADA2 and I have come across a pattern. Namely, that with my datasets, the number of ASVs produced using the pseudopooled method is highest, followed by independent, and lastly pooled. I have seen this across multiple sample types and I am wondering if there is any reason this might be happening? I know that DADA2 pooling increases sensitivity to rare variants, but does pooling also increase DADA2's ability to recognize low prevalence ASVs in order to eliminate them? Have you ever seen the pooling method eliminate ASVs that were in pseudopooled or independently processed samples?

Thanks,

JP

**Comment by benjjneb** [comment]
Q1: Is this ASVs per-sample, or in the whole study?
Q2: Is this pre and/or post-chimera removal?
Q3: Are you (as recommended) using pooled chimera removal for the pooled denoised data?

**Comment by jp589** [comment]
1. I processed each sample type separately (using the same general parameters); however, each sample type had a different number of samples run together with a range of 8 samples per sample type up to 80 samples. I did not run all samples in the whole study at the same time.

For example, Sample type A run with DADA2 pooled analysis shows the least number of ASVs compared to Sample type A run with DADA2 pseudopooled or Sample type A independently analyzed.

After doing a bit of digging I noticed that on an ASV per sample basis (for the majority of samples), the pooled method does indeed produce more ASVs than pseudopooled or independent analyses. For sample type A, mean ASVs per sample with pseudopooled analysis was 36.6 whereas with pooled it was 41.5. When looking at all the samples within this sample type, there were 1750 ASVs pseudopooled and only 1300 pooled. 

Have you noticed this differential and could you speculate as to why it exists? It seems to me that some ASVs seen in pseudopooled results are being eliminated in the pooled analysis and that ASVs independently seen in one sample are noticed in others with a pooled analysis, leading to a higher prevalence. 

2. These results are post chimera removal. I also removed unclassified bacteria, chloroplast, and eukaryotic sequences, but their removal would not explain consistent differential between methods. For reference, Sample type A, which was the most complex sample type, had 1750 ASVs pseudopooled and only 1300 pooled. There were 26 sequences removed from the pooled results and 28 removed from the pseudopooled results.

3. Yes, my removeBimeraDenovo() function includes method="pooled".

**Comment by benjjneb** [comment]
> Have you noticed this differential and could you speculate as to why it exists? It seems to me that some ASVs seen in pseudopooled results are being eliminated in the pooled analysis and that ASVs independently seen in one sample are noticed in others with a pooled analysis, leading to a higher prevalence.

I think it likely is due to difference in chimera detection and removal more than the initial denoising. One quick test of that is the numbers of ASVs prior to chimera removal from each method.

There is also some discussion that the default value of `minFoldParentOverabundance=2` for pooled chimera removal is too stringent, and should instead be more like `8` or so. See Robert Edgards unoise2 preprint for more information on that.

**Comment by jp589** [comment]
I took a look at the differences in chimera removal when using a pooled method as opposed to a pseudopooled method. It does appear that the pooled method is able to detect and remove more chimeras, but the difference is usually around 1-2% of the total merged sequences. Chimera removal certainly is a factor, but perhaps not the entire reason for the difference since there is a 10-20% decrease in ASVs per sample type and a 10-20% increase in ASVs per sample when pooling vs. pseudopooling.

I took a look at the unoise2 preprint you pointed out. I understand the debate over how stringent chimera removal should be, but unless this minFoldParentOverabundance parameter is different for the pooled method than when using the pseudopooled method I'm not sure how it would be responsible for the differences I'm seeing.

Would the pooled method allow for a greater parent overabundance so that more chimeric sequences are flagged and removed?

**Comment by benjjneb** [comment]
> Would the pooled method allow for a greater parent overabundance so that more chimeric sequences are flagged and removed?

Because the pooled method is calling chimeras from the entire pool, rather than in each sample and then "voting" across samples, it is valid and probably preferable to set the parent overabundance higher. This is because the "voting" across samples also prevents against false-positive chimera assignments in the default method, while `minFoldParentOverabundance` is doing all the work in the pooled chimera removal method.

**Comment by jp589** [comment]
I believe I understand what's going on. 

So would you recommend that for pooled analysis the minFoldParentOverabundance parameter be set to 8? If not, what should it be?

**Comment by benjjneb** [comment]
> So would you recommend that for pooled analysis the minFoldParentOverabundance parameter be set to 8? If not, what should it be?

In very limited testing on my own part, and taking into account Robert Edgar's suggestions from his research, I think `minFoldParentOverabundance=8` is a reasonable setting for `pool=TRUE` inference on moderate-large datasets (dozens of samples or more from similar environs).

I'm hedging a bit because I haven't done the kind of rigorous evaluation across multiple systems that I think is necessary to make a formal recommendation.

**Comment by jp589** [comment]
I appreciate your advice. I will take that into account when proceeding with my analyses. I do have moderately large datasets so perhaps it is best to set that parameter to 8. 

My original question has certainly been answered. Thank you!
