### ISSUE TITLE
run ASV table through just chimera removal

### ISSUE THREAD

**Issue by annarizzibramucci** [benjjneb/dada2#1087]
I have used DADA2 to process my reads and I used:
seqtab.nochim.4 <- removeBimeraDenovo(seqtab, method="consensus", multithread=18, verbose=TRUE, minFoldParentOverAbundance=4);

Now I want to recheck the chimera step without having to rerun everything. So I was hoping I could read in my ASV tables for each plate, and just run 2 steps:
1) collapseNoMismatch 
AND
2) seqtab.nochim.1 <- removeBimeraDenovo(seqtab, method="consensus", multithread=18, verbose=TRUE, minFoldParentOverAbundance=1);

But I have tried several times to do this and it isn't working, somehow I can't get my ASV table into an acceptable format (even when I have it in wide format, with ASVs as the col names and sample code as the row names (just like your normal pipeline makes the seqtab file).

Do you have any suggestions of how I could achieve this?
thanks so much
Anna

**Comment by benjjneb** [comment]
Did you save your sequence tables as a file and then read them back into R?
If so, what was the code you used to do that?

**Comment by annarizzibramucci** [comment]
Hi Thanks for the reply (I am in Australia that is why there is a time delay on my end)

Initially when running dada2 I ran the following code:
`table(nchar(getSequences(seqtab)));
seqtab.nochim.4 <- removeBimeraDenovo(seqtab, method="consensus", multithread=18, verbose=TRUE, minFoldParentOverAbundance=4);
dim(seqtab.nochim.4);
sum(seqtab.nochim.4)/sum(seqtab);

sample <- rownames(seqtab.nochim.4);
sequence <- colnames(seqtab.nochim.4);

#check the col names and check how many ASVs that you are losing in the pipeline
colnames(seqtab.nochim.4);
#what % had chimera's vs non-chimeras?
sum(seqtab.nochim.4)/sum(seqtab);
#this is the %
sum(rev(sort(colSums(seqtab.nochim.4)))[1:1000])/sum(colSums(seqtab.nochim.4));

# Flip table
seqtab.t.4 <- as.data.frame(t(seqtab.nochim.4));
write.csv(seqtab.t.4, file = paste0(trunc_dir,"/",plates[p,1],".ASV.table.chim4.csv"), col.names=NA);
`

Now I want to be able to re-read in my ASV.table.chim4.csv for all of my plates (I have 61 different plates that have been run).
I could run the following steps either on the whole combined ASV table where I already combine those 61 plates or on each plate individually (the individual way might be faster on the HPC).

##Here I am trying to read in just only plate by name, p3ASV.csv
`
p3ASV <-read_csv('p3ASV.csv')
p3ASV_sub = subset(p3ASV, select = c(ASV, abund, code2))
p3ASV_table <- p3ASV_sub %>% spread(key='ASV', value='abund', fill=0)
p3ASV.mat <-as.matrix(p3ASV_table)
rownames(p3ASV.mat) <- p3ASV.mat[,1]
p3ASV.mat = subset(p3ASV.mat, select = -c(code2))
####everything above here works, and the file is in the same format as the seqtab is when running dada2....However nothing below works, even without the first step where I try to make the matrix into the seqtab using makeSequenceTable step...####

#seqtab <- makeSequenceTable(p3ASV.mat);
p3ASV.nochim.1 <- removeBimeraDenovo(p3ASV.mat, method="consensus", multithread=TRUE, verbose=TRUE, minFoldParentOverAbundance=1);
dim(seqtab.nochim.1);
sum(seqtab.nochim.1)/sum(seqtab);
`

**Comment by benjjneb** [comment]
What is the exact error message you are getting with `removeBimeraDenovo`?

Probably the sequence table is not in the exact same format as before, due to the round-trip of being written out to a csv file and then read back in. Possible issues could be extra cols or rows (e.g. are the rownames still in column 1 of the matrix?) or the type/storage.mode of the matrix (should be `is.numeric(st)==TRUE` and `storage.mode(st)=="integer"` respectively).

The best way to avoid these sorts of issues is to use `saveRDS`/`readRDS` instead to store these intermediate objects that are going back into R later anyway. That will get you back exactly the R object you stored, complete with all data types and stroage modes etc.

Presumable the above can be fixed though its just more complicated. But you'll want too inspect the class and storage.mode, as well as the matrix entries (e.g. unname(st[1:5, 1:5])) to try to figure out what the discrepancy is.

**Comment by annarizzibramucci** [comment]
The error is: "Error in isBimeraDenovoTable(unqs[[i]], ..., verbose = verbose) : 
  Input must be a valid sequence table."
`is.numeric(p3ASV.mat)==TRUE
storage.mode(p3ASV.mat)=="integer"`
gave both FALSE

**Comment by annarizzibramucci** [comment]
When I change it to as.numeric, then I get the following error: "Error in removeBimeraDenovo(p3ASV.mat, method = "consensus", multithread = TRUE,  : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns."

So it looks like you are correct, it is a storage mode issue...

**Comment by annarizzibramucci** [comment]
My table has ASV sequences as the col name and sampleID codes as the row names, and then abundances in the table.

**Comment by benjjneb** [comment]
`is.numeric(p3ASV.mat)` is `FALSE`?

Hm...

What is the output of the following (using `st` for shorthand...):

```
is(st)
typeof(st)
unname(st[1:3, 1:3])
```

**Comment by annarizzibramucci** [comment]
[,1] [,2] [,3]
[1,] "0"  "0"  "0" 
[2,] "0"  "0"  "0" 
[3,] "0"  "0"  "0"

**Comment by annarizzibramucci** [comment]
> is(p3ASV.mat)
[1] "matrix"           "array"            "mMatrix"          "structure"        "vector"          
[6] "vector_OR_factor" "vector_OR_Vector"
> typeof(p3ASV.mat)
[1] "character"
> unname(p3ASV.mat[1:3, 1:3])
     [,1] [,2] [,3]
[1,] "0"  "0"  "0" 
[2,] "0"  "0"  "0" 
[3,] "0"  "0"  "0"

**Comment by benjjneb** [comment]
Yeah so when it read in the data it got stored as character type, probably because the rownames/sequences were mixed in.

You may be able to fix this with the following:
```{r}
st.fix <- st
storage.mode(st.fix) <- "integer"
```

I might double check a few cells between st and st.fix to make sure they match up right, but I think that will both convert the character-stored numbers to integers and fix the storage.mode at the same time.

**Comment by annarizzibramucci** [comment]
Yes I think that worked! So then if I want to run collapseNoMismatch can I do so on this seqtab file?
Thanks so much for your help!

**Comment by benjjneb** [comment]
Yep, as long as its in the expected format (integer matrix with ASVs as colnames and samples as rownames) all the other functions that act on sequence tables should work appropriately.

**Comment by annarizzibramucci** [comment]
Hi again, this worked for one of DADA2 processed files without an issue, but one of the other files seems to be formatted very weird and I can't get it formatted properly to feed it back into DADA2...could I email you a small file so you can see what I am talking about?
cheers
Anna

**Comment by benjjneb** [comment]
Is it tabular data? If so you could probably post a snippet here.

**Comment by annarizzibramucci** [comment]
My data table is a csv. But I saved a small portion as a txt here. I think there is something wrong with the format of my actual dataframe out of dada2 which is why it is being so difficult to read it back into dada2 again...
Thanks for your help!
[dada2_asv1.txt](https://github.com/benjjneb/dada2/files/5046575/dada2_asv1.txt)

**Comment by benjjneb** [comment]
> I think there is something wrong with the format of my actual dataframe out of dada2 which is why it is being so difficult to read it back into dada2 again...

This is not the problem, the output of dada2 conforms to the data standard of the package.
Your issue is in the round-trip between outputting things as csv/tsv text files and reading them back into R.

I repeat the question from above, why can't you remove this problem by using `saveRDS`/`readRDS` instead? If you need csv files for other programs, you can still make them, but for working in R, use the right methods that give you back exactly what you output, if you can.

**Comment by annarizzibramucci** [comment]
Of course your advice about the saveRDS is great, and in future I can do this when running your dada2 pipeline, but I have already processed 60 plates, so instead of reprocessing I was looking for a shortcut. However, if it is smarter to just rerun fresh I will do so and this time save the RDS where appropriate.

**Comment by benjjneb** [comment]
> My data table is a csv. But I saved a small portion as a txt here.

First, that file is a tab-separated-variable (tsv) file, not a csv (comma-separated varaibles). So you'll need to use `read.table(..., sep="\t") to read it in. You probably also should specify `header=TRUE` because your sample names are numbers, thus look the same as the entries in the table. It will also need to be transposed (i.e. `t(...)`) back to sequences as column names after being read in.

In general, having numeric sample names is not the best idea, as they can get confused with being numbers. Even adding something simple like an "s12345" can help avoid computational confusion.

**Comment by annarizzibramucci** [comment]
Ok thanks so much for all your help with this issue!
Cheers
Anna
