### ISSUE TITLE
dereplication (derepFastq) required?

### ISSUE THREAD

**Issue by NielsonJ** [benjjneb/dada2#1095]
Hello!

I was going through the documentation and noted dereplication of samples is not part of the default tutorial. However it is mentioned in the Big Data tutorial. If I understand the DADA2 manual correct it seems logical that, priori to infering and partitioning of the reads, dereplication or a similar process must be completed to acquire the abundances. Is it correct to assume `dada()` dereplicates the reads itself and if so, what is the benefit of calling `derepFastq()` separately? 

With regards, Nielson

**Comment by benjjneb** [comment]
In more recent updates to the package, dereplication is performed "on the fly" if filenames rather than derep-class objects are provided. The major benefit here is to memory usage, as only one sample is loaded into memory at aa time. In effect, the main purpose of the Big Data worklow is achieved using the regular tutorial syntax.

> what is the benefit of calling derepFastq() separately?

It can still be a useful diagnostic to look at how many unique sequences were in your total reads. Tyipcally, you should have significantly fewer unique sequences (thus a lot of repeated observations of sequences) for DADA2 to work optimally.

**Comment by NielsonJ** [comment]
That clears it up for me, thank you.

**Comment by carolinedaws** [comment]
Where can I find the latest tutorial syntax that doesn't require calling derepFastq() separately? I am running into a memory issue and would love to use the new syntax. Thanks!

**Comment by benjjneb** [comment]
The dada2 tutorial: https://benjjneb.github.io/dada2/tutorial.html
