### ISSUE TITLE
Any functionality to enrich the taxonomy table with count numbers?

### ISSUE THREAD

**Issue by ms-gx** [benjjneb/dada2#1097]
Is there an embedded function which enriches the taxonomy table with count numbers without the need to do some R-Scripting myself? Did not see any, but might have missed it...

**Comment by benjjneb** [comment]
Probably an R one-liner using `cbind` or `rbind` will get you close to what you want.

What is the exact format you are looking for?  E.g. rows are ASVs, columns are taxonomic levels and then samples?

**Comment by ms-gx** [comment]
Sure, no too complicated. But if there would be anything generic I would this to write a workflow. This must be something that is used a lot, or am I wrong? Like merging the taxonomic results with the counts.

**Comment by benjjneb** [comment]
> But if there would be anything generic I would this to write a workflow.

Basically R has such powerful and flexible facilities to do exactly these kinds of manipulations, that it doesn't make much sense to write a package-specific version.

> Basically I want the taxonomic table (from assignTaxonomy) but enriched with the count numbers per ASV and maybe the sequence in anther column.

Since combining names and counts, it's best to do that as a data.frame (so the different columns can have different data types). I think this will do about what you want:

```
tax.augmented <- data.frame(taxa, t(seqtab), stringsAsFactors=FALSE)
```

That will have a row for each ASV, and a columns as taxonomic levels and then samples.

**Comment by ms-gx** [comment]
OK, then I will just use this command. Thanks!
