### ISSUE TITLE
Assign Taxonomy Issues

### ISSUE THREAD

**Issue by DhebbieF** [benjjneb/dada2#1102]
Hello,
Please, I wold like some form of help with the assign taxonomy command.
I'm sort of a newbie with DADA2 and I am currently trying my hands out on a tutorial that worked with dog samples (before I begin to analyse my actual dataset).

I tried using the trained DADA2 dataset  RefSeq-RDP16S_v3_May2018.fa.gz  to assign taxonomy for 4426 ASVs, but this looked like it got my PC hanging for a very longggg time and I was forced to restart, I repeated this twice (using the command :
taxa <- assignTaxonomy(seq_tab.nochim, paste(MY_HOME, "/RefSeq-RDP16S_v3_May2018.fa", sep = ''), multithread = TRUE, verbose =TRUE).

And then I checked if I had enough memory space (saw that I had 59G of storage), so I tried switching databases using the trained dataset for silva version 138 from  https://zenodo.org/record/3731176  instead using the following command:

taxa <- assignTaxonomy(seq_tab.nochim, paste(MY_HOME, "/silva_nr_v138_train_set.fa", sep = ''), multithread = TRUE , verbose = TRUE)

taxa.print <- taxa
rownames(taxa.print) <- NULL 
head(taxa.print)

write.csv(taxa, file = "ASVs_taxonomy.csv")
saveRDS(taxa, "ASVs_taxonomy.rds")

Having saved the taxonomy table, I proceeded to generate the counts table :

ASV_headers <- vector(dim(seq_tab.nochim)[2], mode = "character")
counts.asv.tab <- t(seq_tab.nochim)
row.names(counts.asv.tab) <- sub(">", " ", ASV_headers)               
write.csv(counts.asv.tab, file = "ASVs_counts.csv")        
saveRDS(counts.asv.tab, file = "ASVs_counts.rds")

But I think I messed something up because my taxonomy table and counts table were not looking OK.
The row names were strings of sequences , while the counts table had no row name whatsoever.
Although I noticed after assigning taxonomy to each ASVs using the silva database, there was no ">" identifier  at the very beginning of each string of sequences.

I was wondering if you could please help shed some insight in to what I should DO or avoid DOING.
I dont know if this would help, but I use a macOS, ran the tutorial on dada2_1.16.0 Rcpp_1.0.4.6 on  R version 4.0.0 (2020-04-24).

Please forgive my newbie questions but could you please tell if
 1. It's possible to keep running such analysis on a local machine (I mean is it likely to crash the computer if it has to analyse more ASVs than what I used?).

I have also read comments and issues raised with assign taxonomy, mine just seems little bit off, that's why I asked,

Please find attached the counts table and the taxonomy table.

Many thanksss.

**Comment by benjjneb** [comment]
Two thing: 

> And then I checked if I had enough memory space (saw that I had 59G of storage)

Your disk storage is not the same as the memory your machine has. A crude analogy how much room the library has for books ("disk storage") versus the limit of 10 books any one person can check out at a time ("active memory"). If you are working on a Mac, go to the Apple Symbol -> About This Mac in the menu, and "Memory" will be one of the things listed. How much memory do you have? It is true that if you have limited memory, `assignTaxonomy` can take very long because it can't load the whole reference database into memory at once.

> But I think I messed something up because my taxonomy table and counts table were not looking OK.

You were making the saving/loading of your tax table and sequence table much too difficult. There is no object reformatting or csv files involved. Just...

```
saveRDS(taxa, "path/to/taxa.rds")
# New session
taxa <- readRDS("path/to/taxa.rds")
```

And same for the sequence table. That is, remove all the headers/transformation/etc code. Just save the R objects, and when you reload them later (via `saveRDS/readRDS`) you will get back exactly what you had originally.

> Please find attached the counts table and the taxonomy table.

These aren't attached (probably too big to attach to a GH comment). But before sending those file, fixing the things above would be worthwhile.

**Comment by termithorbor** [comment]
I get the "ignored 2 invalid one-letter sequence codes" warning while using the latest Unite fungal fasta database with assignTaxonomy, but this is a problem with the database and not with the program, right? So it is just saying that it ignored 2 entries in the database because there were letters in it which are not ATGC or?

**Comment by benjjneb** [comment]
@termithorbor Yeah that's not a concern. Apparently a non-DNA letter or two slipped into a sequence in the Unite release.
