### ISSUE TITLE
Storing the dereplication data

### ISSUE THREAD

**Issue by Biancabrown** [benjjneb/dada2#111]
Hello, 

I am running dada2 on a cluster, and since I am not an R expert I am undergoing some issues. Hopefully you can help. 

Issue 1) Output my quality profile. Using the exact scripts in the tutorial and only changing the path 
I try to place all the output files in a pdf using the following script

pdf("/Users/Binky/Desktop/dada2/BB/plots.pdf")
for(i in 1:length(fnFs)){
plotQualityProfile(fnFs[[i]])
}
dev.off() 

Issue 2) this is a spin off of issue 1. I will also like to obtain the error pdf plots after the inference step.

It creates the pdf, but it's empty. 

3) I spent two days running dada2 and my script time ran out at the Sample Inference step. My CS department only allow us up 70 hours. I'm a bit worried that I may go over this time. Since I have to re-run the script, I was hoping to start from this step,but I do not think  the dereplication output data is stored. I'm not able to do this. Is there a way for me to perform the Sample inference step without going through the dereplication step again? 

Any help would be appreciated.

**Comment by benjjneb** [comment]
Hi Bianca,

(1) Use the `ggsave` function for this purpose. All dada2 plots are created using ggplot2. So if you want to save such a plot, do something like this (`library(ggplot2)` first):

```
plot.quals <- plotQualityProfile(fn)
ggsave("qualplot.pdf", plot.quals, device="pdf")
```

(2) This is the same answer then I think. Except you are using `plotErrors` instead of `plotQualityProfile`. Also, it may be worth testing code locally on just one of your per-sample fastq files before running everything on a cluster.

(3) I very much recommend looking at [our workflow for big data sets](http://benjjneb.github.io/dada2/bigdata.html). Once you get into the 10s or 100s of millions of reads, the workflow laid out there will be much faster (and lower memory) than the tutorial workflow. Note that the big data workflow as written is for forward reads alone, but you can just add the paired-end parts into it from the regular workflow where needed (or let us know if you're not sure how to do that).

**Comment by Biancabrown** [comment]
Thank you so much benjjneb. This was really helpful. I am working through it as we speak.
