### ISSUE TITLE
May the "pool" option cause a great increase on the number of detected ASVs?

### ISSUE THREAD

**Issue by ilapt** [benjjneb/dada2#1120]
Hi, 
I'm trying to reproduce the results of a published work (https://doi.org/10.1371/journal.pone.0227289) in which the authors used DADA2 for their analysis choosing the "pool" option. On the contrary, I chose the independent approach, as from DADA2 tutorial I (maybe incorrectly) understood that this would be the preferableway if samples were sequenced in different runs (or, in alternative, one should use the "pool" option separately for different runs and then merge the obtained ASV tables). Other parameters were left unchanged unless differently specified in the paper. However, what greatly surprised me was the great discrepancy in the number of ASVs obtained by the authors (27,104 that turned to 5,052 after filtering and chimera removal) compared to the almost 2200 I obtained. I then tried to re-run the analysis using pseudo-pooling (I'm working within the QIIME2 framework, where standard pooling is not implemented), but still got a similar result (2200 ASVs). Can you help me in figuring out which could be the reason of this great difference?

Thank you for your kind help and for your time.
Best,
Ilaria

**Comment by benjjneb** [comment]
It is very likely that pooling is causing this difference. Full-pooling (rather than pseudo-pooling) is the most powerful method to detect ASVs that are very rare within the entire study -- hence will typically output more total ASVs from a study than the other methods. You can read a bit more on pooling in DADA2 here: https://benjjneb.github.io/dada2/pool.html

**Comment by ilapt** [comment]
Dear @benjjneb ,
thank for your kind reply. Can I ask which approach would you go for when dealing with data of the same experiment coming from different runs?

Thank you.
Ilaria

**Comment by benjjneb** [comment]
Sorry for the late reply! Somehow this only showed up in my email notifications this past weekend...

The most common thing I do is to simply process all samples as normal (on a run-by-run) basis, and then merge them together. That is, the independent approach, but with error models learned on a run-by-run basis.

If I have specific concerns about run-to-run differences, perhaps big differences in sequencing depth, I would consider passing information between runs using the "priors" functionality. That is, I would process each run independently. Then I would determine the ASVs I am confident of from each run (perhaps those present in at least 3 samples, or something like that). I would compile the experiment wide list of such ASVs. Then I would do a final re-run of the `dada(..., priors=compiled_list)` denoising step on each run, with those priors included, which will increase sensitivity to those ASVs in all runs.

But to be clear, I don't usually do that -- only if I think there is a need for it because of some amount of run-to-run heterogenity that is gross enough that it is affecting sensitivity to ASVs I care about.

**Comment by ilapt** [comment]
Dear @benjjneb,
thank you for your helpful indications! So, if I understand correctly, you suggest (in normal situations, let's say) to analyse runs separately, using the default settings, based on the independent approach. Now, there is a final point that remains unclear to me: in which situation would it be preferable to use the "pooled" option (always on a run-by-run basis and then merging tables)? 
Thanks.

**Comment by benjjneb** [comment]
> in which situation would it be preferable to use the "pooled" option

If maximum sensitivity to rare ASVs is important the overall research question, and if samples are relatively informative about what ASVs are present in other samples (e.g. longitudinal samples from a common subject).
