### ISSUE TITLE
How do we count total number of reads and number of OTUs or ASV ?

### ISSUE THREAD

**Issue by Ravivemuri9** [benjjneb/dada2#1127]
HI Ben, I would like to know if there are any codes to count total number of reads and number of OTUs or ASV ?
My sample type is not fecal, so we assume our counts be low, but how low are they is the question. Also, I would like to plot number of OTUs/ASVs present. Please help.

**Comment by benjjneb** [comment]
Are you trying to do things like calculate alpha-diversity? then I recommenend transitioning your data into a package like phyloseq that is designed for that. An example of that transition is contained at the bottom of the DADA2 tutorial: https://benjjneb.github.io/dada2/tutorial.html

Otherwise you can use basic R commands to do things like count the number of reads in each sample (row), or the number of ASVs present in each sample (non-zero ASVs in each row).
