### ISSUE TITLE
Unwanted taxonomy classification results

### ISSUE THREAD

**Issue by wjlim** [benjjneb/dada2#1138]
I got unwanted taxonomy classification results and **want to check the confidence values of the ASVs.**
In my results, when I ran assignTaxonomy, eukaryotes and NA values were observed. 
The data I used is a Miseq library, so I expect only bacteria to be observed.

The options I used are:
taxa <- assignTaxonomy(seqtab.nochim,  silva_db, multithread=TRUE, tryRC = TRUE, minBoot = 80)

I am wondering how to determine significance of the each taxonomy classification results.

**Comment by benjjneb** [comment]
You can add the `outputBootstraps=TRUE` flag and you will get the bootstrap values for each level as well.

Note that the return value is slightly different -- instead of just a matrix it will be a list of two matrices, one the regular taxonomy table and the second a matrix of the boostrap values for each taxonomic assignment.

You can also just BLAST a couple of the sequences with unexpected taxonomies against a really broad database like nt to see what else they might hit.
