### ISSUE TITLE
"random_device: rdseed failed" error in assignTaxonomy()

### ISSUE THREAD

**Issue by vrbacky** [benjjneb/dada2#1149]
`assignTaxonomy()` raises "random_device: rdseed failed" error when used in multi threaded mode (and single threaded sometimes). It seems to be caused by an error in recent versions of libstdc++ (gcc 9.3.0 and gcc 10.0.1) in Linux (Ubuntu 20.04). A workaround's proposed in Pull requests (Using `rdrand` as the token value to initialize `std::random_device`).

**Comment by benjjneb** [comment]
Thanks for raising this issue and the pull request!

I'm going to be doing some work on `assignTaxonomy` in preparation for the next release in the next week or two, will take a closer look at this then. One request: Is there any documentation elsewhere, even informal, of this libstdc++ issue, and why rdrand fixes it? I don't have access to an Ubuntu test environment, so it's quite useful to see something like that to substantiate that it's fixing something that I otherwise won't be able to test directly.

**Comment by vrbacky** [comment]
Glad to help ;-).

I found it as a workaround to the same problem in another package. It seems to be "fixed" in 10.2 but I don't use this version. It switches from `rdseed` to `rdrand`, if `rdseed` fails:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94087
