### ISSUE TITLE
removeBimeraDenovo - 80% of reads were IDed as chimeras

### ISSUE THREAD

**Issue by maureenbug** [benjjneb/dada2#115]
Hi, I've been testing out dada2 with some MiSeq PE (250bp using the 515/806 primers) data that I've previously analyzed using QIIME. When I ran the removeBimeraDenovo function, I was only left with ~20% of my reads. I  wouldn't think it would be an issue of quality, as the quality of the reads is good, and I can merge ~90% of my PE reads using QIIME... but I could be wrong.
If I look at the (taxonomic) composition of the 20% remaining reads, my samples do not look very similar to the data tables produced by QIIME, so I'm definitely loosing information.

Any ideas of why so many reads were removed? Thanks in advance!

**Comment by benjjneb** [comment]
That shouldn't be happening...

Can you share the .rds file of the object you are feeding to `removeBimeraDenovo`? Eg:

```
saveRDS(seqtab.all, "path/to/myseqtab.rds")
```

Also, what version of the package are you using? (`packageVersion("dada2")`)

**Comment by maureenbug** [comment]
version is 1.1.5
[berg_seqtab.rds.zip](https://github.com/benjjneb/dada2/files/458044/berg_seqtab.rds.zip)

**Comment by benjjneb** [comment]
Hi, did you use the recommended `trimLeft=10` parameter when you filtered?

**Comment by benjjneb** [comment]
Ah. The problem is that the primers were not removed prior to processing this data.

You need to remove the 515F/806R primers from the sequences, as when they are left on the ambiguous nucleotides in the primers get interpreted as biological variation, which messes up things like downstream chimera removal.

I've used trimmomatic for that previously, but there are a number of other options that will get the job done. Once the primers are removed, just run through the same workflow and all should be well.

**Comment by maureenbug** [comment]
Hi, I did use the trimLeft=10 parameter. I will try out trimmomatic, and re-run the workflow. Thanks!

**Comment by maureenbug** [comment]
Just following up - removing the primers did the trick. I'm now only detecting ~4-5% of the reads as chimeras. Thanks!
