### ISSUE TITLE
Sample diversity issue with different sequencing depth despite rarefaction after DADA2

### ISSUE THREAD

**Issue by handuos** [benjjneb/dada2#1158]
I have noticed in my analyses that samples with high sequencing depths tend to have more diversity, even though I perform rarefaction after DADA2 analyses. 

To test this issue more consistently, I did the following: I have a set of samples sequenced at ~100k reads per sample. Then for each of them, I also created a random subset containing 20k of the fastq reads. I put all the raw fastq files and the subsampled ones together into one DADA2, and for the DADA2 output, I further rarefied everything to 10k. Intuitively, doing the subsampling would not affect the final results (since everything in the end was rarefied to 10k). However, the subsampling before DADA2 leads to consistently lower observed diversity in the ASV level. 

In order to understand which ASVs were missing, I further compared the relative abundances of all ASVs for each sample. While subsampling the fastq reads prior to DADA2 does not affect high-abundance ASVs (which is good), for lower-abundance ASVs (< 10^-3 relative abundance), subsampling prior to DADA2 actually caused them to disappear. This is very counter-intuitive: for an ASV at 10^-3 relative abundance, in the original fastq file with 100k reads, it should have about 100 reads. Then subsampling from 100k to 20k means we should still have ~20 sequences for this ASV (and it is unlikely to disappear due to sampling noise). The fact that we consistently see so many ASVs missing after subsampling the fastq files is quite confusing to us.

We have previously been working under the assumption that as long as we do rarefaction at DADA2 output, we should be able to compare samples with slightly different sequencing depths. But the above testing seems to suggest that with a 5-fold difference in sequencing depth, the diversity in a sample with lower sequencing depth can be quite under estimated. I am curious on why DADA2 would have such an unexpected behavior. I believe understanding and resolving this artifact would be beneficial for the DADA2 community, and I would really appreciate any input. Thanks in advance!

**Comment by benjjneb** [comment]
In default operation, DADA2 is performing denoising on a per-sample basis. Furthermore, in order to identify a new ASV in a given sample, there need to be at least 2 error-free reads from that ASV in the sample. Thus, the effective low-frequency sensitivity of DADA2 is not 1/SAMPLE_DEPTH, but something more like 4/SAMPLE_DEPTH (with about 50% error-free reads, as might be found in an Illumina sequencing experiment). This is described in more detail in the original DADA2 paper, albeit in the supplementary information, specifically Supplementary Note 1.

If sensitivity to the rarest variants is critical to your analysis (and ultimately any rarefaction type curve becomes dominated by the rarest detectable variants -- singletons) there are a couple of ways to increase DADA2 sensitivity to rare variants: [pooling (`pool=TRUE` of `pool="pseudo"`)](https://benjjneb.github.io/dada2/pseudo.html) or [`DETECT_SINGLETONS=TRUE`](https://benjjneb.github.io/dada2/ReleaseNotes_1_14.html).

**Comment by dadahan** [comment]
Perhaps a heuristic here could also be do remove doubletons from your runs and check the union of ASVs between your subset and non subset runs? With the higher abundance of rare variants in your more deeply sequenced run, I think the union after removing doubletons would represent a greater proportion of all ASVs.

**Comment by handuos** [comment]
Thanks @benjjneb and @dadahan for the comments! I tried processing the same dataset again with `pool=TRUE` and `pool="pseudo"`, and either option improved the consistency, with `pool=TRUE` nearly completely resolved the discrepancy. With such test, I am now convinced that this issue is mainly due to sensitivity limit in DADA2.

However, in my dataset, the limit of detection seems to be a lot higher than `4/SAMPLE_DEPTH`. In fact, there were several ASVs detected with ~200 reads in the sample with ~100k total reads, but the same ASV was not present after a 1/5 subsampling (20k reads). So this seems to suggest for certain ASVs, the sensitivity would drop to about `40/SAMPLE_DEPTH`. Is that something reasonable?

**Comment by benjjneb** [comment]
I would expect that such low sensitivity to any particular ASV would be rare, but I can also imagine scenarios in which it could transpire, at least for a small number of ASVs.

For one, if the key differences for resolving that ASV from others lie in regions of the reads with lower qualities and higher error rates, then the statistical approach taken by DADA2 has less power and it could require more reads to be detected. Also,  if the fraction of error-free reads for the sequencing data generally are higher than the ~0.5 I suggested above, or if the specific read background these ASVs exist on has a higher error rate (perhaps due to Illumina specific error motifs), then again more reads are needed to get the minimum two error-free reads for detection. Finally, ASVs that are very close to another much more abundant ASV (e.g. 1 SNP different) also may require more than 2 error-free reads to be detected.
