### ISSUE TITLE
maxEE preferential filtering possible?

### ISSUE THREAD

**Issue by wsteenhu** [benjjneb/dada2#1159]
At the moment I am trying to set the most optimal maxEE parameter for our 16S V4-pipeline (target ~250bp). We plan to set truncLen to 180/140.

When looking for papers on maxEE-benchmarking I came across [this paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0227434) by Prodan _et al._ who report a preferential underrepresentation of some ASVs in their mock community (among others streptococci). 
They state that 'While it is widely known that Illumina sequencing error rates are position-dependent (i.e. error rates tend to increase towards the end of the read), it is often neglected that they may also be affected by underlying sequence patterns. Examples of such patterns are “GGC” triplets or inverted repeats (more than 8 bases long) located upstream of the respective position. Thus, if a particular ASV sequence happens to contains such a pattern, application of a quality filter will exclude its reads preferentially before the denoising step.' They therefore advice against using maxEE at all.

Is this something others came across? Since we are currently doubting to either set maxEE on 1 or 2, we might opt for 2 given this finding, however I'd rather have a few less higher quality reads, than more lower quality ones... Any advice on this?

**Comment by benjjneb** [comment]
> however I'd rather have a few less higher quality reads, than more lower quality ones

Yes I agree this is typically preferable. Additional lower quality reads don't add much to the accuracy of sample inference.

> Thus, if a particular ASV sequence happens to contains such a pattern, application of a quality filter will exclude its reads preferentially before the denoising step.' They therefore advice against using maxEE at all.

This is fine as far as it goes, but any bias introduced by EE filtering + patten-dependent errors is so much smaller than the bias produced by DNA extraction and PCR that it becomes essentially irrelevant. This is also part of why multiple papers have reported that 16S copy-number correction doesn't seem to improve bias -- because there is still major bias at other steps of the 16S measurement workflow that are even larger sources of bias. You can read our much more in depth discussion of this topic here: [Consistent and correctable bias in metagenomic sequencing experiments, eLife, 2019](https://elifesciences.org/articles/46923)
