### ISSUE TITLE
Greater # of QIIME OTUs than dada2 "sequences"

### ISSUE THREAD

**Issue by maureenbug** [benjjneb/dada2#116]
Hi,

I've been testing out dada2, and noticed that from the same dataset, QIIME gives me ~700 OTUs while dada2 produces ~300 ISeVs/ISVs/DSVs/sequences (or whatever they're eventually going to be called). Looking at say, the family level, both QIIME-produced and dada2-produced datasets look very similar, and most of the QIIME OTUs are relatively rare taxa. I was curious if anyone knew of a reason why there are more QIIME OTUs, as I would initially expect there to be fewer.

Thanks!
Maureen

**Comment by benjjneb** [comment]
The standard OTU calling pipeline w/in QIIME has very high FP rates, especially for rare (~<0.5%) variants. See for example (our manuscript)[https://t.co/e6L95hB0QN] or (Robert Edgars UPARSE manuscript)[http://dx.doi.org/10.1038/nmeth.2604] or (Kopylova's paper benchmarking OTU methods w/in QIIME)[http://msystems.asm.org/content/1/1/e00003-15.abstract] or the recent (Kohn preprint on QIIME performance on mock communities)[https://peerj.com/preprints/2196.pdf].

DADA2 will almost always output far fewer sequence variants than the standard QIIME pipeline outputs OTUs, because DADA2 has a far lower FP rate. DADA2 will also split some OTUs that contain multiple real SVs, but when simply counting output sequences, that effect is overwhelmed by the fewer number of spurious variants.

**Comment by maureenbug** [comment]
Ah, that makes a lot of sense. Thank you!
