### ISSUE TITLE
variable length primer sets within single run

### ISSUE THREAD

**Issue by AlexaBennett** [benjjneb/dada2#1161]
Firstly, thank you for the active communications and periodic updates within dada2. I have a unique situation within my data for which I have concerns regarding error rate modeling for an entire lane of sequencing (MiSeq 2x300). The amplicons are composed of several primer sets resulting in a range of sizes. The quality data for the longer amplicons is significantly worse than the shorter counterparts from the same run. Is it best practice to calculate error rate per each primer set?

Also, is there any increase in robustness if the error rate is calculated across multiple lanes which utilize the same preparation pipeline for a given primer set? or, is de novo (per lane) always recommended?

**Comment by benjjneb** [comment]
The reads themselves are longer/shorter? Or, you've trimmed off the primers and after that you have longer and shorter reads (corresponding to short amplicons that are <300nts so get truncated at less than the read length)?

**Comment by AlexaBennett** [comment]
My apologies for not being concise. I have several primer sets which are multiplexed on one run. The primer sets vary in their expected amplicon size. For instance primer set A produces amplicons of 300bp while primer set B produces amplicons of 500bp. Primer set A's read 2 average quality drops below 30 at 200bp while primer set B's read 2 quality drops below 30 at 130bp.

**Comment by benjjneb** [comment]
Hm... I guess I probably would do the error model on a per-amplicon basis then, especially given you are seeing the different quality profiles between them. This isn't a situation I've dealt with myself though.

> Also, is there any increase in robustness if the error rate is calculated across multiple lanes which utilize the same preparation pipeline for a given primer set? or, is de novo (per lane) always recommended?

Our recommendation is to do it per-lane, because the relative gain in robustness of error model estimation is typically much smaller than the errors that can arise if one of the lanes had a different error model (and thus is mis-modeled by the cross-lane error model).
