### ISSUE TITLE
Loosing 50-75 % of sequences after filtering and denoising

### ISSUE THREAD

**Issue by Marcel2907** [benjjneb/dada2#1164]
Dear Benjamin,

I am wondering why I am loosing such a big amount of sequences after filtering and denoising in all of my samples.

I used the Pacbio full length 16S sequencing approach and followed the instructions of the tutorials (filterAndTrim(nops_final, filts_final, minQ=3, minLen=1000, maxLen=1600, maxN=0, rm.phix=FALSE, maxEE=2), and the error rates are looking also as expected. 

Do you have an idea what could happen here?

Best,
Marcel 
![Screenshot 2020-10-16 at 12 48 54](https://user-images.githubusercontent.com/72925559/96249788-0191f180-0fae-11eb-8070-4ed175181547.png)

**Comment by Marcel2907** [comment]
additional info: the taxonomy analysis result looks nice at the end, all genera I expected are present etc., was just wondering if its fine to go on with the analysis after loosing so much reads.. the accuracy of PacBio was set to 99 %.

**Comment by benjjneb** [comment]
Losing sequences at filtering is expected, and does not necessarilty indicate any kind of problem. You can consider loosening the filtering threshold (e.g. `maxEE`) if you'd like, but it's not clear whether having more but lower quality sequences really helps the description of the final community. Likewise, losing sequences at the primer removal step is also expected. To be honest, the DADA2 primer matching method could probably be improved a bit to get a few more reads through that step, but it's been shown before (and we've seen the same) that insisting on the presence of the primers in PacBio data is an effective way to screen out poor quality sequences.

Now, at the denoising step, you are losing a decent chunk (10-50%) of reads in various samples. My guess is that this is occurring because some samples have a high fraction of very low abundance ASVs that only appear in the sample data once or twice, and thus aren't detected by default DADA2 denoising. This could be because of high error rates in the data, or because there is a high rare fraction of ASVs in the real samples. The result is that while you will have high confidence in the ASVs that are output, you will be depleted in the rare fraction of the sample.

I would consider either trying `pool="pseudo"` or `DETECT_SINGLETONS=TRUE` at the `dada(...)` step, and see if those options meaningfully increase the fraction of reads being denoised. (both approaches help the detection of very rare variants).

**Comment by Marcel2907** [comment]
Thanks a lot for your help and the information! Could be the case that I have a high number on low abundance ASVs inside my samples, I am working with semi-synthetic medium so there is a lot of aquatic stuff inside! I observed highest loss of reads in the sediment samples, and lower loss of reads in aquatic samples. But again, the analysis after filtering looks really nice, so it should be totally fine! Thanks a lot for your help!

**Comment by pdhrati02** [comment]
@benjjneb I have a similar question. 
As you mentioned that losing reads at filtering step is normal, but what threshold do we keep for that? 
I have ITS datasets, and in one of them my tracks look like this, where a big drop is seen at filtering step:. I understand there is no rule on how much percent should one go ahead with, but in this case there is nearly 40% read loss. Is that okay to proceed with? 
 head(track)
      input filtered denoisedF denoisedR merged nonchim
C102  45535    26873     25590     25564  16149   15922
C103 222856   110709    109711    109434  85535   84313
C104  69429    46216     44735     44346  22214   22066
C105  19508     1079      1037       969    956     956
C108  46535    23160     22479     22309  12911   12836
C111  81468    59187     57999     58002  52569   52412

Thank you in advance
DP

**Comment by benjjneb** [comment]
A 40% read loss at filtering is not a major cause for concern. What concerns me more is that it seems some samples like C105 lose almost all their reads at the filtering step (19508 -> 1079).

**Comment by pdhrati02** [comment]
Hi @benjjneb Yes that is of concern and this is happening for 10 samples. And when I checked the details, I saw that in case the loss was upto 60% also. 
Would you be able to suggest anything one must do in such cases (like the 10 samples) where the read loss is huge?

Thank you very much for all your help.
DP

**Comment by benjjneb** [comment]
> Would you be able to suggest anything one must do in such cases (like the 10 samples) where the read loss is huge?

If it's a small number of total samples, I would just check to see if there is any batching (i.e. is it all one sample type?) or whether it is just randomly spread among the samples. If its randomly spread, I would just ignore it -- a few of the libraries were lower quality, that happens. If it is all in one sample type, I would think gabout it a little more. Is that sample type lower biomass for example? That can impinge on library quality.

**Comment by pdhrati02** [comment]
Hi @benjjneb Thank you very much for your advise. Yes these are low biomass samples, but I did not make this library. And the bad samples seem to be random, however I will try to get a plate layout to see if that can be linked with this. 
Thank you very much once again for your help.
