### ISSUE TITLE
Problem at error rate step

### ISSUE THREAD

**Issue by jwill123** [benjjneb/dada2#1166]
We have a project with about 50 samples, and when looking at the qualities in the fastq files, they initially look pretty good:
![calidad](https://user-images.githubusercontent.com/9499910/96605219-35468180-12f6-11eb-9821-2a91ea9e7339.png)

After we do the filtering and trimming, the error rates look quite bad:
![errores](https://user-images.githubusercontent.com/9499910/96605386-6fb01e80-12f6-11eb-978d-b0c0bcf3e5db.png)

And later during the inference and merging we lose most of the reads. We have played around with the filtering and the number of bases used for learning the error rates, but this problem persists. We are not sure exactly what causes this, or what the solution would be. Any help you could provide would be greatly appreciated.

**Comment by benjjneb** [comment]
Those learned error rates don't look great...

Can you tell us more about the PCR and sequencing technology you are using? Also, what kind of samples are you interrogating?

**Comment by benjjneb** [comment]
One other thing... are you sure you removed primers, and is there any possibility that some sort of "technical" variation is in this data, for example heterogenity spacers or variable length primers?

**Comment by jwill123** [comment]
Hello, thanks for the quick response. We are looking into this now, so I will get back to you once we have checked it out.
Thanks a lot

**Comment by jero91** [comment]
Hello,
We use amplification and sequencing the V3-V4 regions of the 16S rRNA gene. The Ilumina Miseq sequencing 300x2 approach was used.
Samples from mice bronchoalveolar lavage.
In our case the primers are always the same length(about 15) and cut them with trimLeft=(20,20)
The values of the other parameters that we try to change without results are:  truncLen=c(240,220), maxEE=c(1,1).
Thank you!

**Comment by benjjneb** [comment]
> Samples from mice bronchoalveolar lavage.

I would recommend inspecting your data for the possibility that it is highly contaminated with mouse DNA. This is something that is seen due to off-target amplification and the often very low microbial biomass of BAL samples.

To do this, just select a random set of like 20 forward reads from a couple samples, BLAST them against nt, and then inspect the hits. Is a significant chunk hitting non-microbes?

**Comment by jero91** [comment]
You are right. We had some mouse sequences en the reads.
But, we have already removed all the mouse sequences and the error rates still looking bad.
Have you another idea about?
Thanks

**Comment by benjjneb** [comment]
High rates of off-target amplification and technical variability are the most common causes.

Another possibility is that there is little to now real microbial DNA being amplified, and the sequence data you are getting is mostly just microbial contamination. That's harder to diagnose, but again just inspecting the assignments of a subset of reads can help -- do their closest hits have taxonomies like those previously observed in BAL samples? Or more like common contaminants?

**Comment by Emiliana-ux** [comment]
Hi, 
I have same problems with learnerrors, take so long two days and nothing about results...

[1] "Learning errors from forward reads"
3751012544 total bases in 24866061 reads from 56 samples will be used for learning the error rates.
Initializing error rates to maximum possible estimate.
selfConsist step 1 ........................................................
   selfConsist step 2
~
~
~
~

**Comment by Emiliana-ux** [comment]
I did this command with filter:
out <- filterAndTrim(fnF, filtF, fnR, filtR,
                     minLen = 120, matchIDs=TRUE, multithread=4,
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, verbose=TRUE)

I need help.

**Comment by benjjneb** [comment]
@Emiliana-ux I don't think anything is going wrong there, it just is taking a long time to complete.

The question is why you are running `learnErrors` on such a large amount of data? By default, `learnErrors` will use a sufficiently large subset of the data (`nbases = 1e+08` by default, 100 million) to learn the error rates from. But you have turned that option off (?) it would seem as the output indicates `learnErrors` it is using 3.75 billion bases -- that's going to take a lot longer.

**Comment by Emiliana-ux** [comment]
> @Emiliana-ux I don't think anything is going wrong there, it just is taking a long time to complete.
> 
> The question is why you are running `learnErrors` on such a large amount of data? By default, `learnErrors` will use a sufficiently large subset of the data (`nbases = 1e+08` by default, 100 million) to learn the error rates from. But you have turned that option off (?) it would seem as the output indicates `learnErrors` it is using 3.75 billion bases -- that's going to take a lot longer.

**Comment by Emiliana-ux** [comment]
Hi Ben,

Thanks for help me, and today I running my script and I did this command:

errF <- learnErrors(filtFs, nbases= 1e8, multithread=TRUE, verbose=TRUE)

[1] "Learning errors from forward reads"
139763582 total bases in 926543 reads from 2 samples will be used for learning the error rates.
Initializing error rates to maximum possible estimate.
selfConsist step 1 ..
   selfConsist step 2
   selfConsist step 3
   selfConsist step 4
   selfConsist step 5
   selfConsist step 6
   selfConsist step 7
   selfConsist step 8
   selfConsist step 9
   selfConsist step 10

and I don't know why it stopped!

**Comment by benjjneb** [comment]
> and I don't know why it stopped!

Because the command completed I think.

**Comment by Emiliana-ux** [comment]
Hi Ben,

Previously, we had server problems, and the ran stopped.
I ran this command below and got this result, can you help me?


# Learn forward error rates
print("Learning errors from forward reads")
errF <- learnErrors(filtFs, nbases= 1e8, multithread=TRUE, verbose=TRUE)
# Learn reverse error rates
print("Learning errors from reverse reads")
errR <- learnErrors(filtRs, nbases= 1e8, multithread=TRUE, verbose=TRUE)



Carregando pacotes exigidos: Rcpp
Self-consistency loop terminated before convergence.
Error rates could not be estimated (this is usually because of very few reads).
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.
Calls: learnErrors -> dada -> getErrors
Execução interrompida


[1] "Learning errors from forward reads"
139763582 total bases in 926543 reads from 2 samples will be used for learning the error rates.
Initializing error rates to maximum possible estimate.
selfConsist step 1 ..
   selfConsist step 2
   selfConsist step 3
   selfConsist step 4
   selfConsist step 5
   selfConsist step 6
   selfConsist step 7
   selfConsist step 8
   selfConsist step 9
   selfConsist step 10
[1] "Learning errors from reverse reads"
139227062 total bases in 926543 reads from 2 samples will be used for learning the error rates.
Initializing error rates to maximum possible estimate.

**Comment by benjjneb** [comment]
The estimation of error rates finished from the forward reads.

On the reverse reads there was an error immediately, suggesting that something about the function call was wrong. Perhaps the definition of the `filtRs` or something. The issue is there though, with the reverse reads.

**Comment by Emiliana-ux** [comment]
Thanks Benjjneb,and I'll try to solve
