### ISSUE TITLE
Might over-estimate diversity

### ISSUE THREAD

**Issue by gaofeng-ni** [benjjneb/dada2#1188]
Dear authors,

I'm wondering if you could comment on a recent analysis I did with DADA2.
I ran DADA2 protocol without changing much parameters, reads were from Illumina PE300, ASVs were 461 bp in lenght.
Taxonomy was assigned using trained SILVA 138.

Out of 2879 ASVs, 789 belong to the genus of "Candidatus_Nitrosoglobus". I found this a big surprising and wonder if we have over-estimated such diversity.

I attached count table and taxonomy table, and I'm more than happy to hear comments and suggestions.

Kind regards,
Gaofeng 
[ASVs_counts.tsv.txt](https://github.com/benjjneb/dada2/files/5478962/ASVs_counts.tsv.txt)
[ASVs_taxonomy.tsv.txt](https://github.com/benjjneb/dada2/files/5478963/ASVs_taxonomy.tsv.txt)

**Comment by benjjneb** [comment]
> Out of 2879 ASVs, 789 belong to the genus of "Candidatus_Nitrosoglobus". I found this a big surprising and wonder if we have over-estimated such diversity.

I don't know anything about Nitrosoglobus, so i don't know if that is unreasonable for your study environment.

There are technical reasons that can lead to ASVs being split when they shouldn't be, so that's one thing to look for. You can try aligning and comparing some of the Nitro ASVs. Are there repeated differences at the start and end of the ASVs? That could indicate primers that were not removed. Are there ASVs in both forward and reverse complement orientations? Etc.

**Comment by gaofeng-ni** [comment]
Thanks a lot! I'll look into these issues.
