### ISSUE TITLE
sequence retention

### ISSUE THREAD

**Issue by kruehling** [benjjneb/dada2#1211]
Hi @benjjneb, 

I am having some problems with sequence retention in the learn error and merging steps. I have attached a file detailing the sequences retained during the various steps of the pipeline. 
[SequencesRetained2_DADA2.pdf](https://github.com/benjjneb/dada2/files/5570471/SequencesRetained2_DADA2.pdf)

Here are the variations in the filter and trimming steps that I've attempted: 

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, trimRight = 15 ,   truncQ = 10, minLen = 50, maxN = 0, maxEE = c(2, 2), rm.phix = TRUE, compress = TRUE, multithread = TRUE) 

out2 <- filterAndTrim(fnFs, filtFs2, fnRs, filtRs2, trimRight = 15 , trimLeft=20,  truncQ = 10, minLen = 50, maxN = 0, maxEE = c(2, 2), rm.phix = TRUE, compress = TRUE, multithread = TRUE) 

out4 <- filterAndTrim(fnFs, filtFs4, fnRs, filtRs4, trimRight = 15 , trimLeft=20,  truncQ = 2, minLen = 50, maxN = 0, maxEE = c(2, 2), rm.phix = TRUE, compress = TRUE, multithread = TRUE) 

out5 <- filterAndTrim(fnFs, filtFs5, fnRs, filtRs5, trimRight = 15 , trimLeft=20,  truncQ = 10, minLen = 50, maxN = 0, rm.phix = TRUE, compress = TRUE, multithread = TRUE) 

I've tried both the default and the "fastqQuality" parameters for the learnErrors function. I have attached the error plot of forward sequences from the out4 iteration of the filter/trim step. I can include other error plots if you are interested, but they look basically the same. 
[Rplot_errorPlotv4.pdf](https://github.com/benjjneb/dada2/files/5570620/Rplot_errorPlotv4.pdf)

errF4 <- learnErrors(filtFs4, multithread = TRUE, qualityType = "FastqQuality")

At this point I am just using the default denoise, derep and merger arguments.  

Thank you in advance for your help. 
-kelsey

**Comment by benjjneb** [comment]
That doesn't look good, the read retention (or lack thereof) and that your learned error rates have no quality score signal at all.

Can you say more about the data you are working with. What amplicon is being sequenced? What sequencing technology? Could there be any artefectual variation introduced by previous processing, or by library protocols like "heterogeneity spacers" that causes reads to begin at different starting points? Also, roughly what environment is being sequenced here?

**Comment by kruehling** [comment]
The sequencing was performed by GENEWIZ using their 16s-EZ application for amplification of the V3 V4 region using the Illumina platform. I am using the fastq files that were returned to me by the sequencing facility. There report (attached) gives very few details about the library prep process and does not include their primer sequence, which I assumed they removed before sending back the fastq files however I'm not entirely sure of that. Half of the sequences are from aquatic environments and the other half of the samples are sourced from sediment. The sequencing facility used QIIME1 and their sequence retention was very good, so it doesn't appear to be an issue with the sequence quality and additionally when I plot the quality profile of the sequences before and after filtering everything looks great. Here is a few plots of the sequences after the filter/trim step:  [Rplot_filtF5.pdf](https://github.com/benjjneb/dada2/files/5578359/Rplot_filtF5.pdf)

 I'm sorry this pdf is a bit hard to read but hopefully you can gather a bit more about their process from it. 
[GENEWIZ NGS 16S-EZ ANALYSIS REPORT.pdf](https://github.com/benjjneb/dada2/files/5578338/GENEWIZ.NGS.16S-EZ.ANALYSIS.REPORT.pdf)

**Comment by benjjneb** [comment]
> which I assumed they removed before sending back the fastq files however I'm not entirely sure of that.

I'm making a best guess here, but I doubt the primer sequences were removed and probably are on the reads. The most common V3V4 sequencing prep is the "Illumina" library prep that includes the primers sequences on the reads. Primers must be removed from the reads in order to run DADA2 properly.

> Half of the sequences are from aquatic environments and the other half of the samples are sourced from sediment.

You could try to learn the errors from just the aquatic environment samples -- sediments are notoriously hyper-diverse, which makes learning the error model significantly harder. But this is a secondary issue to figuring out how the libraries were prepared and consistently removing any primer/adapter type sequence.

> The sequencing facility used QIIME1 and their sequence retention was very good, so it doesn't appear to be an issue with the sequence quality and additionally when I plot the quality profile of the sequences before and after filtering everything looks great.

An ASV approach like DADA2 is trying to achieve single-nucleotide resolution, and thus will be substantially affected by things like unremoved primer sequences, or varying start positions of the reads. OTUs or just taxonomic mapping are much less sensitive to that kind of unresolved technical variability in the reads.

> I'm sorry this pdf is a bit hard to read but hopefully you can gather a bit more about their process from it.

I would just ask them to fully describe their amplicon library construction and what the sequenced reads cover. They ought to be able to tell you what primers they used and whether they are on the reads etc.
