### ISSUE TITLE
Abundance p-value and probability compared to OMEGA_C 

### ISSUE THREAD

**Issue by kdpaepe** [benjjneb/dada2#1215]
Dear, 

I am still learning the basics of DADA2, which I find a very user-friendly and valuable package, and I had some questions related to the abundance p-value and the probability value that is compared to OMEGA_C. 

- If I understand it well, sequences that are excluded for alignment based on the k-mer distance are assigned a lambda<sub>ij</sub> value of 0. When applying the p-value formula mentioned in the 2016 paper by Callahan et al.,  ppois(n<sub>iobs</sub>,E<sub>nifromj</sub>,lower.tail=FALSE)/(1-dpois(0,E<sub>nifromj</sub>)), this would result in NA p-values as the denominator would reduce to 0. What happens with these p-values when they are compared to OMEGA_A? Imagine there are a couple such sequences in the first round, which starts with the most abundant sequence as the center, do they immediately form their own partition in the first cycle of the algorithm? Is this done step wise? Since the sequences are all largely dissimilar from the center of partition 1, I could imagine the excluded sequences might be similar to each other? Is the order of forming partitions for NA p-values then random, because you could see this NA value as a sort of 'tie'? Or am I completely mistaken about the 'NAs'?

- Related with this, if the denominator in the p-value equation would be omitted, the above mentioned very dissimilar sequences would have p = 0, which also would make sense to me and the information to judge if a sequence is consistent with the error model is in fact included in just the numerator (cumulative Poisson)? I understand that adding the denominator makes the p-value conditional on a read being sequenced at least 1 time. And I get that zero observed reads would result in a p-value of 1. But I do not entirely understand why this is needed. Because DADA2 starts from alignments and my understanding was that it calculated the lambda<sub>ij</sub> and E<sub>nifromj</sub> only for those observed alignments? I did find an interesting paragraph in the 2012 paper by Rosen et al. in this regards: _'If we had not conditioned on having observed at least one read of each family, then the unobserved families would not have born any significance (they could all have py = 1), but before looking at the data these families could have been significant. This would create a difficulty in choosing an appropriate multiple hypothesis correction; a naive Bonferroni correction of α 4Lα with Lα the length of Gα, which treats all possible families as tested hypotheses, would deprive the p-value of any statistical power. Conditioning on Ry > 0 and evaluating only the observed sequences avoids this complication.'_ Intuitively I can follow this reasoning but when I overthink it, I get stuck:  in the scenario without denominator you could indeed theoretically evaluate every possible substitution and combinations thereof from all observed template molecules, which could inflate the number of hypotheses to consider in multiple testing and decrease the significance level a lot, but what I don't fully understand is why having all p-values of those imaginary, non-existing pairwise comparisons set to 1 changes any of the above? You could still in theory perform all the possible pairwise comparisons, but now you would simply get a value of 1 instead of a smaller value. Or do you assume that p-values of 1 can be filtered out and ignored, thereby reducing the number of hypotheses? 

- Finally, am I right that for comparison with the OMEGA_C threshold, the numerator of the abundance p-value equation is used. This would always be a bit smaller than the abundance p-value and hence you could find a sequence which exceeds the omega_A threshold (which has the same default value as OMEGA_C) and will therefore not form its own partition, but at the same time since the numerator of the p-value equation is slightly smaller than the p-value, when comparing this numerator to threshold OMEGA_C it could turn out to be smaller resulting in the sequence being excluded from sample inference? 

Apologies for the lengthy questions and thank you for your consideration.

**Comment by benjjneb** [comment]
On 1) Those lambda=0 sequences get a log p-val of -Inf (effectively). The creation of new partitions is iterative (or step-wise). That is one new partition is made, all sequences get the chance to move to that new partition if they are closer to its center than the current one, and then new lambdas/p-vals are calculated as needed.

On 2) The idea is that the p-values being computed are conditional p-values, that are only computed on the abundance of a sequence after it is in the observed set. Thus, the change in the universe of hypotheses. So, yes basically your last sentence. In reality, the DADA2 p-value is a useful way to produce a score that is good at discriminating real sequences from errors, but probably shouldn't be interpreted as a true p-value (i.e. a guarantee on the T1 error rate) for multiple reasons (model misspecification etc.).

(3) Yep. The main reason for OMEGA_C at its default setting is to avoid "correcting" singleton sequences that both are not able to form their own partition, and are way far away from anything actually identified in the sample. OMEGA_C is also a very useful knob at times -- in particular OMEGA_C=1 changes the way ASV abundances are estimated to the number of error-free reads rather than the number of same-partition reads, which could be a more accurate estimate of the relative abundances in some situations.

**Comment by kdpaepe** [comment]
Thank you so much for the swift reply and clear answers! I am just wondering about one more thing: if multiple sequences get a p-value inf after the first error estimation round, is one of them randomly selected to form the new partition? Or is it still the smallest non-inf p-value that becomes the center of a new partition and are those initially excluded sequences then assigned to the new partition because they may be sufficiently similar to the new center to align them?

**Comment by benjjneb** [comment]
> is one of them randomly selected to form the new partition?

The most abundant of the Inf ties is chosen to start the new partition.
Also a technical note that I forgot -- in the first partition, everything is aligned (no kmer screen) so that every unique sequence has at least one computed lambda value. However, due to the limits of floating point numbers, there are still Inf p-values.

> initially excluded sequences then assigned to the new partition because they may be sufficiently similar to the new center to align them?

They still have to be "more likely" to be from the other partition to join it, so will need to get a non-zero lambda value for that to be possible within the bounds of the floating-point computation being performed.

**Comment by benjjneb** [comment]
Also, given that you seem very interested in the statistical ideas behind DADA2, you should also know about an excellent new take on this same problem (inferring the real variants from noisy amplicon sequencing data) that in my opinion is even more statistically principled: AmpliCI by @xiyupeng and Karin Dorman. Read more here: http://dx.doi.org/10.1093/bioinformatics/btaa648

**Comment by kdpaepe** [comment]
Thank you very much. This is very insightful! I unfortunately don't have a very strong statistics background but I like to understand all details when I'm applying a technique :) Thanks also for the AmpliCI recommendation. I will definitely give it a try.
