### ISSUE TITLE
Taxa not found 

### ISSUE THREAD

**Issue by Zuby88** [benjjneb/dada2#1223]
Hi Ben,

I am trying to run the addSpecies command  but got an error : Error in rownames(taxtab) : object 'taxa' not found. 
The assignTaxonomy command ran successfully but I got stuck with the addSpecies command. 

Below is my command lines - 
dada2::assignTaxonomy(seqtab.nochim, "/Users/egboluch/Desktop/FASTQ/silva_nr_v132_train_set.fa", multithread=TRUE, tryRC = TRUE)
dada2:: addSpecies(taxa, "/Users/egboluch/Desktop/FASTQ/silva_species_assignment_v132.fa", tryRC = TRUE)
taxa.print <- taxa # Removing sequence rownames for display only
rownames(taxa.print) <- NULL
head(taxa.print)

Please what do you suggest i do to resolve this issue. 

thanks

**Comment by vfonti** [comment]
I am no expert but it looks to me (since your taxa object is not found) that the problem is in the `assignTaxonomy` step.
Are you sure that the extension of your reference database isn't .fa.gz rather then .fa? And are you sure that you downloaded the realise n.132? I am working with the 138.

Hope this can help.
V.

**Comment by Zuby88** [comment]
Thank you so  much V. I have resolved the issue.
