### ISSUE TITLE
How to remove bacterial ASVs from archaeal ASV taxa and seqtab

### ISSUE THREAD

**Issue by microanand** [benjjneb/dada2#1227]
Hi Ben, 
            I am new to dada2, however, somehow I managed to process my Archaeal amplicon V3-V4 data in dada2. 
I am getting "Bacteria" in my taxa file (after assigning taxonomy to the seqtab.nochim). 

Can please let me know how to remove bacterial ASVs from by taxa and seqtab.nochim....

Thanks in advance...

regards
Anand

**Comment by jgrzadziel** [comment]
Hej @microanand ,
first of all in order to process your data, you will need to convert your dada2 results into phyloseq. Just folllow the dada2 tutorial:

https://benjjneb.github.io/dada2/tutorial.html

Then using phyloseq you can easily filter your samples and/or taxa 
e.g. 
`phyloseq.filtered = subset_taxa(phyloseq.file, Kingdom =="Archaea")`

Here are some tips concerning _phyloseq_ package:
https://joey711.github.io/phyloseq/preprocess.html

**Comment by microanand** [comment]
Hi
      Thanks a lot...for the prompt reply....I will try to use
phyloseq...thanks
regards
Anand
Dr Anand Jain
Project Scientist
Arctic Group
National Center for Polar and Ocean Research
Head Sada, Vasco-da-gamma, Goa
Email: ajain@ncaor.gov.in; <ajain@ncaor.gov.in>microanand2003@yahoo.com;
microanand2003@gmail.com <microanand2003@yahoo.com>
skype:dr.anand.jain
Phone: +91 7350818590
            +91 832 2525 636
https://scholar.google.com/citations?user=Yp2im0kAAAAJ&hl=en
