### ISSUE TITLE
output bootstraps for assignTaxonomy

### ISSUE THREAD

**Issue by rec3141** [benjjneb/dada2#124]
Thanks for your work, I'm having fun testing out dada2. 

An option to output the bootstrap values along with the assignment would be useful. In mothur I  usually classify at a permissive cutoff (e.g. 1%) then explore the quality of the assignments from there.

**Comment by gblanchard4** [comment]
I have been playing around with trying to get this to work and have been thinking about how the output should be formatted. 

Do you think the bootstrap values should be the first column in the returned matrix or the last?
My thought is it should probably be the first column. That way if we run `addSpecies` we don't have a (potentially confusing) bootstrap value between genus and species. 

I was thinking of adding a `Verbose` kwarg to the `assignTaxonomy` that would allow the bootstrap values to be output.

@benjjneb What are your thoughts on this?

**Comment by benjjneb** [comment]
The right way to do this is to return a character matrix of the best hit taxonomy assignments, and an integer matrix of the bootstrap values at each sequence/level. That makes all the information easily usable in R.

To do that the return value from the C function that does the processing needs to change, and then a flag needs to be added to `assignTaxonomy` to request the raw taxonomy character matrix and bootstrap matrix instead of the usual return value of the thresholded taxonomy character matrix.

**Comment by benjjneb** [comment]
Thanks to @gblanchard4 for adding this functionality, which is now merged in: d31afdfcda1d12d08d485e1de26485eff7d7db3f

`assignTaxonomy(..., outputBootstraps=TRUE)` returns a list with both the assigned taxonomy matrix, and a corresponding matrix of the bootstrap values. Also set `minBoot=0` if you want to do all bootstrap thresholding maually.
