### ISSUE TITLE
Error in access(object, "tax_table", errorIfNULL) :    tax_table slot is empty.

### ISSUE THREAD

**Issue by Zuby88** [benjjneb/dada2#1246]
Hi Ben,

Please I will need direction on how to resolve this issue.

I ran this : rank_names(tax_table, errorIfNULL = TRUE) to take a look at the taxa table but it keeps giving error that the "tax_table slot is empty".

Here is my phyloseq- class object

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 28540 taxa and 20 samples ]
tax_table()   Taxonomy Table:    [ 28540 taxa by 7 taxonomic ranks ]

Please what does this mean and how can i resolve this issue.

Thanks

**Comment by benjjneb** [comment]
I think this is an issue with phyloseq, so should be posted to the phyloseq Issues forum: https://github.com/joey711/phyloseq/issues

You should include a bit more of the code that leads to that error, in particular how the `tax_table` object is defined (or if that is the literal code you are providing, the error is probably that you are passing in the function `tax_table` rather than `tax_table(my_phyloseq_object)`.
