### ISSUE TITLE
extract forward and reverse reads assigned to specific ASVs?

### ISSUE THREAD

**Issue by Krasnopeev** [benjjneb/dada2#1247]
Hi!

It is possible to extract from raw data forward and reverse reads assigned to specific ASVs?
for example: I need to extract raw reads pairs which were identified as "Cyanobacteria" and get filtered raw data with only cyanobacteria F and R reads.

Thanks!

**Comment by termithorbor** [comment]
Hi,

you can use the subset_taxa function:
ps_object_subset <- subset_taxa(ps_object, Class=="Cyanobacteria")

But I guess you merged the reads before so you can only extract the merged sequence. Why do you want the raw reads? 

I allways extract all "important information" like this:

family_species <- do.call(paste, c(as.data.frame(tax_table(ps_object_subset))
                                   [c("Family","Genus","Species")], 
                                   sep = "__"))  # to distinguish from "_" within tax ranks


# turn the asv_table into a data.frame
asv_export <- as.data.frame(otu_table(ps_object_subset)) #it is still called otu in phyloseq but it is not otu anymore due to dada2 output
tmp <- names(asv_export)

# paste wholetax and OTU_ids together
for(i in 1:length(tmp)){
  names(tmp)[i] = paste(family_species[i], tmp[i], sep = "__") # you can also use wholetax here!
}

# overwrite old names
names(asv_export) <- names(tmp)

#turn rownames into column
asv_export<-cbind(rownames(asv_export), data.frame(otu_export, row.names=NULL))


#transpose otu (switch columns and rows)
asv_export_transpose<- data.table::transpose(asv_export, keep.names = 'File') %>%
  row_to_names(1)

#export as excel sheet
write_xlsx(asv_export_transpose,"Subset_ASV.xlsx")

**Comment by Krasnopeev** [comment]
thanks @termithorbor for advise but I need raw reads or merged sequences for further analysis with another tool. I would like to screen unwanted reads to compare Cyanobacteria in different datasets.

**Comment by termithorbor** [comment]
With the tool extracting the ASV table you also extract the merged sequences.
