### ISSUE TITLE
Using merged reads as input

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#1252]
I am trying to use data from a paper for a comparative study. However, the authors have provided only the merged data i.e. raw paired-end reads merged using FLASH. The forward and reverse reads are not available separately.

Can I treat these as single-ended reads and run them through DADA2. Is this a valid approach given the constraint?

**Comment by benjjneb** [comment]
You can do that, and the results won't be completely wrong. BUT, there are likely to be more "false positives" than their usually would be, i.e. falsely detected ASVs, due to both the crude heuristics FLASH uses to assign quality scores in the overlap regions of the read, and the fact that the quality scores in the overlap regions and the unoverlapped regions probably don't relate the same way to the actual error rates.

**Comment by adityabandla** [comment]
Thanks, Ben, much appreciated!
