### ISSUE TITLE
Sequencing facility does not provide primer sequence for ITS

### ISSUE THREAD

**Issue by Lavandel** [benjjneb/dada2#1255]
The sequencing facility told me that their ITS2 primers are proprietary, so they cannot provide the sequences, but only the length of the primers. But, the sequences of the primers are needed to trim out the read-through to the opposite primers according to the ITS2 workflow (https://benjjneb.github.io/dada2/ITS_workflow.html). 

Is there any possibility to check if there are read-throughs and trim them out with only the length of the primers?

**Comment by and3k** [comment]
There is a `trimOverhang` option in the `mergePairs` command that should help.

You can also align your dominant sequences against UNITE or another database to find the primer binding site and use that sequence to trim (allowing some mismatches).

**Comment by Lavandel** [comment]
Thank you very much!

**Comment by benjjneb** [comment]
> The sequencing facility told me that their ITS2 primers are proprietary, so they cannot provide the sequences, but only the length of the primers.

That's ridiculous, at least if the primers are sequenced on the reads. You might want to verify with them that the primers are (or are not) sequenced as well.

**Comment by Lavandel** [comment]
They said they used DADA2 (https://benjjneb.github.io/dada2/tutorial_1_8.html) to process their ITS data as well with filterAndTrim function with only the primer length.  The facility said that it has proven to work well with the data.

**Comment by benjjneb** [comment]
Can they provide the successful DADA2 scripts they used at least then? I'm sure it can work well, but if you are redoing that processing yourself not knowing the primers leaves you flying blind.

**Comment by Lavandel** [comment]
They said the script is also proprietary so they cannot provide the script.

**Comment by benjjneb** [comment]
That doesn't leave us much to go on unfortunately. You can use the `trimOverhang` approach @and3k described above. That will mostly work but is not ideal (the untrimmed primer sequences will reduce sensitivity before you get to the merging step).

You can also try to "reverse-engineer" the primer sequences from the reads if that's something you feel comfortable trying to do.

Otherwise, I'd probably go with a sequencing provider that doesn't keep critical data processing information like what primers they are using [!] secret from their customers.
