### ISSUE TITLE
SILVA 138 species assignment 18S - correct train set?

### ISSUE THREAD

**Issue by naurasd** [benjjneb/dada2#1256]
Hi @benjjneb ,

I want to perform taxonomy assignment for ASVs infered from 18S amplicon sequencing - if possible down to species level.

Just wanted to know if I should use 

`silva_nr99_v138_wSpecies_train_set.fa.gz` with the `assignTaxonomy` function 

or

`silva_species_assignment_v138.fa.gz` with the `assignSpecies` functionfollowing assignment to genus level with  `silva_nr99_v138_train_set.fa.gz`?

What purpose does the `silva_nr99_v138_wSpecies_train_set.fa.gz` serve in the first place, if species level assignment for 16S for example is so challenging?

Thanks

Nauras

**Comment by benjjneb** [comment]
If it is standard short-read 16S, we recommend `assignTaxonomy(..., silva_nr99_v138_train_set.fa.gz)` followed by `addSpecies(..., silva_species_assignment_v138.fa.gz)`.

If it is long-read 16S, we recommend `assignTaxonomy(..., silva_nr99_v138_wSpecies_train_set.fa.gz)`.

The issue is that a specialized algorithm (unambiguous exact matching) is really needed for species-assignment to short-read 16S. For long-read 16S, the normal `assignTaxonomy` method with a species-level database works pretty well.

**Comment by naurasd** [comment]
I understand, thanks for the clarification. Please note that I was talking about 18S and not 16S though, does this apply for 18S as well?

**Comment by naurasd** [comment]
Hi again,

sorry I am a bit confused. I am performing 18S classification, not 16S.

Using the dada2 formatted `silva_nr99_v138_train_set.fa.gz` downloaded from here[https://zenodo.org/record/3986799#.YA_u2RZCc2w](url), none of my ASVs get assigned below kingdom level, except for Mitochondria. Isn't this train set also meant for eukaryotic SSU markers?

Cheers
Nauras

**Comment by benjjneb** [comment]
> sorry I am a bit confused. I am performing 18S classification, not 16S.

Oops! My bad on the reading comprehension.

> Using the dada2 formatted silva_nr99_v138_train_set.fa.gz downloaded from here, none of my ASVs get assigned below kingdom level, except for Mitochondria. Isn't this train set also meant for eukaryotic SSU markers?

No, the new formatting of the Silva db is not meant for Eukaryotic markers (almost all of the Euk portion was dropped).
You can use the previous formatting in Version 1 here: https://zenodo.org/record/3731176#.YBHTiHdKjUI

**Comment by naurasd** [comment]
Alright, thanks so much.

**Comment by naurasd** [comment]
Sorry, just reopened this briefly.

For short read 18S, the same applies as for 16S, so a 2-step `assignTaxonomy` folowed by `assignSpecies`?

Maybe it is a good idea to clarify on the Taxonomic reference data page that the links for the v138 formatted SILVA database are for prokaryotes only. The link you sent is not available on this page, maybe add this on there too?

cheers
Nauras

**Comment by benjjneb** [comment]
> For short read 18S, the same applies as for 16S, so a 2-step assignTaxonomy folowed by assignSpecies?

I have less confidence on this recommendation, since I have less experience with short-read 18S. But it won't hurt anything at least.

> Maybe it is a good idea to clarify on the Taxonomic reference data page that the links for the v138 formatted SILVA database are for prokaryotes only. The link you sent is not available on this page, maybe add this on there too?

Good point.

**Comment by naurasd** [comment]
thanks, as always.

**Comment by benjjneb** [comment]
Re-opening to track this issue until I fix the documentation on the taxonomic reference page.

**Comment by benjjneb** [comment]
The taxonomic reference page has been updated to include the text: "NOTE: As of Silva version 138, the official DADA2-formatted reference fastas are optimized for classification of Bacteria and Archaea, and are not suitable for classifying Eukaryotes."

**Comment by bathyscapher** [comment]
Hello benjjneb,
after I failed to classify eukaryotic sequences with dada2 and SILVA 138.1, I came across this thread. My I ask what is/was the reason to drop the support of eukaryote classification?

**Comment by benjjneb** [comment]
@bathyscapher This was done for computational performance reasons, in particular limiting the memory required to use the Silva database after we relaxed the previous pre-filtering of the database to include more Bacterial/Archael sequences.

This is something we may revisit, especially after the next Silva release (hopefully a not-too-far into the future "minor" version release) that we expect will fix some remaining taxonomic string parsing issues as well.

**Comment by bathyscapher** [comment]
I see... for the attempts to resolve eukaryotic microbiomes this is a huge disadvantage though. Is there the possibility that eukaryotes will be supported again in future? Maybe with two versions of the db (one for the pro- and one for the eukaryotes)?

**Comment by benjjneb** [comment]
> Is there the possibility that eukaryotes will be supported again in future? 

Yes. For now the previous versions of the Silva db (e.g. v132) for `assignTaxonomy` can still be used for Eukaryotes.

> Maybe with two versions of the db (one for the pro- and one for the eukaryotes)?

Either this or if we can improve memory performance we can go back to keeping everything together.

**Comment by bathyscapher** [comment]
Yaa, that would be great! Thank you for your answers :)

**Comment by seven-tenths** [comment]
Just following up on this issue with Dada2, SILVA 138 and Eukaryotes. Any update?

**Comment by seven-tenths** [comment]
@benjjneb Just following up on this issue with Dada2, SILVA 138 and Eukaryotes. Any update?

**Comment by Plankton-chris** [comment]
Hi @benjjneb, 

I am currently working with sequences from an Illumina MiSeq 250 platform (203 lake water samples). I used universal primers targeting V4-V5 regions. I processed my sequences with the DADA2 pipeline. I skipped the` collapseNoMismatch `step because after 8 days the task was still not complete on the high performance computing server. I use the SILVA 132 database formatted for dada2 (`silva_nr_v132_train_set.fa.gz`) with the `assignTaxonomy` function. I get in my taxonomy file 152,694 ASVs. 1280 ASV has no taxonomic assignment, ok that's not too bad. However, none of my Eukaryotic ASVs (i.e. 150 ASVs) have a taxonomic assignment below kingdom level. I will try other database, but what could explain this problem?  

Thanks for your help!

Chris

**Comment by benjjneb** [comment]
Are you expecting to capture Eukaryotes with these primers? If not, my guess is that the ASVs getting a Eukaryote Kingdom classification, but nothing else, are potential misclassifications of off-target amplification. The way I would check is to pull out the sequences from a few of them, maybe the 5 most abundant and another 5 random "Euk" ASVs, blast them on NCBI (https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome), and inspect the results. What are they hitting?

(Note: As of Silva v138, the dada2-formatted training files are only suitable for Prokaryotes, so if classifying Euks use Silva v132)

**Comment by Plankton-chris** [comment]
Yes, i'm expecting to capture Eukaryotes with this set of primers. Here's more info on them : 
<img width="923" alt="image" src="https://user-images.githubusercontent.com/101011374/160865103-75a8350a-74f1-414e-8d27-1eeb25a33e73.png">

I have to mention that i have 2 ASVs that have taxonomic level down to Phylum (Microsporidia), 1 ASV that have taxonomic level down to Order (Calanoida) and 1 ASV that have taxonomic level down to Genus (Distigma). 

As for the blast, seems that i am hitting for most ASV ( 5 most abundant and 5 random) uncultured bacterium, so yeah probably not a good sign i guess.
Here's the detailed results : [Blast.txt](https://github.com/benjjneb/dada2/files/8382008/Blast.txt)

So it's might be misclassification? but why I have no representatives of the eukaryote Kingdom..? Where should i investigate more?

Thanks a lot for your answers and time,

Kindly

Chris

**Comment by benjjneb** [comment]
> So it's might be misclassification? but why I have no representatives of the eukaryote Kingdom..? Where should i investigate more?

One possibility is that there is so little real Eukaryotic DNA in the sample, that it doesn't show up in the limited number of reads sequenced. That could be because Eukaryotes are present in a much lower numbers than bacteria, or also because the DNA extraction approach doesn't effectively liberate DNA from the types of Euks present in these samples.

Massive misclassification could do something similar, but doesn't seem likely (assuming most ASVs are classified to at least the order level). To be extra-safe, trying `assignTaxonomy(..., tryRC=TRUE)` would rule out any chance of read orientation issues.

**Comment by Plankton-chris** [comment]
Will do!

Thank you very much for your time and support. 

Chris
