### ISSUE TITLE
Doubt in using dada2 for preprocessing genomics data from illumina

### ISSUE THREAD

**Issue by balaTHLkuopio** [benjjneb/dada2#1258]
Hi,

I am planning to clean the fastq files sequenced for genomics purposes with dada2 although this tool is designed specifically for microbiome data. I find the cleaning process is great in dada2 pipeline and like to know from the author whether it is still applicable for genomics data as well atleast till preprocessing steps. After that, i can proceed with my own pipeline integrating tools for genomics.

### cleaning paired end fastq files obtained from whole genome sequencing data ###
##forward reads###WGS_S1_L001_R1_001.fastq.gz 
##reverse reads###WGS_S1_L001_R2_001.fastq.gz 
path <- "/path/to/fastqfiles"
fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
#### but you can get the maxEE value from figaro still to see which is good parameter to trim for unbiased approach ##
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(0,0),
              maxN=0, maxEE=c(2,1), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE)
##### get the quality processed reads as fastq reads by below code provided once by the dada2 author ###
for(nm in names(out)) {
    preprocessed <- out[[nm]]
    if(nrow(preprocessed) > 0) {
        uniquesToFasta(preprocessed, paste0("preprocessed_", nm, ".fasta"))
    }
}
OR

uniquesToFasta(out, '/path_to_fasta_file/uniques.fa', ids = paste0("SV", seq(length(getSequences(out)))))

Please correct me if i am wrong!

Best Regards,
Bala

**Comment by benjjneb** [comment]
Yes you can use the pre-processing in DADA2 for downstream applications in genomics, but as you are aware some of the options are tailored to the amplicon sequencing application for which the whole package is designed.

A couple things: Yes you probably don't want to use `truncLen` in the same way as in amplicon sequencing data. You should consider using `truncQ` however. This is because having filltering-induced length variation is fine for shotgun data (while it is not a good idea for amplicon data).

Figaro will not be useful to set a `maxEE` value here, that tool is for the specific case of paired-end amplicon data.

You will not want to use `uniquesToFasta` to output your preprocessed data. You'll just want to perform the filtering and trimming to create preprocessed fastq files. Then, to convert those files to fasta files, you can do the following:

```
library(ShortRead)
for(fl in my_preprocessed_files) {
  fa <- gsub("fastq$", "fasta", fl) # Defines new fasta file name as same as before, but with .fasta instead of .fastq extension
  writeFasta(readFastq(fl), fa, width=20000)
}
```
