### ISSUE TITLE
Suggestions on running R in windows 10 Multithreading and Parellization. What about MRAN?

### ISSUE THREAD

**Issue by lcamVz** [benjjneb/dada2#1267]
Hi, I've been trying to set DADA2 in a WSL2 system ubuntu 20. but also want to have an installation in windows 10 for other people in my lab. bad thing is that Windows 10 doesn't allow for multi threads but Microsoft has done their version of CRAN R called MRAN wanted to see what suggestions you might have for this scenario.

**Comment by benjjneb** [comment]
Windows 10 allows multi-threading. You can use dada2 as usual on Windows. The one exception is the `filterAndTrim` command, but all other commands multithread as usual with the `multithread=TRUE` flag.

**Comment by lcamVz** [comment]
That's what got me thinking about that step of the Filter and Trim. 

Thank you for the clarification!

**Comment by nweerasu** [comment]
Hello,

Just wondering if there's something I'm missing. I've run most of the dada2 Big Data, but once I'm at the removeBimeraDenovo(..., multithread=TRUE) parameter gives me:

Error in mclapply(mc.indices, loopFun, unqs.loop = unqs.int, allowOneOff = allowOneOff,  : 
  'mc.cores' > 1 is not supported on Windows

I'm on R 4.04, through R Studio. 
I had also tried using the Microsoft Open 4.0.3 which is supposedly made to help specifically with multithreading, but that gave me the same error. I assume it's with the forking vs multithreading on Windows, but that's as much as I could figure out from Google.
Let me know what other information you may need - thank you!

**Comment by benjjneb** [comment]
>  I assume it's with the forking vs multithreading on Windows, but that's as much as I could figure out from Google.

Yes, basically this. However, this only comes up in `removeBimeraDenovo` if you are not using the recommended and default `"consensus"` method. "consensus" chimera identification is multi-threaded using RcppParallel and will run on Windows in multithreaded mode just fine.

As a workaround, I'd suggest using that default "consensus" method, or running in single-threaded mode. It would be nice to move the multi-threading over to RcppParallel, but it's not a high priority since this is only affecting Windows users running a non-default mode of `removeBimeraDenovo`.

**Comment by nweerasu** [comment]
Thanks! That makes sense
