### ISSUE TITLE
OTU table output in .txt format

### ISSUE THREAD

**Issue by BPaarwater** [benjjneb/dada2#1273]
Good day, 

I hope you are well? I was wondering if you can maybe assist into getting an OTU table in the .txt format in order to make use in ampvis2 package. This will be really appreciated.

**Comment by benjjneb** [comment]
Isn't ampvis2 an R package? It's probably(?) easier to just use the R sequence table of dada2.

@KasperSkytte Any advice on how to import a dada2 sequence table (rownames are samples, colnames are sequences, values are read counts) into ampvis2?

**Comment by KasperSkytte** [comment]
Hi!

Thanks for tagging Benjamin. I used to work fine just fine, but it's been quite some time since I tested with DADA2. I see now that I have to adjust `amp_load()` a bit to make it compatible and work straight away. At the moment the easiest way to import the output from DADA2 directly into ampvis2 would be to go through `phyloseq` with a converter function, see https://madsalbertsen.github.io/ampvis2/articles/faq.html#loading-phyloseq-objects-1.

**Comment by KasperSkytte** [comment]
ampvis2 expects the abundance and taxonomy tables to be merged together in one table and not individual ones, which is really just an old in-house habit from the early days since people messed up the ordering of OTU/ASV's with two tables. I have long been wanting to have both options, I will implement it soon.

**Comment by KasperSkytte** [comment]
I have now updated `amp_load()` and tested with DADA2. Please refer to the documentation at https://madsalbertsen.github.io/ampvis2/reference/amp_load.html. Feel free to close this issue @benjjneb

**Comment by benjjneb** [comment]
Thanks @KasperSkytte !

Just for clarity for those who might come on this thread later, is below a correct example usage in the case of a DADA2?

```
# seqtab is DADA2 generated ASV table
# taxa is DADA2 generated taxonomy table
my.ampvis2.object <- amp_load(seqtab, taxonomy=taxa)
```

**Comment by KasperSkytte** [comment]
Yep, correct. And also loading some sample metadata is highly recommended for meaningful analyses.
