### ISSUE TITLE
Filtering negative control from some samples but not all of them Dada2

### ISSUE THREAD

**Issue by microjuliamey** [benjjneb/dada2#1278]
Hi Benji,

Here is my question : Is there a way to use "my negative control" to filter out the contaminants from **some** of my other samples? But not all of them. 

In fact, I am working with samples that come from the terrestrial subsurface. To get them, we had to use drilling fluid. But we used different driling fluids so a subset of my samples are contaminated with one drilling fluid and the others with an other drilling fluid.

I usually use this command :

control <- subset(as.data.frame(t(seqtab)), 'ctrl1' != 0) 
seqtab <- seqtab[-c(1),-which(colnames(seqtab) %in% rownames(control))] 

Here c(1) is the ctrl1 in seqtab.

But unfortunaltly this command doesn't allow me to select a part of the samples... 

Best,
Ju

**Comment by benjjneb** [comment]
I would probably try to simplify the code slightly. Also, `c(1)` is just evaluating as `1` in R which is not(?) what you might want? My simplified code attempt:

```
in.control <- seqtab['ctrl1',] > 0
seqtab.nocontam <- seqtab[,!in.control]
```

(it's also advisable to use a new data.frame rather than overwriting the previous one in these cases, so that the code can be re-run more consistently)

Now, if you want to drop taxa seen in the controls in just some of the real samples, something like the following should work:

```
samples.to.decontam <- [DEFINE THOSE SAMPLE HERE]
seqtab.nocontam.partial <- seqtab
seqtab.nocontam.partial[samples.to.decontam, in.control] <- 0
```

That code sets to zero the abundances of taxa found in the control sample, only in those samples defined in that initial vector.
