### ISSUE TITLE
0.36.0 version of Biocgeneric is not getting downloaded

### ISSUE THREAD

**Issue by Ruddhida** [benjjneb/dada2#1294]
When checking for the loaded packages after running the code- 
library("knitr")
library("BiocStyle")
.cran_packages <- c("ggplot2", "gridExtra")
.bioc_packages <- c("dada2", "phyloseq", "DECIPHER", "phangorn")
.inst <- .cran_packages %in% installed.packages()
if(any(!.inst)) {
   install.packages(.cran_packages[!.inst])
}
.inst <- .bioc_packages %in% installed.packages()
if(any(!.inst)) {
   source("http://bioconductor.org/biocLite.R")
   biocLite(.bioc_packages[!.inst], ask = F)
}
# Load packages into session, and print package version
sapply(c(.cran_packages, .bioc_packages), require, character.only = TRUE)

it is showing the below message.
"the necessary packages can not open compressed file 'C:/Users/hp/Documents/R/win-library/4.0/BiocGenerics/DESCRIPTION', probable reason 'No such file or directory"

When we are downloading the 0.36.0 version of Biocgeneric, 0.34.0 is getting downloaded from Bioconductor.

**Comment by benjjneb** [comment]
I see that you've opened several issues in the past day. From my end, these issues don't have enough information to really help you, and seem primarily related to installing packages in R rather than the dada2 R package itself.

Question: Are you completely new to working in the R environment?

If so, some basic background on installing packages and working with the R environment might help you get started.

Suggestion: If trying to get DADA2 up and running, start with the tutorial workflow rather than the F1000 workflow: https://benjjneb.github.io/dada2/tutorial.html

The tutorial workflow provides more description and trouble-shooting help, and is also more updated. See also the "Install" link at the top of that website, which gives the currently recommended way to install Bioconductor packages such as DADA2.

**Comment by Ruddhida** [comment]
When i downloaded the biocgeneric from bioconductor its getting downloaded
but while installation its again 0.34.0

**Comment by benjjneb** [comment]
Assuming you are installing using `BiocManager::install`, you need to check the version of `BiocManager` you have. It should be 3.12 in order to get version 0.34.0 of the Biocgenerics package.

```
BiocManager::version()
```

Does that return 3.12? Also, what version of R do you have installed?

```
R.version
```
