### ISSUE TITLE
Does assigntaxonomy remove some reference sequences from customized DB?

### ISSUE THREAD

**Issue by mammerlin** [benjjneb/dada2#1315]
Hi,
I was wondering if assigntaxonomy remove some reference sequences from customized DB.
The customized reference DB I used contains 370K sequences. 
Some sequences have the same rank level name which sequences are not 100% identical.

$ grep '>' 20210401.Refseq.silva.fa|head
>Bacteria;Firmicutes;Bacilli;Bacillales;Listeriaceae;Listeria;Listeria riparia
>Bacteria;Spirochaetes;Spirochaetia;Spirochaetales;Spirochaetaceae;Treponema;Treponema socranskii
>Bacteria;Firmicutes;Bacilli;Lactobacillales;Lactobacillaceae;Lactobacillus;Lactobacillus gasseri
>Bacteria;Tenericutes;Mollicutes;Mycoplasmatales;Mycoplasmataceae;Mycoplasma;Mycoplasma mycoides
>Bacteria;Tenericutes;Mollicutes;Mycoplasmatales;Mycoplasmataceae;Mycoplasma;Mycoplasma capricolum
>Bacteria;Tenericutes;Mollicutes;Mycoplasmatales;Mycoplasmataceae;Mycoplasma;Mycoplasma capricolum
>Bacteria;Tenericutes;Mollicutes;Mycoplasmatales;Mycoplasmataceae;Mycoplasma;Mycoplasma leachii
>Bacteria;Proteobacteria;Betaproteobacteria;Neisseriales;Neisseriaceae;unknown.genus;Neisseriaceae bacterium DSM 100970
>Bacteria;Proteobacteria;Betaproteobacteria;Neisseriales;Neisseriaceae;unknown.genus;Neisseriaceae bacterium DSM 100970
>Bacteria;unknown.phylum;unknown.class;unknown.order;unknown.family;unknown.genus;uncultured bacterium
>Bacteria;unknown.phylum;unknown.class;unknown.order;unknown.family;unknown.genus;uncultured bacterium
>Bacteria;unknown.phylum;unknown.class;unknown.order;unknown.family;unknown.genus;uncultured bacterium
>Bacteria;unknown.phylum;unknown.class;unknown.order;unknown.family;unknown.genus;uncultured bacterium

I have two questions.
First, in assignTaxonomy function, the integer maps are created from reference to type ("genus") and for each tax level. Do those sequences with the same rank level would be treated as the same one?

Second, I compare the result from DADA2's assignTaxonomy  with Blast result. I found DADA2 skip (or discard?) uncultured bacterium or unknown.xxx perfectly. Doese DADA2's assignTaxonomy process those rank level header?

For example, here is the result of ASV_1002 from blast. I remove rank level1-3 from sseqid to make them more readable.

>sseqid                                                                                                           qseqid          pident   evalue score qcovs
>unknown.order;unknown.family;unknown.genus;uncultured_bacterium ASV_1003          94.165      0  1124    93
>Pasteurellales;Pasteurellaceae;Haemophilus;Haemophilus_sp._Smarlab_3302188 ASV_1003          93.729      0  1187   100

Here is the result from DADA2's assignTaxonomy.

>                            order           family        genus                    species
>ASV_1003 Pasteurellales Pasteurellaceae Haemophilus Haemophilus sp. Smarlab 3302188

As you can see, the first blast hit has higher percent identity and query coverage. But DADA's would not match to this reference sequence. 

Is there any filter rule embedded in assignTaxonomy  function?

Thanks.

**Comment by benjjneb** [comment]
> Is there any filter rule embedded in assignTaxonomy function?

There is not a filter rule that should be removing such entries in `assignTaxonomy`. The only filtering performed on the reference sequences by `assignTaxonomy` is to remove reference entries below a minimum length of 20. (caveat, if UNITE format is detected a bit more filtering is done).

> As you can see, the first blast hit has higher percent identity and query coverage. But DADA's would not match to this reference sequence.

If I'm reading the BLAST entry right, the first entry has a higher percent ID (94.165), but a lower query coverage (93) than the second entry (93.729 ID and 100 coverage). This suggests that over the full query, the second entry is probably a better match than the first, as local alignments like those made by BLAST will cut off portions where mismatches are found.

**Comment by benjjneb** [comment]
The sequence comparison methods used by `assignTaxonomy` and BLAST are quite different (and there are many methods within BLAST as well). `assignTaxonomy` is breaking the query and reference sequence into short kmers (8-mers) and then comparing kmer profiles. BLAST is doing a search for local alignments, with a variety of heuristics to improve speed based on choice of BLAST algorithm and parameters.

Diagnosing issues in custom reference databases is difficult, as it's hard to know all the ins and outs of the custom databases though. In this example, it even appears that the outlined entry in the BLAST results isn't the same as the `assignTaxonomy` best hit, as one is _B. wexlerae_ and the other _B. obeum_.

Probably the best way to move forward would be to generate a minimal example, i.e. a very small reference fasta and a single query sequence that show the suggested behavior -- a mismatch between the `assignTaxonomy` results and the BLAST best hits.

**Comment by salix-d** [comment]
>First, in assignTaxonomy function, the integer maps are created from reference to type ("genus") and for each tax level. Do those sequences with the same rank level would be treated as the same one?

The sequences aren't treated as the same one, but they are treated as a group.

>Second, I compare the result from DADA2's assignTaxonomy with Blast result. I found DADA2 skip (or discard?) uncultured bacterium or unknown.xxx perfectly. Doese DADA2's assignTaxonomy process those rank level header?

No, but I also noticed that they do get skip _sometimes_. The reason being the previous answer. From what I got looking at the functions(r and c ones), assignTaxonomy  looks at all the sequences for each taxa, compare them with the sequence to assign, and choose the taxa that has both the most similar sequences to it and the biggest proportion of sequences that matches. 
In your case, assuming you have more unknowns than the 10 showed here, it's possible that they would be from various taxa (not phylogeneticly close), and so chances are that the total sequences of the unknown taxa are just too varied to let assignTaxonomy() think that it would be the an appropriate match. 

When unknowns have some known ranks, one thing that can help is to change the unknowns with [last known taxa]_unknown_[actual taxa], like Firmicutes_unknown_class;Firmicutes_unknown_order; etc. But since the unknowns in your DB seem to all start at the phylum level, I'm not sure that it would useful for your case.

You could also possibly make a DB in the assignSpecies format to look for exact match to these sequences and overwrite wrongly assigned taxa, but it wouldn't get you approximate matches. (if you could get the ids of the uncultured bacterium, tho, it might give more interesting results)

Also, the assignement (with blast or dada2) does only tell you 'this is it's closest known taxa'. So considering that dada2 assigned it to the genus, I'd say it's probable that those uncultered bacterium might be in the same genus, or at least family. So depending on the goal here, you might be getting more information with the dada2 assignment.
