### ISSUE TITLE
difference between SILVA DBs 

### ISSUE THREAD

**Issue by AnaMariaCabello** [benjjneb/dada2#1319]
Dear Ben,
What's the difference between "silva_nr99_v138.1_train_set.fa.gz" and silva_nr99_v138.1_wSpecies_train_set.fa.gz?

Thanks,
Ana

**Comment by benjjneb** [comment]
The `wSpecies` file includes taxonomy designations down the species level, as gleaned from the binomial names included in the Silva database. The other file only goes down to the genus level, which is as far as Silva's official taxonomy goes.

**Comment by AnaMariaCabello** [comment]
> The `wSpecies` file includes taxonomy designations down the species level, as gleaned from the binomial names included in the Silva database. The other file only goes down to the genus level, which is as far as Silva's official taxonomy goes.

**Comment by AnaMariaCabello** [comment]
Ok, Thanks! So, does this wSpecies file replace this additional step? 
"addSpecies(taxa, "~/tax/silva_species_assignment_v132.fa.gz")"

**Comment by benjjneb** [comment]
For short-read 16S sequencing, we recommend using `assignTaxonomy` down to the genus level, and then the `addSpecies` step for species assignment (this uses a different algorithm for the species-assignment step).

For long-read 16S sequencing, we recommend using `assignTaxonomy` down to the species level, so using the `wSpecies` reference.

**Comment by AnaMariaCabello** [comment]
Thank you so much! as always!!

**Comment by Lebyleb** [comment]
Dear Benjamin, 

I am currently working on short-read 16S sequencing (V4-V6). Based on the discussion above, you recommend using assignTaxonomy up to the genus level (with silva_nr99_v138.1_train_set.fa.gz reference), and then the addSpecies step for species assignment (with silva_species_assignment_v138.1.fa.gz reference) rather than assignTaxonomy up to the species level (silva_nr99_v138.1_wSpecies_train_set.fa.gz reference). However, when testing both methods on my dataset, AssignTaxonomy up to the species level (with silva_nr99_v138.1_wSpecies_train_set.fa.gz)  seems to give better results ( less NA for genus and species  levels). Do you have any idea for such results? Which method should I use?

Thanks in advance,

Yohan

**Comment by benjjneb** [comment]
We haven't done systematic comparisons for every possible 16S gene region. My guess is that the recommended short-read approach (`assignTaxonomy` to genus, then `assignSpecies` if wanting species-level) might be more accurate. Less "NA" is not necessarily a good thing if the assignment its replaced with isn't correct.

**Comment by Lebyleb** [comment]
Thank you very much for your quick and clear response! 

Best regards,

Yohan
