### ISSUE TITLE
dada2 at different read length

### ISSUE THREAD

**Issue by ARW-UBT** [benjjneb/dada2#1325]
Would you expect that trimming fastq sequences (of the same Illumina run) to different length will result in different numbers of ASVs detected by the dada2 pipeline? 
 
Background: 
We have sequenced 16S amplicon libraries on an Illumina iSeq-100 in a ‘non-official’ 292 bp mode (the software allowed us to sequence longer R1 reads, although it is not officially supported by Illumina). Using this mode, we circumvent to problems joining R1 and R2 reads of 16S amplicons (515F/806R) by 150-bp-machines such as HiSeq and iSeq-100. However, I have to compare these longer reads with previous data obtained on the same sequencer in the 150 bp paired-end mode. For this, I truncated the 292 bp reads to 150 bp and fed theses data to dada2 in Qiime2. 
I realized that the number of ASVs produced by the long 272 bp sequences (I removed the last 20 bp representing the R2 primer sequences) is ca. 10% lower compared to the same R1 reads truncated to 150 bp. I assume that this is due to the fact, that DADA2 can parameterize its error model from the data itself (https://benjjneb.github.io/dada2/).  I have tried to find some hint whether the fastq length is involved in the dada2 algorithm in your 2016 paper, but could not find a clear answer. 
 
I would appreciate if you could shortly comment on this.

**Comment by benjjneb** [comment]
Good question. There are two competing things going on that will affect the total number of ASVs detected.

First, the longer amplicon region will capture some diversity that the shorter region didn't. This will intend to increase total ASVs (although by less than is often expected).

Second, the longer amplicon region will produce fewer error-free reads. This will tend to decrease the total ASVs detected. The reason for this is that DADA2 relies on at least two (by default) error-free reads of an ASV to be present in order to identify it, and thereby detect that ASV. Longer amplicons will produce a lower fraction of error-free ASVs. This effect is rather minor when quality scores stay high, but becomes more pronounced when the longer amplicon extends into the part of the read where quality scores drop.

So, the modest decrease in total ASVs you are seeing is not unexpected for this second reason. It is expected that this loss in ASVs will occur almost entirely among low-abundance ASVs.

**Comment by ARW-UBT** [comment]
Thank you for the detailed descriptions. In particular, the second aspect seems to be very important as we detect significantely higher sequence qualities with the CMOS flow cell in the new benchtop machine at longer read length compared to MiSeq.
