### ISSUE TITLE
recommended software/parameters for tree reconstruction

### ISSUE THREAD

**Issue by csmiguel** [benjjneb/dada2#1348]
I would appreciate recommendations on software and parameters for tree reconstruction from thousands of sequences from metabarcoding data (ie 5000 sequences of ~425nt from 16S).
- it was suggested to move from phangorn to raxml in [issue 88](https://github.com/benjjneb/dada2/issues/88).
- at the moment, I am running raxml with the "standard" "-f a -N 100 -m GTRGAMMAIX". However, the running time is very long as raxml is forced to finely tune parameters which are probably not necessary for metabarcoding data (often short sequences).
- the creator of raxml suggests turning off bootstrapping, activating fast tree searches with "-f E" or "-f F", and using the "-m GTRCAT" model of evolution (https://groups.google.com/g/raxml/c/9purYfDDJzE/m/vPwX05-vCQAJ). Any experience with this?
- an alternative could be to use FastTree (https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0027731).
Any suggestions? thanks

**Comment by benjjneb** [comment]
I can say that FastTree is widely used for tree-ing short read 16S, perhaps in part because I think it was the default method in QIIME1. RaxML is a very good tool that covers many types of tree construction. It will work, but the parameter choices are important.

However, I don't have any good suggestions, as building de novo trees from short-read 16S is not something I typically do.

Suggestions welcome!

**Comment by ktmbiome** [comment]
I'm also interested in alternative tree-building methods. I am working with a 16s dataset now that contains over 50,000 ASVs after filtering to a level we're comfortable with and our amazing HPC can't handle it with the phangorn/DECIPHER combo (takes about three days and fails with a memory crash). 

@benjjneb, are you suggesting that you typically don't work with short-read 16s? Or that you build trees by alignment to a known bacterial tree? I've been thinking about making this kind of change to our lab's in-house pipeline -- basically aligning to a known bacterial tree to build my 16S tree -- but haven't figured out the particulars of that yet. To some extent, it would be nice to get out of _de novo_ tree-building.

So mostly posting to follow, but also mentioning that I'm needing to start look into these things, and if I find anything new, I'm happy to share.

**Comment by benjjneb** [comment]
> @benjjneb, are you suggesting that you typically don't work with short-read 16s? Or that you build trees by alignment to a known bacterial tree?

I personally don't usually use de novo trees for short-read 16S because most often I'm not including phylogeny in my analyses, or I'm using a reference tree. But, when I do make de novo trees, I just use FastTree and accept that while it's not perfect, it's good enough for capturing the high-level phylogeny at least, which is usually all I need for my subsequenty phylo-aware analyses.

**Comment by andreiprodan** [comment]
For ASV tree building I'd go Fastree2 Double Precision/ IQTree / RAXML (from fastest to most accurate). Fastree2 Dbl is probably just fine for most ASV-focused purposes (e.g. Unifrac distance calculation). For the multiple sequence alignment (MSA) needed to make the tree, I'd go MAFFT (or MUSCLE, if on Windows).

**Comment by ktmbiome** [comment]
I'm considering implementing SINA (https://github.com/epruesse/SINA) into our pipeline, since I've been interested in bringing back some level of reference-based tree building. In their methods, it looks like they do a first-pass SINA tree and then go back and implement FastTree for anything that doesn't align, but having a sense of what doesn't align would likely serve as an additional quality control. Does anyone have any takes on this?
