### ISSUE TITLE
Error in filterAndTrim

### ISSUE THREAD

**Issue by rwiscor** [benjjneb/dada2#1367]
Hi

I'm trying to follow the DADA2 Pipeline Tutorial (1.16) and ran into the following error for filterAndTrim function:

Error in filterAndTrim(fnFs, filtFs, truncLen = 100, maxN = 0, maxEE = 2,  : 
  These are the errors (up to 5) encountered in individual cores...
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': invalid class “SRFilterResult” object: superclass "Mnumeric" not defined in the environment of the object's class

I'm currently using dada2_1.18.0

Any information will greatly be appreciate. Thank you in advance :)

**Comment by benjjneb** [comment]
This bug was introduced when the Matrix package moved to version 1.3.3. This is fixed in the latest releae (1.20.0). Otherwise you can downgrade the Matrix package.

See https://github.com/benjjneb/dada2/issues/212#issuecomment-836757295 for that workaround, and https://github.com/benjjneb/dada2/issues/212#issuecomment-841703077 for the latest fixed version.

**Comment by rwiscor** [comment]
Thank you sooo much. I didn't know there was a 1.20 version. Because I had
an older version of R it downloaded version 1.18 of dada2

Thank you :)
