### ISSUE TITLE
there are big differences in the length of forward and reverse sequences after filtering

### ISSUE THREAD

**Issue by FengqingWang0712** [benjjneb/dada2#1383]
Hello @benjjneb,
I met two problems via using dada2. One is that there are big differences in the length of forward and reverse sequences after filtering; the other one is that nearly 70% of data are missing after merge.
Here is my code: filterAndTrim(fnFs, filtFs, fnRs, filtRs,minLen=175,matchIDs=TRUE,maxEE=c(5,5),compress=TRUE, multithread=20)
mergers <- mergePairs(dadaFs, fw_derep, dadaRs, rv_derep,minOverlap=20,verbose=TRUE)

I also tried to change the minOverlap=5, it's similar that nearly 70% of data are missing after merge.
[180301_F_filt.fastq.gz](https://github.com/benjjneb/dada2/files/6858102/180301_F_filt.fastq.gz)
[180301_R_filt.fastq.gz](https://github.com/benjjneb/dada2/files/6858103/180301_R_filt.fastq.gz)
[180301.R2.fastq.gz](https://github.com/benjjneb/dada2/files/6858123/180301.R2.fastq.gz)
[180301.R1.fastq.gz](https://github.com/benjjneb/dada2/files/6858124/180301.R1.fastq.gz)

I attached one example of my sequences. Could you help me find out the reason? Thanks a lot.

Best,
Fengqing

**Comment by benjjneb** [comment]
What primer set are you using, and what is the expected length of the sequenced amplicon?

Also, am I correct that some pre-processing was performed on (e.g.) `180301_F_filt.fastq.gz` to remove primers that were originally present at the start of the sequences?

**Comment by FengqingWang0712** [comment]
Thanks for your reply. The primer set is 341F and 805R. The expected length of each is ~250 bp and ~450bp after merge. Yes. I did the process to remove the barcode and primers. As I got the abnormal filtering and merged results from dada2, so I am not 100% sure if it is successful now.

BYW. The 180301.R1.fastq.gz is raw reads after removing the barcode and primer. The 180301_F_filt.fastq.gz is the result I got from dada2 after running filterAndTrim.

**Comment by benjjneb** [comment]
Provided this is a standard setup (primers of constant length at the start of the reads) I would recommend using the `trimLeft` parameter in `filterAndTrim` to remove the primers, rather than an external program. I would also inspect the `plotQualityProfile` results on forward and reverse reads, and determine what `truncLen` should be to reduce the number of low quality bases, with the understanding that the sum of the forward and reverse truncation lengths should be `460 + 20` or longer to ensure enough overlap for good merging.

Then it would be helpful to see what the stats are for read passage through the entire workflow, as is shown in the tutorial: https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline

**Comment by FengqingWang0712** [comment]
Thanks for your reply. I found the reason and sort out the problem. Thanks a lot.
