### ISSUE TITLE
Merging technical replicates

### ISSUE THREAD

**Issue by aflandau** [benjjneb/dada2#1397]
Hi all,

I have sequences from three technical replicates per sample that were included in the same sequencing run to reach a good number of reads. These are named *-R-1.fastq, *-R-2.fastq, *-R-3.fastq. For these I am wondering about the best way to go and how this is done in DADA2. 

1) Split them into three different "runs" before analysis and merge the sequence variant tables using mergeSequenceTable in order to work with only one sequence table per sample?
2) Keep the 3 technical replicates in the same data set during the initial analysis and merge the samples before the taxa assignment in order to work with only one sequence table per sample?
3) Keep the 3 technical replicates separately during the whole analysis and work with 3 sequence tables per sample, which would artificially create more samples than were actually taken?

I assume there are "cleaner ways" to proceed with the samples, which I did not think of yet. I'm happy to get any insight, thanks in advance.

Alex.

**Comment by benjjneb** [comment]
Since they were all sequeenced in the same run, they should be processed together as one "batch" in the DADA2 stage. That should give you a sequence table with three rows (technical samples) per biological sample.

Typically I would keep the table in that format for subsequent analysis in many (most?) cases, as it allows technical variation to be quantified. But, if you just want to collapse the technical variation, one can simply create a new sequence table at that point that has one row corresponding to each biological sample, with values equal to the total number of reads from each ASV seen across the three technical replicates. Since sequence tables are matrices in R, the `rowsum` function will do that cleanly.

**Comment by aflandau** [comment]
Hi Ben,

many thanks for the advice. The suggested procedure was also my "favorite" as it seems to be the cleanest and most defensible option.

Best regards,
Alex
