### ISSUE TITLE
DADA2 inferred 0 sample sequences present in the Mock community: DADA2 Pipeline Tutorial (1.16)

### ISSUE THREAD

**Issue by Nillesworld** [benjjneb/dada2#1401]
Hello everyone,
I currently started using the DADA2 package.
Thanks a lot in advance for the programm.

So I am trying to recreate the DADA2 Pipeline Tutorial (1.16), because I ran into some problems with the older versions I upgraded to hopefully the newest versions, here my session info:
![Session Info R DADA2](https://user-images.githubusercontent.com/89575380/130929598-1504cab6-5974-4e7f-b4d2-965f672dd600.PNG)

So I checked my results and until "Remove chimeras" everything is fine, but my "> sum(seqtab.nochim)/sum(seqtab)"
is 0.9640374, but in the tutorial it is 0.964263.

Which leads to slightly different 
![head track](https://user-images.githubusercontent.com/89575380/130930436-b5d49a95-4488-476c-aece-52ac60eff580.PNG)

And in the end leads to this:
> cat("DADA2 inferred", length(unqs.mock), "sample sequences present in the Mock community.\n")
DADA2 inferred 0 sample sequences present in the Mock community.

I really tried a lot of things like using different version of R, different versions of the Bioconductor, opening in different sessions.

I hope someone could help me, I am kind of lost.

Cheers

**Comment by benjjneb** [comment]
> So I checked my results and until "Remove chimeras" everything is fine, but my "> sum(seqtab.nochim)/sum(seqtab)"
is 0.9640374, but in the tutorial it is 0.964263.

Very small differences like this have cropped up between versions, perhaps because of bug fixes or because of usually edge-case improvements in function operation. This shouldn't concern you that your installation of DADA2 is acting inappropriately.

> cat("DADA2 inferred", length(unqs.mock), "sample sequences present in the Mock community.\n")
DADA2 inferred 0 sample sequences present in the Mock community.

The first place I would look here is at the input files. What does the reference fasta file for the mock community `HMP_MOCK.v35.fasta` look like on your machine? Is it as expected? 

Also, what does the mock community row in the sequence table look like? e.g. `seqtab.nochim["Mock",]`. Are there lots of non-zero entries?
