### ISSUE TITLE
Construct phylogenetic tree - max number sequences?

### ISSUE THREAD

**Issue by rjhuang5** [benjjneb/dada2#1410]
Dear Benjamin,

I'm trying to create a phy_tree from seqtabNoC. I have paired-end 16s V3V4 data from human stomach biopsies (low prokaryote abundance relative to eukaryote).

My sample size is as follows: > dim(seqtabNoC)
[1]   198 54650

I am trying to use DECPIHER to align sequences: 
alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA,verbose=FALSE)

However I've been waiting about 24 hours on the server without any results.

I know this issue was discussed a few years ago (https://github.com/benjjneb/dada2/issues/88). One idea is to build the tree using raxml, but it seems giriarteS still used DECIPHER for the sequence alignment step.

Should I just be patient or is there a way to perform sequence alignment in an external program?

Thanks,
Rob

**Comment by benjjneb** [comment]
> Should I just be patient or is there a way to perform sequence alignment in an external program?

For large numbers of ASVs (>10k) you are probably best served in using an external-to-R multiple aligner and tree building program if you want to create a phylogenetic tree.

**Comment by masumistadler** [comment]
Hello,
it's been a while since this was discussed but I wanted to chime in here and ask a similar question. I too, have a big data set (>100 000 sequences) and have been encountering issues with aligning the sequences using DECIPHER. 

It took several days, but I had run the AlignSeqs() function with the default anchor=0.7 a while ago for a different step.  I had saved the output of this run and was wondering if I can use it to construct the phylogenetic tree. I've tried re-running the AlignSeqs() function with anchor=NA without success. I tried to read through the documentation, but I didn't quite understand why removing the anchors is essential.

If keeping the anchor=NA is crucial, do you have a recommendation for another software to align sequences? I've searched around and MUSCLE seems to be an option?

Thank you in advance!

Best,
Masumi

**Comment by benjjneb** [comment]
There are various options, including aligning against a reference database (the old method commonly used for 16S there was NAST), or something like MUSCLE/MAFFT. I don't have any specific recommendation as to the best possible current tool. I imagine they mostly will work "good enough" given the limitations inherent to a phylogeny reproduced from a single fragment of a marker gene.
