### ISSUE TITLE
ShortRead Package and Number of ASV reads changing

### ISSUE THREAD

**Issue by markdjohnson** [benjjneb/dada2#1414]
Hi Ben,

I had two quick questions for you. First, I was attempting to use the ShortRead package and the write.fasta function and I got the message: 
Installing package into ‘C:/Users/markd/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning message:
package ‘ShortRead’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
> 
Do I just need to update R? But if I do so will it throw off all the other DADA2 functions?

My second question is, I was exploring the number of reads with cs<- colSums(seqtab.nochim) and I noticed that the number of reads and ASVs were different than when I ran them a couple of months ago. The ASV at the top was still for the same species but the number of reads associated with it were slightly different. Is this normal? 

Thank you,
Mark

**Comment by benjjneb** [comment]
> Warning message:
package ‘ShortRead’ is not available for this version of R

I'm not sure why you are getting this warning. Can you `library(ShortRead)` and load it into R already? If you are already running dada2, then you necessarily do have ShortRead installed, as the dada2 R package requires it.

> My second question is, I was exploring the number of reads with cs<- colSums(seqtab.nochim) and I noticed that the number of reads and ASVs were different than when I ran them a couple of months ago. The ASV at the top was still for the same species but the number of reads associated with it were slightly different. Is this normal?

If you changed versions of the package, then this sort of minor variation can happen. It should be quite minor, but there have been various small bugs or edge cases that have been fixed in recent versions that can cause minor changes in ASV counts.
