### ISSUE TITLE
Sample identifiers from single file fastq headers

### ISSUE THREAD

**Issue by derele** [benjjneb/dada2#143]
Would it be possible to stratify the "drep-class and dada-class" objects by sample based on patterns in the fastq-headers from a single file instead of names of the multiple files given?

Usually people get their samples stratified in different files by the index-calling but in my case (I have many different amplicons and stratify by primer-pair keeping the sample-info in the fastq headers),  I would benefit from a feature to do so. This feature would also make dada2's different steps more exchangable with usearch/uparse where [this feature is present](http://drive5.com/usearch/manual/upp_labels_sample.html).

**Comment by derele** [comment]
Seeing that FastqStreamer is used (and understanding how this works) I guess it is the easiest to write something using `tempfile()` like your `DerepFasta()`.
I will try and see wether what I come up with is worth sharing and do so in case.

**Comment by benjjneb** [comment]
I'm a bit hesitant to add this in, largely because we are making an intentional decision to stay out of the demultiplexing business because of the high support burden that comes with keeping up with the still various formats across sequencing centers/platforms. Having a single officially supported entry format (per-sample fastqs) into the dada2 workflow keeps things much more manageable for us.

However, a solution like `derepFasta` (i.e. splitting the input file into individual temp-files that are then read-in by `derepFastq` as normal) would probably be simple and effective, and I can see how it would be useful to more easily process usearch-format files. 

If you wrote a function that worked I would be happy to add it to the package, although probably as an unexported function (like `derepFasta`) at first. Unexported functions are there for expert users, but don't come with the same support commitments that the "official" API of exported functions have.

**Comment by derele** [comment]
Sounds very reasonable! Especially in a fiel in which too much software tries to do everything and fails to do anything properly . 
 
```R
derepMultiSampleFastq <- function(fls, headerRegex="RECORD:(.*?)_S.*", n=1e6, ...){
    samplefiles <- character()
    for(file in fls) {
        f <- FastqStreamer(file, n = n)
        while( length(suppressWarnings(fq <- yield(f))) ){
            samples <- sub(headerRegex, "\\1", id(fq))
            ## get the uniqes samples in sequential order
            uni.samples <- sort(unique(samples))
            ## factor to map unique values to sequential integers
            map <- as.numeric(factor(samples))
            for (i in seq_along(uni.samples)){                
                tmppath <- paste0(tempfile(tmpdir="/tmp"), basename(file),
                                  uni.samples[[i]], ".fastq")
                ## lazy append for further stream   
                writeFastq(fq[map%in%i] , file=tmppath, mode="a")
                samplefiles <- append(samplefiles, tmppath)
            }
        }
    }
    derepFastq(samplefiles, ...)
}
```
I enjoyed very much  browsing through the code of your package in the attempt to come up with something more clever than the above. And using it is a pleasure anyways!

**Comment by benjjneb** [comment]
The code looks reasonable to me. In order to add it to the package (as an unexported method) I need two more things: (1) an example multi-sample fastq file I can test it on, and (2) a simple description (1 sentence -- 1 paragraph) that describes what it does, for its documented description.

It's also OK to just leave it in this thread, as the code will be discoverable via web searches (but not via inspecting the package itself).

**Comment by derele** [comment]
Okay! Will do both at the end of the week!

One more question: What speaks against moving the naming of the samples > derep > dada objects into derepFastq? I am tempted to add this for DerepMultiSampleFastq as it has to mess with regular expressions anyways. 

But also or your general derepFastq: Would it make sense to allow extraction of a name from a filename via an optional regex (default staying as is, no regex, no name)?

I could provide both in two commits via pull request.

**Comment by benjjneb** [comment]
Naming the DerepMultiSampleFastq returns by the sample names would make sense, since they are being extracted from the fastq.

As for the normal `derepFastq`, I have considered naming the returns, but just by the filename. If a user is prepared to write a regex to turn filenames into sample names, they can do so in the next line in R, so adding that into the function just seems like complexity with little-to-no payout.

**Comment by derele** [comment]
Yes, okay! And yes, having the filname as default in the `derepFastq` would mak esense.

For DerepMultiSampleFasta it is different: As the files are genereated in `/tmp` you probably don't want to mess with getting the object names from those. And as the functions anyways need to regex-extract I'll add this directly in. 

I will test the function for a couple of days myself and then provide you with a test-fastq file and the help file for the function.

**Comment by derele** [comment]
Hi there,
motivated by dada2 and phyloseq I took another look into writing a bioconductor package (maily the S4 classes were a hinderance for me sofar) and  decided to go a different route: I replaced a dodgy perl-script in my pre-processing (which actually produced the multi-sample-but-single-amplicon fastqs) with bioconductor/Biostrings. So much faster, so much cleaner...
I plan to build this into a small package for multi-amplicon processing (matching and cutting of primer sequences) wrapping around dada2. I want to avoid duplication of efforts and do something that you could do better: You do not plan to add this, right?

Back to on topic: I will still provide the multi-amplicon combined file for testing above. I just need another week for testing my two approaches against each other.

**Comment by elsherbini** [comment]
@derele Though it is not written in R, I can't help but plug [caravan](https://github.com/swo/caravan), a amplicon-processing pipeline written by @swo and that I help maintain. It is a modular framework for amplicon processing, and works well for the steps leading into the dada2 pipeline (demultiplexing, primer trimming, and even quality filtering/ truncating). Would love to have another contributor if you know python.

**Comment by benjjneb** [comment]
> I plan to build this into a small package for multi-amplicon processing (matching and cutting of primer sequences) wrapping around dada2. I want to avoid duplication of efforts and do something that you could do better: You do not plan to add this, right?

Sounds like a good project. And I can confirm that we do not plan on adding that sort of functionality to dada2.
