### ISSUE TITLE
reformatting sequence table for assigning taxa?

### ISSUE THREAD

**Issue by marwa38** [benjjneb/dada2#1468]
Hello 

After using microdecon for decontamination I got that error when I ran taxonomy on the sequence table. 
Not sure what is wrong here? could you please help with that?

```
taxa <- assignTaxonomy(seqtab.microdecon, "silva_nr99_v138_train_set.fa", multithread = TRUE)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'reverseComplement': key 80 (char 'P') not in lookup table
In addition: Warning message:
In assignTaxonomy(seqtab.microdecon, "silva_nr99_v138_train_set.fa",  :
  Some sequences were shorter than 50 nts and will not receive a taxonomic classification.
```

attached the sequence table (seqtab.microdecon
[seqtab.microdecon.zip](https://github.com/benjjneb/dada2/files/7709655/seqtab.microdecon.zip)

Thanks very much

**Comment by benjjneb** [comment]
`assignTaxonomy` assumes that the sequence table you are giving it has the columns named by the sequence. Is that still the case after using the microdecon package?

A quick way to check, what does `head(colnames(seqtab.microdecon))` return? It should be DNA sequences in order to work with `assignTaxonomy`.

**Comment by marwa38** [comment]
I worked with decontam() and it worked fine.
