### ISSUE TITLE
assignSpecies : Returns NA genera but non-NA species when allowMultiple = TRUE

### ISSUE THREAD

**Issue by salix-d** [benjjneb/dada2#1478]
When using the function `assignSpecies()` with the argument `allowMultiple = TRUE`, sometimes you get multiple species assignment without but no genus information.

I understand that returning that information could be confusing (which species are in which genus?), although, maybe some people would still like that information.
But, if assuming that the function is generally used by `addSpecies()`, and in that case, those NA genera are filtered out by `matchGenera()`, a solution could be to only use `maphits()` for species on the genus returned values that aren't NA.

For example, by changing the lines 280-81 in taxonomy.R :
```r
  rval <- cbind(unlist(sapply(hits, mapHits, refs=genus, keep=1)),
                        unlist(sapply(hits, mapHits, refs=species, keep=keep)))
```
to
```r
rval <- cbind(unlist(sapply(hits, mapHits, refs = genus, keep = 1)), NA_character_)
rval[!is.na(rval[,1]), 2] <- unlist(sapply(hits[!is.na(rval[,1])], mapHits, refs = species, keep = keep))
```
Wich also speeds the function a bit by not running `mapHits()` unnecessarily.

edit :
The behavior also happens with `allowMultiple = TRUE` since some species' names are associated with different genera (i.e. _falsenii_ which could be _Wautersiella falsenii_, _Corynebacterium falsenii_, _Prevotella falsenii_, etc.

**Comment by benjjneb** [comment]
First, I haven't touched this code in long enough that I don't remember every deatil. That said,

I think that when `assignSpecies` is returning `NA` in the genera slot, it is not because any entry in the database had an NA genera designation. In fact, the species reference is curated to include only entries with genus/speices binomials. It is because multiple genera were returned, and `allowMultiple` only applies to the species rank. That is confusing, but it is also assumed by the `addSpecies` functionality that assumes a match between the species-level assignment genus and the `assignTaxonomy` naive Bayesian assigned genus.

**Comment by salix-d** [comment]
I didn't think any genera was assigned NA in the database. I was saying that since the genus and species assignment aren't verified simultaniously, by verifying genus first,  there's no need to check for species for which no genus has been returned.
