### ISSUE TITLE
Sequences instead of ASV

### ISSUE THREAD

**Issue by najouamghazli** [benjjneb/dada2#1512]
Hi,

I am running DADA2 on my 454 data, but when I generate the Phyloseq object I get the sequences as tip labels and as row names for the otu table.

PS: I used the same pipeline 2 months ago and it worked corrrectly.

Any help will be appreciated.

Najoua

**Comment by benjjneb** [comment]
Please review the DADA2 tutorial section on the handoff to phyloseq: https://benjjneb.github.io/dada2/tutorial.html#bonus-handoff-to-phyloseq

In particular, the 3rd code block describes how to rename ASVs with shorter `ASV21` type names, while retaining the sequence information in the phyloseq object.

**Comment by DieSofia** [comment]
Hi, 
I am having the same issue with my ITS dataset.. The names of the sequences have the same name of the sequence.. So I have a very long name with ACGAAAAA.... I think this might be an issue during the mergePairs function. I am wondering if correcting the names or assigning a name to the sequence, can be done after this or in the seqtab.nochim object. (I am pre-processing my data with the same DADA2 tutorial from above  https://benjjneb.github.io/dada2/tutorial.html#bonus-handoff-to-phyloseq)

Thanks for your help!

**Comment by benjjneb** [comment]
@DieSofia I am not understanding what your issue is? The standard dada2 tutorial workflow keeps the names of the ASVs as the sequences all the way through until the handoff to phyloseq.

**Comment by DieSofia** [comment]
Sorry for not explaining the full picture before. My initial plan was to pre-process the ITS sequences with QIIME, but since concatenation is not possible when running the dada2 plugging within QIIME, I decided to pre-process the sequence with dada 2 in R, which have worked perfectly. However, I wanted to keep working in QIIME, mainly for building a phylogenetic tree, so for this I exported the dada2 table and the sequences as a .fna file. This has work perfectly, but the moment I want to build the tree, is not possible because the names are the same as the sequences... SInce I had this problem I had build a phylogenetic tree in R with decipher and phargon, but the little issue here is that I want to provide a sequence to be used as an outgroup, but I haven't figure it out how to do that yet. 
So, in another words, if there would be a way to change the names of the sequences in the seqtab object after the merging step, would be easier to manage that data.  
I hope you can understand the issue, is a bit complicated I know, because one issue brings me to a different one later. 
If you have any suggestions let me know. Thanks!!

**Comment by benjjneb** [comment]
Have you looked in the [QIIME2 forum](https://forum.qiime2.org/) for previous issues related to importing DADA2 data (from R) into QIIME2? I know this has come up a few times, and I believe they have some good instructions over there on how to do this.
