### ISSUE TITLE
DADA2 and PICRUSt

### ISSUE THREAD

**Issue by naarkhoo** [benjjneb/dada2#152]
I wonder if you there is any best practices to predict functional metagenomic profiles from dada2 abundance table. 

One of the challenges is there are multiple green gene hits for each Inferred Sequence Variant. So I wonder, if there is any hack or one should build a conventional closed- reference OTU picking abundance table.

**Comment by joey711** [comment]
This is a common question, but maybe not as ambiguous as you might think at first. To your point "One of the challenges is there are multiple green gene hits for each Inferred Sequence Variant" -- this consideration is also the true for OTUs. Actually, exact sequence resolution is a better starting place for inferring gene content because some of the genome hits that seemed ambiguous for a particular 97% OTU (e.g. were better than 3% match to the representative sequence), are no longer ambiguous when you know the exact sequence. For instance, you have an exact sequence match in the reference genome database as well as a 2% hit to a second genome. Hopefully its obvious in that scenario that you would use the former and not the latter. Said another way, the exact sequences provides you the ability to be more strict in your hit criteria for a match. This is a good thing, particularly for cases where there are a lot of different genomes from the same genus or species represented in the reference database.

Of course it is still possible to have >1 exact (or near exact) hit in your reference genome database, and this is an intrinsic ambiguity present for any method to infer gene content from an amplicon sequence profile, not in any way specific to a workflow that includes DADA2.

**Comment by benjjneb** [comment]
Closing as subsumed by discussion in #168
