### ISSUE TITLE
dada2 pipeline for metabarcoding

### ISSUE THREAD

**Issue by safiqu** [benjjneb/dada2#1520]
# dada2 pipeline for metabarcoding (CO1)
Thanks a lot for your dada2 pipeline, this is really cool. Our research group has been using it for our human microbiome projects. This is really cool.

We want to use your dada2 pipeline for our metabarcoding projects. Mostly we are sequencing 658bp long CO1 genes for species identification. We need to use a reference data set from this data repository or Barcode of LIfe (BOLD) (https://v3.boldsystems.org/index.php/datarelease ) data set.

Do you have any pipeline that I can follow?

I am facing a problem with this step.

####  Assign taxonomy
tax <- assignTaxonomy(IMGM_nochim, refFasta = "/Users/sislam/Desktop/Metagenomics-R/iBOL.tsv.zip", multithread = T)
tax <- addSpecies(IMGM_tax, "/Users/sislam/Desktop/Metagenomics-R/ iBOL.tsv.zip ")
colnames(tax) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus","Species")
taxa.print <-tax
rownames(taxa.print) <- NULL
head(taxa.print)

Somehow this is not working. Do you have any suggestions that I can follow? Thanks a lot for your nice development for the science

Kind Regards
Safi

**Comment by benjjneb** [comment]
`assignTaxonomy` requires the reference data set to have a specific format, that is described here: https://benjjneb.github.io/dada2/training.html#formatting-custom-databases

I am not myself familiar with the BOLD files you are working with, but the fact that it has a .tsv file extension strongly suggests that it is not in the fasta format expected by `assignTaxonomy`. So, I'd take a look at the format described at the link, and then see how to convert the BOLD files into that format.

**Comment by Sbu211** [comment]
Hi thanks you for the Dada2 pipeline.
It has really given me hope to easily analyze my HTS data. I would like to ask whether the assignTaxonomy would take the input of the Genbank database? the ones in fasta format on the ftp site?...In addition is it possible to also add sequences that were generated in a normal Sanger sequence to this databas locally and sort of make a customized database?

Thank you

**Comment by benjjneb** [comment]
@Sbu211 As mentioned above, the format required by assignTaxonomy is described here: https://benjjneb.github.io/dada2/training.html#formatting-custom-databases

You can certainly add sequences to make a custom database, as long the combined fasta file conforms to that format.

**Comment by danchurch** [comment]
I know this is closed, but in case someone else comes here with google, etc, MIDORI2 ([article](https://doi.org/10.1002/edn3.303), [website](https://www.reference-midori.info/)) is now claiming they have a wide-taxonomic-spectrum CO1 database in several formats, including ones formatted for dada2 and RDP. I will be trying this resource for our data, which is a dada2/phyloseq framework.

**Comment by safiqu** [comment]
Wow, thanks a lot for the comment; this will be useful.
I have another question from the dada2 pipeline, mainly used this code  

taxa <- assignTaxonomy(seqtab.nochim, "~/tax/silva_nr_v132_train_set.fa.gz", multithread=TRUE)
taxa <- addSpecies(taxa, "~/tax/silva_species_assignment_v132.fa.gz")

from this reference database, As I understand, it has only one fasta file where they mention till species level.
my question is how can we assign the species? (assign two times same ref database?). Thanks a lot for the support.

Kind Regards

**Comment by benjjneb** [comment]
Thanks for the heads up @danchurch . Will you let us know if it works? If so, I will add it to the list of "contributed" reference on the dada2 taxonomic training sets we page.

**Comment by benjjneb** [comment]
@safiqu `assignTaxonomy` and `addSpecies`/`assignSpecies` use different algorithms to do taxonomic assignment. `assignTaxonomy` uses the naive Bayesian classifier method, and is appropriate in the shot-read 16S application for assigning down to genus-level. To assign species to short-read 16S data, we recommend using `addSpecies`/`assignSpecies` method which requires exact, unambiguous matching to make a species assignment. This uses a different reference file format, which is why in the code you posted above there are two different reference files for the two different commands.

(long-read 16S can use `assignTaxonomy` to assign down to the species level, in which case you would use the `_wSpecies` version of the `train_set` reference for `assignTaxonomy`)

**Comment by danchurch** [comment]
> Thanks for the heads up @danchurch . Will you let us know if it works? If so, I will add it to the list of "contributed" reference on the dada2 taxonomic training sets we page.

Hi, I tried the midori2 database. It ran smoothly in the dada2 pipeline, out-of-package, without any errors. But it made very few (<5%) taxonomic assignments. Most were phylum-level assignments only, mostly to arthropoda and fungi. I think this is probably the due to the lower number of the non-animal entries, the conservative approach of RDP classifier, and our own noisy data. We ended up doing a simple closest-blast match approach for our CO1 data instead.

So I would say that MIDORI2 runs perfectly well with the dada2 pipeline, but gave too few results in our case. Someone who has very simple data, or who is willing to tweak defaults of the RDP classifier extensively might have better luck.

**Comment by RRDomingues** [comment]
> > Thanks for the heads up @danchurch . Will you let us know if it works? If so, I will add it to the list of "contributed" reference on the dada2 taxonomic training sets we page.
> 
> Hi, I tried the midori2 database. It ran smoothly in the dada2 pipeline, out-of-package, without any errors. But it made very few (<5%) taxonomic assignments. Most were phylum-level assignments only, mostly to arthropoda and fungi. I think this is probably the due to the lower number of the non-animal entries, the conservative approach of RDP classifier, and our own noisy data. We ended up doing a simple closest-blast match approach for our CO1 data instead.
> 
> So I would say that MIDORI2 runs perfectly well with the dada2 pipeline, but gave too few results in our case. Someone who has very simple data, or who is willing to tweak defaults of the RDP classifier extensively might have better luck.

I encountered the same issue with Midori—it ran smoothly but returned limited taxonomic assignments. Please share your approach if anyone has found a way to run COI ASVs from DADA2 against a more comprehensive reference database!

**Comment by Harkstetunz** [comment]
@benjjneb could you please direct me to where to get the script? I'm working on similar project and the script would be very helpful. Thank you.

**Comment by benjjneb** [comment]
@Harkstetunz What script?
