### ISSUE TITLE
Non-corresponding derep-class and dada-class objects

### ISSUE THREAD

**Issue by katmcferrin** [benjjneb/dada2#1548]
Hi! I'm stuck at the mergePairs step and have gotten this error: Error in FUN(X[[i]], ...) : 
  Non-corresponding derep-class and dada-class objects. 

I've already checked to make sure dada() and mergePairs() are using the same filenames, and I've checked to make sure the derep-class and dada-class lists are the same length. I would appreciate any help or suggestions on troubleshooting!

**Comment by benjjneb** [comment]
Can you give more information about the workflow you are running, and where exactly the error is arising?

> I've already checked to make sure dada() and mergePairs() are using the same filenames, and I've checked to make sure the derep-class and dada-class lists are the same length.

Can you say more about how you checked here? Because the `mergePairs` is also doing a similar checking (not on filenames, but on summary stats from the files) and coming to a different conclusion.
