### ISSUE TITLE
Versions and changes

### ISSUE THREAD

**Issue by gregdenay** [benjjneb/dada2#1577]
I am a bit confused with the different versions of dada. The latest release on Github is 1.20 but bioconda and bioconductor offer a version 1.22. The output from `sessionInfo()` does match the indicated versions in both cases.
The Changelog only lists changes up to 1.20, is it posible to find changes in successive versions somewhere?

**Comment by benjjneb** [comment]
The github and Bioconductor versions should be coming back into synch with this next Bioconductor release.

They got unsynched because there was a two-BioC release cycle (about a year) where there weren't any non-documentation changes to the package, and I was lazy and didn't keep things synched between the bumped BioC versions and the primary Github repo.

That said, from 1.20 to 1.24 are functionally identical. Changes between versions are cataloged: In very fine grain with github commits, but more broadly in Release notes for releases that have meaningful changes.

**Comment by gregdenay** [comment]
Thanks for clarifying. Keeping versions synced can be a pain!
Cheers
