### ISSUE TITLE
Error rates of DADA2

### ISSUE THREAD

**Issue by aksbiome** [benjjneb/dada2#1578]
Hi,

I have done 16S rRNA gene sequencing of v4 region (with 2x250 chemistry) on Hiseq platform, and analyzed data using DADA2.
I am just worried about the error plot generated for same data as the dots that appear far from the model line.
Should I proceed with this ? Please guide. I have shared forward and reverse plots.

Thanking You.

![R1_aks](https://user-images.githubusercontent.com/52836596/175932665-1a0cc073-1e39-49b3-9d1b-718630399c18.png)

![R2_aks](https://user-images.githubusercontent.com/52836596/175932691-df6aa4ec-2b02-4975-bdee-fb3dd193ca6d.png)

**Comment by benjjneb** [comment]
The error model is the black line, so it is fitting the observations fairly well. The red line is the nominal definition of the q-value as -10*log10(err-rate).

I would be concerned about this, because there appears to be nearly no reduction in error rates at higher quality scores as would usually be expected. Is there a reason for this though?

More details are needed. What is the sequencing tech? How are these libraries being created? What is the environment sampled? What amplicon is being sequenced?

**Comment by aksbiome** [comment]
Thank you for reply.
