### ISSUE TITLE
Error in Examining quality profiles of forward and reverse reads

### ISSUE THREAD

**Issue by m-ocejo** [benjjneb/dada2#159]
Hi again!
In the examining quality profile step after removing the primers with cutadapt, I encounter this error message:
> plotQualityProfile(fnFs[[1]])
Error in density.default(qscore) : 'x' contains missing values

What is "x"? The sequences in the fastq file seems OK. Any help??
Thanks!!!

**Comment by benjjneb** [comment]
My first guess is it means there is an empty sequence in the fastq, but I'm not sure. Can you share the cutadapt-ed file that is causing this error message?

**Comment by m-ocejo** [comment]
Sure!
The file is too big, I will attempt sending you the files to your email attaching pre-cutadapt file (no problem in plotting the quality profile) and cutadapt-ed file.


Thanks!!

**Comment by benjjneb** [comment]
The problem is that cutadapt has created length zero sequences in the fastq file. If there's a fix to that on the cutadapt side that would be optimal.

Unfortunately the `plotQualityProfile` function relies on some code in another package that we can't easily change, and that code causes this error. However, this can be worked around by enforcing a length requirement before examining the quality profiles. The key bit is picking the right length requirement, which can be done by looking at the distribution of lengths in the cutadapted file. Below is some code to do that, choose a `truncLen` parameter, trim to that length, and then view the quality profile to see if additional trimming is necessary:

```
library(ShortRead)
fn <- "~/Desktop/Sample01_cutaadpted_R1.fastq.gz"
trimmed <- "~/Desktop/Sample01_trim_R1.fastq"
srq <- readFastq(fn)
seqlen.tab <- table(width(srq)) # Table of how many RSVs have a given length in nts
seqlen.tab
seqlens <- as.integer(names(seqlen.tab))
counts <- as.integer(seqlen.tab)
plot(x=seqlens, y=counts)
plot(x=seqlens, y=log10(counts))
# Vast majority have length 226
# Trim just below that (224) to keep minor length variation in data

library(dada2)
fastqFilter(fn, trimmed, truncQ=0, truncLen=224, verbose=TRUE)
plotQualityProfile(trimmed)
```

Hope that is helpful. Paired end data should be trimmed jointly after looking at the distro of forward and reverse lengths post-cutadapt. We'll look into a more graceful solution to this problem in the future.

**Comment by benjjneb** [comment]
The better solution here is to enforce a minimum length using cutadapt with the `--minimum-length N` flag.

See here: http://cutadapt.readthedocs.io/en/stable/guide.html#filtering-reads

**Comment by m-ocejo** [comment]
Yes! you are right that the problem is in those seq with length 0 in the fastq file.
plotting the quality profile after running cutadapt with --minimum-lenght we found that we don´t even need to trim the first 10bp.
thank you very much for the thorough solution!
