### ISSUE TITLE
Question regarding LearnErrors

### ISSUE THREAD

**Issue by alanxelena** [benjjneb/dada2#1592]
Dear @benjjneb and all,

  I'm having trouble understanding the process behind the LearnErrors module of Dada2, we have discussed the matter with some colleagues and couldn't come to an agreement. Hopefully you can help us.
Our doubt is how the error freq vs Q plot is made. Are all the reads aligned and then a consensus Q for each position is calculated? If so, how are the error rates for the position computed? Does it analyse the frequency of each base in that certain position and then pulls a frequency of each base and after comparing it to the most frequently called base in that position, it calculates the frequency?
Or does the algorithm calculate the error rate based on the Q score of each position of each read independently and assumes the probability of the rest of the bases to be (1-p(N))/3 (and corrected by biologial variation)? Then, would the consensus Q be calculated independent on the position?
Our doubts rely that with the first approach, you would be able to get more accurate estimators of biological variation but you would also be comparing positions that might be unstable, on the other hand, the second approach just assumes transition probabilities to be identical which is not the most real case.
I would really appreciate some insights on this aspect, it's driving us crazy.

Thank you all!

Cheers,

**Comment by benjjneb** [comment]
The `learnErrors` algorithm alternates between two steps until it reaches a "convergent" solution:

A. Infer the sample composition. This appliesthe DADA2 algorithm described in the original paper using a provided error model. The outcome of this is a set of "true ASVs", and an assignment of each unique sequence in the data to one of those "true ASVs" (modulo a typically small number that are removed as too different from a true ASV to be caused by a normal error process).

B. Estimate the error model. Given a provided sample composition, each unique sequence in the data is aligned against the  "true ASV" it was inferred to originate from. The number of "transitions" (aka an A read as an A, or a T read as a C) are recorded for each quality score. Then a loess fit is applied within each transition type over the quality scores, generating an error model.

A -> B -> A -> B -> ... until the error model isn't changing anymore.

Also, this is initialized by starting with an inferred sample composition of only one real ASV -- the most abundant sequence in the data.

**Comment by alanxelena** [comment]
Hi @benjjneb, 

That was really useful, the generation of "true ASVs" was the gap that we needed to fill.
Thank you for your reply!

Alan.
