### ISSUE TITLE
Can I generate a single-sample fasta file id and all the sequences it contains after chimera removal?

### ISSUE THREAD

**Issue by marinacreuzade** [benjjneb/dada2#1611]
Do you think I can generate a single-sample fasta file containing one sample id and all the sequences it involves from a seqtab.nochim?
I mean, can I do it after a massive (10 samples) dada2 filtering, denoising, merging, removing chimeras etc.etc? So before doing assign taxonomy? I'm asking this because I want do use the single sample-fasta files to make a local blastn and then analyze all 10 blastn outputs using MEGA software for comparison.

**Comment by marinacreuzade** [comment]
![Screenshot from 2022-09-27 17-47-14](https://user-images.githubusercontent.com/87028326/192573660-fc8c3a08-c7d1-4dad-a6fe-e009f56d8107.png)
Right now I have a seqtab.nochim organized in this way: all the ASVs sequences followed by samples aboundances (see loaded terminal screenshot). So if I use the uniquesToFasta function for generate .fasta file I obtain the total ASVs independently from my samples specificity. I wondered if there is a way for create my 10 samples (one by one) .fasta files with uniquesToFasta so as I can trasform them for blastn separately.

**Comment by benjjneb** [comment]
You can make any kind of fasta file you might imagine using regular R manipulations of the sequence table and the `writeFasta` function. For example, in order to get a fasta file containing just the sequences present in sample 1, you first construct a vector of the ASVs in that sample, and then (optionally) name them in some way if you want specific names to show up in the fasta id lines. Example code:

```
asvs <- getSequences(seqtab.nochim)
names(asvs) <- paste0("ASV", seq_along(asvs))
in.sam1 <- seqtab.nochim[1,] > 0
asvs.sam1 <- asvs[in.sam1]
writeFasta(asvs.sam1, "path/to/output/sam1.fa")
```

In similar fashion, any other organization of sequences can be written to a fasta file.
