### ISSUE TITLE
learnErrors takes too long

### ISSUE THREAD

**Issue by ColdySnow** [benjjneb/dada2#1621]
Hello!

So... I have 120 sample files, each divided into R1 and R2. I want to run the DADA-pipeline, everything worked so far, but now I am on the "leanErrors" step.
It sais:

500164320 total bases in 2084018 reads from 1 samples will be usesd for learning the error rates.

This runs now round about 4 whole days. I know, its a very time consuming step, but is it right that it takes SO long? Is there any way I could decrease the run time? It runs on our university server, so there should be enough memory and cores. 
Hope you can help me out here, I don't want do anything wrong. If it is right, that it takes so long for such an high amount of data, than its fine and I'll guess, I just have to wait :D

Thank you in advance!

Christin

**Comment by benjjneb** [comment]
It is taking longer than usual because your samples appear more deeply sequenced than is common (2M reads per-sample).

To speed things up, make sure you turned on multithreading: `learnErrors(..., multi=TRUE)`. Other than that, you could consider downsampling your samples a bit for the `learnErrors step`, e.g. subsetting to 200k reads per sample. It also runs a bit faster (and produces better error models) from lower complexity samples.

**Comment by ColdySnow** [comment]
Oh okay. Thank you! I turned multithread=FALSE, because I use a Windows Laptop. So it is no problem if I turn it on?

But thank you anyway! Because it runs now for 124h already, I leave it run, but next time I use the pipeline, I'll turn on the multithread. Thank you for your help!

**Comment by benjjneb** [comment]
> Oh okay. Thank you! I turned multithread=FALSE, because I use a Windows Laptop. So it is no problem if I turn it on?

Just following up, multithreading works on Windows for every command except `filterAndTrim`. So it should be used for these compute intensive steps.
