### ISSUE TITLE
doubt about data treatment, almost 2k of ASVs after taxonomic assignment 

### ISSUE THREAD

**Issue by yo-soy-alex** [benjjneb/dada2#1623]
Greetings! This is my first question ever at github, i've searched for all my past doubt but this one has been kinda tricky and i would like to get a second opinion of other bioinformatics since i'm still new and learning every day a bit

So I have some samples from soil that we amplify the ITS 86F and 4R, after following the steps of the dada2 pipeline for ITS and assign the taxonomy i realize that there's 1930 different ASVs on 12 samples which seems to be a bit uncommon from the other studies I've already seen (including one from my own college), and after applying some filter like taking those who appear less than 5 time in 10% of the samples the number drop to 335, that makes me think that i might be having more false positives rather than rares ASVs, if someone who's already work with similar data has an idea if that's normal or i missed something while applying the filters let me know! I'll leave the code i used to generate the data with some details

![Rplot](https://user-images.githubusercontent.com/116311934/197053540-c2f2ed49-a281-4dfd-83c9-e3e890d0fc05.png)

![Rplot01](https://user-images.githubusercontent.com/116311934/197053549-94461ba8-d445-47bd-afaf-1090d042c4df.png)

Reverse reads were not used due to low quality and suggestion from biobliography

```
filtFs <- file.path(path.cut, "filtered", basename(cutFs))
filtRs <- file.path(path.cut, "filtered", basename(cutRs))

out <- filterAndTrim(cutFs, filtFs, cutRs, filtRs, maxN = 0, maxEE = c(2, 2), 
                     truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = TRUE)  
head(out)

                                 reads.in  reads.out
10BN_S15_L001_R1_001.fastq.gz    37276     20604
1IN_S10_L001_R1_001.fastq.gz     37855     24220
2BI_S7_L001_R1_001.fastq.gz      39025     18766
2II_S2_L001_R1_001.fastq.gz      40775     27713
2IN_S11_L001_R1_001.fastq.gz     38309     23583
3IN_S12_L001_R1_001.fastq.gz     43809     24245


set.seed(100)
errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
plotErrors(errF, nominalQ=TRUE)

derepFs <- derepFastq(filtFs, verbose=TRUE)

# Name the derep-class objects by the sample names
names(derepFs) <- sample.names

dadaFs <- dada(derepFs, err=errF, multithread=TRUE, pool="pseudo")
```
Merge was not made because the Reverse reads were not used
```
seqtab <- makeSequenceTable(dadaFs)
dim(seqtab)
table(nchar(getSequences(seqtab)))
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)

12 1930

sum(seqtab.nochim)/sum(seqtab)

0.9419792

getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), rowSums(seqtab.nochim))
# If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
colnames(track) <- c("input", "filtered", "denoisedF", "nonchim")
rownames(track) <- sample.names
head(track)

     input filtered denoisedF nonchim
10BN 37276    20604     20034   19630
1IN  37855    24220     23675   22516
2BI  39025    18766     18026   17355
2II  40775    27713     27152   24561
2IN  38309    23583     23120   22265
3IN  43809    24245     23687   21918
4BN  41361    25268     24749   22870
6BI  35946    17306     16737   15600
6II  36675    20744     20143   19058
7BN  42154    24378     23762   22786
8BI  39583    15685     15264   13911
8II  35499    20543     20042   19045
```

**Comment by benjjneb** [comment]
So, in terms of the basic read tracking numbers, this looks fine. You lose a chunk at the filtering step, but that's OK. (that said, you should redo the filtering on the forward reads alone since that is all you are using, because right now you are unnecessarily losing forward reads where the reverse read quality was too low to keep)

As far as the number of ASVs goes, I don't have a good rule of thumb for what to expect from fungal ITS sequencing, and it surely depends on the environment you are investigating as well. Should there be more overlap between taxa here than you are seeing, perhaps because of some experimental design? Or are these just disparate environmental samples that may have only modest taxonomic overlap?

That said, two things to try. One, what is the fraction of reads (i.e. weighting ASVs by abundance) that are in the shared ASV fraction? Is that the vast majority? Second, you could try doing denoising with `dada(..., pool="pseudo")`, which is a method that shared information across samples and might help increase the number of cross-sample ASVs that are detected.
