### ISSUE TITLE
how to merge two ASV tables from two runs, the sequences were used two different primers

### ISSUE THREAD

**Issue by FengqingWang0712** [benjjneb/dada2#1638]
Dear Ben,
I have two kinds of samples. The first was sequenced using primer V3-V4, and another was used V4. I wondered if there is a way to merge the ASV tables from these two runs into one ASV table. 

Thanks in advance for your help.

All the best,
Fengqing

**Comment by benjjneb** [comment]
Yes, but you need to trim the ASVs from each study to a common region of the 16S gene. If the V4 sequences are completely contained inside the V3V4 sequences, then this is reasonably straightforward and just involves trimming the V3V4 sequences down to the V4 region.

**Comment by FengqingWang0712** [comment]
Thanks for your reply. I trimmed V3V4 sequences down to the V4 region and merged them with sequences only sequenced using V4 primer. However, the results show no similarity between the ASVs in the two kinds of sequences, and no merge was performed. the output table merges the ASVs in the two kinds of sequences separately, which means that the number of ASV obtained is now the sum of the two kinds of sequences. The relative abundance is displayed as shown (column names are the number of ASVs, and row names are the samples): The second sample is exactly 0 under the ASV sequence from the first samples, and the first one is exactly 0 under the ASV from the second samples. 
<img width="1496" alt="Screenshot 2022-11-30 at 14 36 12" src="https://user-images.githubusercontent.com/58179925/204810757-d546f37e-58df-4d50-a4c6-61abf769fc2a.png">

**Comment by FengqingWang0712** [comment]
Here I attached two kinds of my sequences, the 1.R* were sequenced using primer V3-V4, and I trimmed the V3V4 sequences down to the V4 region. The 2.R* were sequenced using primer V4. Could you help me check why I got these results? Thanks in advance for your help.
[1.R1.fastq.gz](https://github.com/benjjneb/dada2/files/10123731/1.R1.fastq.gz)
[1.R2.fastq.gz](https://github.com/benjjneb/dada2/files/10123732/1.R2.fastq.gz)
[2.R1.fastq.gz](https://github.com/benjjneb/dada2/files/10123733/2.R1.fastq.gz)
[2.R2.fastq.gz](https://github.com/benjjneb/dada2/files/10123735/2.R2.fastq.gz)

**Comment by benjjneb** [comment]
How are you cutting the V3V4 region down to V4? If there are no overlapping ASVs between these groups, that cutting procedure is not leading to the same region as the V4 region you sequenced. What primers are being used in both cases?

**Comment by FengqingWang0712** [comment]
one was 341F and 805R, the other one was 515F and 806R.

**Comment by benjjneb** [comment]
How are you cutting the V3V4 region down to V4?

**Comment by FengqingWang0712** [comment]
Yes. I did. Here is what I did, "for i in *.R1.fastq.gz; do name=`echo $i | sed 's/.R1.fastq.gz//g' `; cutadapt/cutadapt-1.15_slv/bin/cutadapt -g GTGCCAGCMGCCGCGGTAA -G GGACTACHVGGGTWTCTAAT -e 0 -O 23 -j 52 --discard-untrimmed -o $name.R1.for.fastq.gz -p $name.R2.for.fastq.gz $name.R1.fastq.gz $name.R2.fastq.gz; done"
and "for i in *.R1.fastq.gz; do name=`echo $i | sed 's/.R1.fastq.gz//g' `;cutadapt/cutadapt-1.15_slv/bin/cutadapt -g GTGCCAGCMGCCGCGGTAA -G GGACTACHVGGGTWTCTAAT -e 0 -O 23 -j 52 --discard-untrimmed -o $name.R1.rev.fastq.gz -p $name.R2.rev.fastq.gz $name.R2.fastq.gz $name.R1.fastq.gz; done"

The sequences using the V3V4 primer were different (R2 quality is better than R1). Is it the reason?

**Comment by benjjneb** [comment]
One thing to look at is the distribution of sequence lengths in the V4 sequence table versus the V3V4->V4 sequence table. Is the length distribution the same? Or could it be off by a base or two (possible because of 805R vs. 806R)?

For merging of the sequence table it is important that lengths are exactly the same.

Another thing to try is to run `collapseNoMismatch` on the merged table. If the differences between the V4 and V3V4->V4 sequences are just small length variations, that will combine them together. That said, that function can be slow and has never been multithreaded, so fixing upstream is preferable if possible.

**Comment by lagreenga** [comment]
Hello!
I have a similar problem. 
I have two tables of sequences. Both tables correspond to sequences of the V4 region of 16S, using the same primers 515F and 806R. However, the first one has sequences of a length of 253 bp, and the other one has sequences of 250 bp. I was already able to merge the tables using the mergeSequencesTable command, but I wonder if there is a way to align the sequences of both samples to the same overlapping region and then cut so that all sequences are the same length. 
thank you very much

**Comment by benjjneb** [comment]
One quite robust approach is detailed in our recent meta-analysis preprint: https://www.medrxiv.org/content/10.1101/2022.09.26.22280389v2

That said, probably a much simpler approach would work here. If it is the case that your ASVs from both studies start at the same position (i.e. right after the 515F primer), then you could simply truncate the ASVs from the 253 bp study (presumably merged reads) to 250 nts. Then you should be able to `mergeSequenceTables` the two studies together. The sanity check would be that there should be lots of overlap, i.e. many reads in both studies are in ASVs that appear in both studies.
