### ISSUE TITLE
12% chimeras

### ISSUE THREAD

**Issue by alberjo0296** [benjjneb/dada2#1655]
Hi,

I'm analyzing my data with the primers CCTACGGGNGGCWGCAG and GACTACHVGGGTATCTAATCC , that have already been deleted from the fastq sequences. However, I've got almost a 12% of chimeras, when I usually get around a 3% with these primers. How is it possible? What can be the reason?

Regards,

Alberto

**Comment by benjjneb** [comment]
> How is it possible? What can be the reason?

Variation in PCR conditions and protocols, and the input microbial biomass to the PCR reaction, can change the amount of chimeras produced. 12% (of reads?) as chimeric is within the range not uncommonly seen, so that itself is not an immediate red flag. That said, I would take a critical look at whether anything changed about the PCR performed, or about the quality of the input DNA, if everything else is otherwise the same between your previous experiments with only 3% (or reads?) being contaminants.
