### ISSUE TITLE
Understanding the effect of primer sequences in DADA2 pipeline

### ISSUE THREAD

**Issue by ManuelAOS** [benjjneb/dada2#1678]
Hi all!

I have some 16S sequences amplified with the universal primers 341F: CCTACGGGNGGCWGCAG & 805R: GACTACHVGGGTATCTAATCC. I have checked the sequences and primers are present in all sequences, yet, they do not have ambiguous bases. For example, for 341-F instead of having: "CCTACGGGN..." there is, "CCTACGGGT...".
I am using DADA2 to analyze these sequences, but I have read the following: "DADA2's chimera removal step requires primers to have been removed, as otherwise the ambiguous nucleotides in most primer sets cause large numbers of false-positive chimeras to be identified". But, sequences do not have ambiguous nucleotides...
My questions are the following:
1.- Does keeping primers (without ambiguous nucleotides) could affect 16s subsequent analysis?
2.- And if so, how would it affect it?

Additionally, I have run DADA2 pipeline without trimming the first 20 nucleotides (that is, keeping primer sequences) and with first 20 nucleotides trimmed. 

DADA2 run without trimming primer nucleotides have an inconsistent detection of chimeric sequences, that is, some samples loss more than 90% of sequences while others lose 50%. In contrast, DADA2 run with 20 first nucleotides trimmed do not suffered from this high percentage of sequence lost.

Any help/insight/feedback will be appreciated. Thanks in advance!

**Comment by benjjneb** [comment]
> DADA2 run without trimming primer nucleotides have an inconsistent detection of chimeric sequences, that is, some samples loss more than 90% of sequences while others lose 50%. In contrast, DADA2 run with 20 first nucleotides trimmed do not suffered from this high percentage of sequence lost.

That's because the unremoved degenerate primers are interfering with chimera detection.

> I have checked the sequences and primers are present in all sequences, yet, they do not have ambiguous bases. For example, for 341-F instead of having: "CCTACGGGN..." there is, "CCTACGGGT...".

The primers themselves don't actually have an "N" base, that's biochemically impossible. An "N" base at some position just means that the primers you are using are a mixture of 4 primers, for each potential base that could fit that N.

You need to remove those degenrate primer sequences, as they interfere with denoising and chimera removal.

**Comment by ManuelAOS** [comment]
Hi Ben!

Thanks for the fast reply, deeply appreciated.

Could you elaborate more on how degenerate primer sequences interfere with denoising and chimera removal?

Otherwise, could you share a link where I can read how primer sequences interfere with these processes so I can understand it better?

Thanks in advance!

**Comment by benjjneb** [comment]
Let's say you have a forward primer with an N. So, you really have 4 forward primers, with A/C/G/T in that position. Most ASVs will be amplified by all of them. So you'll have 4 versions of each real ASV unless you remove primers first. Each with ~1/4 of the real ASV abundance, and 3/4 of which contain the wrong nucleotide at the degenerate primer position. This is bad for data interpretation, and causes more loss of low-abundance ASVs.

Chimera detection then can interpret each ASV primer-variant as a chimera other than the most abundant one, since it could be made by a combination of its primer variant from some other ASV, and the rest of the more abundant ASV primer-variant.

**Comment by ManuelAOS** [comment]
Hi Ben!

Thanks for your explanation, it is really helpful!

Excellent day :)

Manuel
