### ISSUE TITLE
assignTaxonomy() Confidence scores drops after adding one level to greengene database

### ISSUE THREAD

**Issue by Leran10** [benjjneb/dada2#1683]
Hi,

I have a question regarding to how were the confidence scores of each levels calculated. 
In order to get OTU IDs instead of taxonomy names in my OTU table, I added one more taxonomy level to my original gg database to make it looks like this:

![image](https://user-images.githubusercontent.com/17597071/214903859-39981dc4-1626-4db0-9546-8d049157bf5e.png)

Then I used this modified db in assignTaxonomy() function and checked my bootstrapping confidence scores, they dropped dramatically comparing to using the original gg database.

I don't understand why this could happen? I didn't change anything of the reference sequences but just the names, how this could affect the k-mer matchings?

Thanks very much!
Leran

**Comment by benjjneb** [comment]
The terminal bootstrap scores will necessarily be lower, since now your terminal level is the GG OTU ID instead of the species.

**Comment by Leran10** [comment]
Hi,

Thanks for your reply! 

So when I used the original gg database in assigTaxonomy(), the bootstrapping scores are like:
![image](https://user-images.githubusercontent.com/17597071/215160996-11dfb12b-86a9-4eb3-8042-82561b932903.png)

And if I used my modified database in assignTaxonomy(), the scores are like:
![image](https://user-images.githubusercontent.com/17597071/215161193-3b2983ba-d994-4920-9294-1bdfbbaf3b5f.png)

As you can see, it's not just the terminal scores were low, but all levels have been affected.

And I also tried to just append the OTU IDs to one of the levels in the database file to avoid adding more levels. 

When I append OTU IDs to Species level:
![image](https://user-images.githubusercontent.com/17597071/215162676-b8624971-8029-4ff4-ac5a-48a118995834.png)
And the bootstrapping scores for this version of database is:
![image](https://user-images.githubusercontent.com/17597071/215162799-4eaf1b46-e0c7-456f-af6f-de5cfb33d8d5.png)


When I append OTU IDs to Kingdom level:
![image](https://user-images.githubusercontent.com/17597071/215161944-821948c1-2ef1-4025-955f-0378e07d1e58.png)
And the bootstrapping score for this version of database is:
![image](https://user-images.githubusercontent.com/17597071/215162225-589c5268-7939-4d1d-ae36-d2862e18db17.png)

I'm confused why modifying the names could affect the bootstrapping results? The only thing that I can think of as a big change to the database is that after appending the OTU IDs the taxonomy names become completely unique. Like in the original database, there are 93322 unique sequences with 4000+ unique taxonomy names, after appending the IDs, the names because all unique to each other. But I don't understand why the uniqueness of the names can affect bootstrapping.

In the paper, it says 
"So for each bootstrap trial, a subset of one-eighth of the words was randomly chosen (with replacement) and the words in this subset were then used to calculate the joint probability. The number of times a genus was selected out of 100 bootstrap trials was used as an estimate of confidence in the assignment to that genus. For higher-rank assignments, we sum the results for all genera under each taxon".

Is the unique taxonomy names affecting the calculation of the joint probability?

Thanks so much!
Leran

**Comment by benjjneb** [comment]
The IDs should not be appended to any previous level. That will result in every (e.g. Phylum in your example) being treated as a unique phylum, and necessarily then to often very low bootstrap confidence values, since the subsets will be assigned to different references, which by string matching are now different phyla. That propagates then to all lower taxonomic levels. That also holds for appending at the species level, just less dramatically.

So, adding a new level for OTU ID is the only thing that could make sense, but even that doesn't make sense. The naive Bayesian classifier is not intended for application to a set of references where there is no overlap between them. That said, there remains a bit of a mystery as to why appending this new level (which should just get very poor boostrap scores) would be affecting higher levels. My first guess is that not all references in the original fasta file have all 6 taxonmic levels assigned. Thus, when the OTU ID is appended as a new level, sometimes its being appended in the e.g. Order position, and then being treated as a unique new Order in the data that can only result in lowering bootstrap scores at and below that level.
