### ISSUE TITLE
Gaining reads after filtering step

### ISSUE THREAD

**Issue by IMMmember2023** [benjjneb/dada2#1688]
Hi, 

We are performing an analysis of 16s sequencing data from human fecal samples following dada2 pipeline. After the raw sequences were input and filtered, instead of the number of denoisedR and denoisedF reads decreasing in the amount, in some samples we gained reads. Therefore, the output in the merging step is currently bigger than in the filtering step. I am attaching an example in the pdf document for better visualization where I highlighted those samples as well as the plot of transition of filtered and merged reads. Has anybody encountered the same issue? 

Thank you in advance for your insights! 

[filtered_merged_sequences_example.pdf](https://github.com/benjjneb/dada2/files/10548118/filtered_merged_sequences_example.pdf)

**Comment by benjjneb** [comment]
That can't happen. What is probably going on is that some samples were lost at the filtering stage, but this wasn't accounted for when constructing the table tracking read counts through the pipeline: https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline

Do you get a warning message about "number of rows of result is not a multiple of vector length" when doing the `cbind` command to construct the read tracking table?

The fix is to subset the filtering data down to the set of files that passed through filtering, and then (hopefully) everything should have the same number of columns and correctly be joined into the read tracking table.
