### ISSUE TITLE
[Documentation] The quality score of Illumina in the `truncQ` argument of the `fastqPairedFilter()`

### ISSUE THREAD

**Issue by wolass** [benjjneb/dada2#170]
I am wondering what does the the truncQ = 2 refer to? In my opinion it requires clarification.

I understand this value is the quality score assigned by the platform. 

But these are ambiguous. The documentation of this function reports:

> `truncQ` (Optional). Default 2. Truncate reads at the first instance of a quality score less than or equal to truncQ. The default value of 2 is a special quality score indicating the end of good quality sequence in Illumina 1.8+.

What does the "end of good quality" mean?
Can you provide a reference for this claim?

Is this the `2` as defined in [this Wikipedia article?](https://en.wikipedia.org/wiki/FASTQ_format) ?

> The character '!' represents the lowest quality while '~' is the highest. Here are the quality value characters in left-to-right increasing order of quality (ASCII):
> 
>  `!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_abcdefghijklmnopqrstuvwxyz{|}~`

or is it a number 1-40 as reported in the `plotQualitProfile()` function???

Thanks!

**Comment by gblanchard4** [comment]
I agree that documentation is a little vague. 

A Q-score of 2 is a N base,  so I believe that what he means by "end of good quality" is that it's an uncalled base. I need to find a source, but it was a rule of thumb to discard any part of a sequence after the first N base. The lowest Q-score on an assigned base that I have seen is a 7, I believe this is how the Illumina software is designed.

**Comment by benjjneb** [comment]
The quality scores (an integer) is the unit of information. There is not a universal mapping from those integers to ASCII characters. Both ascii=score+33 and ascii=score+64 have been used by Illumina, and the current (Casava 1.8+) encoding is score+33.

Quality score 2 was often what Illumina outputs for poor quality read ends. However, it can pop up early in reads at times, generally when Ns are called. It is not a requirement to use `truncQ=2`, you can set `truncQ=0` to turn off that behavior. See more on that here: https://en.wikipedia.org/wiki/FASTQ_format#Encoding

The dada2 package relies on the ShortRead package to detect the encoding and convert the ascii to integer quality scores. Our filtering/trimming are recommendations based on best practices for the currently most widely used technologies (Miseq/Hiseq and Casava 1.8+). Because there are no universal standards, and sequencing techs differ, you should feel free to modify them to what works better for you.

Incidentally, this is IMO one of the major advantages of DADA2. Our pipeline learns the error rates, as a function of the assigned quality scores, from your data. Technologies change, software versions change, and so forth in ways that alter the relationship between quality scores and real error rates. When you use this pipeline, you are not relying on parameters fitted from some past dataset, you are getting the error rates for your data, your sequencing tech, your PCR protocol etc.

**Comment by wolass** [comment]
I agree that this feature is needed.
My question is only: what does this 2 mean. 
I have [found this description](http://www.drive5.com/usearch/manual/quality_score.html). 

>The quality score of a base, also known as a Phred or Q score, is an integer value representing the estimated probability of an error, i.e. that the base is incorrect. If P is the error probability, then:
>  P = 10^{–Q/10}

So according to this image: 

![image](https://cloud.githubusercontent.com/assets/2356167/21419405/b9d6713a-c827-11e6-89bc-6e5c25501556.png)

`trunQ = 2` will discard all the sequences in which there was at least one read with the high probability of erroneous base assignment (>63%).

**Comment by benjjneb** [comment]
Yes, the 2 converts to an estimated probability of an error as per the table posted. Note also the following special usage by Illumina (from the link I posted above): 

> Starting in Illumina 1.5 and before Illumina 1.8, the Phred scores 0 to 2 have a slightly different meaning. The values 0 and 1 are no longer used and the value 2, encoded by ASCII 66 "B", is used also at the end of reads as a Read Segment Quality Control Indicator.[6] The Illumina manual[7] (page 30) states the following: If a read ends with a segment of mostly low quality (Q15 or below), then all of the quality values in the segment are replaced with a value of 2 (encoded as the letter B in Illumina's text-based encoding of quality scores)... This Q2 indicator does not predict a specific error rate, but rather indicates that a specific final portion of the read should not be used in further analyses.

And to clarify slightly, `truncQ=2` will truncate the read at the first nucleotide with a quality score of 2 (if there is one). The read is only then thrown away if it is now shorter than `truncLen`.

**Comment by wolass** [comment]
Thanks for the explanation!

**Comment by chemokine** [comment]
The manual of phyloseq said that: from **1.8+** Q2 means end of high quality region. But the description you cited actually was referring to "**BEFORE** Illumina 1.8 ".  Dose the manual need to be modified to avoid confusion? Thanks!

**Comment by benjjneb** [comment]
@chemokine

Yep, you are right on that. I think it may be best to remove the rationale on truncQ=2 entirely actually to avoid confusion. It's a decent default value for <1.8 or 1.8+, and delving into the vagaries of various Cassava versions is not the best idea in our help text.

**Comment by benjjneb** [comment]
References to the 1.8 CASAVA version removed in 567acabcdd4d5b7140093e80f6fe40af3e43f985

**Comment by andzandz11** [comment]
So the 2 is actually a Phred quality score? Because I was very confused about that too. I think if you use the aforementioned designation it is less confusing as Phred score is defined on Wikipedia and easy to google.
