### ISSUE TITLE
Some sequences were shorter than 50 nts and will not receive a taxonomic classification.

### ISSUE THREAD

**Issue by FarzanehRah** [benjjneb/dada2#1706]
Hello, 
The amplicon we use for plant barcode classification is trnL (length 10-143 bp), with assignTaxonomy function I have this message:
`Some sequences were shorter than 50 nts and will not receive taxonomic classification.
`
So we lost some information from our data, is there any way to change the MIN_REF_LEN <- 20 and MIN_TAX_LEN <- 50?

Thank you so much

**Comment by benjjneb** [comment]
There is no way in the API to change those parameter values.

Depending on your proficiency with R, you could redefine the function with those values changed in your R session. I.e. start by copying the function code, then modifying it so it makes the private package function calls correctly, and change those values. A warning, anything less than 8 will result in a segfault, since the kmer size of 8 is hard-coded C-side. Also, I'm not sure how good a choice the naive Bayesian classifier method is for very short sequences.

**Comment by FarzanehRah** [comment]
Thank you so much,  it's very nice that questions are answered here.

When I copy the function, and try to run it I get this error:
`Error in as.list.default(X) : 
  no method for coercing this S4 class to a vector`

**Comment by benjjneb** [comment]
Functions in a package have native access to all the private functions (non-exported) defined in that package. This breaks when you copy the function code into your console, or working R script.

You can often fix this by prepending `dada2:::` to functions throwing errors.

That said, I'm unclear as to what exactly is causing this error. It ie best to identify the specific line causing the error, by stepping through the function line-by-line, rather than calling it all at once.

**Comment by FarzanehRah** [comment]
Thank you so much for your help, now I'm able to change the min length, results changed slightly  (tryRC  = TRUE).
I tried to find about best way for short read classification and in a study it says: _composition-based methods are now perfectly capable of classifying short query sequences. For example, Naive Bayes Classifier obtained over 90% accuracy for 25 bp reads with 5-fold cross-validation_  [(](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-13-92)
but in my case the majority of the sequence are not classified, even with length more than 50 (range 10-148), while with blast there are several hits for some of them.  I'm unsure whether there is another option available in this particular case.

**Comment by benjjneb** [comment]
I can't really say. Depending on the marker, and how well it separates between taxa at various levels, the naive Bayesian classifier may work better or worse.

Given that you are working with a less-common locus like trnL, it would make sense to look at other approaches to taxonomic classification. Staying within R, the `IdTaxa` approach from the DECIPHER package is one such approach (and some basic usage is noted in the dada2 tutorial) but will require more work to build the relevant reference database. There are other options outside R of course as well. I don't have any particular insight on what might work the best for this specific application though.

**Comment by FarzanehRah** [comment]
Thank you for your invaluable help. By training the database using the `LearnTaxa `function for the` IdTaxa` function in the `DECIPHER` package, in my initial attempt, the majority of ASVs were assigned. This was also helpful  for another analysis with COI amplicons, where my database consisted of a large collection of 1.5 million sequences from NCBI. Using `assignTaxonomy`, the majority of ASVs were assigned up to the insecta class (although I noticed that the insecta sequences were overrepresented in my database), now based on the control positive samples, the classification has further improved.
I am truly grateful for your insights and guidance.
