### ISSUE TITLE
Error in UseMethod("close") : 

### ISSUE THREAD

**Issue by swuyts** [benjjneb/dada2#172]
Dear,

I've been trying to run DADA2 on our cluster as described in the big data tutorial (http://benjjneb.github.io/dada2/bigdata_paired.html), but get the following error message in the filtering step if I submit the Rscript as a job.

`Error in UseMethod("close") : 
  no applicable method for 'close' applied to an object of class "FastqStreamer"
Calls: fastqPairedFilter -> close
Execution halted
`

However, when I run R interactively and not as an Rscript it seems to work fine. Any suggestions on how to improve this so I don't have to interactively login to the nodes?

Thank you very much for your feedback!
Sander 

EDIT: I might need to add that the first part seems to work fine, but that it crashes after the first paired reads are filtered.

EDIT 2: The same happened when running the sample inference script. It did not work when calling
`Rscript sample_inference.R`
But it did work when I fired up R and copy and pasted all of the commands in there. Although we noticed that everything just ran on one core, even with multithreading option enabled.

EDIT3: All of our problems are solved when going back to version 1.1.6

**Comment by benjjneb** [comment]
Can you tell us a bit more about your Rscript setup, in particular the following when Rscript is invoked: OS, `R.version`, `packageVersion("ShortRead")` and `packageVersion("dada2")`. Also, can you try one change to the Rscript, adding `library(methods)` to the start of the script?

@joey711 could you chime in on this one? It appears that the following lines in `fastqPairedFilter` are failing:

```
f <- FastqStreamer(fn, n = n)
on.exit(close(f))
```

For some reason it's failing to find the `close` method for the `FastqStreamer` S4 object here...

**Comment by swuyts** [comment]
Sure,

I've got both the filtering and the sample_inference in two separate scripts (filtering.R  and sample_inference.R) which are both called using `Rscript filtering.R` or `Rscript sample_inference.R`.

We're running Ubuntu 14.04.5 ; R version 3.3.1 ; ShortRead version 1.32.0 ; dada2 1.2.0

Adding library(methods) seems to fix the problem!

Thanks!

**Comment by benjjneb** [comment]
Great!

Leaving open for now and marking as a bug though, as we should be explicitly importing all the `methods` functions we need so that Rscript works as expected without needing the `library(methods)` call.

**Comment by joey711** [comment]
This is a classic namespace issue and error message. One of the canonical workarounds is to add the intended package in front of the method name with double-colon: `ShortRead::close()`. In some settings this becomes limiting because you've now restricted that call to just the method(s) defined in ShortRead. In this context, that is what you want.

The real fix is to add `@importFrom methods close` and/or `@importFrom ShortRead close`... (probably the latter) in the roxygen header of this function. Then when you rebuild the doc, it will be added to the namespace. Though you don't want to modify it directly at all because you're using roxygen, the NAMESPACE file is where the magic happens, and it *should* have had the equivalent import statement for `close`, but did not: `importFrom(ShortRead,close)`.

I suspect at some point in the past we had a full import of either methods, ShortRead, or both; and that's how this slipped through the cracks. It's weird, because `R CMD check` would normally catch this as a warning or error. There may be something strange about the users R session prior to calling the script, but clearly the absence of the `close` explicit import is a namespace bug that should be fixed either way.

**Comment by benjjneb** [comment]
Promoted `methods` to a `Depends:` package in the Namespace file. This fixes the filter issue when invoking via Rscript, which does not load `methods` by default, unlike interactive R sessions: 2c8d08f8b1e09503eb9fdd6cbd858e5e8f702854

Still need to propagate this change to the BioC release branch.

**Comment by benjjneb** [comment]
Fixed in 1.2 release: 44503523b3471cbaf11398326fc0a03a16f5b398

Pushed to BioC release, and should propagate to the binaries in a couple days.
