### ISSUE TITLE
DADA2 Trimming Parameter Automation

### ISSUE THREAD

**Issue by alexandriai168** [benjjneb/dada2#1729]
I'm using DADA2 as part of a eDNA metabarcoding data pipeline, and I was hoping to automate choosing TruncLen (instead of visually choosing based on plotQualityProfile()).  As you've said in multiple github threads, however, there are a bunch of ways to choose TruncLen and you just want to not do it incorrectly.  Currently, I use the attached code to choose TruncLen for both forward and reverse reads.  (some of the code is from the plotQualityProfile() function)

```
 print(paste0("Calculating quality trimming length...", Sys.time()))
    n <- 500000
    trimsF <- c()
    for(f in fnFs[!is.na(fnFs)]) {
      srqa <- qa(f, n=n)
      df <- srqa[["perCycle"]]$quality
      means <- rowsum(df$Score*df$Count, df$Cycle)/rowsum(df$Count, df$Cycle) #calculate mean qual at each cycle
      where_to_cut <- min(which(means<30))-1 #trim first time mean qual dips below 30
      trimsF <- append(where_to_cut, trimsF) 
    }
    where_trim_all_Fs <- median(trimsF) #get average of all trims - use this as Trunclen forwards
    
    trimsR <- c()
    for(r in fnRs[!is.na(fnRs)]) {
      srqa <- qa(r, n=n)
      df <- srqa[["perCycle"]]$quality
      # Calculate summary statistics at each position
      means <- rowsum(df$Score*df$Count, df$Cycle)/rowsum(df$Count, df$Cycle)
      where_to_cut <- min(which(means<30))-1
      trimsR <- append(where_to_cut, trimsR)
    }
    where_trim_all_Rs <- median(trimsR)

    both_length <- where_trim_all_Fs + where_trim_all_Rs
    min_length <- primer.data$tapestation_amplicon_length_F[i] + 25
    if(both_length < min_length){
      stop("Trim qual too high- not enough overlap. Choose a new Q score.") #if you trim too much, can't overlap
    }
  ```

I was wondering if you think this would be effective?  Are there any suggestions you have that would improve this (the runtime is really long)?  Is there a reason DADA2 doesn't currently have a function that does this?

Thank you!

**Comment by benjjneb** [comment]
In my reading, the approached described by this code seems to hit the necessary points: A common truncation length is chosen for all samples, and overlap after truncation is checked (although I'm not surea bout the `[i]` index in the tapeastation length.

> Are there any suggestions you have that would improve this (the runtime is really long)?

I haven't worked in depth with the ShortRead package in a while, but I do remember when playing around with it before that some steps can be made much faster. I would recommend running a time profiler to identify slow lines, and seeing what might be done to make them faster. For example, looking at the top-n reads in a fastq file might be a lot faster than sampling n reads from a fastq file (the `qa(r, n=n)` step) which may require reading the entire file in.

> Is there a reason DADA2 doesn't currently have a function that does this?

Not an obvious one. Maybe partly because I am in favor of people looking at data and making decisions most of the time. But for larger operations automation can be useful. The Zymo folks did make a tool called Figaro to do this `truncLen` selection in DADA2 as well: https://files.zymoresearch.com/documents/figaro_whitepaper.pdf
