### ISSUE TITLE
Merging Multiple Batches in DADA2

### ISSUE THREAD

**Issue by nmshahir** [benjjneb/dada2#175]
Excellent tool. I have a question regarding merging multiple batches, you mention that the parameters need to be the same in order to merge? Does that mean that  trimLeft and truncLen parameters need to be the same or do all the filtering parameters need to be the same? 
Thank you in advance.
-Nur

**Comment by benjjneb** [comment]
Just the trimming parameters need to be the same (and I'm assuming your primers were the same across your batches) so that the same sequence region is covered by each batch.

Filtering parameters (eg. `maxEE`) can be different, and sometimes should be different if the quality was very different between your sequencing runs.

**Comment by nmshahir** [comment]
Awesome! Extension of previous question, when combining multiple batches should you aim for trimming parameters that preserve the highest the quality or preserve the length or like a compromise?

Thank you.

**Comment by benjjneb** [comment]
No one answer for everyone, but probably a compromise. More length can give better taxonomic resolution, while tighter trimming will let more reads through.

Another thing to keep in mind, when using paired reads that overlap in the middle, only the `trimLeft` parameter really matters for merging different batches, as that determines the amplicon length.

**Comment by nmshahir** [comment]
I'm a little confused now.

> Another thing to keep in mind, when using paired reads that overlap in the middle, only the trimLeft parameter really matters for merging different batches, as that determines the amplicon length.

 So, I'm using paired reads from Illumina MiSeq runs and all are from the V1V2 regions. Are you saying that I can have varying truncLen parameters for the different batches BUT trimLeft has to be the same across all batches?

**Comment by benjjneb** [comment]
Yes.

Because runs are merged **after** merging paired reads, and because `truncLen` does not affect the length of the **merged** reads (just the length of the overlap between them), then `truncLen` can vary between runs. 

`trimLeft` must be the same between them all, because it affects the length of the **merged** reads.

* caveats: `truncLen` must always be long enough for reads to overlap, and I'm assuming your reads don't extend past the end of the other primer *
