### ISSUE TITLE
Dealing with Variable Sequence Lengths in DADA2

### ISSUE THREAD

**Issue by alexandriai168** [benjjneb/dada2#1774]
Hello! I'm working with primers that result in variable fragment lengths (DLoop, sequenced using Illumina miseq).  I was wondering if you have any suggestions for handling this type of data. Will there be issues with merging/learning error rates? Especially since dloop's fragments can range from ~240-450, I'm hesitant about trimming too much (trunclen) so there isn't a healthy amount of overlap for merging or too little, which would incorporate low quality reads (right now I'm using 245 F and 178 R, determined by a quality scoring algorithm I created).  Attached is some info about my sequences' quality.
![muri305_dl_DL_forward](https://github.com/benjjneb/dada2/assets/115185382/b917fa6b-4c48-4eba-8b98-1d3cb0ca8ed8)
![muri305_dl_DL_reverse](https://github.com/benjjneb/dada2/assets/115185382/af5da583-a9ff-4f9b-8c74-2b1462d11179)

Thank you so much for your help!

**Comment by benjjneb** [comment]
What is DLoop?

It is important to note that `truncLen` not only truncates reads, it also filters out any reads shorter than the truncation length. Depending on where the length variation is coming from that may be quite undesirable (for example, ITS sequences often shouldn't be filtered using `truncLen` because all the real ITS ASVs with length less than the threshold will be lost).
