### ISSUE TITLE
Error with taxonomic assignment in 16s analysis

### ISSUE THREAD

**Issue by Sada-mwatelah** [benjjneb/dada2#1796]
I have a huge file thus due to lack of memory on the HPC cluster after cleaning the sequences and merging them (my file has 300 rows and 16,000 columns).I exported out the seqtab.nonchim file as a csv and imported it back. I want to attach the taxa and i am getting the following error constantly even after trying different solutions posted here:- Error in getUniques(object, collapse = collapse, silence = silence) : 
  Unrecognized format: Requires named integer vector, fastq filename, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

I used the following work flow:
data_frame <- read.csv('~/Desktop/CC_scripts/seqtab.nochim copy.csv', header = TRUE,sep = ",")

asv_seqs <- colnames(data_frame)
asv_headers <- vector(dim(data_frame)[2], mode="character")
for (i in 1:dim(data_frame)[2]) {
  asv_headers[i] <- paste(">ASV", i, sep="_")
}
asv_fasta <- c(rbind(asv_headers, asv_seqs))
asv_otu <- t(data_frame)
row.names(asv_otu) <- sub(">", "", asv_headers)

RDP <- "~/Desktop/Trainingset/rdp_train_set_18.fa.gz"

taxa <- assignTaxonomy(data_frame RDP, multithread = TRUE, tryRC = TRUE)

When i transform the data freame i get the following error:- **Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'reverseComplement': key 88 (char 'X') not in lookup table**

Am not sure where am going wrong. Same Error appears when i use the SILVA training set.
I have attached a sample of my data here
[Seqtab.nonchim_1.csv](https://github.com/benjjneb/dada2/files/12317899/Seqtab.nonchim_1.csv)

**Comment by benjjneb** [comment]
In the future, when saving R objects for later reloading, use `saveRDS`/`readRDS`. This maintains the R object completely. When you use `write.csv`/`read.csv` instead, you are losing the structure of the R object (e.g. is it a matrix or a data.frame, what storage mode etc), and it is easy to make mistakes and lose rownames/colnames as well.

Here, I am not completely following the data manipulation you are using to create the data frame, but it is not creating a "native" DADA2 object that `assignTaxonomy` can recognize. So, just give the vector of ASV sequences instead (`asv_seqs` I think). That said, I recommend sticking with the base dada2 workflow all the way through `assignTaxonomy`, rather than interpolating this creation of a custom data.frame in the middle.

**Comment by Sada-mwatelah** [comment]
Thanks for the input
