### ISSUE TITLE
Taxa assignment fail 

### ISSUE THREAD

**Issue by luisymbio** [benjjneb/dada2#1831]
Hi!
I'm following the bigData workflow, withouth any type of modification. 

To give you a little bit of background, I runned this workflow on a subset of samples (122 x 2) and was all ok, then I modified the starting samples for other reasons, substituting a part of it. Now I'm trying to run it on 121 x 2 (paired ends). 

How I could manage this error? or in which way I could try to understand what is the problem? 

> taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread = parallel::detectCores(), tryRC = TRUE)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'reverseComplement': key 95 (char '_') not in lookup table
In addition: Warning message:
In assignTaxonomy(seqtab.nochim, unite.ref, multithread = parallel::detectCores(),  :

The addition warning message is regarding sequences that find less than 50 nt, I'm trying to solve also this problem.

**Comment by benjjneb** [comment]
This error message suggests that there is an underscore character in at least one of the sequences being extracted from `seqtab.nochim`. This is usually due to some misformatting of the object. Do you see anything unusual in `sq <- getSequences(seqtab.nochim)`? What is the output of `dada2:::C_isACGT(sq) |> table()`?

**Comment by luisymbio** [comment]
There was an error in the asv sequences generated along the pipeline and in the database that I was using, I solved it, thank you!
