### ISSUE TITLE
Error: vector memory exhausted (limit reached?)

### ISSUE THREAD

**Issue by JR-EvolEcol** [benjjneb/dada2#1894]
I’m trying to filter an Illumina MiSeq data set with dada2, but I keep running into a problem: derepFastq fails after a while with this error message: Error: vector memory exhausted (limit reached?)

It fails on the filtRs after succeeding with quite a bunch of the files (and succeeding with all the filtFs). 

Do you have any idea how I can solve this?

I have tried to reinstall R, reinstall dada2, update packages, etc.

I’m running a 14” MacBook Pro 2021 with 16GB RAM and Apple M1 Pro chip. 

MacOS Ventura 13.2
R 4.3.2
R Studio Version 2023.12.1+402
dada2_1.30.0 
Rcpp_1.0.12

Kind regards,
Jacob Roved
Postdoc
Department of Biology
Lund University

**Comment by cjfields** [comment]
@JR-EvolEcol I ran into a similar error, and found that if I set the `n` value to a lower number like 100k it helped.

**Comment by JR-EvolEcol** [comment]
Thank you for the suggestion! I tried to reduce n to 100K and even to 10K, but I still got the error. 

It seems to occur after about the same number of samples each time I try (though not always at the exact same sample). When running verbose=TRUE I can see that the algorithm slows down, and eventually throws the Error: vector memory exhausted (limit reached?).

**Comment by cjfields** [comment]
It looks like a similar issue was reported but for `assignSpecies`, in #1282.  As @benjjneb pointed out there it may be a memory limitation issue.  Does memory increase while running this (might also explain the slowdown)?  Also, just checking, but is the version of R you are running one built for Apple Silicon?

**Comment by benjjneb** [comment]
@JR-EvolEcol Can you post the exact command where this error is occurring?

If you are running the `derepFastq` command yourself, you can probably sidestep this error by updating to the more modern dada2 workflow that loads in samples one-at-a-time rather than all at once. See [the dada2 tutorial](https://benjjneb.github.io/dada2/tutorial.html). `derepFastq` is never called explicitly, it is called on-the-fly by `dada` and `learnErrors` etc. This means only one sample is loaded into memory at a time.

**Comment by JR-EvolEcol** [comment]
Dear benjjneb, 
Thank you, that solved the issue. I had not been aware of  the tutorial with the updated protocol. 
Kind regards
