### ISSUE TITLE
Dereplication timing

### ISSUE THREAD

**Issue by PSchulman** [benjjneb/dada2#1901]
I just received just received the feedback from a reviewer related to the dada2 pipeline I used (afaik, I used the dada2 pipeline with standard parameters) and I just received the following text:

> Based on lines 207-210, 16S reads with more than 2 errors were first discarded. Then reads were dereplicated, followed by merging forward and reverse sequences. This pipeline is rather uncommon as dereplication is usually after merging, and then reads with errors can be discarded. I wonder how many sequences would be lost if reads were dereplicated before merging. Please provide more information to justify this pipeline.

As far I'm aware derep wouldn't change much as it is only pulling together equal sequences, is that right? Do the reviewer's comments have any merit?

**Comment by benjjneb** [comment]
Well, the workflow you are using is by definition quite common, as it is the standard worfklow that follows the dada2 tutorial. That might be sufficient as a response to "justify [the] pipeline".

Other than that, I think the reviewer might be mixing together dereplication and denoising when they are using the term "dereplication". So, I agree with you that dereplication isn't changing anything, but changing what step you do denonising could matter. The reason dada2 does denoising of reads first, then merges, is because merging the reads first leads to an inconsistent relationship between quality scores and error rates along the merged reads, specifically between the overlapping and non-overlapping sections of merged reads.
