### ISSUE TITLE
Weird error plot with doubtful taxonomy

### ISSUE THREAD

**Issue by Varun9599** [benjjneb/dada2#1906]
Hello @benjjneb ! 
Hope you are well.
I am currently running 2x300 PE samples on DADA2. Quality score looks good and doesn't drop below 30. Although, I observed an atypical error plot with sudden drops. (Attaching below)
On top of that, the taxonomy assignment was really weird with names that we have never seen in our kind of samples. Can you please help me understand the problem?
We have recently shifted from 2x250 to 2x300. Did not face this issue in our 2x250 data.

Thanks and Regards,
Varun
![Error plot](https://github.com/benjjneb/dada2/assets/132902216/a44daac8-35ea-4a9f-baed-431b5b9b3c77)

**Comment by Varun9599** [comment]
P.S. My earlier 2x250 data was Illumina miseq but the current data is nextseq.

**Comment by benjjneb** [comment]
Your error models look OK, the "funniness" in them is because of the binned quality scores from nextseq, but in practice we see that even though it looks odd they work well. You can read this Issue for a lot more discussion: https://github.com/benjjneb/dada2/issues/1307

I don't know what to tell you about unexpected taxonomies though. Could be a variety of things, off-target amplification, mismatch between reference database and your environment etc. Technical things to check would be `assignTaxonomy(..., tryRC=TRUE)` which will also check the reverse-complement of all the query ASVs, which takes care of the situation where your reference is in reverse-complement orientation to your amplicon data.
