### ISSUE TITLE
Sequence table is very large and taxonomy assignment is only at kingdom level

### ISSUE THREAD

**Issue by ramay** [benjjneb/dada2#192]
Hi,

I am trying to process 51 samples with dada2 to assign taxonomy but at several steps the results seem off to me. It will be very helpful, if you can point me in the right direction.

As a first step I run cutAdapt to remove primers and do quality trimming on the raw fastq files. After this I start the dada2 big data pipeline.

I use fastqPairedFilter in dada2 also with the following parameters:
```
trimLeft<-c(20,10)
truncLen<-c(275,220)
maxEE<-2
trunQ<-2
maxN<-0
```
I then followed the pipeline steps for denoising and merging.

First result which worried me is that the `seqtab <- makeSequenceTable(mergers)`
returns a matrix of size 51 x 99267. The sequence table seems extremely large.

Following is the result from 

`table(nchar(getSequences(seqtab)))`

```
255   256   257   258   259   260   261   262   263   264   265   266   267
 4597   342   349   336   338   360   295   322   331   372   322   334   319
  268   269   270   271   272   273   274   275   276   277   278   279   280
  337   382   331   354   365   388   362   362   376   354   335   363   389
  281   282   283   284   285   286   287   288   289   290   291   292   293
  347   351   339   361   355   355   365   365   354   407   357   361   392
  294   295   296   297   298   299   300   301   302   303   304   305   306
  350   364   358   379   362   367   382   348   358   349   349   370   381
  307   308   309   310   311   312   313   314   315   316   317   318   319
  368   345   341   380   357   366   373   380   342   361   363   389   389
  320   321   322   323   324   325   326   327   328   329   330   331   332
  380   358   305   337   353   369   330   355   359   342   336   340   345
  333   334   335   336   337   338   339   340   341   342   343   344   345
  392   348   354   359   372   364   336   346   336   353   356   320   340
  346   347   348   349   350   351   352   353   354   355   356   357   358
  327   363   338   347   352   317   331   357   340   364   324   341   348
  359   360   361   362   363   364   365   366   367   368   369   370   371
  292   338   317   342   301   308   323   325   313   316   332   312   318
  372   373   374   375   376   377   378   379   380   381   382   383   384
  319   767  1316   990   853  1350  1303   853   558   321   301   321   283
  385   386   387   388   389   390   391   392   393   394   395   396   397
  330   290   283   346   252   348   512   489  1454  6904   517   334   421
  398   399   400   401   402   403   404   405   406   407   408   409   410
 2032 12169  3101   732   415   371   282   225   241   236   241   235   368
  411   412   413   414   415   416   417   418   419   420   421   422   423
  941   216   184   210   295  1654   811   955   217   184   233   827  1451
  424   425   426   427   428   429   430   431   432   433   434   435   436
  466   210   151   144   133   145   124   123   117   131   167   197   123
  437   438   439   440   441   442   443   444
  115   115   187   227   106    96    89    94
```

After using removeBimeraDenovo, I am left with only 13 % of the sequences.
 

I found in an other issue thread that this could be due to primers being present, but in my case CutAdapt output shows that sequences are trimmed for primers.

In the next step when I try to assign taxonomy and I get assignment only at the kingdom level. All other levels are NA.

I am attaching the merger.rds file which contains output after merging the reads and also seq.rds which contains the sequences after chimera removal and quality plots for the reads in a zipped file.
[dada2_test.tar.gz](https://github.com/benjjneb/dada2/files/771979/dada2_test.tar.gz)

Thanks for your help in advance!

Hena

**Comment by benjjneb** [comment]
Hi Hena,
There are a couple things going on here:

1) You have a lot of phiX contamination (12074/13634 SVs in the sequence tabel you shared). The canonical way to deal with that in the dada2 workflow is at the filtering stage: fastqFilter(..., rm.phix=TRUE)  However, you can also remove it from the raw sequence table you created from the merger objects: `st.nophix <- st[,!isPhiX(st)]`

2) Your reads are in the "reverse-complement" orientation relative to the reference databases. If you are using dada2 1.3.3 or later this is fixed with: `tax <- assignTaxonomy(st, ref.file, tryRC=TRUE)`. With earlier versions you can just RC the seqeunces yourself: `tax <- assignTaxonomy(dada2:::rc(getSequences(st)), ref.file, tryRC=TRUE)`

3) On the chimera removal issue -- most of your **reads** should pass chimera filtering, but it is not uncommon for most **sequence variants** to be flagged chimeric. That is, the number of columns in your sequence table might decrease a lot, but its sum shouldn't decrease too much, so check no that: `sum(st.nochim)/sum(st)`

**Comment by ramay** [comment]
Thank you very much! 
I did not think Phix would be such a sizeable contaminant ! The steps you mentioned have solved my problem.
I checked sum(st.nochim)/sum(st) and it is ~ 0.73. Seems reasonable.
Thanks Again!
Hena
