### ISSUE TITLE
Non-fitting Error Plots

### ISSUE THREAD

**Issue by SophMN** [benjjneb/dada2#1937]
Hello. I was analysing the error rates of my filtered files and I got some strange plots that don't fit perfectly for some base transitions. Should I proceed, if not, how can I troubleshoot this? Thank you. 

Here are the error plots:
filtFs: 
[filtFs error rates plot.pdf](https://github.com/benjjneb/dada2/files/15113488/filtFs.error.rates.plot.pdf)
filtRs: 
[filtRs error rates plot.pdf](https://github.com/benjjneb/dada2/files/15113493/filtRs.error.rates.plot.pdf)

**Comment by benjjneb** [comment]
What is the sequencing technology you are using? Has the data been pre-processed in any way?

**Comment by SophMN** [comment]
The samples were sequenced on the MGI platform. I did filter and trim the reads, should I trim the reads a bit further? Will that improve the error rates perhaps?

**Comment by benjjneb** [comment]
I can't offer great guidance because we have not worked with MGI sequencing data ourselves.

There do appear to be some irregularities in the fitted error models, but with some other previous technologies what we typically find is that the fitted error model is "good enough" such that the DADA2 algorithm still works well. If you do have any positive control samples, it might be worth checking that your getting back more or less what you expect there.

**Comment by SophMN** [comment]
Okay. Thank you. Unfortunately they didn't sequence a mock community that would've served as a positive control.
