### ISSUE TITLE
Unassigned levels with Greengenes

### ISSUE THREAD

**Issue by nmshahir** [benjjneb/dada2#197]
I have a a question regarding the assignTaxonomy step for DADA2. I'm assigning taxonomy using GreenGenes 13.8 clustered at 97%,

Can I assume that if I have taxa that are unassigned at the genera level, that implies that greengenes doesn't have a consensus for that genera BUT believes it to be a "distinct" genera?

Thank you,
Nur

**Comment by benjjneb** [comment]
No, it does not imply that it must be distinct from other assigned genera.

NA means that the classifier is uncertain which genus the sequence is. This might be because the genus is not represented in the database, or because the sequence could be classified to more than one genus.

**Comment by nmshahir** [comment]
So if I run DESeq and get a result like:
k__Bacteria p__Firmicutes c__Bacilli o__Gemellales f__Gemellaceae g__

This implies that the A) classifier is could be classified as more than one genus in the Gemellaceae family OR B) it's in the Gemellaceae family but that genus is not represented in the database?

**Comment by benjjneb** [comment]
The sequence variant can be classified the the Gemellaceae family, but the classifier cannot resolve what genus it is in, either because the genus is ambiguous or because the database is incomplete.

Classifiers are not infallible, so if you find an SV of interest it may be worth looking into it by hand, eg. by BLAST-ing it against nt.
