### ISSUE TITLE
`fastp` before `dada2`

### ISSUE THREAD

**Issue by andrebolerbarros** [benjjneb/dada2#1991]
Hey everyone,

Thanks for the amazing package!

I was wondering if there is a disadvantage of running the fastq files through a program like `fastp` before running dada2. I would expect that, when one gets sequences from different lengths, this could impact the ASV step ("Losing" ASVs and merging sequences that are indeed different).

Thanks in advance

**Comment by benjjneb** [comment]
> I would expect that, when one gets sequences from different lengths, this could impact the ASV step

Yes this is the main problem. In short, the core denoising algorithm is using repeated observations of the exact same sequence (including length) to identify ASVs. When random length variation is introduced by approaches like per-read truncation based on e.g. sliding window quality, this makes dada2 less sensitive to detecting rarer ASVs, since it is less likely that there will be multiple error-free reads that are also of the exact same length.

In general, the length variation will be collapsed within identified ASVs, so it is mainly the loss-of-sensitivity issue that is problematic.

**Comment by andrebolerbarros** [comment]
Thanks @benjjneb. 

I would then assume programs that use the approach of sliding windows for quality trimming or others that may lead to variation of sequence length should not be used before dada2, letting dada2 make its magic.

**Comment by benjjneb** [comment]
> I would then assume programs that use the approach of sliding windows for quality trimming or others that may lead to variation of sequence length should not be used before dada2

Yes. The DADA2 filtering approach of `truncLen` + `maxEE` is preferred because it works well with the subsequent steps in the DADA2 workflow.

**Comment by andrebolerbarros** [comment]
Thank you @benjjneb !
