### ISSUE TITLE
Should you trim samples individually or together?

### ISSUE THREAD

**Issue by hjarnek** [benjjneb/dada2#1997]
Hi,

As I've understood it, DADA2 essentially needs the reads adhering to the same ASV to be equally long for the ASV inference to work properly. Does this apply cross-samples? Or can you trim different samples at different locations (to optimize for varying quality profiles), as long as all the reads within the same sample are the same length?

If not, how should you deal with different samples having their quality drop at different locations? If for example one sample has its quality drop significantly earlier than the others, quality-trimming it at the same location in combination with a maxEE filter can almost obliterate it. Is that really the way to go?

**Comment by benjjneb** [comment]
In order to produce a valid ASV table across samples, it is important that each sample is truncated in the same way. In short, the simple methods used to merge ASV profiles across sample/studies in DADA2 expect that the length of ASVs are constant, not variable amongst samples.

> If not, how should you deal with different samples having their quality drop at different locations?

If we are talking about a set of samples that have been sequenced on the same sequencing run, I would say this variability is not relevant. The sequencer does not know which sample a read comes from, so reads from various samples being multiplexed on the same run should have the same error-rate profile along the read.

This becomes more complicated if we are talking about integrating data across "batches", which in the DADA2 context are PCR/sequencing batches.

**Comment by hjarnek** [comment]
Alright, thanks @benjjneb

Just one thing.

> If we are talking about a set of samples that have been sequenced on the same sequencing run, I would say this variability is not relevant. The sequencer does not know which sample a read comes from, so reads from various samples being multiplexed on the same run should have the same error-rate profile along the read.

This makes perfect sense, but samples can be of varying quality nonetheless. I don't know how. But why otherwise would I be seeing such different quality profiles for my samples, processed and sequenced together? S4 and S5 are outliers in this context, I have more samples that look like the others.

![QC_plot](https://github.com/user-attachments/assets/0a47477f-8e8a-4b0b-8dd0-5d0143723120)

**Comment by benjjneb** [comment]
The R1 and R2 reads (the `_1` files and `_2` files) typically have different error profiles from each other, as they are not sequenced at the same time (R2 is sequenced after R1). So your error profiles here will look a little more consistent if you look at just R1 or R2 by themselves.

The quality of the library preparation can vary by sample and can influence quality profiles. This is the most common source of major differences in profiles across samples. It is still advised to perform consistent quality trimming/truncation across samples though because the simple methods used to merge ASV profiles across sample/studies in DADA2 expect that the length of ASVs are constant, not variable amongst samples.

**Comment by hjarnek** [comment]
Alright. Yes, I meant only to compare forward to forward and reverse to reverse quality profiles, in which case S4 and S5 are the odd ones out. But I guess I must have done something that affected them during the library preparation. It bugs me a little though that I don't understand how that could happen. I mean, all the samples are pooled during library preparation, so it couldn't be any interfering contamination in just those samples, and the DNA strands coming from those specific samples shouldn't statistically be any different than the ones coming from the other samples in terms of difficulty of sequencing. Could it be something with the indexes, affecting the cluster generation on the flowcell? Anyway, I will close this now, as these thoughts are not related to DADA2. Thank you for your help in clarifying the preferred trimming strategy!
