### ISSUE TITLE
Problem with Taxonomy Assignment DADA2

### ISSUE THREAD

**Issue by TamarKopadze** [benjjneb/dada2#1998]
I have been having an issue assigning taxonomy to ITS sequences using dada2 pipeline.

I am able to get ASV table and I even checked ASV lengths and it was in the normal range for ITS1 (200-250 bp). I also ran the final sequences in the BLAST and was able to get matches to fungal species. But for some reason the assigntaxonomy portion of my dada2 script is producing a table with NA NA NA NA under Kingdom, Phyla, ..., Species. 

this is the portion of the script for the taxonomy assignment:

taxa_fungi <- assignTaxonomy(seqtab.nochim, "file.path/UNITE_public_21.04.2024.fasta", multithread=TRUE)

I hope somebody is able to help me with the issue.

**Comment by benjjneb** [comment]
Could you clarify exactly which UNITE fasta file you are using here? To work with the DADA2 `assignTaxonomy` function, it is expected you have downloaded files from the "General Fasta" release section here: https://unite.ut.ee/repository.php#general

I ask because your filename doesn't look the same as the names of the files downloaded there.

If you are using the right file (just renamed), the first thing to try is to set `assignTaxonomy(..., tryRC=TRUE)`. This will also try the reverse complement of each query sequence. By default `assignTaxonomy` only compared the query sequences to the reference database assuming they are in the same orientation, and if they aren't it can results in large amounts of NA assignments.

**Comment by TamarKopadze** [comment]
I was using a file from this link: https://unite.ut.ee/repository.php#general but the files under "UNITE+INSD". I will try assignTaxonomy(..., tryRC=TRUE) and see if that helps with the issue.

**Comment by benjjneb** [comment]
I would also try the "General FASTA release" files. These are what we have evaluated in the past. The "UNITE+INSD" files are an order of magnitude larger, and there may be memory and/or run-time issues when using those files as the reference.

**Comment by TamarKopadze** [comment]
Thank you, I will try the general release file. Do you also recommend using tryRC=TRUE as well?

**Comment by benjjneb** [comment]
> Do you also recommend using tryRC=TRUE as well?

The only cost is it takes about twice as long to run. The benefit is it avoids the misorientation issue. So I would try it.

**Comment by TamarKopadze** [comment]
Thank you!
