### ISSUE TITLE
16S data treatment with very low abundance

### ISSUE THREAD

**Issue by karenandreac** [benjjneb/dada2#2019]
Hello!

I'm analysing the trunk's microbiome of a tree (MiSeq 16S V4). Since it's woody tissue, is expected to have very low diversity, therefore, my ASV abundance table has samples with very low features. I'm trying to normalize my data to create the PCoA through the CSS method, but after the filters, it deletes a lot of samples and that doesn't work for me.
Does someone know what are my options to treat data with very low abundances/features? 

Thanks :)

**Comment by benjjneb** [comment]
I'm don't think this is a DADA2 question, this sounds like a question about how to analyze microbiome data after creating an ASV table with DADA2 in a low biomass environment. So this forum is not the right place for that question. Broadly, I would look at other manuscripts looking at low biomass environments for ideas. One I'm familiar with (because I'm an author) is this one: https://doi.org/10.1111/jvim.16852 , but there are many others.
