### ISSUE TITLE
Write failed: broken pipe

### ISSUE THREAD

**Issue by vhertzb** [benjjneb/dada2#202]
I am running dada2 on an R AMI on Amazon Web Services. I have 38 samples, most of them (i.e., all but 2) with 100K - 200K reads. I spent yesterday getting everything ready to run in dada2.

I started the first dada2-forward step running, and I had set the options to allow for 200 iterations (since this same step failed at 20 iterations on my MBA). When I got in this morning I found that the run had aborted after 26 iterations, and it threw me, not only out of R, but also out of AWS. The message was "Write failed: Broken pipe"

Should I just give all of this up and go to your "Big Data Strategy"? What else can I do (other than throwing out those 2 samples with < 10K reads? Please advise.

I've attached the R script as a .txt file. There is a comment at the point of failure.

[HIAMIdada2.txt](https://github.com/benjjneb/dada2/files/824534/HIAMIdada2.txt)

**Comment by benjjneb** [comment]
I believe that "Write failed: Broken pipe" means that your SSH connection to the AWS instance was terminated, not that the R script terminated. Have you tried logging back into the instance and seeing if the job is still running?

Also, it is almost certainly OK to simply use the error rates learned after 20 iterations, despite the warning message. Even if it hasn't reached perfect convergence yet, the estimates are probably very good by then.

One last unrelated question: what primer set are you using? I just want to check that you will still have sufficient overlap between the paired reads after truncating both at 160.

**Comment by vhertzb** [comment]
I'll check on the AMI status - thanks. I will also use the error rates after 20 iterations - otherwise this is going to take me weeks!

I have to check on the primer set - it is on the MBA and I am not at this moment. We did the V4. I used 160 for both because the quality dropped off pretty substantially between 150 and 200.

Back in another moment.

**Comment by vhertzb** [comment]
Actually there is a message about doing V3 and V4. I am not finding the primers so I am going to have to ask.

**Comment by vhertzb** [comment]
When I asked about primers I got the Illumina guide in response. On page 3 it says that the primers for V3-V4 are

"16S Amplicon PCR Forward Primer = 5' TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG
16S Amplicon PCR Reverse Primer = 5' GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC"

**Comment by benjjneb** [comment]
In order to successfully trim and merge these reads it's important at this point to understand what the amplicon being generated looks like, and what the sequencing tech being used here is.

If this is the Illumina guid (https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/16s/16s-metagenomic-library-prep-guide-15044223-b.pdf) then these are V3/V4 primers that amplify an amplicon of ~460nts, not including the primer sequence. If the primer sequence is included in the sequencing reads, the total amplicon will be ~550nt.

In order to merge, the sum of the two truncation lengths has to be enough for the reads to still overlap in the middle. So, assuming 2x300 reads, the forward `truncLen` plus the reverse `truncLen` must be >~485 if the primers aren't in the reads, and >~575 if they are.

`truncLen=160` for both means that the reads won't be mergable later.

Can you share one sample, or even part of one sample, for some quick testing?

**Comment by benjjneb** [comment]
Thanks for the files Vicki. A couple things here:

You are using the 341F (CCTACGGGNGGCWGCAG), 805R (GACTACHVGGGTATCTAATCC) primer set.

Your amplicons are ~460nt, which includes those primers. The primers must be removed for proper processing. The best way to do that is with an outside program (we recommend trimmomatic) but you can also do it with the `trimLeft` parameter when you filter. Given what I've seen from your test files, this would be a reasonable set of filtering parameters for your data:

```
fastqPairedFilter(c(fnF, fnR), c(filtF, filtR), trimLeft=c(17,21), truncLen=c(285, 230), maxEE=3, rm.phix=TRUE, verbose=TRUE)
```

This will likely help with the non-convergence issue, as part of the problem was that the degenerate bases in the primers were interfering with the estimation of the error model.

And for all that may read this in the future: **PLEASE REMOVE YOUR PRIMERS!**

**Comment by vhertzb** [comment]
Color me suitably humbled (I thought they were already trimmed out) and thankful!
