### ISSUE TITLE
Question from DADA2 + PacBio: Fecal samples tuorial 

### ISSUE THREAD

**Issue by AngusBall** [benjjneb/dada2#2049]
Hi!

Firstly I wanted to thank you for all the effort put into Dada2 and the various tutorials surrounding it. I have recently begun work on my own long read sequencing data and was working through the [Pacbio tutorial](https://benjjneb.github.io/LRASManuscript/LRASms_fecal.html). 

1) Near the end of the Dada2 part of the tutorial bimeras are checked with isBimeraDenovo; however, in the tutorial they aren't removed with removeBimeraDenovo. I was wondering if they were left intentionally in the dataset and if so what was the reasoning behind it?

Aswell since I'm asking questions

2) in github issue #990 Best practices for PacBio taxonomic assignment you suggest that assignTaxonomy with minBoot=80 is recommended for long read. Given that this issue was updated 3/4 years ago now I wanted to see if this is still the official opinion? (versus say IDTaxa for example).

Thank you so much in advance!
Angus

**Comment by benjjneb** [comment]
> Near the end of the Dada2 part of the tutorial bimeras are checked with isBimeraDenovo; however, in the tutorial they aren't removed with removeBimeraDenovo. I was wondering if they were left intentionally in the dataset and if so what was the reasoning behind it?

The workflow you are looking at had the intention of investigating Pacbio data. So we were more interested at that time in understanding the contribution of chimeras to the data rather than just removing them. The chimeric fraction was very small, so in that investigatory work we did not remove them going forward.

> I wanted to see if this is still the official opinion? (versus say IDTaxa for example).

`assignTaxonomy(..., minBoot=80)` is still the recommendation for long-read 16S (the default is `minBoot=50` which is appropriate for short-read 16S). We have not systematically evaluated other taxonomic assignment algorithms like IDTaxa on long-read 16S data.

**Comment by AngusBall** [comment]
Ah that makes perfect sense, Thank you!
