### ISSUE TITLE
Plots!

### ISSUE THREAD

**Issue by joey711** [benjjneb/dada2#21]
I love graphics. This package needs at least a few plot methods to help users visualize and understand the awesome results coming out of `dada`.

**Comment by FabianRoger** [comment]
Hej,

I am trying the DADA2 pipeline right now and I am loving it! Especially together with the .rmd tutorial it is extremely easy to follow. 

However, I agree that some visualisation along the way would be great. I noticed that a lot of information is printed out via message to the console but few summary statistics are produced / visualised. 

One instant where I found a summary useful was for the function `mergePairs`

`mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)`

where the output looks like 

`[1] "75635 paired-reads (in 197 unique pairings) successfully merged out of 78358 (in 642 pairings) input." `

I redirected the output and captured the message so that I could extract the numbers and compute some summary statistics, like

`prct_seq_min      44.44444`
`pct_pairs_min    22.37062`
`prct_seq_median   98.05412`
`pct_pairs_median 38.21810`
`prct_seq_mean     97.07703`
`pct_pairs_mean   39.13568`
`prct_seq_max      99.91426`
`prct_pairs_max    72.48322`

(I'm happy to share the code if you would be interested) 

Would you agree that these kind of summary statistics, especially if presented graphically,  would be a good addition? 
Especially if the pipeline is written as .Rmd file and documented as html output!

**Comment by benjjneb** [comment]
@FabianRoger 

That does sound useful. I think @joey711 started working on something like this but I can't find it now?

The fraction of reads successfully merging is a useful diagnostic for identifying problems, and as you've pointed out is only easily accessible right now by browsing the standard output.

The fraction of pairs successfully merging is not a very useful diagnostic though. It depends strongly on the diversity of the sample, and the non-merging pairs are driven by single read-pairs that get assigned to mismatched clusters, giving a very outsized impression of the amount of mismatching in the data.

**Comment by FabianRoger** [comment]
I agree. I computed it "because it was there"  more than anything else. 

As long as it is not implemented here is how I did it for now (using `dplyr` )

```
stdout <- vector('character') # save messages in variable
con    <- textConnection('stdout', 'w', local = TRUE)
sink(con,  type="message")

mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)

sink(NULL, type = "message") # close connection
close(con)

lapply(strsplit(stdout, "\\s+"), function(x) x[c(1,4,11,13)]) %>% 
  do.call("rbind", .) %>% 
  as.data.frame(., stringsAsFactors = FALSE) %>% 
  mutate_each(funs(as.numeric)) %>% 
  mutate(prct_seq = (V1/V3) * 100, prct_pairs = (V2/V4) * 100) %>% 
  summarize_each_(funs(min, median, mean, max), names(.)[c(5,6)]) %>% 
  t
```

**Comment by wolass** [comment]
I'm doing some plots along my analysis for quality control. I think all users should at least look at similar ones when they want to inquire if there were any outlying samples. 

These are just my ideas for useful plots along the dada2 pipeline. Please advise if these are sound - I can provide code, but that's basic ggplotting :) Maybe these are to basic ideas but I guess this should also be sth to look at along the analysis and If we can make it easier for more users then why not share :)

So after filtrating the reads using fastqPairedFilter() i'm plotting the fraction of reads after filtration with a mean:
![image](https://cloud.githubusercontent.com/assets/2356167/23296696/902987d8-fa76-11e6-9201-986f1b200080.png)

Next I would suggest plotting the fraction of filtrated reads in your forward and reverse primers. This gives also you a hint if you should strengthen or relax your filtration parameters.

![image](https://cloud.githubusercontent.com/assets/2356167/23297129/8dbb579a-fa78-11e6-88fd-8eaad0d3cb3d.png)

**Comment by SilasK** [comment]
In #151 there is a way to extract the numbers from the dada2 pipeline.
