### ISSUE TITLE
Error in seqtab <- makeSequenceTable(dds)

### ISSUE THREAD

**Issue by mghanbari** [benjjneb/dada2#210]
Hi

I have 100 16S files and I filtered, merged and truncated the data using another software. Everything was ok until this step.  Please don't tell me to do it again as it takes ages even with 56 threads!

I appreciate your help for this.

```
filts.learn <- sample(filts, 15) #
drp.learn <- derepFastq(filts.learn, verbose=TRUE)
dd.learn <- dada(drp.learn, err=NULL, selfConsist=TRUE, multithread=TRUE)
err <- dd.learn[[1]]$err_out
plotErrors(dd.learn[[1]], nominalQ=TRUE)
rm(drp.learn);rm(dd.learn)
```

# Sample inference
```
dds <- vector("list", length(sample.names))
names(dds) <- sample.names
for(sam in sample.names) {
  cat("Processing:", sam, "\n")
  derep <- derepFastq(filts[[sam]])
  dds[[sam]] <- dada(derep, err=err, multithread=TRUE)
}
rm(derep)
```
# Construct sequence table and remove chimeras
`seqtab.all <- makeSequenceTable(dds)`

```
Error in FUN(X[[i]], ...) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.
```

**Comment by benjjneb** [comment]
From that code I don't understand how you got that error.

What version of the dada2 package are you using?

Also, did you save the intermediate objects in this analysis?

**Comment by mghanbari** [comment]
I got the error in this step
`seqtab.all <- makeSequenceTable(dds)`

_What version of the dada2 package are you using?_  
```
> packageVersion("dada2")
[1] ?1.3.0?
```

_Also, did you save the intermediate objects in this analysis?_ I just followed the tutorial for large files with single-end reads.

**Comment by benjjneb** [comment]
Well, I have some bad news, you are going to have to re-run it, unless the session is saved somewhere. 

What I would recommend is doing a much faster test-run to see if we can isolate the error (also consider upgrading to the latest version 1.3.4 if its not too much trouble):

```
samples.test <- sample.names[1:3]
dds <- vector("list", length(samples.test))
names(dds) <- samples.test
for(sam in samples.test) {
  cat("Processing:", sam, "\n")
  derep <- derepFastq(filts[[sam]])
  dds[[sam]] <- dada(derep, err=errBalancedF, multithread=TRUE)
}
rm(derep)
seqtab.all <- makeSequenceTable(dds)
```

Can you run that (will take a small fraction of the time for your whole dataset) and see if the error arises again?

**Comment by mghanbari** [comment]
I've saved the session before running r`m(derep)` part. As you suggested I ran the test-run. After each sample I got this 

> The supplied error matrix does not extend to maximum observed Quality Scores in derep (41).
>   Extending error rates by repeating the last column of the Error Matrix (column 41).
>   In selfConsist mode this should converge to the proper error rates, otherwise this may not be what you want.

and after running `seqtab.all <- makeSequenceTable(dds)` I got the following (same) error
```
Error in FUN(X[[i]], ...) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.
```

**Comment by benjjneb** [comment]
That's useful, its happening even with the small test data.
Can you try the following commands:

```
class(dds)
sapply(dds, class)
```

**Comment by mghanbari** [comment]
Here is the output.

> class(dds)
[1] "list"
> sapply(dds, class)
Cntr1Col Cntr1Col Cntr1Col 
  "dada"   "NULL"   "NULL"

**Comment by benjjneb** [comment]
Hm... how about these commands?

```
head(sample.names)
head(names(filts))
```

**Comment by mghanbari** [comment]
Here it is

> head(sample.names)
[1] "Cntr1Col" "Cntr1Col" "Cntr1Col" "Cntr1Fec" "Cntr2Cae" "Cntr2Col"
> head(names(filts))
[1] "Cntr1Col" "Cntr1Col" "Cntr1Col" "Cntr1Fec" "Cntr2Cae" "Cntr2Col"
>

**Comment by benjjneb** [comment]
Ah, we've found the problem -- duplicated sample names.

For the processing loop in the code to work correctly, all the `sample.names` have to be distinct from one another, otherwise every duplicate just gets assigned to the first instance of that name in the list, and overwrites the others. Hence all the `NULL` entries, which are breaking `mergeSequenceTables`.

The best thing to do here would be to ensure all samples have a unique name and then re-run.

**Comment by mghanbari** [comment]
Thanks. I'll give a try and keep you informed.

**Comment by mghanbari** [comment]
Yes. That worked. Thank you for the support.

**Comment by cpavloud** [comment]
I get the same error when I try to run the same command
seqtab.all <- makeSequenceTable(dds)

Error in FUN(X[[i]], ...) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

I checked also the 
head(sample.names)
and the head(names(filts)
<img width="398" alt="screen shot 2018-10-29 at 16 28 21" src="https://user-images.githubusercontent.com/32954293/47656636-1cd47e00-db98-11e8-9efa-dadc00198daf.png">
It seems that there duplicated sample names, although I am not sure why this happened. 

I tried to install the newest version of dada2, in order to overcome the issue, using the command
devtools::install_github("benjjneb/dada2"
but it also doesn't seem to work


<img width="1440" alt="screen shot 2018-10-29 at 16 27 35" src="https://user-images.githubusercontent.com/32954293/47656577-04646380-db98-11e8-93a1-56cd12187833.png">

**Comment by cpavloud** [comment]
Also, in case it is useful, I am posting another screenshot
<img width="617" alt="screen shot 2018-10-29 at 16 37 34" src="https://user-images.githubusercontent.com/32954293/47657200-46da7000-db99-11e8-9c40-deec1d9f91be.png">

**Comment by benjjneb** [comment]
@cpavloud Previously in this thread, the same issue arose due to duplicated sample names, which it appears you also have in your data. Looking at your screenshot, it further suggests that this is the issue, as the duplicately named entires in your `dds` objects are `NULL`, leading to the error.

If you fix the duplicate sample name issue upstream, this problem should go away. Remember, the parsing of sample names in the tutorial may have to be modified slightly if your file name formats are different. Further, you should not use sample names with underscores in them.

**Comment by cpavloud** [comment]
But originally, my files don't have duplicate names. 
I am trying to follow this workflow https://benjjneb.github.io/dada2/bigdata.html
so I am guessing that at some point during the workflow this duplication arises....

Ok, the sample.names contains duplicates because there are R1 and R2 files (from the same sample) in the sample folder. 

![problem](https://user-images.githubusercontent.com/32954293/47965459-56056600-e050-11e8-9959-40825ce49d35.PNG)

So, I have tried these solutions to solve the problem, and they seem to work, i.e. the command
seqtab.all <- makeSequenceTable(dds) does not produce an error anymore

Solution 1:
![solution1](https://user-images.githubusercontent.com/32954293/47965465-69b0cc80-e050-11e8-9d85-df95eaf1f6bc.PNG)
![solution1 continue](https://user-images.githubusercontent.com/32954293/47965475-851bd780-e050-11e8-856d-33171b77fa04.PNG)

Solution 2:
![solution2](https://user-images.githubusercontent.com/32954293/47965482-95cc4d80-e050-11e8-8229-2de21561a0c4.PNG)
![solution2 continue](https://user-images.githubusercontent.com/32954293/47965602-e55f4900-e051-11e8-8ffb-88e2e4e10007.PNG)

Solution 3:
![solution 3](https://user-images.githubusercontent.com/32954293/47966025-7b956e00-e056-11e8-96f0-eeebb5210221.PNG)
![solution 3 continue](https://user-images.githubusercontent.com/32954293/47966026-7f28f500-e056-11e8-971b-4c9b49dd300b.PNG)

All the solutions seem to work until the taxonomy step where I get the error
Error in C_assign_taxonomy(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  Sequences must be at least 50 nts to classify.
Maybe this should be moved to another thread?

**Comment by benjjneb** [comment]
Of those solutions, definitely solution 2, as that is the only one that is really appropriately treating your issue. But are you intending to ignore the reverse read files? You just want to process the forward reads? That's a valid approach, but that is what you are doing here. The "Big Data" workflow is for single-end reads, but there is a link to a paired-end version as well under the "Starting point" heading.

> Error in C_assign_taxonomy(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int, :
> Sequences must be at least 50 nts to classify.

You have some very short sequences in your final table. You could remove them by imposing a length filter on the table, see the "considerations for your own data" section here: https://benjjneb.github.io/dada2/tutorial.html#construct-sequence-table

**Comment by cpavloud** [comment]
Thank you!
It was my mistake, I accidentally followed the tutorial for the single end reads.
