### ISSUE TITLE
No singletons left in dataset after processing with dada2.

### ISSUE THREAD

**Issue by lfaller** [benjjneb/dada2#214]
Hi all,

I processed my data with dada2 and am now exploring it further in `phyloseq`.

I ran into the following warning message when trying to plot richness:

```
The data you have provided does not have
any singletons. This is highly suspicious. Results of richness
estimates (for example) are probably unreliable, or wrong, if you have already
trimmed low-abundance taxa from the data.

We recommended that you find the un-trimmed data and retry.
```

I actually did not do any trimming to my data, just followed the dada2 tutorial for processing (described here: http://benjjneb.github.io/dada2/tutorial.html).

Did all the singletons somehow get merged? Please let me know if you have any thoughts!

Thank you,
~Lina

**Comment by benjjneb** [comment]
DADA2 does not call singletons, due to the difficulty of differentiating rare singleton errors from real singleton variants.

This means you should not use the output of DADA2 to estimate richness (eg. Chao S1). However, you shouldn't have been doing that with the output of other methods either, as the high levels of FP singletons made richness estimates wrong anyway. Right now, I don't think a method exists that can make valid richness estimates from high-throughput amplicon data due to the difficulty of calling singletons accurately, and the sensitivity of richness estimation to the number of singletons.

Other measures of diversity that aren't totally reliant on singletons, eg. Shannon/Simpson, are valid to use, and you can ignore the warning in phyloseq when calculating those measures.
