### ISSUE TITLE
"Twin OTU" artifact

### ISSUE THREAD

**Issue by kkapuria3** [benjjneb/dada2#216]
I am running dada2 with 'tableMethod=consensus' while removing chimeras. But there seems to be some problem with my final result.

![image](https://cloud.githubusercontent.com/assets/25559534/24304566/296633f4-1090-11e7-979f-2f22e1ee82d2.png)

If you look at those sequence pairs they aren't identical.  They all seem to have a single difference.  In every case I tried to look at, one sequence has a "C" at position 9 while the other has an "A".  

I am unsure what part of the code is causing this error. I had also mentioned earlier that most of my reads were getting deleted in removeBimeraDenovo, where you suggested me to use "tableMethod=consensus".

Can you please guide me what is going wrong ?

**Comment by benjjneb** [comment]
You've found an unremoved primer (515F I believe). The primer has an ambiguous nucleotide at the highlighted position, which can be either an A or a C, which causes exactly this "twinning" effect - there is one sequence variant for the A primer and one for the C primer.

You must remove primers before going through the dada2 method. Otherwise you get this twinning, and lose most of the reads in chimera removal.

**Comment by kkapuria3** [comment]
Doing my analysis again.
