### ISSUE TITLE
error with assignTaxonomy

### ISSUE THREAD

**Issue by henkbolhuis** [benjjneb/dada2#223]
Dear Ben,

Thanks for the great program 
I just got stuck however at the assignTaxonomy level which gives me the following error message in R-studio

> taxa <- assignTaxonomy(seqtab.nochim, "rdp_train_set_14.fa.gz")
Error: Input/Output
  no input files found
  dirPath: rdp_train_set_14.fa.gz
  pattern: character(0)

i have generated seqtab.nochim, giving me a 1,6 mb file 
I do have loads of bimeras (very bad run V3-V4 bacterial 16S)  but still shoud have about 3000 good ones
reads are in proper orientation 
train set is in the proper folder .... 
check check double check

any suggestions ?

**Comment by benjjneb** [comment]
I would try giving the absolute path to the fasta file, and see if that solves the issue. Eg.

"/path/from/root/to/rdp_train_set_14.fa.gz"

**Comment by henkbolhuis** [comment]
that did the trick...... i tried this before but included the "C:/" 
without it worked fine... 
thanks a lot

**Comment by IrshadUlHaq1** [comment]
Hi Ben,

I am struggling with the following error for a while:

### > taxa <- assignTaxonomy(seqtab.nochim, "silva_nr_v128_train_set.fa.gz", multithread=TRUE)
Error: Input/Output
  no input files found
  dirPath: silva_nr_v128_train_set.fa.gz
  pattern: character(0)
### > unname(head(taxa))
Error in head(taxa) : object 'taxa' not found

Do you know how to circumvent this?

Also, I got a large number of bimeras: 

> seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
Identified 1447 bimeras out of 10002 input sequences.
> dim(seqtab.nochim)
[1]  111 8555
> sum(seqtab.nochim)/sum(seqtab)
[1] 0.9825717


What might be the reason? and does that compromise the analyses?

Best
Irshad

**Comment by benjjneb** [comment]
@IrshadUlHaq1 

You probably need to give the full, or "absolute", path to the training fasta. Also, did you download that file first? Those training fastas have to be downloaded separately, they don't come with the package because of their size: https://benjjneb.github.io/dada2/training.html

And that is a fairly low number of chimeras actually: <2% of the reads were found to be chimeric. Indicates a good wet lab protocol!

**Comment by IrshadUlHaq1** [comment]
Now I get this error:

> taxa <- assignTaxonomy(seqtab.nochim, ~"/Users/irshadulhaq/Desktop/Databases/Fastq", multithread=TRUE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘readFasta’ for signature ‘"formula"’

**Comment by benjjneb** [comment]
You need to move the tilde inside the quotes.

**Comment by IrshadUlHaq1** [comment]
I think there is something wrong with the fasta file in the database. I probably need someone in my group to look at it. Should I send you my database (termites and cockroaches) file?

> taxa <- assignTaxonomy(seqtab.nochim, "~/Desktop/Databases/Fastq/filtered/DictDb_v3_fasta_tax.tar.gz", multithread=TRUE)
Error in .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  : 
  reading FASTA file /Users/irshadulhaq/Desktop/Databases/Fastq/filtered/DictDb_v3_fasta_tax.tar.gz: ">" expected at beginning of line 1

**Comment by benjjneb** [comment]
Is that file formatted to be used with `assignTaxonomy`? There is a specific format expected for the id lines: https://benjjneb.github.io/dada2/training.html#formatting-custom-databases

I think you might need to look further into the documentation for some of these functions. You can pull up detailed help on each function with e.g. `?assignTaxonomy` or `help("assignTaxonomy")`

**Comment by IrshadUlHaq1** [comment]
Hi Ben,

Whats your thoughts on this? Is it compromising my analyses and subsequent conclusions?
Many thanks!

> taxa <- assignTaxonomy(seqtab.nochim, "~/Desktop/data/filtered/DictDb_3_taxonomy_header.fasta", multithread=TRUE)
Warning message:
In .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  :
  reading FASTA file /Users/ztq148/Desktop/data/filtered/DictDb_3_taxonomy_header.fasta: ignored 15615245 invalid one-letter sequence codes

**Comment by benjjneb** [comment]
@IrshadUlHaq1

It indicates that you have non-ACGT characters in your custom taxonomy files. Is that file appropriately formatted? It's possible this could interfere with your results if the non-ACGT characters are needed to represent important taxa.

**Comment by Mdrexel2018** [comment]
Hello,
I am quite new to programming so bear with me. I am using the dada2 pipeline tutorial 1.8 and it's working great so far. I ran into a similar problem as the person before me but those solutions have not been working for me. I am not sure if it is because I am using a PC with windows 10. I had gotten an error saying that seqtab.nochim could not be found and that was solved by putting the '_' around it. Once I did that I ran the following command and I got this error: 

taxa <- assignTaxonomy('seqtab.nochim', "Users/x x/Desktop/Drexel 2018/Step1_FASTQ/Reference_Databases/silva_nr_v123_train_set.fa.gz")

         Error: Input/Output
 	 no input files found
	 dirPath: Users/x x/Desktop/Drexel 2018/Step1_FASTQ/Reference_Databases/silva_nr_v123_train_set.fa.gz
	Pattern: character(0)

I tried all of the previous solutions but they're not working. Do you have any suggestions?

thank you!

**Comment by sewuneta** [comment]
I run the following command using DECIPHER to assign taxonomy,
taxid <- t(sapply(ids, function(x) {
  m <- match(ranks, x$rank)
  taxa <- x$taxon[m]
  taxa[startsWith(taxa, "unclassified_")] <- NA
  taxa
}))
colnames(taxid) <- ranks; rownames(taxid) <- getSequences(seqtab.nochim)
 taxa.print <- taxa
 However, I'm getting this message at last
Error: object 'taxa' not found
Pls could you guide me through to resolve it

**Comment by termithorbor** [comment]
I also have the "ignored 2 invalid one-letter sequence codes" error when using the latest Unite fungal fasta database, but this is a problem with the database and not with the program, right? So it is just saying that it ignored 2 entries in the database because there were letters in it which are not ATGC or?

**Comment by wangz14** [comment]
Hi Ben, 

I was trying to assign taxa against the MIDAS database using the code: 
taxa_midas_genus <- assignTaxonomy(seqtab.nochim, "C:/Users/zzw18/R/RGeneticAnal/CleanData/MiDAS.fa",
                                     taxLevels = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus"),
                                     verbose = TRUE,
                                     tryRC = TRUE,
                                     minBoot = 80) %>%

    as_tibble(rownames = "sequence")

I keep getting the error: 
Error in if ((is.null(names) || any(bad_names <- duplicated(names) | names ==  : 
  missing value where TRUE/FALSE needed

Any ideas on how to solve this?

**Comment by benjjneb** [comment]
Is this error happening from `assignTaxonomy` or from the `as_tibble` call?

**Comment by zzw21** [comment]
I believe the as_tibble calll as I've tried adding an if else statement after the as_tibble, but it always stops after the as_tibble line.

**Comment by benjjneb** [comment]
You may have to look for help with the tidyseq folks then. We just develop the `dada2` functions.

Maybe this link is useful: https://tibble.tidyverse.org/reference/as_tibble.html
