### ISSUE TITLE
Determining filtering parameters

### ISSUE THREAD

**Issue by durrantmm** [benjjneb/dada2#232]
I’m interested in implementing the DADA2 pipeline with a dataset of ~326 16S samples. The data is 2x300 MiSeq data, with about 70 bases of overlap. For filtering, I've chosen truncLen=c(290,275). My reverse strands have quite poor quality:

![image](https://cloud.githubusercontent.com/assets/10098419/25249764/f5d25674-25c7-11e7-99ad-db03fe940922.png)

I seem to lose a lot of the data if I use the truncQ=11 cutoff, but it is probably too lenient to use truncQ=2. Can someone recommend a more systematic way to determine the ideal filtering parameters for a dataset like this? 

Thank you,

Matt D

**Comment by benjjneb** [comment]
Hi Matt,
Because you have very little overlap, you have relatively little wiggle room in how you trim your data, and will have to relax the quality filtering parameters. That's OK though, while higher quality data is better, dada2 handles lower quality data quite well because it incorporates the quality scores into its error model.

For your data with 70 nts of overlap, I would recommend trimming off no more than 35 bases, to keep a good overlap region. So I would go with `truncLen=c(295, 270)` or something close to that.

What I'd do then is find a set of quality filtering parameters that works on a small set of test data (maybe 5 samples). Be ready to relax the quality filtering on the reverse reads. For example, I might try `maxEE=c(2,6)`. I'd run my 5 samples through the whole pipeline (including merging) and then see what fraction of my reads come out the other end. If its too low, I'd try a different set of parameters.

On `truncQ` specifically, I would just leave it at its default of `truncQ=2` and let the `maxEE` parameter be the primary quality filter. We've found expected errors to generally be the best quality filtering method (see also Flyvberg and Edgar 2014 on that).

Hope that helps but let us know if any further questions.

**Comment by durrantmm** [comment]
Great, thanks for the response. Is there an absolute number of sequences I should be aiming for, or is it some proportion of the total sequences in the original fastq?

**Comment by benjjneb** [comment]
There are no hard cutoffs, but I would pay attention to both.

In general I would want to have at least thousands of sequences per-sample, to have good resolution down to 1% frequency.

In general I would want to keep a good proportion of my reads (i.e. >>10%) all the way through the pipeline. When the proportion of kept reads gets very low, issues with bias against some types that might be more prone to falling afoul of the filter become more prominent.

**Comment by benjjneb** [comment]
Please reopen if you have additional questions.
