### ISSUE TITLE
dada2 - maxee

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#248]
Hi Benjamin, Others

I have gone through quite a number of threads discussing the possible values for expected errors. Is there a threshold, beyond which the dada2 algorithm breaks down? For instance, does it still do well with maxee thresholds of 10-12?

Regards,
Aditya

**Comment by benjjneb** [comment]
The biggest benefit of a `maxEE` filter is it reduces computation time, by removing a lot of reads with unique sequences because of their many errors. This is usually worthwhile, because reads with errors don't improve the inference of what is really there. Additionally, in some unusual cases there are pathological artefacts that show up in very low quality reads which are best to get rid of (eg. non-target sequences).

However, because the algorithm is modeling errors, it is quite robust to lower quality sequences ([for example](https://twitter.com/bejcal/status/771010634074820608)). I've never seen it "break down", so if you need to raise the `maxEE` cutoff to get more reads through, you can do so.

**Comment by adityabandla** [comment]
Hi Benjamin

Thanks for the reply! I agree with your point that the `maxEE` removes a lot of uninformative reads. 

In this case, would you suggest an approach that UNOISE2 currently takes? Robert, in his pipeline suggests a stringent filtering using `maxEE=1`, and then mapping back all the length-trimmed reads (which includes the reads which didn't make it through the expected errors filter) back to the denoised sequence variants

Best,

**Comment by benjjneb** [comment]
The more stringent filtering approach is appropriate for UNOISE2, as that algorithm doesn't account for sequence quality in its error model.

Since DADA2 does incorporate sequence quality it isn't bothered much by lower quality sequences, and simply relaxing the `maxEE` filter is the recommended way to expand the number of output reads (if data is low-enough quality to need that).

**Comment by adityabandla** [comment]
Thanks Benjamin! I am giving it a try with `maxEE=8`. I'm trying to see if I can salvage the reverse reads from one of our Miseq 300bp paired-end runs, as the quality is quite bad towards the ends as usual.
