### ISSUE TITLE
Function to Automate Quality "Elbow" Analysis to Define Optimal Length Trim

### ISSUE THREAD

**Issue by joey711** [benjjneb/dada2#25]
One issue I've run into for scaling this up for lots of different datasets is knowing where to trim, for both read directions.

Any thoughts or prototype for defining the "elbow", after which the sequence should be thrown away?

**Comment by joey711** [comment]
I think we can close this for now. I have some heuristics to define trimming on either end that are probably good enough (along with some diagnostic plots). 

As I think Ben as alluding, there are other problems to consider for trimming aside from the quality read out that can depend on subtle nuances of a particular laboratory preparation. 

Automating this parameter choice might encourage users to ignore its implications. Also a bad thing.

I'll close unless we have some aspect we'd like to revise.

**Comment by meren** [comment]
I had a similar problem at one point, and I decided to solve it by writing a little program that determines the best trimming location to keep at least a user-defined X% of the reads in the dataset:

https://github.com/meren/oligotyping/blob/master/bin/o-smart-trim

So you give an alignment file to it, and say "I want to keep at least 95% of the data, find the best position to trim while discarding less than 5% of the shortest reads".

This is definitely a step that it should not be fully automated, and the user has to take a look at their results (how many nucleotides were lost due to trimming, etc).

My 2 cents.
