### ISSUE TITLE
Different filtering thresholds for error learning and sample inference?

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#252]
Hi Benjamin

I was wondering if it would be prudent to use a stringent quality filtering for the error learning step (say maxEE=1) and then use reads with a lower quality threshold (say maxEE=5) for sample inference?

Regards,
Aditya

**Comment by benjjneb** [comment]
It will probably work fine, but why?

**Comment by adityabandla** [comment]
Hi Benjamin

My samples take quite some time to run (even though I am running only a randomly chosen subset of 9 samples), as each has close to 200k reads after `maxEE=6` filtering

Hence, I was trying to see which would be the most optimal way to reduce compute time for the error learning step

**Comment by benjjneb** [comment]
You can reduce `maxEE` somewhat on the learning step, although maybe `maxEE=2` would be better, just to make sure you have enough low quality sequence to accurately estimate those error rates, given that you are using a much higher `maxEE` for the full dataset.

I'm surprised this is taking that long though. What version of dada2 are you using, and what hardware are you using? If you have access to any kind of multi-threaded compute node, the `multithread=TRUE` argument will speed things substantially.

Also, if there is a very low quality tail of your forward reads, you may be better off truncating the reads a bit rather than making `maxEE` very large, both in terms of computation time and in sensitivity to rare variants. Something to consider depending on your quality profile.

**Comment by adityabandla** [comment]
Hi Benjamin

I was thinking along the same lines with respect to maxEE, so that enough low quality reads are taken into account while modelling the errors

I am using v1.5. I am actually running it on a HPC node (24 cores). However, going by the compute times, DADA2 seems to be using only cores = number of samples, and not the full set available (with `multithread=TRUE`

I have trimmed my reads to 200bp, to get rid of the erroneous tails
