### ISSUE TITLE
filterAndTrim - Error in `colnames<-`(`*tmp*`, value = basename(fwd))

### ISSUE THREAD

**Issue by bioinfonm** [benjjneb/dada2#263]
Morning all,

  I am a new dada2 users. I am on OSX 10.11.6 with XCode install. Both R and R studio are installed.

I am working my way through the tutorial with my own data this time. I keep running into this error:
`
out <- filterAndTrim(fn, filt, truncLen=c(240,160),
maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
compress=TRUE, multithread=TRUE)

Creating output directory:/Users/ara/Desktop/tor_cry//filtered
Error in `colnames<-`(`*tmp*`, value = basename(fwd)) : 
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code
`

And here are my inputs:
`> fn
[1] "~/Desktop/tor_cry//042116DN27F-full.fastq"       "~/Desktop/tor_cry//072216DN27F2-full.fastq"     
[3] "~/Desktop/tor_cry//082815DN3bacteria-full.fastq"`

`> filt
[1] "~/Desktop/tor_cry//filtered/042116DN27F_filt.fastq.gz"      
[2] "~/Desktop/tor_cry//filtered/072216DN27F2_filt.fastq.gz"     
[3] "~/Desktop/tor_cry//filtered/082815DN3bacteria_filt.fastq.gz"`

If anyone has any insight into this. I guessing it might be a file path issue but I am not sure.

ara

**Comment by joey711** [comment]
I've also recently debugged this same error message. It turned out that I was using an old version of R and Bioconductor. Specifically the ShortRead package needs to be the latest version.

Make sure you are using R version 3.4 (codename: "you stupid darkness"), and then the release of Bioconductor that corresponds to that R release.

Please come back here and close this issue if it solves the problem. If not, then please post the new error message, and more details about your system.

**Comment by bioinfonm** [comment]
Partial solved this. I'll open up a new thread.

**Comment by joey711** [comment]
Great.

@benjjneb you probably want to update the minimum required version of ShortRead as a formal communication to avoid this error in general. I don't understand exactly why it is happening, but I did debug it all the way to a specific function in the previous version of ShortRead. In the latest version, this error does not appear, all other things being equal.

**Comment by benjjneb** [comment]
> @benjjneb you probably want to update the minimum required version of ShortRead as a formal communication to avoid this error in general.

Yes, I've been lax on the enforced requirements, relying on a standard Bioconductor install. Should bring them all up to date...

**Comment by RachelRodgers** [comment]
Hello - I came upon this thread because I was getting the same error here:

```Error in `colnames<-`(`*tmp*`, value = basename(fwd)) : 
  attempt to set 'colnames' on an object with less than two dimensions```

When running the filterAndTrim() function.

This problem occurred because I didn't have write permissions to the directory where I wanted to send the trimmed files.  I wanted to leave this comment here in case it helps someone else encountering the same error, since I didn't find it obvious :)

**Comment by adriaaula** [comment]
Hello there, 

My two cents: i was sending a job through Rscript defining args. By mistake i defined some values for the filterAndTrim() function as strings and this outputted the same error.
