### ISSUE TITLE
Attempt to set colnames on an object with less than two dimensions

### ISSUE THREAD

**Issue by akknight** [benjjneb/dada2#268]
Hi, 

I tried to run dada2 on a small subset of my files using the code below. I've gotten dada2 to run successfully before, so I'm not sure what the issue is. The fastq files have been filtered to contain only sequences that have the primers. I didn't use the primer filter step of trimandFilter since there are 18 possible primers. 

> filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
+               rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs),
+               truncLen=c(250,250), trimLeft = c(10,0),  maxEE=2, truncQ=11, maxN=0, rm.phix=TRUE,
+               compress=TRUE,  matchIDs = TRUE,verbose=TRUE, multithread=TRUE)
Creating output directory:./FW/filteredR1
Creating output directory:./RV/filteredR1
Error in `colnames<-`(`*tmp*`, value = c("FilteredEIGC9_300_S24_L001_R1_001.fastq.gz",  : 
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code

I also tried to just run fastq paired filtered as below, but hit a stack limit. I'm running this on a fairly large amazon instance, so RAM should not be a problem:

fastqPairedFilter(c("Filtered_062017/FW/FilteredEIGC9_300_S24_L001_R1_001.fastq.gz", "Filtered_062017/RV/FilteredEIGC9_300_S24_L001_R2_001.fastq.gz"), c("forwardMatch.fastq", "reverseMatch.fastq"),matchIDs=TRUE)
Error: C stack usage  7969844 is too close to the limit

Best,

Anna

**Comment by joey711** [comment]
Hi Anna,
This sounds like the same ShortRead version issue that we just answered. Please update to the latest version of R and Bioconductor.

**Comment by joey711** [comment]
See 

https://github.com/benjjneb/dada2/issues/263

**Comment by akknight** [comment]
I am running the latest versions of both:

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dada2_1.5.2  Rcpp_0.12.11

loaded via a namespace (and not attached):
 [1] compiler_3.4.0             RColorBrewer_1.1-2        
 [3] GenomeInfoDb_1.12.2        plyr_1.8.4                
 [5] XVector_0.16.0             bitops_1.0-6              
 [7] tools_3.4.0                zlibbioc_1.22.0           
 [9] tibble_1.3.3               gtable_0.2.0              
[11] lattice_0.20-33            rlang_0.1.1               
[13] Matrix_1.2-3               DelayedArray_0.2.7        
[15] parallel_3.4.0             GenomeInfoDbData_0.99.0   
[17] hwriter_1.3.2              stringr_1.2.0             
[19] Biostrings_2.44.1          S4Vectors_0.14.3          
[21] IRanges_2.10.2             stats4_3.4.0              
[23] grid_3.4.0                 Biobase_2.36.2            
[25] data.table_1.10.4          BiocParallel_1.10.1       
[27] latticeExtra_0.6-28        magrittr_1.5              
[29] ggplot2_2.2.1              reshape2_1.4.2            
[31] scales_0.4.1               Rsamtools_1.28.0          
[33] matrixStats_0.52.2         BiocGenerics_0.22.0       
[35] GenomicRanges_1.28.3       GenomicAlignments_1.12.1  
[37] ShortRead_1.34.0           SummarizedExperiment_1.6.3
[39] colorspace_1.3-2           stringi_1.1.5             
[41] RCurl_1.95-4.8             RcppParallel_4.3.20       
[43] lazyeval_0.2.0             munsell_0.4.3

**Comment by akknight** [comment]
Also, do you know why I'm hitting a stack limit?

**Comment by joey711** [comment]
The system you're describing is very similar to what I use, and I encountered the same column names / stack limit error. When I eventually diagnosed the bug, it was because I had a new version of DADA2, but an old version of ShortRead. AFAIK, only the latest version of ShortRead has resolved this stack limit bug. 

The version above, 1.34, is the latest
http://bioconductor.org/packages/release/bioc/html/ShortRead.html

It's possible that there's a low stack limit available to your R session for some reason, but if you google around, most of the time these errors turn out to be a logic error that simply manifested as a memory fault. 

include `packageVersion("ShortRead")` in the script that previously generated this error, just to be sure.

You can also tune the parameter in `filterAndTrim` the governs the number of reads that are processed at one time. Lowering this can slow things down slightly, but still keep the peak memory burden low.

Try these things and then get back to us. Make sure to start from a fresh R session.

**Comment by joey711** [comment]
@akknight any news?

**Comment by joey711** [comment]
I came across another instance of this error with `filterAndTrim`. It occurred when one or more of the file names I provided to the `fwd` or `rev` parameters are not valid (`file.exists()` returns `FALSE`), either because the file doesn't exist anywhere, or the path is under-specified. This is an easy mistake to make if your current directory (`getwd()`) is not what you expected, making your relative file path wrong; or if the file just turns out to be missing.

@benjjneb it probably makes sense to through the following at the beginning of `filterAndTrim`:

```r
stopifnot( all( file.exists(fwd) ) )
# If rev is not NULL...
stopifnot( all( file.exists(rev) ) )
```

**Comment by akknight** [comment]
Installing the latest ShortRead version didn't fix the issue, and the paths are correct. I've given up on fixing this error and am taking a different approach. Thanks for your help!

**Comment by joey711** [comment]
@akknight for the sake of other users and our own debugging, do you care to elaborate on what "taking a different approach" means?

Thanks!

**Comment by joey711** [comment]
I'm re-opening until @benjjneb responds on the file path testing...

**Comment by akknight** [comment]
I've gone back to using the Qiime2 implementation, the files I provided to dada2 seem to work fine in that environment.

**Comment by joey711** [comment]
Nice to know. Thanks.

@benjjneb is the QIIME2 implementation updated? Anything @akknight should know about that relative to the current release?

**Comment by benjjneb** [comment]
Adding the `file.exists` check sounds reasonable.

No important info on the Q2 implementation, it is on the current version of the package, but `fastqPairedFilter` instead of `filterAndTrim` which is maybe why its avoiding this.

**Comment by benjjneb** [comment]
Checking for the existence of input files in `filterAndTrim` added: 3df52082067c33289001ffd2584c3df377265e64
