### ISSUE TITLE
mergePairs & justConcatenate

### ISSUE THREAD

**Issue by cresil** [benjjneb/dada2#279]
Hi,

Is it possible to both merge pairs and concatenate those which do not overlap?

The reason for the request is Im dealing with ITS data which of course consists of variable amplicon size. Therefore some of the sequences meet the minimal overlap criteria and merge while others do not and I lose them in the process.
JustConcatenate option just concatenates everything even though there is a potential merge.

I think a combination of both would get the best results for further use in multiple alignments and phylogeny analysis.

Cheers

M

**Comment by benjjneb** [comment]
Yes and no. You can get the result you are asking for with some R code and the `returnRejects` flag:

```
merger <- mergePairs(ddF, drpF, ddR, drpR, returnRejects=TRUE)
concat <- mergePairs(ddF, drpF, ddR, drpR, justConcatenate=TRUE)
merger[!merger$accept,] <- concat[!merger$accept,]
```

The issue is that some of the pairs that failed to merge are because of mismatches in the true overlap region, rather than non-overlap, thus those should not be replaced by concatenated versions of the sequences.

We don't have an automated issue for that, but its certainly something you could devise a solution for, probably based on the output in the merger `data.frame`, in particular the `$nmatch`, `$nmismatch` and `$nindel` columns.
