### ISSUE TITLE
Downstream analysis: filtering rare SVs

### ISSUE THREAD

**Issue by StollML** [benjjneb/dada2#286]
Hi:

I submitted a manuscript in which 16S analysis was performed exclusively with DADA2. I used the output to generate a table with the same format of an OTU table and inputted this into QIIME for subsequent analyses. A reviewer suggested that I filter out rare "OTUs." My impression is that this seems to make sense if QIIME were used for clustering, as QIIME does not have a mechanism to tease out sequence errors from true sequences. However, with DADA2, there does not appear to be any rationale for filtering out rare SVs. What are your thoughts on this? Thanks in advance --

Matt

**Comment by benjjneb** [comment]
There is not one answer to this question.

There is much less need to filter rare OTUs if using DADA2 than using some other methods, like the common QIME1/uclust workflow, that would generate large numbers of spurious rare OTUs. But there are processes which introduce spurious rare sequences which DADA2 does not fix -- in particular contaminants - so in some cases it may be useful to filter rare variants as a way of removing potential contaminants. Additionally, a preliminary "independent filtering" step that removes rare and low-prevalence variants can increase the power of subsequent statistical testing by reducing the number of multiple hypotheses.

However, there is legitimate biological signal among rare variants which may be of interest. The impact of bacteria is not directly proportional to their numeric abundance, and the readout of amplicon sequencing is directly proportional to the numeric abundance either (primer bias, multi-copy operons and so forth...), so variants that are rare in amplicon data could still be important biologically. If that's the case in your system, it may be best to keep them.

So I would say there is a balance to be struck depending on the analyses and biological questions you are asking. I don't know what is appropriate for your study because I don't know what you did. I do not think that filtering "rare OTUs" is a blanket prescription that should be followed though.

**Comment by StollML** [comment]
Thank you very much for your input; this makes perfect sense.

Regards,

Matt

**Comment by janetw** [comment]
We have also been wondering about when and how much to filter rare SVs. Would it also be prudent to keep the SVs especially if we plan to agglomerate at particular taxonomic levels? Because several SVs may actually combine together at a taxonomic level and comprise many of the reads for a particular taxa? For example, there might be hundreds of rare SVs that when agglomerated at the genus level, all get put into the same genus? Does that make sense?

**Comment by benjjneb** [comment]
> Would it also be prudent to keep the SVs especially if we plan to agglomerate at particular taxonomic levels?

If your primary analysis is at that agglomerated higher level, I would perform any filtering of rare variants after agglomerating to that level. For the reasons you point out, and because it is best as a rule to perform the steps of multi-stage analyses (eg. abundance filtering, testing, etc) at the same level of organization if possible.

**Comment by janetw** [comment]
Thank you!!

**Comment by joey711** [comment]
@StollML 
Matt, out of curiosity, what were you doing in QIIME? Especially, what were you doing that phyloseq (or other analyses in R) does not do?

**Comment by StollML** [comment]
Hi Paul,



Probably nothing that couldn't be done in PhyloSeq -- I've just never used it. I ran alpha and beta diversity analyses in QIIME, also like that QIIME breaks down the taxa output into the different levels (L2 = phyla, etc). I gather from your question that there are substantial advantages to using PhyloSeq?



Regards,



Matt



________________________________
