### ISSUE TITLE
Does the dereplication happen twice in the pipeline

### ISSUE THREAD

**Issue by ZeweiSong** [benjjneb/dada2#290]
According to the output of learnErrors:

    ## Initializing error rates to maximum possible estimate.
    ## Sample 1 - 7113 reads in 1979 unique sequences.
    ## Sample 2 - 5299 reads in 1639 unique sequences.

Isn't we already finish the dereplication before the derepFastq command?

**Comment by benjjneb** [comment]
Yes there is a slight inefficiency there -- when the `learnErrors` command is passed filenames it has to re-run dereplication. In general that is a relatively minor part of the computational costs though.

To avoid re-dereplication, you can give `learnErrors` the list of `derep-class` objects directly instead of the filenames (and thanks to @gblanchard4 for adding that feature).

**Comment by ZeweiSong** [comment]
Thanks, this makes sense!

Another question though, do you have details on how the error rate is modeled? Since the error rate is estimated based on the data, how do yo know it is a (for example) A -> G transition introduced by amplification and sequence error instead of true variance?

Sorry this seems a dumb question ...

Zewei

**Comment by benjjneb** [comment]
The self-consistent learning of the error rates is described in the paper introducing the method: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4927377/
