### ISSUE TITLE
Merging paired reads before splitting into sample files

### ISSUE THREAD

**Issue by rlh13** [benjjneb/dada2#300]
Hello,
Is there a way to merge paired reads before splitting them into sample files? I only have barcodes on one end and the problem I am having is that I cannot assign un-barcoded sequences (our reverse reads) to individual sample files (since the barcode tells you which sample it belongs to) and it seems like all of the DADA2 objects require sequences to be separated into files by sample. This creates a problem downstream when I am trying to assess the accuracy of DADA2 on the mock community because the function uses the "mergers" object (which I skipped) and I can't figure out how to work around it. This is the code I used and the error I get:

unqs.mock <- getUniques(removeBimeraDenovo(dadaFs, verbose=TRUE))

Error in getUniques(removeBimeraDenovo(dadaFs, verbose = TRUE)) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

I tried using the seqtab.nochim object and removing the nested removeBimeraDenovo function (since this was already performed to create seqtab.nochim) and it worked but the numbers were definitely not accurate. Any help is appreciated!

**Comment by benjjneb** [comment]
It's hard to answer your problems because it seems like several separate issues have all been wrapped together.

1) The dada2 package does not do demultiplexing of barcoded samples, but there are a number of solutions out there to do that. See [our FAQ](https://benjjneb.github.io/dada2/faq.html) for some suggestions.

2) I can't tell what went wrong with the R command you posted, because you don't provide enough information about the script you ran up to that point. Are you trying to process a single sample (the mock community)?

**Comment by rlh13** [comment]
Sorry I tried to create a new code file but I apparently don't have permission. I will post it below. In this experiment, we are comparing different DNA extraction kits as well as QIIME vs. DADA2 on accuracy to a mock community. We have samples of the Mock Community that have been extracted with the different kits as well as samples of the Mock Community DNA that were subjected directly to PCR (no extraction necessary) as a control. These control samples are the ones we would like to use to evaluate the accuracy of DADA2. The sample names for these are "MockDNA1" through "MockDNA6".

source("https://bioconductor.org/biocLite.R")
library(dada2);packageVersion("dada2")
library(ShortRead);packageVersion("ShortRead")
library(ggplot2);packageVersion("ggplot2")
path <-"~/Riley/2017-03-30_Mock_Spike_In/SeqBySamp"
fns <- list.files(path)
fns
fnFs <- sort(list.files(path, pattern= "_R1.fastq"))
sample.names <- sapply(strsplit(fnFs,"_"),'[',1)
fnFs <- file.path(path, fnFs)
plotQualityProfile(fnFs[1:2])
#truncate at 190
filt_path <- file.path(path, "filtered")

filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
#previous code: for(i in seq_along(fnFs)) {
#  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
#                    truncLen=c(240,180),
#                    maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
#                    compress=TRUE, verbose=TRUE)
#}
out <- filterAndTrim(fnFs, filtFs, truncLen=c(190),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE)
#previous code: dadaFs.lrn <- dada(derepFs, err=NULL, selfConsist = TRUE, multithread=TRUE)
#errF <- dadaFs.lrn[[1]]$err_out
errF <- learnErrors(filtFs, multithread=TRUE)
#plotErrors(dadaFs.lrn[[1]], nominalQ=TRUE)
plotErrors(errF, nominalQ=TRUE)
derepFs <- derepFastq(filtFs, verbose=TRUE)
names(derepFs) <- sample.names
#Sample inference (infer sequence variants in each sample)
dadaFs <- dada(derepFs, err=errF, multithread=TRUE)
dadaFs[[1]] 
seqtab <- makeSequenceTable(dadaFs)
dim(seqtab)
table(nchar(getSequences(seqtab)))
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)
sum(seqtab.nochim)/sum(seqtab)
#Track reads through the pipeline
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), rowSums(seqtab), rowSums(seqtab.nochim))
colnames(track) <- c("input", "filtered", "denoised", "tabled", "nonchim")
rownames(track) <- sample.names
head(track)
#Assign taxonomy
taxa <- assignTaxonomy(seqtab.nochim, "gg_13_8_train_set_97.fa.gz", multithread=TRUE)
unname(head(taxa))

write.csv(seqtab.nochim, "OTU_table_no_chimeras_DADA2_mock_spike_in.csv")

#Evaluate Accuracy
unqs.mock <- getUniques(removeBimeraDenovo(dadaFs, verbose=TRUE))
message("\n", "DADA2 inferred ", length(unqs.mock), " unique sequences present in the Mock community.\n")
mockRef <- readFasta("~/Riley/BioPool_genomes/16S-18S/MockComm.fasta")
match.ref <- sum(sapply(names(unqs.mock), function(x) any(grepl(x, as.character(sread(mockRef))))))
message("Of those, ", sum(match.ref), " were exact matches to the expected reference sequences.\n")
```

**Comment by benjjneb** [comment]
As I understand it, you are running into trouble when you get to

```
unqs.mock <- getUniques(removeBimeraDenovo(dadaFs, verbose=TRUE))
```

The problem is that `getUniques` expects a single sample, and you have given it all the samples at once (`dadaFs` is a list of dada-class obejcts, one for each sample).

If you want a `unqs.MockDNA1` object, you need to specify that sample, e.g:

```
unqs.MockDNA6 <- getUniques(removeBimeraDenovo(dadaFs[["MockDNA6"]], verbose=TRUE))
```

Assuming that you've named the samples as expected.

**Comment by rlh13** [comment]
Would it be possible to run it on all of the MockDNA samples (i.e. MockDNA1-6)?

**Comment by benjjneb** [comment]
You can put a loop around the "Evaluate accuracy" code that goes through each mock sample name.

**Comment by rlh13** [comment]
I'm sorry this is probably a stupid question but what would be the most efficient way to do this? I tried this:
for(i in 1:6){
unqs.mock <- getUniques(removeBimeraDenovo(dadaFs[["MockDNAi"]], verbose=TRUE))
}
but it didn't work.

**Comment by benjjneb** [comment]
`mock.name <- paste0("MockDNA", i)` and `dadaFs[[mock.name]` should get you what you want.

**Comment by rlh13** [comment]
Ok thank you that worked! But so won't the loop overwrite the value of unqs.mock from the last iteration? Would the end result of unqs.mock then only represent the last loop (MockDNA6)?

**Comment by benjjneb** [comment]
Yes but what are you trying to do w/ unqs.mock? If you just want to print out the matches to the reference, the for loop will print the results each time through the loop (so for 1-6) as long as you include the printing line inside the loop.

**Comment by rlh13** [comment]
Ok yeah I was hoping to just get an average but this is fine! I hadn't included the printing line in the loop before so this will work. I am concerned about the discrepancy between the identified unique sequences vs. those present in the samples. The average # of identified unique sequences is 123 but the number actually present in the mock community is either 9 or 10 for all of them. Is this indicative of something I've done wrong in the code?

**Comment by benjjneb** [comment]
The most likely reason you would see such a larger number of sequences is contamination, which can come in two forms -- cross-contamination between samples or environmental contamination (often from the reagents). The DADA2 method does not remove contaminants (they are real biological sequences as far as its concerned).

There are other possibilities that can be diagnosed using auxiliary information in the `dada-class` object, but that's not been made easy to use yet, especially if you aren't comfortable in R.

But if you'd like to share one of the mock-community `dada-class` objects I'd be happy to take a quick look. Eg. `saveRDS(dadaFs[["MockDNA1"]], "path/to/dada_mock1.rds")` and share the created rds file.

**Comment by rlh13** [comment]
Hello,
Thank you for all of your help! I don't want to share the file publicly yet
so I hope it's alright that I'm emailing it to you. I do want to look
further into exactly what type of differences there are between the
reference sequences and the incorrect sequences. If you could help that
would be great!

Thank you again,
Riley

On Tue, Aug 1, 2017 at 11:41 AM, Benjamin Callahan <notifications@github.com

**Comment by benjjneb** [comment]
That's fine, you can email me at benjamin DOT j DOT callahan AT gmail DOT com

**Comment by benjjneb** [comment]
So I did a check on your data, and I think the evidence is pretty strong that the extra sequences you are finding in your mock community come from contamination, with my best guess being that it is cross-contamination from other samples on your sequences. But let me show my work:

```
dd <- readRDS("~/Desktop/gitmock/dada_mock1.rds")
cc <- removeBimeraDenovo(dd$clustering, verbose=TRUE)
tax <- assignTaxonomy(cc, "~/tax/silva_nr_v128_train_set.fa.gz")
```

This gets me the chimera-free "clustering" data.frame associated with the sample you sent me, which has the sequence, abundance and diagnostic information for each inferred sequence variant. First let's look at the abundances:

```
plot(cc$abundance, log="y")
![image](https://user-images.githubusercontent.com/5797204/28973094-371b079e-7900-11e7-86c1-96604f1ac965.png)
```

This is a log-scale plot, and we see clearly that there are 8 SVs at high abundance, one more a bit below, and then a long-tail of much lower abundance SVs. This seems to track with the 9 or 10 real strains in your mock community, plus a tail of other stuff. But what's that other stuff? Let's look at the "clustering" diagnostics:

```
ii <- 9 + sample(1:(nrow(cc)-9), 10) # Pick 10 non-high-abund samples
> cc[ii,-1]
    abundance n0 n1 nunq          pval birth_type    birth_pval    birth_fold birth_ham birth_qave
146        11  7  3    5 4.670326e-168          A  1.339165e-83  6.032726e+14         5   36.62857
24         91 51 19   44 7.283471e-242          A  0.000000e+00  5.090009e+07         3   36.50725
72          4  3  0    2  0.000000e+00          A  0.000000e+00 3.647356e+114        35   37.32381
35         72 29 18   42  0.000000e+00          A  0.000000e+00  5.943109e+43        14   36.60714
74         27  2  0   25  0.000000e+00          A  0.000000e+00 2.625412e+237        71   36.26056
125         5  3  1    3  0.000000e+00          A 2.919876e-110  1.191907e+57        17   37.60784
204         8  5  0    4 7.391093e-124          A  1.232393e-41  1.815484e+15         5   38.00000
197        18  6  5   15 4.943052e-301          A  1.069899e-44  1.903099e+16         5   37.50000
138         3  3  0    1 5.867064e-144          A  1.768520e-91  4.843057e+47        14   37.21429
137         7  4  3    4 1.572567e-226          A  3.574287e-92  1.273051e+32        11   36.02273
```

There's 3 columns I am interested in to check if it might be algorithm problems producing these errors: `$pval`, `$birth_ham` and `$birth_qave`.

`$pval` is a post-hoc p-value that the sequence variant still seems legit after the entire algorithm completes. Here we see all these p-values are highly significant (good).

`$birth_ham` is the hamming distance from this sequence variant to the more abundant sequence-variant from which it was split. We expect to see a range of valufes here, and we do (good). The indicator of a problem would have been if almost all of these values were `1`.

`birth_qave` is the average quality score at the variant positions used to discriminate this sequence variant as real. We expect to see qualities here in line with the average quality of this sequencing run, which we do (good). The indicator of a problem would have been if many of these values were very low, or if they were much lower than the `$birth_qave` of the most abundant sequence variants.

End result - our diagnostics suggest there are no issues with the core denoising algorithm here. Next, let's BLAST these sequences against previous observations:

```
dada2:::pfasta(cc$sequence[ii])
# BLAST output againt nt: https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome
```

When I flip through the output for these 10 sequences, 8/10 are exact (100% ID/100% coverage) matches to previously observed sequences. This indicates that these are real biological sequences rather than uncorrected sequencing/PCR artefacts. (note that the fraction of reads that will exactly match references will vary a lot across different environments, so 8/10 is not a magic number).

Finally, let's look at the taxonomy for these sequence variants:

```
> unname(tax[ii,])
      [,1]        [,2]             [,3]                 [,4]                 [,5]                  [,6]               
 [1,] "Bacteria"  "Bacteroidetes"  "Bacteroidia"        "Bacteroidales"      "Bacteroidaceae"      "Bacteroides"      
 [2,] "Bacteria"  "Firmicutes"     "Erysipelotrichia"   "Erysipelotrichales" "Erysipelotrichaceae" "Turicibacter"     
 [3,] "Bacteria"  "Firmicutes"     "Clostridia"         "Clostridiales"      NA                    NA                 
 [4,] "Bacteria"  "Firmicutes"     "Clostridia"         "Clostridiales"      "Lachnospiraceae"     NA                 
 [5,] "Eukaryota" NA               NA                   NA                   NA                    NA                 
 [6,] "Bacteria"  "Proteobacteria" "Betaproteobacteria" "Burkholderiales"    "Alcaligenaceae"      "Sutterella"       
 [7,] "Bacteria"  "Bacteroidetes"  "Bacteroidia"        "Bacteroidales"      "Rikenellaceae"       "Alistipes"        
 [8,] "Bacteria"  "Firmicutes"     "Clostridia"         "Clostridiales"      "Lachnospiraceae"     "Blautia"          
 [9,] "Bacteria"  "Firmicutes"     "Clostridia"         "Clostridiales"      "Lachnospiraceae"     "Coprococcus_1"    
[10,] "Bacteria"  "Firmicutes"     "Clostridia"         "Clostridiales"      "Ruminococcaceae"     "Caproiciproducens"
```

This gives me an idea of what kind of sequences I'm seeing here. This can qualitatively distinguish a bit between reagent contaminants and cross-contamination. This doesn't look to me at first glance like kit contamination, but that is an eyeball test. What would be best is to compare this to the abundant taxonomies observed in the other samples on this run, if there is a lot of overlap you are probably looking at cross-contamination.

**Comment by rlh13** [comment]
Thank you so much for all of your help! I replicated your code for the remaining samples and got very similar results. We're looking into the issue of contamination now and I'll let you know if I have any follow-up questions!

Thanks!

**Comment by saifsikdar** [comment]
@benjjneb 
I am analysing 16S metagenomic data sequenced for V3-V4 region.   I am facing problem with getUniques function.   I run the following code:

getN <- function(x) sum(getUniques(x))  
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), 
            sapply(mergers, getN), rowSums(seqtab.nochim))

But  I get following error message -- "Error in getUniques(mergers) : could not find function "getUniques" "

The installed dada2 package version is 1.8.0

Could you please let me know what I did wrong here?

**Comment by benjjneb** [comment]
That's the error you would get if the dada2 package was not loaded. Can you try loading the package again `library("dada2")` and see if that resolves the issue?

**Comment by saifsikdar** [comment]
Yes, it worked after reinstalling DADA2!  thanks a lot
This is what I got:
                      input        filtered        denoisedF          denoisedR          merged         nonchim
NC3-noFeces  6104        4709          2356                  2914                  1544             1543
NC4-elute       7227        5695          2949                  3489                  2092             2089
NTC-water       7072       5673           2741                  3269                 1766              1766
S112m1         63224      46360         46066                46197                43900           40358
S112m2         43221      30729         30595                30648                29343           27337
S112m3         60287      41507         41275                41397                39335           35656

First 3 samples are negative controls where I don't want to see any DNA.   Next 3 (S112m1 -m3) are mouse fecal samples.   Could you please suggest if I should conduct more tight filtration for these 16S (V3-V4) metagenomic data (Illumina MiSeq)?  

I used following code for filtration step:
 
filtered <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, 
                     truncLen=c(280,255), 
                     trimLeft=c(15,10),
                     maxN=0, 
                     maxEE=c(3,3), 
                     truncQ=2, 
                     rm.phix=TRUE,
                     compress=TRUE, 
                     multithread=TRUE)
head(filtered)
