### ISSUE TITLE
custom database with more than 6 taxonomic levels

### ISSUE THREAD

**Issue by nomascus** [benjjneb/dada2#302]
Hi, I'm building a custom 18s database for DADA2, and I'm hoping you can clarify a few points about the DADA2 format. 

1) Am I correct that when running assignTaxonomy each RSV in the taxonomy fasta file can only have 6 or fewer levels? And do those levels need to be Kingdom, Phylum, Class, Order,Family, Genus? I'm a bit confused, because the "Formatting custom databases" section on the website lists 6 levels, but the assignTaxonomy source code (taxonomy.R, correct?) has 7 default levels Kingdom->Species.

2) If some species are under a superfamily and a family and others are only under a family, I would need to remove all the superfamily info from the headers, right?

3) I presume that I can use multiple RSVs with the same taxonomy header, correct? That is, if I have multiple species in the same genus, would the headers be the same, just with different sequence data?

**Comment by benjjneb** [comment]
1. It can have an arbitrary number of levels actually. If your levels do not correspond to the default `taxLevels=c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")` hierarchy, provide a different hierarchy to the `assignTaxonomy` function when using that reference db.

2. The functionality doesn't work correctly for levels like super-family that are only used for some taxa, so you'll need to restrict yourself to the levels that are used across all taxa (it's ok for the lower levels to be unassigned due to uncertainty, but not some random upper level, e.g. superfamily, that just isn't used for that taxonomic group)

3. Yes.
