### ISSUE TITLE
question about learnErrors nreads

### ISSUE THREAD

**Issue by rmm257** [benjjneb/dada2#303]
Hello,

I am working with a fairly large dataset and wondering a bit about the selection of reads for error estimation. If I have fairly deep coverage within a sample,  my nreads threshold can be maxed on in 1 or 2 samples off a run.  However, in reality, if the DNA quality going into the samples was highly variable (pre-processing, PCR differences, sample storage prior to library prep, etc), the error calculation could be based off a particularly good (or bad) sample if it truncates too soon.  Is there any thought to make the reads a stratified random sample from each sample in a run, rather than the first n reads?  If not, I'd be interested to hear your thoughts on whether it could be important?

Best wishes,
Rebecca

**Comment by elsherbini** [comment]
I brought this up before, in #100.  My understanding of this issue is this:

A core assumption of the method is that error rates should be the same for all samples. The method needs to consider whole samples at once in order to infer the error rate, since it depends on seeing both abundant and rare sequences that likely arose due to sequencing error. 

One approach to deal with samples that might have variable quality would be to Do the learn error step a few times with different subsamples and plot the results using the `plotErrors()` function. If it looks like the fit is highly variable, you might need to use a lot more reads for training, or even consider another method entirely.

**Comment by rmm257** [comment]
Hi Elsherbini! Thanks for the link to the previous thread. I missed that one entirely.  Makes a lot of sense that pulling a very small number of reads from each sample would be problematic.  Sounds like I should actually extend my nreads to cover more samples and look at how the error rates change.
