### ISSUE TITLE
Some estimated error rates increase again at high quality scores

### ISSUE THREAD

**Issue by ckenkel** [benjjneb/dada2#306]
Hi Ben,

I can't find another thread with this issue, so I'm posting it here. 
I'm running version 1.3.5 (from your current release .zip file download link) and following your 1.4 tutorial. I'm only allowing 1 expected error to get convergence (allowing 2 returns an non-convergence error). But when I plot the errors I see this weird behavior for some of the transitions where the estimated error rate begins to increase again at high quality scores - are there parameters I can change to remedy this behavior?
[Consensus.pdf](https://github.com/benjjneb/dada2/files/1206350/Consensus.pdf)

**Comment by benjjneb** [comment]
You can safely ignore this behavior. This artefact exists because in many sequencing runs there are almost no Q=40 bases. This causes this weird looking behavior as the loess smoothing hits the edge and a lack of observations at the same time. However, it also makes it unimportant (there aren't (almost) any Q=40 bases anyway) and at worst the error rates are overestimated, so will be conservative for calling new variants.

**Comment by ckenkel** [comment]
That makes sense - Thanks for the super speedy response!
