### ISSUE TITLE
compress=FALSE option in filterAndTrim doesn't work

### ISSUE THREAD

**Issue by Starnite** [benjjneb/dada2#307]
Hello,

I tried running filterAndTrim with compress=FALSE, but the files in the output folder are all (uncorrupted) compressed files. Does there currently exist a functionality to directly output uncompressed files from filterAndTrim?

Thanks!

**Comment by benjjneb** [comment]
Apologies, this is a known bug that has already been fixed on the the master branch on github, but isn't fixed in the current Bioconductor release (will be fixed in the October Bioconductor release).

Right now I would recommend installing the current devel-version (`devtools::install_github("benjjneb/dada2")`) if you can compile from source, or using the older `fastqFilter` or `fastqPairedFilter` commands as those do respect `compress=FALSE`.

**Comment by Starnite** [comment]
Great, thanks!
