### ISSUE TITLE
value of p-value threshold (OMEGA_A) for divisive partitioning

### ISSUE THREAD

**Issue by igor25** [benjjneb/dada2#315]
I noticed that the default value of p-value threshold (OMEGA_A) seems really small, i.e. 1e-40. This works pretty well on the Extreme dataset, so I suppose it is justified. 

- Are we supposed to use this more like an empirical parameter?

I was hoping that it does not have be so arbitrary since it has a nice intuitive explanation: if the (Bonferroni corrected) p-value for a unique sequence is below this number, a new partition is generated.

- I was wondering if there is a way to calculate what this parameter should be (at least order of magnitude), from the data. For example, if the best possible Q score is around 40 and say we have 10^5 unique sequences, then perhaps 10^-4-5 = 10^-9 would seem reasonable? (Still far cry from 10^-40 though).

- The reason I am asking this is my other concern. Say I use OMEGA_A = 10^-40 that was shown to be a good value for Extreme data set. I now move to another 16S dataset with different errors, different unique number of denoised sequences, etc. Is the same OMEGA_A still good to use or do I need to somehow recalibrate it?

Thank you so much for all your work and answering these questions!

**Comment by benjjneb** [comment]
> Are we supposed to use this more like an empirical parameter?

Yes. It would be much more satisfying if we could take these p-values completely at face-value, but in practice we must be more conservative because there are deviations from the error model in real data. 

There are two key assumptions in the implemented error model, independence of errors between sites (after accounting for quality) and independence between reads. These largely hold, but not perfectly, and unmodeled variaition (e.g. error-rate dependence on nearby nucleotides) leads to p-values for some errors that are more extreme than appropriate, and thus can be misinterpreted.

OMEGA_A = 1e-40 is small, but we've found it to be an appropriate default in that it gives a reasonable balance between FPs and FNs over a wide range of amplicon sequencing experiments. It is as small as it is in part because FPs are more of a problem than FNs unless one really cares about variants present at 1 or 2 reads, and defaults need to be appropriate for a range of higher and lower quality sequencing experiments.

In the DADA1 paper, we described a procedure for setting OMEGA_A (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-13-283 - Fig.3) that basically boils down to histogramming the p-values, and looking for a natural break. However, I have not generally found this to be effective with Illumina-scale data because of the issue of chimeras, which tend to fill in all parts of the p-value spectrum. You can try it and see if it might work for your data though.

In practice, I have sometimes set OMEGA_A to lower values on my own datasets via an ad hoc procedure in which, basically, I lower it and then evaluate a subset of the additional variants reported by comparing them to previously observed sequences (e.g. BLAST against nt) and using that information to pick a threshold that gives a good balance of FP/FN. However, in most cases I do not bother, as I find that the very low frequency variation is too difficult to robustly interpret due to the prevalence of contamination at those low frequencies.

Hope that helps!

**Comment by igor25** [comment]
Thanks a lot for the detailed reply! I played with it a bit and did notice it was mainly affecting low abundance (or frequency) variants. I think it is nice that the model is pretty robust with respect to changes in p-value, at least with respect to variants that are not low abundance. 

I'll close this issue, but if I have any constructive suggestion to add later, I'll post it.
