### ISSUE TITLE
unusually large number of bimeras with isBimeraDenovo() (44%)

### ISSUE THREAD

**Issue by igor25** [benjjneb/dada2#319]
I have a dataset that looks like it's a really good quality, at least based on quality scores. It's the 16S sequencing run of V3/V4 region, so the reads are 250 nts each and the overlap is about 60 nts so they merge to about 440 nts. If I keep track of reads through the pipeline, everything looks good (only small % is removed on each step), until I get to chimera removal step. 

In that step, I lose almost a half of all reads (not only unique sequences but all reads) that are detected as bimeras. Similarly, if I process only forward reads I lose about 38%. This is all after trimming PCR primers and I even tried trimming a substantial amount (40nts right and left) and it didn't make much difference. 

If I use UPARSE chimera removal with RDP Gold FASTA file, only 5% are thrown out as chimeras. However, I think isBimeraDenovo algorithm is far superior (and it comes with actual documentation) and would prefer to use that one. In fact, I am now concerned about the quality of my dataset.

- I was wondering if you have any thoughts about why would it detect that many reads as bimeras? (After trimming primers of course.)

**Comment by benjjneb** [comment]
You are encountering the not entirely solved issue of identifying nearby chimeras in exact sequence variant data.

Chimeras are made at a higher rate between similar sequences. However, especially when you get to multi-V-region amplicons (like V3/V4) there are many real variants that differ by 1-3 nucleotides. Thus there is lots of variation and lots of chimeras near to other sequences. The result is a difficult classification problem, and in some circumstances at least a high FP rate of identifying close-by chimeras (which is probably waht you are seeing).

The one other person that I know that has looked at this is Robert Edgar, see the "Chimera Filtering" section in his UNOISE2 preprint: http://www.biorxiv.org/content/early/2016/10/15/081257.full.pdf+html

To briefly summarize, Robert Edgar has implemented (essentially) the same method as isBimeraDenovo, but concludes that different parameters should be used based on a FP/FN evaluation of chimeras called on sequences that were 1 or 2 nts away from another sequence. (In dada2 terms he recommends using `minFoldParentOverAbundance=2` or even higher, rather than the default of `1` in dada2).

We've also seen this same issue, but are solving the issue in a different way, as of 1.4 the default chimera removal method in dada2 is to identify chimeras across samples, then vote, and only remove those that are voted as chimeras in 90% of samples. This is instead of pooling all samples together to call chimeras, which is more prone to FPs. In admittedly limited testing thus far, this has seems to work fairly well on V3V4 amplicons, at least in studies with ~100-300 samples.

However, if the testing you are doing is on a single sample or two, the `method="consensus"` approach won't help, and you may want to look into Edgar's approach of more stringent requirements on chimeric "parents".
