### ISSUE TITLE
dada2 singletons - can we keep them?

### ISSUE THREAD

**Issue by cladva** [benjjneb/dada2#320]
dada2 discards singletons as part of the QC steps, but there must be a place where they are stored before this discard. Is it possible to retain these reads separately as an output?

**Comment by benjjneb** [comment]
dada2 does not throw away singleton *reads*. However, it does not infer biological *sequence variants* that are only supported by a single read - singletons are assumed too difficult to differentiate from errors. Hence no singletons in the output table of amplicon sequence variants.

Right now we have no option to infer sequence variants supported by singleton reads.

**Comment by cladva** [comment]
Thanks for the clarification! Would it be possible to separate out the singleton reads, as you already do, and have a separate output/dump for these that's user accessible? From a research perspective, I think there may be something useful in singletons within a sample with a different algorithm that borrows information from other samples. I'd like to be able to explore this, and use dada2 for characterizing sequence variants for the rest of the signals.

**Comment by benjjneb** [comment]
> Would it be possible to separate out the singleton reads, as you already do, and have a separate output/dump for these that's user accessible?

Right now, no, there's no way to achieve that without going back to the original fastq files.

> From a research perspective, I think there may be something useful in singletons within a sample with a different algorithm that borrows information from other samples.

Agreed. The method that is available right now is to pool samples together `dada(..., pool=TRUE)`. Inference of sequence variants is then performed on the total pool of samples, and singletons w/in samples will be called if supported by >1 read across all samples.

The downside to this is computational costs that scale quadratically with sequencing depth. Very roughly, pooled inference will be computable out to about a Miseq run, but will start to become intractable after that.

We do have plans on adding a feature that allows a set of "initial hypotheses" to be provided, i.e. sequence variants they have reason to suspect might really be there perhaps because they were inferred as present in other samples, that will allow per-sample singletons to be called even when processing samples independently. However that is unlikely to be added in this release cycle, i..e. before the end of this year.
