### ISSUE TITLE
Reads vs clusters

### ISSUE THREAD

**Issue by jazzyjakemusic** [benjjneb/dada2#321]
Hi, I'm a new user to dada2, and I'm pretty excited about the app. However I get a bit confused by the introduction in the tutorial. It says the data must meet certain criteria, and one of them is this: "If paired-end sequencing, the forward and reverse fastqs contain reads in matched order". I see the world this way: In each fastq file, the reads are the sequences of all the clusters that were identified as belonging to that sample, including the Q-scores. The reads are identified by the coordinates of each of those clusters on the flowcell. This is given in the first line of each read. I'm pretty sure I'm correct, but how can the reads be in matched order between fastq-files? The coordinates on the flowcell appear as the DNA-fragments ligate randomly in different positions. I suppose this could just be a mistake in the phrasing of the tutorial, that it's the fastq-files that contain the reads that have to be in matched order? Please enlighten me.

**Comment by jnesme** [comment]
Illumina machines output R1 and R2 fastq files in matching order. Following your logic anyway, R1 & R2 would have the same coordinates as they stem from the same cluster being imaged anyway. Hence, they would be ordered. And that's why DADA2 expects that, it is the most common machine output one can get.

**Comment by jazzyjakemusic** [comment]
Thanks a lot for your answer. It helped me understand the process better.
