### ISSUE TITLE
more than 90% of reads as bimeras

### ISSUE THREAD

**Issue by ycl6** [benjjneb/dada2#330]
Hi, I have a similar issue as #115 where majority of the reads were discarded during removeBimeraDenovo()

I am analyzing a subset of a public dataset I obtained from ENA (PRJEB5542). From the methods described in the manuscript, I know the 16S V3-V4 amplicons were generated using the 341F/806R primers and sequenced with MiSeq 2x250.

Primers were trimmed with cutadapt and data was analyzed with dada2 v1.4.0 following the 1.4 pipeline protocol, except the fastqPairedFilter() parameters were: trimLeft=10, truncLen=c(245,235), minLen=200, maxN=0, truncQ=2, maxEE=c(2,5), rm.phix=TRUE

The stdout from removeBimeraDenovo() is as follow:
```
> seqtab.nochim <- removeBimeraDenovo(seqtab, verbose=TRUE, multithread=TRUE)
As of the 1.4 release, the default method changed to consensus (from pooled).
Identified 6791 bimeras out of 7208 input sequences.

> seqtab.nochim <- removeBimeraDenovo(seqtab, method ="pooled", minFoldParentOverAbundance = 2, verbose=TRUE, multithread=TRUE)
Identified 6956 bimeras out of 7208 input sequences.
```
I attached the RDS for your reference. 
What do you think have caused the removal of so many reads? Thanks

**Comment by benjjneb** [comment]
Could you clarify what fraction of the reads are being removed? I.e. `sum(seqtab.nochim)/sum(seqtab)`

It is possible that 90% of the unique variants are chimeric, but in that case it should represent a much lower fraction of total reads (maybe 15% of total reads). The multi-v-region amplicons are more prone to chimerism due to the conserved region in the middle. However 90% of the ASVs is still higher than usual, so you are right to look in to this more closely.

ps: I don't see an attached `.rds` so I can't look at the data itself.

**Comment by ycl6** [comment]
Hi @benjjneb. It seems the RDS attachment get deleted when I edit the post. I am re-attaching it here.
[seqtab.zip](https://github.com/benjjneb/dada2/files/1305600/seqtab.zip)

Below are the stats, does this mean 87% of reads remained after removeBimeraDenovo() although majority of the unique variants were removed?
```
> sum(seqtab)
[1] 1246994
> sum(seqtab.nochim)
[1] 1090080
> sum(seqtab.nochim)/sum(seqtab)
[1] 0.8741662
```

**Comment by benjjneb** [comment]
> Below are the stats, does this mean 87% of reads remained after removeBimeraDenovo() although majority of the unique variants were removed?

Yes, that's exactly what it means, and ~12.5% chimeric reads is within with what we expect for multi-V-region amplicons.

This indicates that your data processing is probably fine. There are a lot of low-abundance chimeras in the data, which is common, hence a high fraction of sequence variants are removed, but they only represent a low fraction of reads.

I definitely recommend using the default `method="consensus"` for your data though, as we've found it works much better than `method="pooled"` for multi-V-region amplicons.

**Comment by ycl6** [comment]
Thanks @benjjneb, this is the first dataset that I've handled having that high proportion of unique variants being chimeras, so I was alarmed by it. Thanks for the explanation and I am now confident with further analysis of this dataset.

**Comment by benjjneb** [comment]
As a follow-up: The number of unique variants that are chimeras is higher in exact amplicon sequence variant (ASV) methods like DADA2 than they were in OTU methods, as chimeras very close to the real sequences are the most common type of chimera, and those used to be hidden by being lumped into an OTU. So some expectations based on previous OTU processing should be modified a little bit.

Robert Edgar discusses this in more detail in his uchime2 paper: https://doi.org/10.1101/074252

**Comment by ranjanmanishblue** [comment]
if i got Identified 118496 bimeras out of 125600 input sequences. during running command seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE) and value of 0.8136388 by running sum(seqtab.nochim)/sum(seqtab), does it qualifies for further analysis?
I am using V4 region amplification of 16S region, with 515F and 806R universal primers, primer sequences are removed earlier, however getting ~95% sequences as bimera?

**Comment by benjjneb** [comment]
The more important metric here is the fraction of reads removed as bimeras, which is <20% here, so in the range of what we see. It is normal that a much higher fraction of ASVs than reads will be removed as bimeras, because chimeras are highly diverse but usually quite rare. You will see more chimeric ASVs if you sequence deeply, but not a meaningfully higher number of chimeric reads.

That said, your near 20% of reads being chimeric is higher than what we normally see for V4 data, so you may want to re-examine your PCR protocol in the future. Longer extension times and fewer PCR cycles are both approaches that have been shown to reduce the formation of chimeric amplicons.

**Comment by ranjanmanishblue** [comment]
> The more important metric here is the fraction of reads removed as bimeras, which is <20% here, so in the range of what we see. It is normal that a much higher fraction of ASVs than reads will be removed as bimeras, because chimeras are highly diverse but usually quite rare. You will see more chimeric ASVs if you sequence deeply, but not a meaningfully higher number of chimeric reads.
> 
> That said, your near 20% of reads being chimeric is higher than what we normally see for V4 data, so you may want to re-examine your PCR protocol in the future. Longer extension times and fewer PCR cycles are both approaches that have been shown to reduce the formation of chimeric amplicons.

Thanks for your kind reply, Surely I will re-examine PCR protocol, It seems from your comments that it's ok if I proceed with further analysis, thank you again.

**Comment by nerepm** [comment]
Hi, 

I have a similar problem. I am using V3V4 region amplification of 16S region, with 341F and 785R universal primers. Primer sequences are removed earlier with removePrimers commad. 

![image](https://user-images.githubusercontent.com/123003169/213237619-ce95a63c-bb07-4765-835d-649fe425b04a.png)

![image](https://user-images.githubusercontent.com/123003169/213238176-8d9f9ecb-ee07-4671-a9c2-f61d7e34e790.png)

I do not know why am I getting those number of chimera... What should I do?  Do you recommend me to follow with the analysis?

Thanks a lot, 

Nerea

**Comment by benjjneb** [comment]
@nerepm 

In both the screenshots here, it looks like the `trimLeft` line is commented out (i.e. has a `#` character preceding that line). Thus, there is no trimming of primers happening here.

You should revise the `filterAndTrim` step to actually include primer removal. The `trimLeft` lengths should be the actual lengths of the primers, and not `c(30,30)`. And then you might want to look at the DADA2 ITS tutorial for example code on how to check on whether primers were present before/after trimming: https://benjjneb.github.io/dada2/ITS_workflow.html

**Comment by nerepm** [comment]
Thank you for your answer. 

I have run cutadapt command following the DADA2 ITS tutorial and I get to remove the primers. 

After that I run filterAndTrim command 
![image](https://user-images.githubusercontent.com/123003169/213395167-2adc518e-7528-497f-9800-8f0b9a06924e.png)
and I get lot of reads.out
![image](https://user-images.githubusercontent.com/123003169/213395297-51932304-d1b3-435e-901e-74eff5f9500e.png)

After that, I included truncLen, and the results were better:
![image](https://user-images.githubusercontent.com/123003169/213395600-7b4a986e-38eb-4a3c-b4c9-a6a938e61ae6.png)

![image](https://user-images.githubusercontent.com/123003169/213395755-fa6dbfec-d94d-44e6-a25e-6d617e8cb7a3.png)

![image](https://user-images.githubusercontent.com/123003169/213395810-e056179e-bec3-48a2-bc1c-35bdb0967eb5.png)

Here is how was going the analysis. It went better than the last analysis, but I'm still loosing sequences. 
![image](https://user-images.githubusercontent.com/123003169/213396133-a9faf4f4-c0cb-4d4e-90d7-275f47d13f49.png)

What can I do?

Thanks a lot,

Nerea

**Comment by benjjneb** [comment]
Why are you using cutadapt at all? Just use `filterAndTrim` with the appropriate `trimLeft` parameters. cutadapt introduces a lot of potential twitchy errors in how flags are assigned. We use it in the ITS tutorial because of the highly variable length of that locus. It is not needed for 16S sequencing.

> What can I do?

Another thing to consider is just dropping the reverse reads. You haven't shown quality profiles, but often they are worse quality, and add little.

**Comment by nerepm** [comment]
Hi Benjamin, 

These are plot quality of some of the sequence (the first ones are forwards and the second ones revers:
![image](https://user-images.githubusercontent.com/123003169/214064226-19430dd4-36ab-4140-a4b7-185b669e6bc1.png)
![image](https://user-images.githubusercontent.com/123003169/214064467-13da4daa-44b5-485c-8eb0-76cdaf28d271.png)
![image](https://user-images.githubusercontent.com/123003169/214064664-f5355e74-7021-4792-a9bb-0380a047e520.png)

![image](https://user-images.githubusercontent.com/123003169/214064284-a012235d-add6-4ced-9f3e-9e747896f1ca.png)
![image](https://user-images.githubusercontent.com/123003169/214064536-97ffa504-359f-4b4e-b2a3-509d250041fc.png)
![image](https://user-images.githubusercontent.com/123003169/214064966-66aa769e-88d5-4ae5-bb39-8b52e74f89cf.png)

I did add trimLeft to the command filterAndtrim, where I put the lenght of my primers 17 and 22.
![image](https://user-images.githubusercontent.com/123003169/214064052-9338b34c-c5e7-438e-9c1f-44b71d728011.png)
After that, I check if primers where removed and I got this:
![image](https://user-images.githubusercontent.com/123003169/214063899-4b4ce685-7c5c-4d35-8667-8a39d2026d4e.png)

When I run to make the sequence table I get this.
![image](https://user-images.githubusercontent.com/123003169/214065479-b5e73fb5-e28e-4274-8007-e3f3db927375.png)

Do I have to remove 403 and 404?
I got 33% of chimeras
![image](https://user-images.githubusercontent.com/123003169/214065923-8f9f32bd-0754-4981-a126-a7f1b4b3ac72.png)

And the track of the analysis if the next one:
![image](https://user-images.githubusercontent.com/123003169/214066161-012676ab-707b-4171-af05-e98d5b06fa1e.png)

I continue with the analysis and when I want to know how many phylum I got I got this, this is weird for me as I've never got something like that... I do not know if there reason is the low number reads or what...

![image](https://user-images.githubusercontent.com/123003169/214067324-efec5335-9b19-4b8d-87a5-4eb343102079.png)

What do you think?

Thanks a lot, 

Nerea

**Comment by benjjneb** [comment]
You are losing more reads at every step in the pipeline than is normally seen, so that is not a good sign. My guess is that there is something about your library preparation that is not yet understood and is causing issues downstream. For example, might your sequencing provider be using "heterogeneity spacers" or variable-length pads before the primers? If so, different pre-processing steps are needed.

I would contact the sequencing provider and get the full details on how they prepared the libraries, and exactly what is expected on a sequenced read. I would also open up a forward read file, and look for the forward primers. Are they always at the start of the reads?
