### ISSUE TITLE
Accessing previous DADA2 versions

### ISSUE THREAD

**Issue by Nick243** [benjjneb/dada2#332]
Hi Ben,

Is it possible to access older versions of DADA2?  I was comparing two different projects for which we used the DADA2 package and algorithm and wanted to ensure that the differences in diversity we are seeing are not due to differences in any of the default parameters.  

In particular, if the dada function dada(pool= FALSE) has been the default from versions 1.1 to v1.5

Thanks in advance,

Nick

**Comment by benjjneb** [comment]
The easiest way to see old release versions is on the github releases page: https://github.com/benjjneb/dada2/releases

Otherwise, the code at any commit version can be interrogated through standard github functionality. You can also look through the NEWS file, as we try to record all defaults that change there.

To answer your specific question, `dada(..., pool=FALSE)` has always been the default. The most important default that has changed since 1.0 is `removeBimeraDenovo(..., method="consensus")` replacing `method="pooled"` as the default in 1.4
