### ISSUE TITLE
Warning: Not all the sequences were the same length

### ISSUE THREAD

**Issue by NinaKons** [benjjneb/dada2#338]
Ben, another question now,

When I process Trimmomatic trimmed **F/R reads of different length**, I am getting a warning during the error estimation, such as:
**errF <- learnErrors(filtFs, nread=2e6, multithread=TRUE)** 
"**Not all the sequences were the same length**" 
But then it shows the number of reads in each sample etc and seem to proceed.

Do you think the pipeline is proceeding canonically, and that this warning for different length of input (raw) F/R reads will not affect the results?

**Comment by benjjneb** [comment]
You can ignore this warning, as in the 1.4 version we updated the algorithm to be able to handle different input amplicon lengths.

However, the very best results will be obtained by trimming reads to the same length, _if the length variation is artefactual rather than biological_ (i.e. due to trimming at a minimum quality score, and not biological variation of the length of the amplicon as in ITS).

**Comment by NinaKons** [comment]
Thanks, again, it is good to know that DADA2 v1.4 can handle the reads with differential length.
