### ISSUE TITLE
AlignSeqs error: protect(): protection stack overflow

### ISSUE THREAD

**Issue by clfrankling** [benjjneb/dada2#348]
I have trimmed and translated my NGS data and now have all the amino acid sequences in file: trans_seqs1 (Large AAStringSet, 14.7 Mb).
These have been quality controlled down from the original 600000 sequences.
Info;
> length(trans_seqs1)
[1] 482694
> summary(nchar(trans_seqs1))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.00   20.00   20.00   19.97   20.00   39.00

When I try aligning all the sequences (widths between 18-20) I get this error;
> library(DECIPHER)
> seqsalign <- AlignSeqs(trans_seqs1)
Determining distance matrix based on shared 3-mers:
  |                                                                     |   0%
Error: protect(): protection stack overflow

What can I do? Is it the function or my computer (Windows 7, 64bit operating system, 8GB RAM)?

I have also tried using the msaClustalW function but Clustal does not seem to align more than 500 sequences at a time. Can anyone suggest a package to align such a large amount of sequences in one go?

**Comment by benjjneb** [comment]
Apologies, but I actually haven't done any amino-acid alignments in R, so I can't really help. Any suggestions from others?

You may want to ask this question in another place (e.g. the Bioconductor support forum) as the dada2 package doesn't deal with AA sequences at all.

**Comment by digitalwright** [comment]
The issue of aligning large numbers of unique sequences (up to 46,340) in [DECIPHER](http://DECIPHER.codes) version 2.4 has been fixed in DECIPHER version 2.6.  Please update your R and then reinstall DECIPHER to begin using the latest version.  The plan is to extend DECIPHER to allow alignment of up to 92,682 sequences in the next major release (May 2018).

Please remember to dereplicate the sequences before alignment.  For instructions on how to do this, refer to the [alignment vignette](http://DECIPHER.codes/Documentation/Documentation-ArtOfAlignment.html).  If there are still too many sequences remaining, consider clustering the sequences at high-identity and only aligning cluster representatives.

At the moment, there is no plan to enable the alignment of several hundred thousand sequences, as requested here.  There may be other tools for this purpose, but the accuracy of such extremely large alignments remains unclear.

**Comment by clfrankling** [comment]
That is great news. I have updated R and reinstalled DECIPHER.
I have then taken 46340 unique sequences from my data set and run the AlignSeqs function.

I then ran the function through R using the following job request;
#!/bin/sh
#$ -cwd             # Set the working directory for the job to the current directory
#$ -pe smp 12       # Request 1 core
#$ -l h_rt=24:0:0   # Request 48 hour runtime
#$ -l excl=true     # Request an entire node
#$ -l node_type=dn  # Request a dn node

But received this error file back;

Bioconductor version 3.5 (BiocInstaller 1.26.1), ?biocLite for help
A newer version of Bioconductor is available for this version of R,
  ?BiocUpgrade for help
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.0 (2017-04-21).
Installing package(s) â€˜DECIPHERâ€™
trying URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/DECIPHER_2.4.0.tar.gz'
Content type 'application/x-gzip' length 8119678 bytes (7.7 MB)
==================================================
downloaded 7.7 MB

* installing *source* package â€˜DECIPHERâ€™ ...
** libs
installing to /data1/home/btx020/R/x86_64-pc-linux-gnu-library/3.4/DECIPHER/libs
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (DECIPHER)

The downloaded source packages are in
	â€˜/tmp/160940.1.all.q/RtmpU8mSFE/downloaded_packagesâ€™
installation path not writeable, unable to update packages: boot, foreign,
  Matrix, mgcv
Loading required package: Biostrings
Loading required package: methods
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: â€˜BiocGenericsâ€™

The following objects are masked from â€˜package:parallelâ€™:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from â€˜package:statsâ€™:

    IQR, mad, sd, var, xtabs

The following objects are masked from â€˜package:baseâ€™:

    anyDuplicated, append, as.data.frame, cbind, colMeans, colnames,
    colSums, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, lengths, Map, mapply, match,
    mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rowMeans, rownames, rowSums, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors
Loading required package: stats4

Attaching package: â€˜S4Vectorsâ€™

The following object is masked from â€˜package:baseâ€™:

    expand.grid

Loading required package: IRanges
Loading required package: XVector

Attaching package: â€˜Biostringsâ€™

The following object is masked from â€˜package:baseâ€™:

    strsplit

Loading required package: RSQLite
Error: cannot allocate vector of size 8.0 Gb
Execution halted
Warning message:
system call failed: Cannot allocate memory 









What does this mean?
That I don't have enough memory? Or that the application still isn't working?

**Comment by digitalwright** [comment]
First, based on the messages above, it looks like you are using an old version of DECIPHER.  Please update to the latest R and reinstall DECIPHER (v2.6+).

Second, from the error message, it is unclear at which step your script fails.  It looks like you do not have enough memory available.  It will take a considerable amount of memory to align 46,340 sequences (around tens of gigabytes).  You could try repeating the process with fewer sequences, or using a machine with more memory.  (Note that you will also need to use a 64-bit build of R, which is typical for most installations.)

**Comment by digitalwright** [comment]
I forgot to add that some versions of R support multiple versions of Bioconductor.  It may be necessary to run "BiocUpgrade" to reinstall the latest version of DECIPHER after upgrading R:
```
source("https://bioconductor.org/biocLite.R")
biocLite("BiocUpgrade")
```
The messages that are printed by `biocLite()` will notify you if this is necessary, but oftentimes they are hard to spot.

**Comment by clfrankling** [comment]
Thank you for your help. I installed all the latest versions and then ran the job with 60GB memory available. After 36 hours it failedbecause it used more memory than requested (62.587G / 60G). Could you recommend how an amount of memory required for the maximum 46340 sequences?

**Comment by clfrankling** [comment]
I meant could you estimate the amount of total memory I need to assign to my job to enable the whole 46340 sequences to be aligned?

**Comment by digitalwright** [comment]
Alignment of 46k sequences should require approximately 10GB for typical sequence sets.  This could be much higher if a lot of the sequences are not homologous, so the alignment would start to expand in size dramatically as more non-homologous sequences are incorporated.

To mitigate this issue, I would recommend classifying the sequences prior to alignment, and removing sequences that are not part of the same gene.  For example, you could follow along with the "Classifying Sequences" vignette that is part of DECIPHER.  If you are trying to align 16S sequences then I suspect that many of the sequences are classified as "unclassified_Root" with low confidence.  This happens when non-16S sequences are part of the set, and their removal would probably eliminate the requirement for high memory during alignment.
