### ISSUE TITLE
How to construct trained datasets for SILVA 119

### ISSUE THREAD

**Issue by montoyah** [benjjneb/dada2#353]
Hi all,

For comparative purposes, I need to use the SSU SILVA 119 with DADA2, which is not readily available. I tracked the source code but I can't find how to construct this trained datasets. If I missed the obvious, please point me in the right directions. Otherwise, how can I make this file formatting, and from what SILVA file (there're a lot of fasta files in each SILVA release)? 

Thanks in advance for any help.

**Comment by benjjneb** [comment]
The Silva training files for dada2 were created using the `dada2:::makeTaxonomyFasta_Silva()` function, https://benjjneb.github.io/dada2/training.html:

>We created the dada2-compatible training fastas from the mothur-compatible Silva training data (described here, and license here)...

I don't know if the mothur team created files for the Silva 119 release, but they posted instructions on how they created their files (see links in [our page on taxonomic reference files](https://benjjneb.github.io/dada2/training.html).

Alternatively, the dada2 `assignTaxonomy` function is just a reimplementation of the naive Bayesian classifier method rather than an original method, so you could potentially find a Silva 119 solution for that elsewhere.

**Comment by montoyah** [comment]
Got it, thanks very much, Ben!

**Comment by montoyah** [comment]
To date (October 27, 2107), Mothur has formatted versions of SILVA 102, 119, 123 and 128 (https://www.mothur.org/wiki/Silva_reference_files).
