### ISSUE TITLE
Installation of blastr and an error message when running Filtering and Trimming

### ISSUE THREAD

**Issue by incognitome** [benjjneb/dada2#359]
Hi all, I started using dada2 yesterday, so if my questions are too basic and have been addressed before, I apologize.

The protocol I am following has this step to install blastr: _library(blastr); packageVersion("blastr")_. I have tried to install blastr by sourcing BiocLite and installing the package through CRAN, but neither worked. Any advice on how to install blastr?

I was running the step of Filtering and Trimming, when this error message popped up: _Error: cannot allocate vector of size 336.9 Mb_   I googled and it seems the problem is that my RAM (4GB) is too small. What would be the minimal PC specs to run DADA2? I do have a personal MacBook Pro, which has 8GM memory. However, the flash storage is only 128 GB and it's almost full now. 

Lastly, I have two general questions regarding DADA2: 
1)  Is it correct to say that the major difference between DADA2 and Mothur is that DADA2 does not cluster sequences into OTUs? 2) Is there any computational advantage for DADA2 to merge the paired reads at a later stage of the pipeline, compared to Mothur?

Thank you very much!

**Comment by benjjneb** [comment]
> I was running the step of Filtering and Trimming, when this error message popped up: Error: cannot allocate vector of size 336.9 Mb I googled and it seems the problem is that my RAM (4GB) is too small. What would be the minimal PC specs to run DADA2? I do have a personal MacBook Pro, which has 8GM memory. However, the flash storage is only 128 GB and it's almost full now.

Is the machine you got that error on a 32-bit machine? What is the total size of the dataset you are trying to process?

For big datasets in which memory becomes a constraint, you can use the [Big Data Workflow](https://benjjneb.github.io/dada2/bigdata.html). This allows DADA2 to process large datasets under low memory conditions since it loads samples one-by-one into memory. For example I processed the TARA oceans ~800M read dataset in 8GB of memory on my laptop. The tutorial workflow will try to load all your data (dereplicated) into memory.

**Comment by benjjneb** [comment]
> Is it correct to say that the major difference between DADA2 and Mothur is that DADA2 does not cluster sequences into OTUs? 2) Is there any computational advantage for DADA2 to merge the paired reads at a later stage of the pipeline, compared to Mothur?

1) Yes, "a" major difference is the use of exact amplicon sequence variants (ASVs) rather than OTUs. We go into some depth about why that has major positive implications beyond just the higher resolution in our ISMEJ paper: http://dx.doi.org/10.1038/ismej.2017.119

Whether or not that is "the" major difference depends on the value you put on other differences.

2) Quoting [the DADA2 paper](http://www.nature.com/nmeth/journal/v13/n7/full/nmeth.3869.html): "One such difference is that the DADA2 pipeline performs merging of paired-end reads after denoising [rather than before]. This is because the core denoising algorithm uses the empirical relationship between the quality score and the error rates. When reads are merged, this relationship will differ between the forward-only, overlapping, and reverse-only portions of the merged read. That variation interferes with the denoising algorithm, and therefore greater accuracy can be achieved by denoising before merging, albeit at some computational cost."

**Comment by incognitome** [comment]
Thank you for the patient explanation, Ben. blastr still doesn't work for me. I'll contact the author.  My laptop is 64-bit. The total size of the raw data (fastq) is 9.5 GB. I'll keep it in mind that Big Data Workflow is a solution to running large data sets on low RAM machines. Right now, I've asked to get access to a server that has 132GB RAM. Let's see...Thanks for answering my last two general questions. I'll educate myself more on this topic by reading your DADA2 paper.
