### ISSUE TITLE
ASV table issue: ASVs are sample specific

### ISSUE THREAD

**Issue by chubbar9** [benjjneb/dada2#379]
I have gone through the "Big Data: Paired-End" tutorial with a small V4V5 16s MiSeq soil dataset and I am having issues with the output ASV table, where each ASV is only present in one sample. For example, ASV1 is only found in Sample3, ASV2 is only found in Sample2, ASV3 is only found in Sample3, and so on. Initially, I thought that the reads still contained their bar codes or some other sequencing artifact, but after checking, this does not seem to be the case. 

I have successfully used this tutorial on other datasets, including a dataset from the same MiSeq lane, but I am not sure what would be different about these samples...

Thank you in advance!

**Comment by benjjneb** [comment]
Could you try running the dataset with the `dada(..., pool=TRUE)` option and see if that improves things? You will have to use the tutorial-style workflow for that, rather than the Big Data one.

Pooling will likely take longer computationally, but if it's a subset of a MiSeq lane it should be tractable with multithreading enabled.

**Comment by chubbar9** [comment]
This worked, thank you!
