### ISSUE TITLE
concatenate sequences, and clustering OTUs

### ISSUE THREAD

**Issue by kdricks** [benjjneb/dada2#386]
I have two questions.
First, about half of my paired reads from my sequencing run do not overlap, while the other do. I know I can use the mergePairs function and specify justConcatenate = TRUE to join all paired reads with 10Ns. However, is it possible to merge without concatenation the paired reads that do sufficiently overlap, while only concatenating the paired reads that do not overlap? Or does something like this not even matter?

Second, when using the assignTaxonomy function, some of my reads are not being called to the species level. For example, it assigns some to the genus Candelariella but the species level is unknown. What’s problematic is that I’ll have multiple lines where something is assigned to some genus, for example Candelariella, and not a species. I don’t know whether these separate lines are actually different species, or the same species within the same genus. Is it possible to use some sort of clustering method (like that used in QIIME) to group like-sequences together in an OTU at some level of similarity?

**Comment by benjjneb** [comment]
>First, about half of my paired reads from my sequencing run do not overlap, while the other do. I know I can use the mergePairs function and specify justConcatenate = TRUE to join all paired reads with 10Ns. However, is it possible to merge without concatenation the paired reads that do sufficiently overlap, while only concatenating the paired reads that do not overlap? Or does something like this not even matter?

Why do half not overlap? Are you putting together different amplicons? Or is this due to some amplicon like ITS with a lot of length variation?

You can in principle do a hybrid merge/concatenate approach, but such hybrids are to be avoided if possible, as they can introduce a bit of bias depending on the size of the amplicon. You would do it by running `m1 <- mergePairs(...)` and `m2 <- mergePairs(..., justConcatenate=TRUE)`, and then combining `m1` with all the pairs in `m2` not found in `m1` (i.e. `m2[!paste(m2$forward, m2$reverse) %in% paste(m1$forward, m1$reverse),]`).

> Second, when using the assignTaxonomy function, some of my reads are not being called to the species level. For example, it assigns some to the genus Candelariella but the species level is unknown. What’s problematic is that I’ll have multiple lines where something is assigned to some genus, for example Candelariella, and not a species. I don’t know whether these separate lines are actually different species, or the same species within the same genus. Is it possible to use some sort of clustering method (like that used in QIIME) to group like-sequences together in an OTU at some level of similarity?

Non-assignment is meaningful, it indicates that there is insufficient confidence to assign this sequence to that taxonomic level. If you have a genera of specific interest, further species level assignments by hand might be useful. Alternatively there is the `assignSpecies` method in dada2 that you could try, it is built to assign to the species level by exact matching, but it is appropriately conservative.

You can further cluster the ASVs output by dada2 into OTUs. But is there a good reason to do so? What are you trying to achieve there?

**Comment by kdricks** [comment]
For the first question, half of the reads don’t overlap because in the ITS region I’m using, there is a lot of length variation such that some reads overlap and others do not.

You say these hybrids can introduce bias. What sort of bias?


For the second question, in the rest of my data that has been called to the species level, I have multiple lines all calling to the same species, despite being slightly different sequences. I’m planning on merging all these lines that get called to the same species. The reason that I’m thinking about clustering non-assigned species (and maybe this is faulty thinking on my part) is that I don’t know if some of these non-assigned reads are different species within the same genus, or the same species with the genus. I’d like to merge those if possible as I’m interested in the diversity of these samples. If there are reads that cannot be assigned to species, and I keep them as separate species, when in fact they are the same species but with slight variations, wouldn’t I be artificially inflating the diversity.

**Comment by benjjneb** [comment]
> You say these hybrids can introduce bias. What sort of bias?

The merging process culls out mismatched F/R reads, while concatenating does not. So the concatenated amplicons will have a higher level of spurious variation.

> If there are reads that cannot be assigned to species, and I keep them as separate species, when in fact they are the same species but with slight variations, wouldn’t I be artificially inflating the diversity.

Diversity of what? Species? What is a species? 97% OTUs are definitely **not** species, so making those isn't helping you there.

The advantages of sticking with exact amplicon sequence variants is that they will be comparable between this and future studies, and they are an equally valid unit of diversity as an OTU at some arbitrary cutoff. If there is a good reason in your system to cluster ASVs into OTUs at some threshold, that's fine to do, but the classic notion of making "species" by OTU clustering is misguided.
