### ISSUE TITLE
What if I don't truncate my reads, what'll happen?

### ISSUE THREAD

**Issue by RBDNUS** [benjjneb/dada2#387]
So, I am superrr new to this. I was trying to do tutorial codes and when i was doing the quality checking of my reads, i think the resulting plot came out bad (i dont know how bad it is since I do not know how to interpret how good/bad Miseq 300x300 paired reads are) and wanted to proceed with the analysis even without truncation. Will my data be really bad if I don't truncate? If I really need to do so, which parts should I look into for truncation. Is there any "standard" for quality scores? Thank you.
![image](https://user-images.githubusercontent.com/34911621/34407665-8aa88b94-ebfa-11e7-8aad-7da865278a41.png)

**Comment by Listen-Lii** [comment]
If you don't truncate your low-quality sequences, you will get bad results in Merge paired resds step at least.
Generally speaking, sequences with Q>20 will be kept for further analysis.
I am also a novice to DADA2. This is my personal opinion and wish you good luck!

**Comment by benjjneb** [comment]
@RBDNUS There are two things to consider (1) How long do my reads need to be to overlap? And (2) where do the quality scores start to drop significantly?

In order to merge, you have to keep enough sequence to overlap by >20nts, so that is priority 1. But after that, you should cut off the low quality tails (i.e. after about position 200 in your plots) where qualities decrease substantially from their initial values.

Low quality tails reduce the ability of the algorithm to resolve low-frequency variants, and as long as you maintain overlap you'll get better results by getting rid of them.
