### ISSUE TITLE
learnErrors terminated before convergence 

### ISSUE THREAD

**Issue by drdee255** [benjjneb/dada2#392]
I have big paired-end data (39 samples) and I am following workflow [](https://benjjneb.github.io/dada2/bigdata_paired.html)
dada2 version - 1.6

commands -
errF <- learnErrors(filtFs, nread=1e6, multithread=TRUE,randomize=TRUE,MAX_CONSIST=10)

the plot of errors is attached. I also want to checkConvergence. But this function is not available in version 1.6
![plot_errf_1m](https://user-images.githubusercontent.com/21307964/34598952-bb9c5e44-f215-11e7-95f8-f46dbb779ec2.jpg)

From the plot, I don't think it is good fitted.

**Comment by drdee255** [comment]
No I have started a learnError() command for 25 Self consistency loops.
Will post that results too.

**Comment by benjjneb** [comment]
You are right to be concerned, that is some very unusual looking data...

Is it possible you are mixing samples from different sequencing instruments?

**Comment by drdee255** [comment]
@benjjneb I am pretty sure that the data is from single instrument only. After setting MX_CONSIST=20, I got similar convergence graphs.
The latest version of dada2 does not have checkConvergence function. Otherwise I would have share numbers also.

**Comment by benjjneb** [comment]
It should still be there as a private function, try `dada2:::checkConvergence`

What sequencing instrument are you using. Is this a Miniseq?

**Comment by drdee255** [comment]
Hiseq2500 paired end
2*250 V4 region

**Comment by benjjneb** [comment]
I've never seen a `plotErrors` plot quite like that one before...

Would it be possible to share one of your samples for me to run locally?

**Comment by drdee255** [comment]
@bejjneb , actually I am not the true owner of data. I am just analyzing
it. I will ask the owner, if he permits I would be happy to share multiple
files with you.
I will get back to you on this.

Dattatray Mongad
9404710355

**Comment by drdee255** [comment]
@benjjneb I have mailed you the link for sample data.
waiting for your response

**Comment by benjjneb** [comment]
Thanks for sending me the data. The unusual `plotErrors` output is arising due to the fact that your sequences have been assigned binned quality scores, rather than raw quality scores. This is something that Illumina has started doing in some cases to allow more compression of fastq data. In your data, only the quality scores 13,22,27,32,38,40 (and probably some rare low score) are present.

With that knowledge, the `plotErrors` plots may be OK. The fitted error model (the black line) is following the points at 13/22/... where there is a lot of weight, as it should be. The in between points are rarer instances where the same sequence was given different quality scores. Those points are all below the fitted line, so at worst the algorithm is assuming error rates are higher than they should be, which is conservative.

My biggest concern would actually be that the error rates don't decrease much with higher qualities, but we do see that sometimes in Illumina runs so its certainly not unprecedented.

**Comment by drdee255** [comment]
Hello Benjamin,
Is there anything you would like to suggest a solution for such problem.

I am stuck now.

Dattatray Mongad
9404710355

**Comment by benjjneb** [comment]
> Is there anything you would like to suggest a solution for such problem.

I think you are OK to proceed as is. Strict convergence is not that important if that is what you are worried about: https://benjjneb.github.io/dada2/faq.html#what-if-the-self-consistency-loop-terminated-before-convergence
