### ISSUE TITLE
PR2 database formatted for dada2

### ISSUE THREAD

**Issue by vaulot** [benjjneb/dada2#400]
PR2 is annotated database widely used for protist metabarcoding (18S rRNA).

I have added to the last release a file formatted for dada2:

https://github.com/vaulot/pr2_database/releases

pr2_version_4.72_dada2_Eukaryota.fasta.gz

Note: pr2 has 8 levels so you should use the parameter `taxLevels = c("Kingdom", "Supergroup","Division", "Class", "Order", "Family", "Genus", "Species")`

**Comment by benjjneb** [comment]
Well that is pretty cool! Thanks @vaulot 

I'll add a link to PR2 from our webpage.

**Comment by benjjneb** [comment]
Link added to https://benjjneb.github.io/dada2/training.html

**Comment by FabianRoger** [comment]
Just a note on the PR2 release by @vaulot: I downloaded the dada2 formatted version from [here](https://github.com/vaulot/pr2_database/releases) and tried it with `assigTaxonomy`. My laptop crashed because of memory overflow. The problem was, it turned out, **that the file had line breaks in the sequences** which lead `DADA2` to take each line as a separate sequence (I think). After removing the line breaks it worked fine. 

ps: the code for reformating was `cat pr2_version_4.10.0_dada2.fasta | sed -e ':a' -e 'N' -e '$!ba' -e 's/[^;]\n[^>]//g' > pr2_version_4.10.0_dada2_nolb.fa`

thanks to @vaulot for the database!

**Comment by vaulot** [comment]
The fasta files of PR2 are formatted as lines of 80 characters.  In the next release of the PR2 files (> 4.10.0)  I will remove the line breaks that cause problems.

**Comment by au541411** [comment]
Dear @benjjneb,

Small request:
It would be greatly appreciated if you would update your DADA2 tutorial to fit with the latest version of the PR2 database taxonomy for the version 5 of the PR2 database:

https://benjjneb.github.io/dada2/training.html

taxLevels = c("Domain","Supergroup","Division","Subdivision", "Class","Order","Family","Genus","Species"))

Thanks to @vaulot for the database and @benjjneb for maintaining the DADA2 pipeline.

Best,
Lasse

**Comment by benjjneb** [comment]
@vaulot Can you confirm the updated `taxLevels` posted above?

**Comment by benjjneb** [comment]
PR2 levels fixed in 38960764ac223a835f93d0ab0d7d1542d027be27
