### ISSUE TITLE
Deeply sequenced samples yielding (too) many ASVs?

### ISSUE THREAD

**Issue by elsherbini** [benjjneb/dada2#412]
I'm working with a data set with 48 (agricultural) soil samples. Each sample has over 250,000 reads. The amplicon is V3-V4 and miseq 2x300 was used so the quality is abysmal and the reads don't overlap. I truncated the forward reads to 150 bps and the reverse reads to 75 bps. 

After denoising (not pooled) I get 1.7 million unique sequences, with over 100,000 ASVs per sample. Normally I work with marine and gut samples, V4 miseq 2x250, and more like 10,000 reads per sample, so I have higher quality, lower diversity, less depth, and overlaps. In these samples I typically see between 200 and 800 ASVs per sample when I don't pool. 

Two questions:

1. Does this number of ASVs seem normal to given all the weirdness with the samples? Would filtering differently be advisable?

2. Because the samples do not overlap, I didn't do bimera filtering. I found that when I tried to do bimera filtering it was taking over 20 hours (although I see now that I was doing it on only one core). Do you recommend bimera filtering with nonoverlapping reads (containing the 10 Ns)?

**Comment by benjjneb** [comment]
> the reads don't overlap

This is the problem. Non-overlapping reads create many (low-frequency) spurious ASVs, largely due to the dust of crazy singleton errors that the algorithm tries to map, but get mapped to different F/R ASVs since they don't really match any of them.

Merging enforces exact matching in the overlap region, hence weeds those all out. Without merging, that cloud of dust stays around, with numbers that scale roughly quadratically with the number of real ASVs (but still a low fraction of total reads).

Chimera removal will get rid of a lot of it, but what I'd really recommend in this case is using just the forward reads alone.

**Comment by benjjneb** [comment]
I still don't recommend the non-overlapping approach, but the new thresholded error-correction feature we just checked in would be one way to mitigate the issue I described above:

> the dust of crazy singleton errors that the algorithm tries to map, but get mapped to different F/R ASVs since they don't really match any of them

`OMEGA_C` now sets a threshold value at which unique sequences are (or are not) corrected. So if a singleton has a "p-value" in the final partitioning of less than `OMEGA_C` to be produced from the center of its partition, its not corrected (essentially assumed to be from an unknown real sequence).

Usually aggressive correction is the right way to go, especially in paired-end sequencing which weeds out the mis-corrected reads by the overlap requirement. But in the non-overlapping case, it might make sense to only correct when there is high confidence, for example `OMEGA_C = 0.1`, or even turn off correction entirely with `OMEGA_C=100`.

If you do try this on this data, we'd love to hear the results!
