### ISSUE TITLE
Exclude "bad" samples before pipeline?

### ISSUE THREAD

**Issue by sfeds** [benjjneb/dada2#442]
Hi,

I have a dataset of over 260 samples, some of which didn't give good results after sequencing (which was sort of expected due to the source material).
However, I have the typical R1/R2 files in my data. I was wondering, does it make any difference if you run the pipeline with these "failed" samples, or should one remove them before running DADA2?

And an extra question: is there any way to get a table similar as the "track" from the MiSeq SOP tutorial for the DADA2 for big data (paired end)?

Thanks! Thoroughly enjoying this pipeline!
sfeds

**Comment by benjjneb** [comment]
It's fine to include the failed low-abundance samples, it won't affect the processing of the other samples.

> is there any way to get a table similar as the "track" from the MiSeq SOP tutorial for the DADA2 for big data (paired end)?

Yes, you can do much the same thing there with a little R scripting.
To get a table with the 4 important columns:

```{r}
out <- filterAndTrim(...)
# run Big Data workflow through to the post-merging sequence table
merged <- rowSums(seqtab)
# Remove chimeras
nochim <- rowSums(seqtab.nochim)
track <- cbind(out, merged=merged, nochim=nochim)
```

**Comment by sfeds** [comment]
Cool, thanks! The only "problem" is that to create the "out" you have to rerun the filterAndTrim function, and it starts rewriting the filtered files. This is ok, I'm just slightly impatient :)

Expanding on the bad samples question: I have sequences (raw) of around 300bp, unfortunately for V3-V4 (I'm not a big fan of multiregion sequencing but this was outsourced). I'm also unsure whether primer sequences are still in there (seems like I drop a lot of reads after the chimera removal, which is a hint). So I have to compromise somewhere in the filterAndTrim function in order to get merging, not chimeras, and good quality reads.

In summary my question is: which parameter would you "sacrifice" to get the best output?
At the moment I use:
filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
              rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs),
              truncLen=c(280,210), maxEE=2, truncQ=11, maxN=0, rm.phix=TRUE,
              compress=TRUE, verbose=TRUE, multithread=TRUE, trimLeft = c(20,20))

I'm using quite a bit of the FWD and REV reads, although the quality drops a bit earlier than that (280 or 210), but otherwise I don't have merging (side note, I'm also using the minOverlap=4 to help a bit).

Maybe I can compromise more on the maxEE or should I just be happy with the filtered output? (going from 20-40% of the reads).

And as a final question (sorry, I'm just very excited with this pipeline!!): I'm using the "big data paired end" code, I read is designed for HiSeq output but I use it for my MiSeq output, just that I have so many samples that this code runs much more efficient. Is there anything I should "tweak"?

Many many many thanks! :)

PS: a couple of example plots of the quality of the reads
![quality score fwd](https://user-images.githubusercontent.com/20225551/38662319-6be35f92-3e23-11e8-886b-1c098183ea42.jpeg)
![quality score rev](https://user-images.githubusercontent.com/20225551/38662329-739b5334-3e23-11e8-8bf2-b749ffd2e5f6.jpeg)

**Comment by benjjneb** [comment]
> I'm also unsure whether primer sequences are still in there (seems like I drop a lot of reads after the chimera removal, which is a hint).

**(See Edit below)** You need to remove primers, it's not optional w/ ASV methods. You can do this with `filterAndTrim` if you know their lengths, i.e. `trimLeft=c(17, 21)` if the F/R primers are 17/21 nucleotides long. You can always inspect the sequences to determine if the start of the F/R reads are primers sequence. V3/V4 often uses the Illumina recommended primer set, so I would check that one first:

V3V4 (Illumina - https://academic.oup.com/nar/article/41/1/e1/1164457)
341F: CCTACGGGNGGCWGCAG
785R: GACTACHVGGGTATCTAATCC
~460 amplicon (w/ primers)

**Edit:** I see you are using `trimLeft=c(20,20)` now, which is probably fine! 
I'd still recommend identifying the exact primer set though for best practice. Leaving the previous text up for future reference.

> I'm using quite a bit of the FWD and REV reads, although the quality drops a bit earlier than that (280 or 210), but otherwise I don't have merging (side note, I'm also using the minOverlap=4 to help a bit).
>
>Maybe I can compromise more on the maxEE or should I just be happy with the filtered output? (going from 20-40% of the reads).

You can always fiddle, but the parameters you've chosen seem reasonable to me. In filtering, there are lots of "right" answers, and you just want to avoid the "wrong" ones. I think you're in the "right" regime. Because you probably have primers on the amplicon, its about 460 nts, and you need to keep that + bio length variation + overlap to get merging. So you can't cut much more than you are. If fiddling, I might push the forward reads to 290 or 295, and pull back a corresponding amount on the reverse reads -- I think that will get another couple percentage points through the filter. But it's not important.

> And as a final question (sorry, I'm just very excited with this pipeline!!): I'm using the "big data paired end" code, I read is designed for HiSeq output but I use it for my MiSeq output, just that I have so many samples that this code runs much more efficient. Is there anything I should "tweak"?

Yep, Hiseq or Miseq data is totally fine. The Big Data tutorial is just written using Hiseq data as an example since that's the data I was working with.

**Comment by sfeds** [comment]
Ooops, I closed too fast!

Got another question regarding bad samples:

I'm exploring the "track" table, and of course the samples that performed badly in sequencing also did in the pipeline.
However, I have a few exceptions where input is very few reads, but somehow the merged and non chimera are quite a few (see figure). I'm not sure I understand this, any explanation?
![capture](https://user-images.githubusercontent.com/20225551/38722146-3a47c358-3efd-11e8-88f5-dbeabc38b3f2.PNG)

PS: I've been playing around with many parameters, in this particular case I'm using:
filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
              rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs),
              truncLen=c(290,205), maxEE=c(2,5), truncQ=11, maxN=0, rm.phix=TRUE,
              compress=TRUE, verbose=TRUE, multithread=TRUE, trimLeft=c(17, 21))

And I have also increased the nread in learnErrors to nread=1e8, and use minOverlap= 5

**Comment by benjjneb** [comment]
20% chimeras is high but not out of bounds, especially for multi-v-region amplicons as the conserved site in the middle is a hot-spot for chimera formation.

When you created your `track` matrix, were there any warnings? I think that some samples were lost in filtering (i.e. zero reads output) and as a result the track matrix is malformed, but that would be indicated by a warning when you `cbind` to create the full matrix.

**Comment by sfeds** [comment]
Ok, good to know about the chimeras! (note to self, avoid multi-v-region sequencing...)

So indeed that was my mistake, let me paste here the whole build of the track table:
> out <- filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
+               rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs),
+               truncLen=c(295,210), maxEE=c(2,5), truncQ=11, maxN=0, rm.phix=TRUE,
+               compress=TRUE, verbose=TRUE, multithread=TRUE, trimLeft=c(17, 21))
Some input samples had no reads pass the filter.
> 
> merged <- rowSums(seqtab)
> nochim <- rowSums(seqtab.nochim)
> 
> track <- cbind(out, merged=merged, nochim=nochim)
Warning message:
In cbind(out, merged = merged, nochim = nochim) :
  number of rows of result is not a multiple of vector length (arg 2)
> row.names(track) <- sapply(strsplit(basename(fastqFs), "_"), `[`, 1)
> head(track)
      reads.in reads.out merged nochim
P1A1     51651     19699  18379  12595
P1A10    47516     16707  15236  10556
P1A11    60355     23434  21813  12495
P1A12      266         7      7      7
P1A2     55612     21361  19786  13679
P1A3     52479     20812  18446   9132


Indeed some samples didn't pass the filtering step (don't know how to check how many), and I got the warning at the cbind. Any way around this to create a "proper" track table?

I'm actually quite relieved that this was the issue :)

**Comment by benjjneb** [comment]
This is fixed by subsetting `out` to just the rows in which reads passed the filter, as rows/samples that didn't pass the filter don't propagate to the later steps, and lead to the mismatched vector lengths and the malformed `track` matrix. Easiest is just to use the sample-names:

```
track <- cbind(out[names(dadaFs),], merged=merged, nochim=nochim)
```

**Comment by benjjneb** [comment]
Minimums are usually a study-specific rather than an absolute thing. DADA2 will do its best no matter what the library depth is. However, I do usually find it useful to plot the library depths of each sample.

Often, as is seen in the [decontam vignette](https://benjjneb.github.io/decontam/vignettes/decontam_intro.html), there is a subset of samples with library depths much lower than all the others. Those are the ones you might consider removing before some of your subsequent analyses, but the cutoff value is best read off the plot of your own data.

**Comment by sfeds** [comment]
Oh right! I had read about this package (don't remember where... maybe BioRX?), but never got to use it. 

Nice, new toy for the week! :)
