### ISSUE TITLE
Expected memory usage

### ISSUE THREAD

**Issue by johnchase** [benjjneb/dada2#45]
Hi, 

I am attempting to run dada2 on a single sample fastq file (1043802 seqs, length ~300). I'm running this on a single node machine with 32 cores and 256GB of ram.

At this point the job has been running for over 14 hours and is using 42GB ram. Having run this on other smaller data sets, this is surprising as the other data sets finished usually within a few minutes, even datasets with over 100,000 sequences.

A link to the code can be found [here:](https://github.com/johnchase/amplicon-pipeline/blob/master/dada2.ipynb)

Is this runtime/memory usage typical?

**Comment by benjjneb** [comment]
That's not typical for a 1M read sample, but I can see why it is happening here from your code: That 1M read sample gets filtered down to 753k sequences, of which 720k (!!!) unique sequences are found.

That is very unusual, there are almost no repeated observations of the same sequence.

This matters, because DADA2's time scaling on single samples is like U^2, where U is the number of unique sequences (memory scaling isn't as problematic and should go like ~U). Thus, while a 1M read sample does not typically take nearly that long, most 1M read samples have <=100k unique sequences after filtering.

Is there a reason this sample would be so hyper-diverse?

**Comment by johnchase** [comment]
Thanks for responding, I just spoke with, with the people who generated this data. That fastq file does actually represent a few different samples as well as different primer sets, so multiple different amplicons. 

I was a little worried about the run time for this with 16S where we may expect a high number of unique sequences, though I have not tried it with that type of data specifically yet. 

If we run into issues there I will let you know. Otherwise, I have found this tool to be incredibly useful.

**Comment by spholmes** [comment]
John
I do not think you should run different samples with different primer sets
in the
same run of DADA2 as a certain homogeneity in the data make for a
better rate estimation, otherwise one would have to put in an extra mixture
parametrization.

Susan

On Fri, Oct 9, 2015 at 11:07 AM, John Chase <notifications@github.com>
wrote:

> Thanks for responding, I just spoke with, with the people who generated
> this data. That fastq file does actually represent a few different samples
> as well as different primer sets, so multiple different amplicons.
>
> I was a little worried about the run time for this with 16S where we may
> expect a high number of unique sequences, though I have not tried it with
> that type of data specifically yet.
>
> If we run into issues there I will let you know. Otherwise, I have found
> this tool to be incredibly useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benjjneb/dada2/issues/45#issuecomment-146950186>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/
