### ISSUE TITLE
Complete changelog

### ISSUE THREAD

**Issue by tholland** [benjjneb/dada2#455]
I'm currently looking to update the version of dada2 I'm using, but I need to know all the significant changes.  I noticed in the [NEWS](https://github.com/benjjneb/dada2/blob/master/NEWS) file that information about some versions (e.g. 1.4.1, 1.6, etc.) is missing.  Is there a file like this with changes in all versions?

**Comment by benjjneb** [comment]
The NEWS file is our version of a changelog. It is not totally comprehensive, but it attempts to capture everything that is "meaningful", i.e. that will affect output or introduce new features.

Some versions aren't represented because they didn't include meaningful changes. For example, those might be minor changes in the DESCRIPTION file introduced to fix a BiocCheck warning, but that don't have any impact on output. So right now the best way to see what changes might be introduced by upgrading to a new version would be to read through the NEWS file from your version to the version you are considering.
