### ISSUE TITLE
subsequences in place of sequences 

### ISSUE THREAD

**Issue by bradfordptaylor** [benjjneb/dada2#478]
Hi Ben,

First off, thanks for developing DADA2, it's an excellent tool.

My question has to do with technical artifacts of identifying subsequences as an ASV instead of the parent sequence. I'll explain the problem, then give details of my analysis.

**Problem:**
Here's a heatmap of relative abundances from multiple samples of a ground truth experiment. The samples share the same strains of bacteria and the relative abundances are logged here to emphasize differences.
![dada2question_heatmap](https://user-images.githubusercontent.com/1470671/40677751-92acdda8-634c-11e8-93db-f5ebeff727f5.png)
DADA2 does mostly a great job identifying the expected ASVs (those numbered 1-7). For sample 8, ASV 5 was misidentified as ASV 9. ASV 9 is an exact subsequence of ASV 8; it is missing the first 3 nt such that ASV 9 is 328 nt long and ASV 5 is 331 nt long. Similarly for sample 14, ASV 3 is misidentified as ASV 8. Again, ASV 8 is a subsequence of ASV 3 and is missing the first 3 nt. ASV 10 is an example of a false positive ASV that is a SNP away from another ASV, it is shown for completeness of output but doesn't concern my question.

**Question:** Would misidentifying subsequences as sequences be an issue of the sequencing run or downstream DADA2 analysis such as during filtering and trimming/merging? Are subsequences considered explicitly in any sense within the error model?

Sorry, if the questions are somewhat vague or if the answer is well-known within the field. I guess I'm just wondering if anyone can illuminate on this type of error.

**Analysis details:** A single multiplexed pool of paired Illumina Miseq using V4-V5 region (typically 330 nt long). Primers have been removed before DADA2 analysis. Default filter and trim parameters were used with trunclength = c(180,180), although this issue appears to remain as I vary the trunclength.

Thanks for any help
-Bradford

**Comment by benjjneb** [comment]
> Question: Would misidentifying subsequences as sequences be an issue of the sequencing run or downstream DADA2 analysis such as during filtering and trimming/merging?

The expectation would be that the amplicon sequences are all starting and ending at the same positions (the F/R primers) thus my thought is this is somehow an artefact of the underlying sequencing. I'm not sure why these sorts of "subsequences" would exist otherwise. Were heterogeneity spacers used by any chance? Or a primer mixture with different lengths?

> Primers have been removed before DADA2 analysis.

The other possibility is there is some heterogeneity being introduced by primer removal. What method are you using? In general, the `trimLeft` feature of `filterAndTrim` works very well to remove primers at the start of the F/R reads: `filterAndTrim(..., trimLeft=c(FWD_PRIMER_LEN, REV_PRIMER_LEN))`. May be worth seeing if that resolves this.

> Are subsequences considered explicitly in any sense within the error model?

They will be merged together within each sample, but a couple of your samples seem to have settled on a different overall amplicon lengths for some sequences.

For overall resolution, the dada2 R package includes the `collapseNoMismatch` method that is intended for these sorts of cases. `collapseNoMismatch(seqtab)` will return a new sequence-table that will merge together sequences that are strictly subsequences of small shifts of other sequences.

**Comment by bradfordptaylor** [comment]
Thanks for the help. The info about collapseNoMismatch is useful to know.

Turns out the issue (like many) is on the user end. You were right at suspecting the origin being "a primer mixture with different lengths", and I was mistrimming my primers during demultiplexing before DADA2.

Cheers
