### ISSUE TITLE
Large variation in results between dada2 and Qiime/Uparse pipeline

### ISSUE THREAD

**Issue by jsan4christ** [benjjneb/dada2#501]
Hello,

I have run both the dada2 and qiime/uparse pipelines as described here (https://github.com/grbot/16SrRNA-hex-tutorial) on the same data used in the guide (dog samples).

As you can see, in the downstream analysis (https://github.com/grbot/16SrRNA-hex-tutorial/tree/master/downstream) the result was 179 OTUs, and in my case I had 186 (minor difference) but when I run the dada2 pipeline as descibed here (https://f1000research.com/articles/5-1492/v2)
I had 250 OTUs and when I changed the repset to greenegenes_13_8 used in the qiime/uparse workflow, if increased to 294 which is quite a huge difference.

The questions that come to mind are;
Is this difference acceptable? if not what is a realistic and allowed difference for a result to be considered right?

In the qiime_uparse, fastq_maxdiffs=3 was used to merge pairs and fastq_maxee=0.1 to filter out erroneous reads while in dada2 maxEE=2 is used, are these maxees the same unit and is it reasonable to set them to the same value? how do the rest of the parameters compare (trimLeft=10, truncLen=c(245, 160), maxN=0, truncQ=2)? Since these parameters can be changed, it would be great to have a guideline for changing them such such that results are always correct and meaningful.

Please advise.

**Comment by benjjneb** [comment]
Those relative numbers of OTUs vs. ASVs look reasonable, and on place to look for comparison would be the results we reported in the paper introducing DADA2: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4927377/

UPARSE, unlike many other previous OTU methods, controlled false-positives pretty well, so it is not uncommon to find more ASVs with DADA2 than OTUs w/ UPARSE, as DADA2 is distinguishing variation that UPARSE lumped together.

As for trimming and filtering parameters, the most important to consider changing in the DADA2 pipeline are `truncLen`. The basic guide is while (1) ensuring your F/R reads overlap sufficiently, (2) trim off post-quality-crash tails. A simple example of this is included in the DADA2 tutorial: https://benjjneb.github.io/dada2/tutorial.html

Also, we now only recommend using `trimLeft` if you need to remove primers from the start of the F/R reads, otherwise you probably want to use `trimLeft=0`.

**Comment by jsan4christ** [comment]
Hi Ben,

Thanks a lot for the clarification,

It all makes sense now,

DADA2 is reference-free, and applicable to any genetic locus...by any genetic locus, are you referring to the regions of the 16S gene or genetic locus in its broad sense of any a gene?

....When applied to the mouse fecal dataset, DADA2 output 389 sequences and UPARSE 327 OTUs, of which 257 were shared; by shared does it mean that they could be used to identify more than 257 organisms?

Much appreciated.

**Comment by benjjneb** [comment]
> DADA2 is reference-free, and applicable to any genetic locus...by any genetic locus, are you referring to the regions of the 16S gene or genetic locus in its broad sense of any a gene?

Any gene.

> When applied to the mouse fecal dataset, DADA2 output 389 sequences and UPARSE 327 OTUs, of which 257 were shared; by shared does it mean that they could be used to identify more than 257 organisms?

It means that 257 of the DADA2 sequences were exactly identical to 257 of the UPARSE OTU reference sequences.

**Comment by jsan4christ** [comment]
I understand,

Thank you very much for the clarifications.
