### ISSUE TITLE
Replicating results across versions.

### ISSUE THREAD

**Issue by jarrodscott** [benjjneb/dada2#532]
Hi there, 

Mac osx 10.13.5
R: 3.5.0
DADA2 v1.4, 1.8 (&1.9)

I am trying to replicate results across v.1.4 (which I originally used to process my data) and v1.8 (I also tried the devmaster 1.9).

Is this even possible? I have wracked my brain trying to figure out what is causing the differences. The two diverge at the merge step it looks like. I tried using all the defaults from v1.4 i could find (e.g, 
`setDadaOpt( OMEGA_C=0, GAPLESS=FALSE, GREEDY=FALSE,  MATCH = 4L, MISMATCH=-5L, GAP_PENALTY=-8L, USE_QUALS = TRUE)` and `minOverlap=20`. I tried various iterations of most of these values but still the datasets diverge. The differences look small but this is just 5 samples out of ~100. The number of SVs is quite different in the final analysis. 

Any help would  be sooooooo appreciated. And thanks for such an awesome tool.
Jarrod

Results from workflow (v1.4)
                   input filtered denoised merged tabled nonchim
SpAur005 79781    58035    58035  45607  45607   39034
SpAur006 94888    55750    55750  18226  18226   16206
SpAur007 87363    58124    58124  39326  39326   30957
SpAur008 41583    26665    26665  13558  13558   11533
SpAur009 64421    44693    44693  27815  27815   24032

Results from workflow (v1.8)
                input filtered denoised merged tabled nonchim
SpAur05 79781    58035    58035  45601  45601   40848
SpAur06 94888    55750    55750  18186  18186   16478
SpAur07 87363    58124    58124  39351  39351   31759
SpAur08 41583    26665    26665  13562  13562   11935
SpAur09 64421    44693    44693  27920  27920   24816

**Comment by benjjneb** [comment]
As a preface, although we do make an effort to make options available to recover previous functionality when we make significant changes to the core methods, we do not guarantee exact reproducibility of results from previous versions. In particular, if there is something that is a bug or at least something working not quite as intended, we will fix it. I know in at least one case we fixed an indexing bug that prevented the last entry in long kmer vectors from being counted. That had a tiny, but non-zero, affect on functionality.

That aside, it looks like you are getting nearly identical results through denoising, and you've identified the key flags to get that reverted behavior (`OMEGA_C = 0, GAPLESS=FALSE, GREEDY=FALSE`).

So, I think that it is the changes we made to default parameters in `mergePairs` and `removeBimeraDenovo` that need to be reverted to (nearly) match 1.4 (see https://github.com/benjjneb/dada2/commit/ae200adfb6632659016a81d0267c32c7dbcbbb67)

To revert that, try `mergePairs(..., minOverlap=20, MATCH=4L, MISMATCH=-5L, GAP_PENALTY=-8L)`. You need to pass those params to `mergePairs`, as now it overrides the `setDadaOpt` values.

Second, the default chimera removal parameters were changed (see https://github.com/benjjneb/dada2/commit/7d2a83125ccce2885b7a69f57384c5c7ab2ca04b)

To revert that, try `removeBimeraDenovo(..., minFoldParentOverAbundance = 1.5)`. I believe the default method was already `"consensus"` in 1.4, so that should be the only change needed.

Let me know if that helps. And all that said, we think the new settings are better in almost all cases!

**Comment by jarrodscott** [comment]
Hi @benjjneb 
First thanks for the detailed and insightful response. and I totally understand the difficulty of maintaining perfect fidelity across code and methodological changes. For me the most important bit of info was whether it was possible or not. I played around with it and got it pretty dang close, esp. with your suggestions plus `allowOneOff=TRUE` in  `removeBimeraDenovo`.

That said, all this digging around in the code base got me excited about whats happened since v1.4. The data is looking much better and I will probably reprocess everything anyway :)

Thanks again
Jarrod
