### ISSUE TITLE
variable-length ambiguity pad

### ISSUE THREAD

**Issue by Perugolate** [benjjneb/dada2#540]
How would having a variable-length N pad affect the pipeline? (I'm guessing badly)
e.g. using the following primers:

linker-N-primer
linker-NN-primer
linker-NNN-primer
linker-NNNN-primer

The ambiguities would be trimmed off but the individual samples would differ in length according to the number of ambiguities used in their primer.

**Comment by benjjneb** [comment]
> The ambiguities would be trimmed off but the **individual samples would differ in length** according to the number of ambiguities used in their primer.

Yes, if the sequence variants inferred from sample 1 are a different length than those in sample 2, they will not be collapsed together appropriately by `makeSequenceTable`.

But, good news!, the `collapseNoMismatch` function is intended to solve this situation. After you make the sequence table, run `collapseNoMismatch` on it, and it should collapse together sequences that are identical up to length variation.

**Comment by Perugolate** [comment]
Can you see any problem in using primers that comprise a mixture of different ambiguity lengths?
i.e. we order the primers above and combine them (rather than having ambiguity length vary across samples)

**Comment by benjjneb** [comment]
> Can you see any problem in using primers that comprise a mixture of different ambiguity lengths?
i.e. we order the primers above and combine them (rather than having ambiguity length vary across samples)

In this situation I highly recommend using an external program like cutadapt to remove the variable length primers and trim the reads to a consistent starting position prior to processing with DADA2. The `trimLeft` solution for fixed length primers won't get your the reads w/ variable length primers to the same starting position, which will reduce sensitivity to infrequent variants.
