### ISSUE TITLE
Increased Spurious ASVs in Deep Sequencing of Low Diversity Samples?

### ISSUE THREAD

**Issue by dcat4** [benjjneb/dada2#546]
Hi there, 

We've been analyzing a batch of 18S mock communities using DADA2. We put the mock communities together by mixing 22 unique, cloned, full-length 18S amplicons (Sanger sequenced before mixing) in known proportions. We then amplified a smaller hypervariable region with a standard dual-indexing PCR and clean-up protocol and sequenced on an Illumina MiSeq. Each separate mock community was amplified and sequenced in technical triplicates. After processing with DADA2, we found 22 ASVs that exactly matched the full-length Sanger sequences of our 22 target ASVs in all mock communities and almost all technical replicates. However, across all the mock communities, we also found 78 ASVs that were > 97% similar to at least one of our 22 target ASVs. All of these "non-target" ASVs were at extremely low read abundance (< 200) and low relative read abundance in each sample (< 1e-4), and most were found in only one technical replicate of a single mock community. Since we used cloned amplicons rather than genomic DNA, I wouldn't think there would be much variation in the sequence identity of the 22 target ASVs.

My question is then, is it reasonable to suspect we're detecting so many of these spurious/non-target ASVs because we're deeply sequencing (36,000 to >200,000 reads per technical replicate passed through DADA2 for these samples) nearly 30 replicates of the same 22 ASVs on the same MiSeq run? My understanding is that ASV inference is partially dependent on absolute read abundance, and I'd expect the odds of producing a PCR/sequencing artifact at high read abundance increases pretty quickly when you sequence the same 22 ASVs that many times. If that seems like the culprit, do you have any recommendations for parameter values we could change (maybe Omega_A?) to help mitigate this problem? 

Any advice would be much appreciated!

**Comment by benjjneb** [comment]
Most commonly inflation in detected variants over the expected number in mocks is due to contamination, sometimes also unrecognized intragenomic variation. From what you describe in your first paragraph it seems you have at least some evidence that this is not the case, but I would still keep this as a strong possibility.

Another possibility is that these are undetected chimeras.

> My question is then, is it reasonable to suspect we're detecting so many of these spurious/non-target ASVs because we're deeply sequencing (36,000 to >200,000 reads per technical replicate passed through DADA2 for these samples) nearly 30 replicates of the same 22 ASVs on the same MiSeq run? 

This is reasonable. The phenomenon here is that false positives due to model misspecification are more likely as sequencing depth increases. One thing i have seen is that a single sample might contribute most (or all) of such FPs, perhaps because the PCR step for that sample was wonky or different.

> do you have any recommendations for parameter values we could change (maybe Omega_A?) to help mitigate this problem?

First, I would interrogate the `dada$clustering` data.frame entries corresponding to the FPs. This has a fair amount of diagnostic information that will be very useful in identifying potential issues. Second, I would systematically determine the number of technical replicates in which each non-target ASV appeared. Are they all in just a few?

There are several approaches that can then be taken to mitigate such FPs. Increasing the stringency of `OMEGA_A` is one. The `MIN_FOLD` approach is another (see `?setDadaOpt`). A simple minimum abundance screen can work. Finally, I might consider inflating the fitted error model, as this is a way to prevent model-misspecification based FPs at any read depth (e.g. `err2 <- inflateErr(err, 2)`).

**Comment by dcat4** [comment]
Thanks so much for the quick and detailed response. I really appreciate the work you all put into making dada2 easy to use and troubleshoot. 

It appears you're correct about a single wonky PCR - a single technical replicate was responsible for 52 of the FP's. We'll keep your other recommendations in mind as we parse apart what's going on with the remaining FPs/contaminants. Thanks again!

**Comment by serine** [comment]
@benjjneb have a couple of additional questions, and this is the closest thread, so I figured it's best to re-open this one, rather then opening new issue.

I'm working with soil data set, libraries were generated as per (earch microbiome protocol)[http://www.earthmicrobiome.org/protocols-and-standards/16s/], although I don't actually have much info about library preps, PCR and sequencing. I know that it was MiSeq 2X300, but this is mainly learning from the data. I can `grep` for these adaptors in my fastqs

- FWD: GTGCCAGCMGCCGCGGTAA
- REV:  GGACTACHVGGGTWTCTAAT

This is extremely deep sequenced data, e.g

```
Poly-12  800414
Poly-11    621375
P10-T1-D1   337010
P12-T1-D2   333764
P10-T1-D2   321432
C1-T1-D2   311071
```

In short summary there are three conditions:

- `C` control
- `P` treatment
- `Poly` blank (different kind of control I guess) 

I've tried various ways to analyse this data. For example I've tried `truncQ` 13 vs 2, filtering with `seqtk trim` and taking a sample from the data

``` 
for i in ../v4_treat/*.gz; do seqtk sample -s 123 $i 100000 | gzip - > $(basename $i)&done
```

1. Do you have a sense whether 6000-8000 ASVs is a sensible number for microbiome diversity of the soil? 

so far I've looked at 3-5 various gut microbiome data and all have around 3000-3500 ASVs and so to me anything bigger then that seem to big.

```
+> readRDS("data_cntrl_sample/seqtab.rds") %>% dim
[1]   12 6461
+> readRDS("data_cntrl_sample/seqtab_nochim.rds") %>% dim
[1]   12 5863
+> readRDS("data_cntrl/seqtab.rds") %>% dim
[1]   12 8247
+> readRDS("data_cntrl/seqtab_nochim.rds") %>% dim
[1]   12 7458
+> 
```

2. Should I split my data into control and treatment groups for ASVs detection? 

Above I've shown ASV numbers when I do split into control and treatment, if I keep all samples together and run through [bigdata workflow](https://benjjneb.github.io/dada2/bigdata_paired.html) I get these numbers

```
+> readRDS("data_v4/seqtab.rds") %>% dim
[1]    48 20980
+> readRDS("data_v4/seqtab_nochim.rds") %>% dim
[1]    48 16794
``` 

I have a funny suspicion that there is something up with errors, either with error modelling or quality filtering the data. Basically I don't fully understand these settings

- `OMEGA_C`
- `OMEGA_A`
- `maxEE` 
- `truncQ`
- `maxQ`

I've tried running tuning `maxEE` down to `c(1,1)`, which reduces number of ASVs (as expected I guess) but only by a handful of ASVs. 

I've calculated EE's for some of my samples, shown below. Table is sorted on `min` column. Some samples have particular low EE and other much larger. I'm not too sure what that means and even if this is a useful information, just attempting to figure out what are EEs.  

```
min     max     mean    median
0.007582466683508604    25.376491903242513      1.0654018811665324      0.25489642851411076
0.00852888398163345     24.54626091413149       1.014005710035999       0.23575807527396603
0.008744499622325734    23.56008230821845       1.1877417597967805      0.3546207138753441
0.009002477361252023    22.083507056806784      1.269831433714665       0.3887910433340519
0.011296612559423805    22.85146649323078       1.001014530888708       0.21996776636317578
0.011740458151281847    25.226615392135965      1.018558089405674       0.23111820543141903
0.012611476487730054    25.238851072668748      1.3649389860129177      0.4538428940291807
0.012753427845486293    24.715945631415885      0.9510466821484247      0.21544191389270642
0.012767809561503076    22.37161890781862       1.3016184246065754      0.38479392070193835
0.012767809561503076    22.083507056806784      1.1064811271036383      0.2844538912801049
0.012767809561503076    28.327471363244204      1.3107668882074364      0.4151284075163132
0.014076761027722746    22.083507056806784      1.1086632042293376      0.26921897721316124
0.01684632038270655     24.36506954528173       1.037213415466651       0.24431521889593533
0.017519678214713195    22.083507056806784      0.9546431487140348      0.21482910419698226
0.01829645901781627     28.057925447558272      1.0106889981380842      0.2416245643150746
0.01838783838663132     22.083507056806784      1.0417875440856936      0.25675448621009916
0.018397009559618507    24.320347550972155      1.0059538766794616      0.2355566565600435
0.019365633826264484    22.16232861668771       1.2754935508183929      0.3931545149171715
0.020972930287366773    23.507994254380737      1.51701422343911        0.5674238563475302
0.02232818696765856     22.083507056806784      1.9202237537947169      0.9851906490869845
0.023443914692403554    26.36895836132371       1.541104201526153       0.5882502524592065
0.027466240527134044    24.796843308873157      1.2683555619315585      0.4225953717880908
0.02775775402206691     22.831163208537923      1.082188359433929       0.28342031591092953
```

I think what I really need to tweak is `OMEGA` A and C. My understanding is that `OMEGA_A` controls when new ASV will get formed. So in my case to attempt to reduce total number of ASVs I should make `OMEGA_A` larger, but how large?  In [this the issue 315](https://github.com/benjjneb/dada2/issues/315) you point to your paper and suggest to make a p-values histogram. I think it's this table that has all the info right?

```  
sequence                             abundance    n0    n1  nunq  pval birth_type birth_pval birth_fold birth_ham birth_qave
   <chr>                                    <int> <int> <int> <int> <dbl> <fct>           <dbl>      <dbl>     <int>      <dbl>
 1 GTAGGGGGCAAGCGTTGTCCGGAATCACTGGGCGT…      1535 17662  2888  2242     0 I                  NA  NA               NA       NA  
 2 CAGCACCCCGAGTGGTCGGGACGTTTATTGGGCCT…      2250 15513  2132  1556     0 A                   0   9.55e185        66       36.9
 3 GTAGGGCGCAAGCGTTATCCGGAATTATTGGGCGT…       757 12577  1786  1494     0 A                   0   2.19e131        48       37.1
 4 AGAGGTCTCAAGCGTTGTTCGGATTCATTGGGCGT…      2749 12036  1683  1402     0 A                   0   4.73e128        47       36.9
 5 GGAGGGGGCTAGCGTTGTTCGGAATTACTGGGCGT…      1216 11486  1777  1543     0 A                   0   5.20e118        44       37.0
 6 GTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGT…       913 11034  1843  1646     0 A                   0   4.32e 99        37       37.1
 7 GTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGT…      1050 10252  1658  1519     0 A                   0   1.59e 17         7       36.3
 8 GTAGGGGGCTAGCGTTGTCCGGATTTATTGGGCGT…       636  7298  1045  1002     0 A                   0   1.65e130        47       37.0
 9 CAGCACCCCGAGTGGTCGGGACGTTTATTGGGCCT…       537  7221  1019   870     0 A                   0   3.44e  5         2       36.5
10 GTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGT…       464  5842  1044  1004     0 A                   0   1.71e  7         3       37 
```

I couldn't find any information on the column names and how to use them for diagnostics..? 

what are all the birth columns? 
Does the pvalue column there corresponds to `OMEGA_A` ? and I should plot histogram of those values? 

```
> dadaFs[[1]]$clustering %>% as.data.frame() %>% as_tibble() %>% select(pval) %>% summary
      pval          
 Min.   :0.000e+00  
 1st Qu.:0.000e+00  
 Median :0.000e+00  
 Mean   :3.207e-43  
 3rd Qu.:0.000e+00  
 Max.   :1.834e-39 
```

This is a rather lengthy question (took me a couple of days to write it lol, mainly because I was testing several things out), in short summary any advise will be appreciated ! 

Thanks !

![errors_plt](https://user-images.githubusercontent.com/6700099/64140946-a81e4000-ce49-11e9-9596-bb5ad5034bcf.png)

**Comment by benjjneb** [comment]
@serine Thanks for the detailed post.

Could you repost this as its own issue though? I think it deserves it, and it will prevent me losing track of it, as might happen when its added onto an old closed thread.
