### ISSUE TITLE
Read Filtering 

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#579]
I have been trying to figure out the optimal number of reads to retain after the filtering step. Do the number of reads after filtering impact the number of sequence variants detected? This is analogous to detecting rare variants with increasing sequence depth. However, I recall from a previous issue that allowing erroneous reads (by relaxing MaxEE) does not help in inferring true sequence variants. 

In this case, is there a gain by allowing erroneous reads for sample inference? 

In the current dataset I am working with, I am in a dilemma whether to filter stringently (maxEE=1) or relax maxEE to allow more reads (with increased compute time). I am trying to figure out if there is any gain to be had by allowing these erroneous reads, given the substantial increase in compute time

**Comment by benjjneb** [comment]
> Do the number of reads after filtering impact the number of sequence variants detected?

The detection of rare variants is dominated by the number of error-free reads, not the total number of reads.

> In this case, is there a gain by allowing erroneous reads for sample inference?

Not really. Not every sequences with EE > 1 is erroneous, so there is some gain there, but there is really no gain from reads that are guaranteed to be erroneous.

> In the current dataset I am working with, I am in a dilemma whether to filter stringently (maxEE=1) or relax maxEE to allow more reads (with increased compute time). I am trying to figure out if there is any gain to be had by allowing these erroneous reads, given the substantial increase in compute time

Our default is to go up to `maxEE=2` because there are usually still a good chunk of error-free reads in that range, but in practice I almost never go higher than that as the number of error-free reads with quality scores indicating more than 2 expected errors is quite low.

**Comment by adityabandla** [comment]
Thanks Ben!

Is there a way to get the number of reads that were error-free/uncorrected post the denoising step?

**Comment by benjjneb** [comment]
Yes, you can track that back through the derep-class object:

```
# 1 sample
drp <- derepFastq(fn)
dd <- dada(drp, err=err)
n.error.free <- sum(drp$unique[dd$sequence])
```

Basically, the above sums the abundances of the denoised sequences (assumed error-free here) in the initial file that was read in by `derepFastq`.

**Comment by adityabandla** [comment]
Thank you Ben!
