### ISSUE TITLE
Question about DADA2's Error Model Between Runs

### ISSUE THREAD

**Issue by compbiolover** [benjjneb/dada2#589]
Hi everyone,
My lab and I have performed 2 separate MiSeq runs and have been using DADA2 for our 16s analysis.  I am curious if analyzing all of the samples (one run contained 16 samples as a test pilot and the other contained 96 samples) from the two runs together at the same time with DADA2 could cause any problems. For example, does the error model generated by DADA2 change substantially between runs on the same MiSeq instrument? Could the samples from each run generate cross-talk that could impact downstream analysis or accurate identification of ASVs? Could it be impacting results in some other way that I haven't even thought of yet? Thanks so much for your help!

**Comment by benjjneb** [comment]
> does the error model generated by DADA2 change substantially between runs on the same MiSeq instrument?

Typically, no. Was your PCR protocol also identical though? PCR is another significant source of amplicon sequencing errors.

> Could the samples from each run generate cross-talk that could impact downstream analysis or accurate identification of ASVs?

Yes, this has been observed to happen. How much this affects your data depends greatly on specifics of your sequencing protocol and library preparations, so I can't give you hard and fast guidance on whether it would be a big concern for your experiment. One practice to reduce this is to cycle through barcodes, so that the same barcodes aren't used on consecutive runs.
