### ISSUE TITLE
dada2  filetrandtrim cammand parameters

### ISSUE THREAD

**Issue by amitpande74** [benjjneb/dada2#598]
Hi Ben,
I loose a lot of reads when I use this command-
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(200,160), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE) and as a consequence the merging does not produce too many contigs.

The situation with the data is as follows-
V1-V3 on the primer spreadsheet says 27F and 619R. So looking at the expected region to be sequenced  would be 592 bps (619-27). 
That would include the primers which were cut being 17 and 21 bps, so 592-38 = 554 should be what we'd expect the median or so length to be of the full fragment. 
The read sizes after trimming the primers and barcodes are about 270 for forward and 280 for reverse. At just touching these, with no overlap, this would be only 550. 

Could you kindly help me with what should be the parameter for minimum length ?

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(200,160), maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE,  minLen=_______________)

**Comment by benjjneb** [comment]
You're forward and reverse truncation lengths should add up to the length of the *sequenced* amplicon plus another 20 nucleotides.

Are you sure you are sequencing your primers? In most V1-V3 setups people don't otherwise the F/R reads barely or don't overlap in some cases.

If you are not sequencing your primers, you still have very little room to truncate because the V1-V3 amplicon is so long. So you can perhaps cut 20nts off the end of the R read, and that's it.
