### ISSUE TITLE
NA values in denoised mapping

### ISSUE THREAD

**Issue by Puumanamana** [benjjneb/dada2#629]
Hi,

I am using dada2 for denoising reads only in my work. To this end, I follow the pipeline you recommend (`filterAndTrim`, `learnErrors`, `derepFastq` and `dada`). Then, I remap the denoised reads to the replicated, filtered reads. However, I have a small issue regarding the mappings between steps:
  - Everything is fine to go from **dereplicated reads** to **replicated filtered reads**
  - However, to go from **denoised reads** to **dereplicated reads**, I noticed some NA values were present in denoised$map (where denoised in the output of the `dada()` command).

Do you know where it could come from? Should I be worried or does it correspond (for some reason) to bad reads to discard? In the test dataset I am using, denoised$map contains about 10% NAs.

Thank you!

**Comment by benjjneb** [comment]
From `?setDadaOpt`:

> OMEGA_C: The threshold at which unique sequences inferred to contain errors are corrected in the final output. The probability that each unique sequence is generated at its observed abundance from the center of its final partition is evaluated, and compared to OMEGA_C. If that probability is >= OMEGA_C, it is "corrected", i.e. replaced by the partition center sequence. The special value of 0 corresponds to correcting all input sequences, and any value > 1 corresponds to performing no correction on sequences found to contain errors. Default is 1e-40 (same as OMEGA_A).

The `NA`s you are seeing in the mapping file are sequences that were removed rather than corrected, due to the low confidence (below `OMEGA_C`) in correcting them to the best possible match.

10% is higher than average in my experience, but is not that unusual. You may be able to reduce uncorrected reads by trimming off low quality read tails, if that is an option. You can also force the algorithm to correct everything with `OMEGA_C=0`.

**Comment by Puumanamana** [comment]
Thank you for the explanation, that was exactly it. I changed the OMEGA_C and it removed all the NA values.

Have a good day,
Cédric
