### ISSUE TITLE
dada is running on single thread

### ISSUE THREAD

**Issue by lmanchon** [benjjneb/dada2#634]
--Hi,

I have run this command below on 80 demultiplexed paired-end files:

qiime dada2 denoise-paired \
 --i-demultiplexed-seqs trimmed-demux-paired-end.qza \
 --p-trim-left-f 25 \
 --p-trim-left-r 25 \
 --p-trunc-len-f 120 \
 --p-trunc-len-r 100 \
 --p-n-reads-learn 200000 \
 --o-representative-sequences rep-seqs-dada2.qza \
 --o-table table-dada2.qza \
 --o-denoising-stats stats-dada2.qza \
 --p-n-threads 12

Filtered step use correctly 12 threads, but after in top command, i see that R use only 1 thread and it is very slow.

is there any problem ?

thank you --

**Comment by benjjneb** [comment]
First off, I suspect that 

> --p-trunc-len-f 120 
> --p-trunc-len-r 100 

is going to be too short for anything to merge. What gene region (amplicon) are you working with here? You need to keep you truncation lengths long enough that the reads still overlap.

> Filtered step use correctly 12 threads, but after in top command, i see that R use only 1 thread and it is very slow.

It is a lot harder to diagnose the Q2 plugin than the R package due to the lower flexibility. Would you consider running your data through the R package? Bonus: It is 2-10x faster because it isn't hurt by the bioconda compile penalty.
