### ISSUE TITLE
Different number of inferred forward reads and inferred reverse reads after sample inference

### ISSUE THREAD

**Issue by misazaa** [benjjneb/dada2#644]
Hi,

I'm using DADA2 to process some reads (MiSeq 2x290) from the V3-V4 region of the 16S of plant microbiome. I follow the DADA2 pipeline tutorial (1.8) and notice that the number of inferred forward reads are equal to the number of inferred reverse reads and that is the case in all of the tutorials I've seen. But when I use my data, the number of inferred forward reads differ from the number of inferred reverse reads in all the samples. So I was wondering why is that?

I know this maybe a dumb question but I need to know if this is normal or should I change some parameters early

Thanks in advance!

This is the code I run until the step of sample inference:
# Quality filtering and trimming
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs,
                     trimLeft=c(17,21), truncLen=c(290, 205), 
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, verbose=TRUE)
# Error rate estimation
errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
# Dereplicate reads
derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)
# Sample inference
dadaFs <- dada(derepFs, err=errF, multithread=TRUE,  pool = TRUE)
dadaRs <- dada(derepRs, err=errR, multithread=TRUE,  pool = TRUE)

**Comment by benjjneb** [comment]
> But when I use my data, the number of inferred forward reads differ from the number of inferred reverse reads in all the samples. So I was wondering why is that?

Can you clarify what you mean here, i.e. what output are you seeing that says this to you?
Can you post the command/output for at least one sample that shows this?

**Comment by benjjneb** [comment]
The minor differences in the number of F and R reads being denoised is due to the algorithm removing some reads that it has insufficient confidence to correct to an inferred true sequence. The number of such uncorrected reads will vary a bit between the F/R reads due to normal stochastic factors.

This is a newer behavior, prior to version 1.8 of the R package all reads were corrected, but in the current version 1.8 of the tutorial, you do see that there are some differences in the denoisedF/R counts: https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline

You can read a bit more about the modifiable error-correction intrduced in version 1.8 in the 1.8 release notes: https://benjjneb.github.io/dada2/ReleaseNotes_1_8.html

See the part about the `OMEGA_C` parameter.

**Comment by misazaa** [comment]
Thank you so much!
