### ISSUE TITLE
Stuck with R version 3.3.1 -- which dada2 version to use?

### ISSUE THREAD

**Issue by claireonthecouch** [benjjneb/dada2#646]
I'm using a linux machine to process a large microbiome dataset, and I'm limited to using R version 3.3.1 because due to some infrastructure limitations, the people who manage the server are unable to install a more recent version. Which version of dada2 should I use under R version 3.3.1?

**Comment by claireonthecouch** [comment]
Also, where can I find archived versions of dada2?

**Comment by benjjneb** [comment]
You can download/install all release versions of dada2 from the GitHub Releases page: https://github.com/benjjneb/dada2/releases

It's particularly easy with the devtools package. E.g. to install version 1.6: `devtools::install_github("benjjnen/dada2", ref="v1.6")`

I stopped testing on R 3.3 with version 1.6, so that might be one to try. I suspect you would be OK using even the most current version though (except if doing PacBio data, which needs more updated versions of the ShortRead/Biostrings packages).
