### ISSUE TITLE
Trimming reverse reads

### ISSUE THREAD

**Issue by aquaticgutseq** [benjjneb/dada2#650]
Hello,

I have used the 515fB and 806rB primers to amplify the SSU and am using dada2 to process the reads. 
I have trimmed the forward and reverse reads to 240 and 160 bp respectively and used the recommended quality parameters. The forwards look absolutely fine but there are some early dips in quality of the reverse reads. These occur at the same place in 150+ samples. 
I used a custom index approach where the primers aren't sequenced. 

![rev_filt](https://user-images.githubusercontent.com/46526087/50898910-7bc03a00-1408-11e9-8955-104cfa0f9191.png)

Do you have any recommendations when dealing with an issue like this?
Is it possible to use trimLeft parameter on the reverse reads alone?

Thanks for your help!

**Comment by benjjneb** [comment]
This isn't terribly uncommon (although less so these days then a couple years ago). You can probably just process your data as usual. DADA2 is including the quality scores in its error model, so it is typically pretty robust to short stretches of lower quality.

> Is it possible to use trimLeft parameter on the reverse reads alone?

Not recommended because then you are changing where your final ASVs terminates, which will make them harder to compare to other datasets using the same primers. If you have to though, you could just use your forward reads, especially since the forward reads essentially capture this entire amplicon which is 252-256 bps.

**Comment by aquaticgutseq** [comment]
Thank you for your reply! 

I continued processing the data and it looked fine. I just wanted to double check.
I'll take a look at the forward reads alone and compare.
