### ISSUE TITLE
filterAndTrim. sample names swapped with wrong seq data

### ISSUE THREAD

**Issue by lara-whoi** [benjjneb/dada2#673]
I had processed a set of 40 samples (16S sequenced with IT) and once I was analyzing the results I realized something was amiss. Somehow the sample names were associated with the wrong sequences – i.e. dataset matched with wrong sample name. 

 I retraced the workflow and the mix up occurred when I ran filterAndTrim because READ NUMBERS were correct for all QUALITY plots – (all ***_trimmed.fq.qz files labeled correctly)
But afterfilterAndTrim – reads mismatched with sample names.  
(When I plotted filtered quality plots – read numbers didn’t match with the correct sample name).

I am confused as to how sample names could get scrambled in filterAndTrim.  Do you have any suggestions? 

thanks again

**Comment by benjjneb** [comment]
I don't really follow. The read numbers should change after running `filterAndTrim` because it will remove some of the reads from each sample that don't pass the filters.

File names could be messed up if your names of the filtered files you give to `filterAndTrim` are wrong though. Did you check to see if the `filt` and `filt.rev` filenames you are providing are properly named and in the correct order (i.e. matched order to `fwd` and `rev` unfiltered filenames).

**Comment by lara-whoi** [comment]
Thank you.
 Yes, it looks like there was a mismatch in the order of the names of the filtered files I gave to filterAndTrim.  Many thanks.  I'm learning to be more conscientious at each step.
