### ISSUE TITLE
version issues? [Update tutorial to Silva v132]

### ISSUE THREAD

**Issue by vhertzb** [benjjneb/dada2#678]
I apologize in advance if this has already been posted as an issue, but I did look and did not see anything equivalent. I also apologize in advance if this should ALSO go on the phyloseq issues page, but the problem stems from the dada2 pipeline.

I have been teaching the dada2 - phyloseq pipeline in my Nursing Analytics class since 2017. In preparation for doing this for the third time in two weeks, I have been updating all of my packages, checking them twice, etc. I guide the students through the dada2 tutorial for the first session, then through phyloseq in the second session.

I first noticed that our bar plots did not agree, although they look similar. I then went up and compared the taxonomy table produced by the dada2 assignTaxonomy and addSpecies functions and compared it to the table produced by the IdTaxa function from the DECIPHER taxa. Just comparing the heads of these tables, they do not agree, but, more importantly, they also don't agree with your results.

I know that when I first started doing this in 2017, our taxonomy tables and graphs agreed, but that was using the RDP classifier and the assignSpecies function from dada2. See [https://htmlpreview.github.io/?https://github.com/vhertzb/Lesson11/blob/master/Fastq2seqtab.html](https://htmlpreview.github.io/?https://github.com/vhertzb/Lesson11/blob/master/Fastq2seqtab.html)

I looked then at my 2018 version, and was startled to see that there were a lot of occurrences of Muribaculaceae NA NA. I didn't recall that, but it must be so, because the repo was last modified in 2018. See [https://htmlpreview.github.io/?https://github.com/vhertzb/2018Week7/blob/master/2018Week7_dada2.html](https://htmlpreview.github.io/?https://github.com/vhertzb/2018Week7/blob/master/2018Week7_dada2.html)
I'm not smart enough to get back to your dada2 tutorial from early 2018 to see if it was similarly finding the Muribaculaceae.

In my 2019 version I do the taxonomy assignment the "old" way (with the dada2 functions) and again see a lot of Muribaculaceae NA NA. But then I do it with IdTaxa and get a lot of Bacteroidales NA NA. On the other hand, in the tutorial you are finding a lot of Bacteroidales S24-7 group NA NA. This is the major difference between the bar plots that we display at the ends of our pages. For my 2019 version, please see [https://htmlpreview.github.io/?https://github.com/vhertzb/dada2-lesson/blob/master/dada2_workflow_as_per_Ben.html](https://htmlpreview.github.io/?https://github.com/vhertzb/dada2-lesson/blob/master/dada2_workflow_as_per_Ben.html)

I am HOPING this is just my stupid mistake and not something happening with versioning. I am running R 3.5.2,  dada2 v 1.10.1, DECIPHER 2.10.2, BioConductor 3.8, and phyloseq 1.26.1. I believe that the tutorial is running dada2 v 1.9.1, DECIPHER v 2.6.0, and phyloseq 1.25.2. I.e., I am running more recent versions than the tutorial.

Do you have any idea what is going on with this?

Thanks!
Vicki

**Comment by benjjneb** [comment]
Typically changes like this are seen due to changes in the reference database, which has the biggest effect on taxonomic assignments. For example, going from Silva v128 to Silva v132 involved a number of important renamings of taxa, especially in [the proteobacteria](https://www.arb-silva.de/documentation/release-132/): "Proteobacteria drastically rearranged. Epsilonproteobacteria are own phylum, Betaproteobacteria now an order of Gammaproteobacteria."

Could differences in the reference database versions could be causing your observation?

Another thing to consider is that there is an element of randomness to `assignTaxonomy` because it uses bootstrapping and kmer subsampling to generate confidence intervals. However, this doesn't usually cause name switches like you are describing. That sounds like a reference db change.

**Comment by vhertzb** [comment]
Thanks, Ben.

I went from RDP in 2017 (and my results agreed with yours) to Silva 132 in 2018 to the Silva 132 SSU in 2019 for using DECIPHER's IdTaxa function. I could understand that these changes in the reference database could cause the observation, but I don't understand why my 2019 results using the Silva 132 SSU don't agree with yours, why you have Bacteroidales Bacteroidales S24-7 group NA NA for 5 of the first 6 ASVs while I get Bacteroidales NA NA NA for the same ASVs that should be the same sequences.

When will you be updating the tutorial to run dada2 v1.10.1, DECIPHER 2.10.2, and phyloseq v 1.26.1? At least I will be able to see what version differences are doing.

**Comment by benjjneb** [comment]
>I went from RDP in 2017 (and my results agreed with yours) to Silva 132 in 2018 to the Silva 132 SSU in 2019 for using DECIPHER's IdTaxa function.

One thing that is important to note here is that it's not clear how closely the curation involved in the Silva databases formatted for assignTaxonomy and for IdTaxa agree. On our end, we have followed the [mothur team's curation of the sequences from the full Silva database](http://blog.mothur.org/2018/01/10/SILVA-v132-reference-files/), but I believe the DECIPHER team have performed their own curation.

My guess it that this is causing the issue you are observing, probably because one curation procedure of the other rejecting/accepting taxonomic groups close to Bacteroidales S24-7.

*Aside* Suggesting that is the case, it is not very satisfying, but it also speaks to the issues associated with reference taxonomic classification because of the changing nature of our taxonomies!

**Comment by vhertzb** [comment]
I downloaded the Silva 132 files (pre DECIPHER) from your zenoto site, so presumably I'm working with the same thing that you are, and maybe the problem is the just the randomness of assignTaxonomy, that I could understand. 

But then where can I download SILVA_SSU_r132_March2018.RData from, which is what DECIPHER uses, and what you are using. I downloaded something from the DECIPHER page that had that same name, but if it is not that, I'm at a loss.

Trying to be independent here. ;-)

**Comment by vhertzb** [comment]
Leaving DECIPHER aside, my other frustration was the differences in the bar plot. You are showing a lot of Bacteroidales S24-7 group, and I am showing a lot of Muribaculaceae. I found this reference (https://msystems.asm.org/content/3/6/e00262-18). If I am reading it correctly, S24-7 is the old name and now it is just an unknown genus of the family Muribaculaceae. I am now satisfied that we are not too different, you are just behind the times. :-)

**Comment by benjjneb** [comment]
> I am now satisfied that we are not too different, you are just behind the times. :-)

That sounds about right. Note to self, time to move the tutorial to Silva v132!

**Comment by vhertzb** [comment]
Silva 132 does not even contain the string "S24-7".

And my apologies - I thought the tutorial *was* using Silva 132, but now I see it was not. I guess I thought that because you had made it available you were using it, but, had I read your code more closely, I could have seen that you were not. 

While you are updating the tutorial to SILVA 132, can you please also update the dada2, DECIPHER, and phyloseq package versions?
