### ISSUE TITLE
addSpecies() error if assignTaxonomy() was run with outputBootstraps=TRUE

### ISSUE THREAD

**Issue by roey-angel** [benjjneb/dada2#690]
This is because `getUniques()` fails to run and gives the following error:
```
Error in getUniques(object, collapse = collapse, silence = silence) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.
```
But running `assignTaxonomy()` with `outputBootstraps=FALSE` and then `addSpecies()` works (eventhough `getUniques()` would still fail)

**Comment by roey-angel** [comment]
OK this is of course because `outputBootstraps=TRUE` produces a list so `addSpecies()` needs to be run on `taxa[[1]]` rather than `taxa`

**Comment by pdcountway** [comment]
> 
> 
> OK this is of course because `outputBootstraps=TRUE` produces a list so `addSpecies()` needs to be run on `taxa[[1]]` rather than `taxa`

Hi - I've hit this same problem in a batch processing script where I'd like to run assignTaxonomy then addSpecies and write an output *.csv file. Would you mind explaining what `taxa[[1]]` is?

**Comment by benjjneb** [comment]
When `outputBootstraps=TRUE` the return value of `assignTaxonomy` is a two element list. The first element (`taxa[[1]]`) is the usual taxonomy matrix, which is acceptable input to `addSpecies`. The second element (`taxa[[2]]`) is a numeric matrix of the bootstrap values at each taxonomic level.

So, if you want to run `addSpecies`, you should run it on `taxa[[1]]`, the normal taxonomy table. I'm not sure what you are wanting to do with the bootstrap value matrix, but remember that it won't have a species column, since `addSpecies` doesn't use boostrapping.
