### ISSUE TITLE
DECIPHER IdTaxa: Classified to the Genus level but not higher level (sometimes)

### ISSUE THREAD

**Issue by jgrzadziel** [benjjneb/dada2#697]
![decipher](https://user-images.githubusercontent.com/35599811/53799714-526ce780-3f3b-11e9-9830-d2b63f7d3ec2.jpg)

As above,
There are few taxa, succesfully classified to the Genus level, but higher levels (Family, Order) remain unclassified. This is unusal, since using the RDP classifier instead of DECIPHER I have never noticed such problems. 

The code I have used:

```
dna <- DNAStringSet(getSequences(OTU1), use.names = T) # Create a DNAStringSet from the ASVs

ids <- IdTaxa(dna, trainingSet, strand="top", processors=20, verbose=FALSE) # use 20 processors
ranks <- c("domain", "phylum", "class", "order", "family", "genus", "species") # ranks of interest

taxid <- t(sapply(ids, function(x) {
  m <- match(ranks, x$rank)
  taxa <- x$taxon[m]
  taxa[startsWith(taxa, "unclassified_")] <- NA
  taxa
}))
```
Database: 

> RDP_v16-mod_March2018.RData

I belive, that it comes from inconsistency of database (for example, when the same Genus belong to different higher taxonomy levels), but as I said, the RDP classifier (using the ~ same ~ database) had no such issues.

**Comment by benjjneb** [comment]
Let me ask @digitalwright to take a look at this, as he is the creator of the DECIPHER package that implements `IdTaxa`.

Also: @digitalwright how would you like us to direct questions we get on DECIPHER taxonomic assignments? Is pinging your username OK, or should we point people to a different forum?

**Comment by digitalwright** [comment]
This is expected behavior. If you look at these two groups in the RDP taxonomy, they do not have names at these rank levels. _Chryseolinea_ is not part of a named family, and _Gp16_ is not part of a named order or family. In such cases the result is **NA**.

From [the RDP website](http://rdp.cme.msu.edu):
<img width="460" alt="chryseolinea" src="https://user-images.githubusercontent.com/6781840/53835140-be127d00-3f5a-11e9-94ad-3d19948730a6.png">
<img width="479" alt="gp16" src="https://user-images.githubusercontent.com/6781840/53835150-c23e9a80-3f5a-11e9-81b5-dc6951f5fa56.png">

> Also: @digitalwright how would you like us to direct questions we get on DECIPHER taxonomic assignments? Is pinging your username OK, or should we point people to a different forum?

@benjjneb feel free to continue pinging my name. I also respond when DECIPHER is tagged on the [Bioconductor support forum](https://support.bioconductor.org).

**Comment by jgrzadziel** [comment]
@digitalwright 
@benjjneb 

Thank you for an explanation, now it makes sense...
However it points that there are some shortcomings in the RDP database. The same taxa have upper-level taxonomic assignments in e.g. Silva (v 132) database.

**Comment by digitalwright** [comment]
The RDP database is derived from Bergey's Manual of Determinative Bacteriology, which is the most authoritative reference of microbial taxonomy. In some case they do not define group names at intermediary rank levels. I suspect this is because they made the choice not to simply inherit names from a higher rank level in these cases.
