### ISSUE TITLE
question to suggested filtering by sequence length 

### ISSUE THREAD

**Issue by bernt-matthias** [benjjneb/dada2#704]
I have another question regarding the tutorial. You get the distribution of the sequence lengths (after applying `makeSequenceTable`) as `table(nchar(getSequences(seqtab)))` and suggest to filter with `seqtab2 <- seqtab[,nchar(colnames(seqtab)) %in% seq(250,256)])`. 

I'm wondering if the distribution might be misleading, because the actual counts of the sequences are ignored. Might the following be better (I guess there is a nicer way instead of the two for loops)

```
seqlen<-c()
for( c in 1:ncol(seqtab) ){
    for( r in 1:nrow(seqtab) ){
	seqlen <- c(seqlen, rep(nchar( colnames(seqtab)[c] ), seqtab[ r, c ]))
    }
}
table(seqlen)
```

This is in particular because I was thinking to provide an option to automatize outlier removal in the Galaxy tool, eg, like so:

```
coef <- 1.5  ## configurable
rng <- range( seqlen[ ! seqlen %in% boxplot.stats(seqlen, coef=coef)$out ] )
seqtab <- seqtab[, nchar(colnames(seqtab)) %in% seq(rng[1], rng[2])]
```

which could be plotted as 
```
pdf( 'plot.pdf' )
D <- data.frame(length=seqlen )
ggplot(D) + 
    geom_histogram( aes(x=length), binwidth=1 ) + 
    geom_vline( xintercept=c(rng[1]-0.5, rng[2]+0.5) ) + 
    theme_bw()
bequiet <- dev.off()
```

**Comment by benjjneb** [comment]
> I have another question regarding the tutorial. You get the distribution of the sequence lengths (after applying makeSequenceTable) as table(nchar(getSequences(seqtab))) and suggest to filter with seqtab2 <- seqtab[,nchar(colnames(seqtab)) %in% seq(250,256)]).

To be clear, that filtering length is mostly based off of prior knowledge of the biological length distribution of the V4 region. It is a good sanity check to inspect the distribution you are getting, but the best filter of this sort is to use expert domain knowledge to set the cutoffs. I think the automatic "outlier" removal you are suggesting can be dangerous because it can and often would systematically exclude true taxa that have longer or shorter amplicon lengths than the bulk of the distro.

I agree it can be useful to plot a histogram of sequence lengths weighted by their abundances though. A more compact way to get that table is the following:

```
reads.per.seqlen <- tapply(colSums(seqtab), factor(nchar(getSequences(seqtab))), sum)
```

That gets you the equivalent of a table, and you can use that to plot a histogram using ggplot:

```
df <- data.frame(length=as.numeric(names(reads.per.seqlen)), count=reads.per.seqlen)
ggplot(data=df, aes(x=length, y=count)) + geom_col()
```
