### ISSUE TITLE
ASVs Not Merging

### ISSUE THREAD

**Issue by Philippa36** [benjjneb/dada2#708]
Hi,

I have run into problems after running the pipeline on a large dataset with 33 sequencing runs.

On the finalised ASV table, once we ran filtering taxa in less than 5% samples, we found that there were many samples which were left with 0 ASVs, and that these samples all came from a few particular sequencing runs. Of these sequencing runs, 1 had ony the reverse read available from which to create the ASVs, and the others contained particularly bad quality data where the qual score fluctuated right from the beginning of the read.

I think this caused differences in the resultant ASVs from these plates in terms of ASV length and inferred ASV sequence, and this impaired the final merge step across all of the sequencing tables.

I think the ASV tables from the problematic data are valid, but problems arise after merging and when considering the dataset as a whole.

Aside from removing these sequencing runs from the dataset, (and losing all that data) I'm unsure how we can remedy this.

Grateful for any suggestion!

Thank you

**Comment by benjjneb** [comment]
If trimming at the start of reads or the merging steps are different between runs (for example because only reverse reads are used from one run) then the ASVs will not simply merge, as the sequences in each run won't be identical. For example in Run 1 you might have ACGTACGT while in Run 2 (no FWD read) you have GTACGT from the same underlying biological sequence.

One thing to try is to run `collapseNoMismatch` on the final table, which will collapse together ASVs that differ only by end gaps, i.e. length.

Other possibilities are to drop runs that don't merge, or to convert ASVs to taxonomy and work at that level. There are downsides associated with both those approaches.

**Comment by Philippa36** [comment]
The collapseNoMismatch step worked for one of the plates so that's great!

 It didn't work for the plate where only 1 read was available but that's to be expected and just a shame we dont have the forward read.

Thank you!!
