### ISSUE TITLE
DADA2 1.12 tutorial missing derep section

### ISSUE THREAD

**Issue by mestaki** [benjjneb/dada2#752]
Was playing around with version 1.12 (great update by the way!) and I noticed that in the most recent [tutorial page](https://benjjneb.github.io/dada2/tutorial.html#sample-inference) the section on dereplication is missing. I thought maybe this was a new addition where dereplication is done automatically since `dada` is clearly shown to have been ran on the filtered files:
`dadaFs <- dada(filtFs, err=errF, multithread=TRUE)`
But I couldn't wrap my head around this, especially when the preceeding line still says:
> We are now ready to apply the core sample inference algorithm to the dereplicated data.

So I'm thinking maybe this is just by error?
Also, the library loaded for the tutorial still apears to be '1.11.4' though the main header says 1.12.

**Comment by benjjneb** [comment]
The removal of the derep section was intentional. You can still include that step if you want, but now all functions that accepted `derep-class` objects will also accept a filename to the fastq file, and do the dereplication on the fly. This leads to lower memory costs especially in `dada` calls, as the samples are only loaded into memory one at a time.

> But I couldn't wrap my head around this, especially when the preceeding line still says:
> >We are now ready to apply the core sample inference algorithm to the dereplicated data.

Thanks for pointing this out, we should update the text!

> Also, the library loaded for the tutorial still apears to be '1.11.4' though the main header says 1.12.

1.11.4 is essentially identical to 1.12, but I'll also update the version we run the tutorial in to 1.12 when I fix the text above.

**Comment by mestaki** [comment]
HI @benjjneb ,
That makes sense now, thanks for clarifying!
When you do end up updating the docs, it might be helpful to clarify that in the 1.12 `dada` manual as well, this is actually where I started to doubt myself with regards to derep still happening automatically.

> derep | (Required). A derep-class object, the output of derepFastq. A list of such objects can be provided, in which case each will be denoised with a shared error model.

Thanks again.

**Comment by benjjneb** [comment]
Improved the help text for `dada` here: 8906caef6dcb9a66852bea9bd97532dfe1a21fa2

Will probably push that to the release version sometime in the next week or so along with the bug fixes for `removePrimers`.

**Comment by benjjneb** [comment]
Fixed in release f4423b93ca96990cb6e0d10e067adf37262fcc7f

**Comment by mikemc** [comment]
I would also consider editing the first line of the "Sample Inference" section of the tutorial, "We are now ready to apply the core sample inference algorithm to the dereplicated data.", to reflect the change. E.g., "We are now ready to apply the core sample inference algorithm to the filtered and trimmed data." (Otherwise it feels to the reader like a step from the tutorial is simply missing.)
