### ISSUE TITLE
Nanopore consensus sequencing and DADA2

### ISSUE THREAD

**Issue by alexpiper** [benjjneb/dada2#759]
Hi Ben,

I have been using DADA2 on illumina sequenced COI data for the last year and it has become the backbone of my bioinformatics pipeline. We now have a PhD student in our group developing metabarcoding/marker gene sequencing for fungal plant pathogens. For Fungi i believe it is inevitable that we will need to move to a long read platform, and while PacBio is an option we would prefer to develop something for Nanopore due to platform costs and scalability.

Some recent work on [Microbes ](https://academic.oup.com/gigascience/article/7/12/giy140/5202451) and [cDNA](https://www.pnas.org/content/115/39/9726) has mimicked the PacBio CCS on Nanopore using Gibson assembly to circularize amplicons, followed by rolling circle amplification to generate long concatamers which are then sequenced via nanopore and then bioinformatically chopped up and turned into consensus sequences with an accuracy of ~99.5% for 1D2 nanopore seq.

I have seen your response in #718 to using DADA2 on raw Nanopore Reads. But i am curious on your thoughts on using a concensus approach to generate high quality nanopore amplicons and putting them through a similar pipeline to the DADA2 PacBio workflow?

Regards,
Alex

**Comment by benjjneb** [comment]
Hi Alex,
We are very interested in progress on consensus reads in Nanopore that could achieve the level of accuracy needed for our approach, but for now the accuracy is still to low for Nanopore consensus reads to be used, at least for 1KB+ amplicons.

The simple calculation to determine if DADA2 can be used effectively as-is is to estimate the number of error-free reads in the data. For 16S (~1.5Kb) and a 99.5% error rate, the error-free fraction E will be about E ~ 0.995^1500 ~ exp(-1500 * (0.005)) ~ 0.0005

That's too low to be useful because of the requirement for an error-free representantive to exist to detect true ASVs (in contrast 30-50% of 1.5Kb PacBio CCS reads are error-free using current chemistries). If that error-free fraction gets up to ~10% then we will be in business.

**Comment by alexpiper** [comment]
Hi Ben,
Thanks for your quick and insightful response. I think we will continue exploring consensus methods for Nanopore, but lets hope for some improvements in the underlying error rate (perhaps with the R10 pore) in the near future.

**Comment by mdehollander** [comment]
Would it be possible to process the data from the [Karst et.al. preprint](https://doi.org/10.1101/645903) in Dada2? They used a UMI-barcode filtering approach to get consensus sequences with a mean error rate of 0.03%.

**Comment by benjjneb** [comment]
> Would it be possible to process the data from the Karst et.al. preprint in Dada2? They used a UMI-barcode filtering approach to get consensus sequences with a mean error rate of 0.03%.

In principle, yes. 

Consider it an exploratory application though, as I don't think anyone has critically evaluated DADA2 on such data yet. There are certainly ways that DADA2's default error modeling could make mistakes when applied to new sequencing technologies (e.g. if certain types of systematic errors are present).

**Comment by callumparr** [comment]
Modal accuracy now up to 97% for raw accuracy. With new 10.3 chemistry and new basecallers along with UMI presumably, things have moved on a bit for Nanopore. However, I think Nanopore does seem to have an issue with some systematic error.

**Comment by DenisGoryunov** [comment]
Hi,
The [Karst, S.M., Ziels, R.M., Kirkegaard, R.H. et al](https://www.nature.com/articles/s41592-020-01041-y#Abs1) paper has been published in the Nature Methods in 2021 and i assume it may be considered as the most relaible procedure to generate consensus sequence from ONT reads now. I'm wonderinf if you are planning to implement similar pipeline for ONT reads in DADA2?

**Comment by benjjneb** [comment]
There are no plans at this time to incorporate UMI aggregation and consensus into the DADA2 software itself. We are interested in exploring how DADA2 works with data like that generated by the Karst et al method. Longer term ONT "duplex" sequencing also looks very interesting: https://nanoporetech.com/about-us/news/oxford-nanopore-tech-update-new-duplex-method-q30-nanopore-single-molecule-reads-0

**Comment by DenisGoryunov** [comment]
Hi,
Thanks for your reply. The link you provided is very interesting indeed. Let me ask one more question please? I'll get ONT amplicons without UMIs soon. Can i use DADA2 to process those data?

**Comment by benjjneb** [comment]
> I'll get ONT amplicons without UMIs soon. Can i use DADA2 to process those data?

No, current ONT data has too-high an error rate for the DADA2 approach to be valid. Specifically, DADA2 assumes that a non-trivial fraction of the reads are error-free, and that will not be the case with current ONT error rates and 1k+ nt reads.

**Comment by julibeg** [comment]
Very interesting thread!

I got a stupid / crazy question: since DADA2 needs 10+% of correct sequences, would it be possible to simply run it on k-mers for short amplicons? I.e. get the 10-mers of a 300bp amplicon (they should be somewhat unique if there are no repeats in the amplicon), denoise them with DADA2, and then cluster the reads based on the 10-mer presence / absence matrix. Can't decide whether that might be feasible or just a brain fart.

**Comment by benjjneb** [comment]
@julibeg I see the idea. My first reaction is skepticism it would be effective, especially for minority sequences that would need to many if not most of their kmers to be properly identified (DADA2 by default won't identify sequences/kmers with abundance < 2 in the data).

To me it seems like clustering on the full sequences would be more straightforward and as or more effective for anything but the most abundance sequences in the data.

**Comment by julibeg** [comment]
Thanks for the reply and I see your points. Actually, I am not coming from a 16S / microbiome angle but would have a somewhat different use case: A colleague did some nanopore amplicon sequencing and it looks like there might be multiple clones present in the samples (but only a relatively small number; let's say not more than 5). Now they asked me for ideas on how to disentangle the sequences and get the consensus for the clones (or at least the majority ones). This is how I found this issue. Maybe I'll give k-mer denoising a go.

**Comment by marcomeola** [comment]
Would like to pick up the discussion again in view of recent advances and ask whether reads basecalled with dorado-duplex on a R10.4.1 with SUP basecalling could be eligible for dada2?

**Comment by cliffbueno** [comment]
Hi - interesting discussion here! I'm also curious about using DADA2 for some MinION 16S data and came across this thread. We have 390 bp V4 amplicons and SUP basecalling. According to the Q23 calculation for that instead of the full length 1500, it would be (1-10^(-23/10))^390 = ~14%.

Are there any other concerns or considerations besides the error-free fraction? Error modeling? We always check the error plots in any case, so can see if it's too far off.

Thanks for sharing any new thoughts as of November 2024.

**Comment by benjjneb** [comment]
> Are there any other concerns or considerations besides the error-free fraction? Error modeling?

I think ONT has a high rate of homopolymer errors (seems likely given the underlying technology). The homopolymer gap penalty option might be relevant.

> dada(..., HOMOPOLYMER_GAP_PENALTY=-1)

**Comment by hjarnek** [comment]
> I think ONT has a high rate of homopolymer errors (seems likely given the underlying technology). The homopolymer gap penalty option might be relevant.

@benjjneb: As I remember it, the homopolymer error rate was significantly improved with the R10.4.1 flowcells which introduced a second reader head, but nonetheless, it's greater than Illumina. As for DADA2 though, what do you think about adjusting the `GAP_PENALTY` as opposed to the `HOMOPOLYMER_GAP_PENALTY`? I'd assume nanopore sequencing inherently misses and double counts bases much more often than Illumina, not just in homopolymer regions.

**Comment by benjjneb** [comment]
> As for DADA2 though, what do you think about adjusting the GAP_PENALTY as opposed to the HOMOPOLYMER_GAP_PENALTY? I'd assume nanopore sequencing inherently misses and double counts bases much more often than Illumina, not just in homopolymer regions.

This could be a good idea, but I don't have enough practical experience with ONT data to say whether it is a good choice. Is the indel rate higher enough than Illumina to warrant a changed gap penalty? With homopolymer errors in earlier ONT or pyrosequencing, the rate was so much higher that changed gap penalties made for better alignments.

**Comment by hjarnek** [comment]
@benjjneb: Here's a paper looking a bit into error rates of recent ONT: https://doi.org/10.1128/aem.00605-23 (Table 2). Seems like the latest flow cells have an error rate of about half a percent each for insertions and deletions respectively, higher in homopolymer regions, although I can't deduce by how much. What would you recommend for DADA2 settings?

Another question I had was about maxEE filtering. With Illumina, I understand it makes sense not to allow too low-quality sequences, because they are comparatively rare and don't contribute much. With Nanopore however, having lower overall quality scores, and on top of that longer amplicons (if you want to utilize the main advantage of the platform), most of the data will have a really high expected error rate, which I'd guess be completely outside of the Illumina distribution. Do you have any benchmarks or indications on how DADA2 performs with really high maxEE value in the filtering step?

**Comment by benjjneb** [comment]
In our hands, and in consoltation with ONT within the past year, we still don't think the error rate of ONT is low enough that it makes sense to use DADA2/ASV methods with it, at least for amplicons at the 1.5kb+ length of full-length 16S.

> With Nanopore however, having lower overall quality scores, and on top of that longer amplicons (if you want to utilize the main advantage of the platform), most of the data will have a really high expected error rate, which I'd guess be completely outside of the Illumina distribution. Do you have any benchmarks or indications on how DADA2 performs with really high maxEE value in the filtering step?

The DADA2 approach makes a fundamental assumption -- a substantial fraction of the reads contain zero errors. It is those zero-error reads that form the seeds of ASVs and from which ASV sequences are determined. There is never the construction of a "consensus" sequence in DADA2.

Thus, the expected error filtering criterion is somewhat technology independent. If the expected number of error=0 reads is too low, it just doesn't make sense to use DADA2 and a fuzzier approach like similarity-based-clustering (e.g. OTUs) is more appropriate.

**Comment by hjarnek** [comment]
@benjjneb: I see. What would you today say is a reasonable % error-free reads to start using DADA2? I've seen duplex-basecalled and quality-filtered ONT amplicon data reach over Q30 on average. Isn't that the same as PacBio?

**Comment by cliffbueno** [comment]
Hi @hjarnek, if you read through the above discussion, there was discussion of a minimum of 10%, as well as how to calculate it from the amplicon length and the Q score.

**Comment by hjarnek** [comment]
@cliffbueno: Sure, but I interpreted Ben's response as a statement that after discussions with ONT, this was not considered appropriate anymore. As evidenced, nanopore sequencing has been able to produce data with quality scores corresponding to >10% error-free reads for quite a while now.
