### ISSUE TITLE
removeBimeraDenovo causing kernel crash

### ISSUE THREAD

**Issue by spencerJD** [benjjneb/dada2#76]
Hello,

I have tried running removeBimeraDenovo a few times on my dataset (after creating the sequence table) and every time it will run for about an hour or so, then causes a kernel crash in my Jupyter notebook. Has anyone else experienced this, or is there a way to get around it?

**Comment by benjjneb** [comment]
My guess is that you downloaded the package today and have version 1.0.2.

Unfortunately (especially timing-wise) there is a memory leak in isBimeraDenovo in v1.0.2 that is almost certainly causing your crash issue. The fix is already checked in as version 1.0.3, but is working its way through the Bioconductor build system and should (accidents aside) be available tomorrow.

You can also get memory-leak free versions from github directly, either using the devel 1.1 branch or the release branch (already 1.0.3 on github).

Sorry about that, and let me know if this isn't your issue!

**Comment by spencerJD** [comment]
I am currently using the devel 1.1.0 branch and still running into this issue.

**Comment by benjjneb** [comment]
Ah OK, easier then since you are already installing from source.

The leak was fixed in devel four days ago, if you pull the latest version (1.1.1) this issue should resolve itself.

**Comment by spencerJD** [comment]
Great - I'll give that a shot. Thanks!

**Comment by benjjneb** [comment]
Closing for now, please reopen if problem persists.

Also, for the record the leak fix in the Bioconductor release (v1.0.3) just went live as well.
