### ISSUE TITLE
not convergent after 10 rounds

### ISSUE THREAD

**Issue by huyue87** [benjjneb/dada2#77]
Hi ! 
I was running dada2 on 70% of the reads yielded from one MiSeq run, which covered 80 environmental samples (targeted amplicon sequencing). After quality trimming steps, each sample contains 18k unique reads on average. For the reverse reads files (210bp long), dada2 took 6 rounds until convergence, while for the forward reads files (263bp long), dada2 automatically terminated after 10 rounds of error estimation. Is that because of the huge amount of diverse sequences or any other reason? How could I solve this problem. Thanks.

p.s. I was running dada2 v1.1 on 16 cores, it took > 2 hours to calculate error matrix for reverse read files, which is efficient.

**Comment by benjjneb** [comment]
Hi Yue,
That is unusual to not have convergence after 10 rounds (and can you post the package version you are using `packageVersion("dada2")`) but as long as it is close to convergence it's not a concern. The error rate estimation part is important primarily because of the huge difference in error rates between different runs.

To check if the rates are close to convergence, use the function `dada2:::checkConvergence(dadaRs[[1]])`. That will give you a vector of the sum of absolute differences between the error rate parameters in each step. That should have gotten much, much smaller from where it started, and if it did, then it's probably OK to use the error rates at the end even though they haven't technically converged. Feel free to post the results here as well if you are unsure.

You can also allow the algorithm to run longer (more steps before terminating) by setting a higher MAX_CONSIST value in the dada call, eg. `dada(derepRs, selfConsist=TRUE, ..., MAX_CONSIST=20)`

**Comment by huyue87** [comment]
Hi Benji,

I am using dada2 (version 1.1.1) and I see your points about the error estimation. Thank you for the clear explanation. 
After 10 rounds, it is showing much smaller distance in error rate parameters in the 10th round than in the 1st round (the sum decreased from 3^10 to 1^10-5).  Though the sums of errors of forward files are not continually decrease in all steps as the reverse files did, the error distance of its last step is as small as the numeric level of the last second run for reverse file (1^10-5). I guess it will convergent by adding 2 or 3 steps further. Do you think it is ok to continue with these close-convergence dadaFs?

Following are the sums of error distances in each step.   

# not convergence forward file
dada2:::checkConvergence(dadaFs[[1]])
 [1] 3.252136e+01 4.968894e-01 4.556446e-02 2.076082e-02 3.130193e-03
 [6] 3.386694e-03 3.383264e-03 4.794636e-03 2.790897e-03 1.037385e-05

# convergence reverse file
> dada2:::checkConvergence(dadaRs[[1]])
[1] 2.839295e+01 5.166795e-01 4.094384e-02 4.112789e-03 1.459067e-05
[6] 0.000000e+00

**Comment by benjjneb** [comment]
I do think it would be fine to use the final output from the 10th step based on the `checkConvergence` results. 

You can re-run with `MAX_CONSIST=20` to get all they way there if you want as well.

**Comment by huyue87** [comment]
I see! Thank you!

**Comment by MartonSzoboszlay** [comment]
Hello Ben,
I'm having the same issue. No convergence even after 25 rounds.

> dadaFs <- dada(derepFs, err=inflateErr(tperr1,3), selfConsist = TRUE, multithread = TRUE, MAX_CONSIST = 25)

> dada2:::checkConvergence(dadaFs[[1]])

>  [1] 3.068910e+01 1.801176e-01 2.167087e-02 3.741876e-03 1.691507e-03 7.852241e-04 1.751274e-03
>  [8] 3.548573e-04 1.073849e-03 6.446898e-04 1.774479e-03 1.284791e-03 1.782676e-03 1.286112e-03
> [15] 8.293197e-04 1.194965e-03 8.560878e-04 9.851772e-04 6.856284e-04 4.515115e-04 1.923871e-03
> [22] 1.120065e-03 3.765320e-03 1.287354e-03 3.768898e-03

I think the sum of absolute differences between the error rate parameters are still relatively high and it seems to fluctuate around 10^-3 after step 5. Is this an indication of some problem, or can I safely proceed with the DADA2 pipeline?
Thanks!

**Comment by benjjneb** [comment]
@MartonSzoboszlay

I would just go ahead and use your data. Those fluctuations are still pretty small, and it is doubtful they meaningfully impact the overall inference.

However, I've never seen non-convergence like that through 25 rounds. Is it possible to share this data? I would be interested to poke around and see what is happening in detail.

**Comment by MartonSzoboszlay** [comment]
Hello Ben,
thank you very much for the advice!
Sure, I'm happy to share the data. I'll send you a link.

**Comment by johnchase** [comment]
Hi, I'm wondering if there was ever resolution regarding the last post? I'm having a similar issue, though unfortunately I am not able to share my data.

**Comment by benjjneb** [comment]
@johnchase 
I still have been unable to replicate this behavior in any of the dozens of datasets I've run, so there is not yet a technical resolution. I just got back in touch with @MartonSzoboszlay for his data that failed to converge after 25 rounds, so hopefully that will replicate and shed some light. I know you can't share your data, but could you describe it a bit ... eg. HiSeq 100nt FWD reads of [XXX] environment?

In any case, it is extremely likely that this can be ignored because the fluctuations in the error rates have become very small even if they haven't hit zero. To check this, do two things on a 25 step output `dada-class` object:

```
plotErrors(dadaObj, nominalQ=TRUE)
dada2:::checkConvergence(dadaObj)
```

If the error model (black line) looks to have well-fit the observations (black points) in the output of `plotErrors`, and the values in the vector returned by `checkConvergence` (sum of absolute differences between error rate parameters between steps) are much lower at the end than at the start, then it is fine to simply terminate the consistency loop at an appropriate point (eg. where the `checkConvergence` values stop decreasing) and use that output.

**Comment by johnchase** [comment]
@benjjneb The reads are soil samples processed on an illumina miSeq 150bp forward and reverse reads, in this case the issue was just with the reverse that was not converging. I don't know if this is related, but the `dada` function took substantially longer to run than it has on our previous sequence data.

The model appears to fit the data quite well
![rplot](https://cloud.githubusercontent.com/assets/2243771/17873138/a8a24f1a-6878-11e6-8e47-60584d4eefdc.jpeg)

I may be doing something wrong here, the `checkConvergence` function returns an empty list

```{r}
> dada2:::checkConvergence(dadaRs)
list()
```

Also given the increased runtime (>96 hours on 8 processors) I only specified ten rounds so it may well be that this would have converged before 25 rounds. I think my interest was more if there was a signature characteristic of sequence data that took a long time to converge.

**Comment by benjjneb** [comment]
Can you run `dada2:::checkConvergence(dadaRs[[1]])` and post the result?

**Comment by johnchase** [comment]
```{r}
> dada2:::checkConvergence(dadaRs[[1]])
 [1] 2.891059e+01 1.396311e-01 5.764801e-03 7.518391e-04 1.681394e-04 3.185464e-05
 [7] 3.453726e-05 3.110506e-05 1.955614e-06 3.111103e-06
```

**Comment by benjjneb** [comment]
@johnchase That's fine to use as is. The error model is fitting well and looks as expected, and the convergence values (the summed absolute differences in the error model) are already very small by round 10.

**Comment by joey711** [comment]
What's going on with that spike in error-rate at Q = 40, esp A2T, A2C, ... ?

**Comment by johnchase** [comment]
@benjjneb My sense is that the reason for increased rounds prior to convergence has to do with the amount of variability in the sequences (rather than quality scores for instance) but i'm not positive.

For instance if we had two sequencing runs; one run that converged quickly and one run that failed to converge, what is different between those two runs and is it meaningful to understand the difference?

@joey711 I was discussing the increase in errors with @wdwvt1 at Q = 40, it seemed odd to both of us, I'd be curious to hear thoughts.

As always thanks for your help.

**Comment by joey711** [comment]
I could make some guesses. I'll wait for @benjjneb to comment, though. He'll have a better idea in this situation. It looks suspicious, though.

**Comment by benjjneb** [comment]
> For instance if we had two sequencing runs; one run that converged quickly and one run that failed to converge, what is different between those two runs and is it meaningful to understand the difference?

I don't think its meaningful. I just think there is some technical issue that (rarely) crops up that prevents certain runs from converging. But as long as the changes in the error model get small (as they are) you can just use the "nearly converged" error model, and you won't see any biological difference.

> What's going on with that spike in error-rate at Q = 40, esp A2T, A2C, ... ?

It's an artefact of the fact that the error rates are being fitted to **mean** quality scores of dereplicated sequences, rather than to the quality scores of individual reads.

Because it is usual in Illumina sequencing for very few 40s to be called (the bulk of the distro tends to be Q33-38), there are few 40s, and fewer^2 in dereplicated sequences with more than one read. The result is almost all the 40s in the dereplicated reads are in singleton sequences, which can't form their own partition, and hence get counted as errors.

End result, artefactual turn up of error rates at the upper boundary of the quality-scores.

Does it matter? Not really. The very effect that causes this, the tiny number of 40s (or 39s/38s depending on sequencing run) means this has little effect on sample inference, and the singletons aren't being called period.

**Comment by joey711** [comment]
Thanks, Ben. That is a helpful explanation. Have you considered tweaking the smoother to be more robust to an outlier at Q=40? You don't believe 40 very much anyway, so you could mask it out (set `y|40 <- y|39`), increase the band, etc..

I guess the point being that the curly-cue jump in error-rate at Q40 is not real, looks funny, and might effect results in special circumstances... Just a thought. I agree that it sounds like it would have a minor effect in most cases, given your explanation.

**Comment by benjjneb** [comment]
@IrshadUlHaq1 That is probably fine. Take a look at our FAQ, in almost all cases this isn't a problem: https://benjjneb.github.io/dada2/faq.html#what-if-the-self-consistency-loop-terminated-before-convergence

**Comment by rahulnccs** [comment]
I experienced the same problem, even after trying the option of MAX_CONSIST=25. For Reverse read convergence was achieved after 6th round of selfconsist. But forwards showing error. Here is the fig for convergence.
[covergence round10.pdf](https://github.com/benjjneb/dada2/files/2770845/covergence.round10.pdf)
