### ISSUE TITLE
assignTaxonomy with PhytoRef

### ISSUE THREAD

**Issue by rotiferFromItaly** [benjjneb/dada2#781]
Dear Mr. Callahan,
I performed the DADA2 tutorial (https://benjjneb.github.io/dada2/tutorial.html) and everything worked fine!!
However, I was curious to see how a different 16S reference database (http://phytoref.sb-roscoff.fr/doblast) would work with this example dataset. The 16S dataset consists of marine and freshwater protist/algal sequences. 

I used the following code:
taxa.phyto <- assignTaxonomy(seqtab.nochim, "/Users/Documents/PhytoRef20190531xDADA2.fasta", multithread=TRUE)
taxa.print.phyto <- taxa.phyto # Removing sequence rownames for display only
rownames(taxa.print.phyto) <- NULL
head(taxa.print.phyto)

and I was surprised to see a matching for these generally bacterial sequences with dinoflagellates. What does this mean? Does it mean that when we use the wrong database (here algae) for taxonomical assignment of bacterial sequences, we will get an assignment that, however, does not make any sense? But what when I use my 16S sequences that also consist of algal sequences and bacteria, what will happen?
May I am missing here something? In any case, I would be very happy for any comment or suggestion,

best regards,
Ulrike

**Comment by benjjneb** [comment]
> Does it mean that when we use the wrong database (here algae) for taxonomical assignment of bacterial sequences, we will get an assignment that, however, does not make any sense? 

Yes this can happen when using the naive Bayesian classifier (the algorithm behind `assignTaxonomy`) when no outgroup representatives are present in the training database. If there are no outgroup representatives, e.g. even just a few bacterial sequences in a fungal database, then legitimate bacterial sequences in your data will be compared only to fungal sequences. In that case, it might be possible there is some fungal lineage happens to be the most simliar to that bacteria and, even if its quite distant in absolute terms, you end up with the kind of spurious assignments you are seeing because it is the most similar relative to all the other fungi in the reference database.

> But what when I use my 16S sequences that also consist of algal sequences and bacteria, what will happen?

To avoid misclassifications of this type, try to have outgroup representatives of other major lineages that could possible be amplified by your primer set. As needed, you can simply append entries to the training fasta files with the appropriate sequences and id lines of new lineages for this purpose.

**Comment by rotiferFromItaly** [comment]
I added 16 bacterial sequences, and the problem still persists, especially for the first 10 sequences  of the bacterial tutorial dataset. My PhytoRef reference databank has 1194 protist sequences. With adding 41 bacterial sequences, the problem persisted for the first 4 and some others. I guess seeking for 100% matching might be the best way.
Many thanks for your help
