### ISSUE TITLE
Length variation in seqtab.nochim

### ISSUE THREAD

**Issue by janetw** [benjjneb/dada2#792]
Hello,
First of all, thank you for this software! I greatly the time and energy that you all have put into it!
I have a question that is not an issue with the software but I am hoping you might be able to provide some insight into what may be going on with our samples and/or sequencing and/or how we process the reads. This may be related to Issue #44 (Length variation in the dada2 output) but not sure. We have used primers targeting the V1-V3 hypervariable region. We are getting a lot of variation in the read length for the SVs. I have included some plots of the reads from two separate MiSeq runs (2 x 300 bp) done on two different sample types. I am using the following parameters when filtering and trimming:

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(270,260),
              maxN=0, maxEE=c(4,8), truncQ=4, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE) 

I am trying to understand why we would have so many merged reads that are shorter than what we would anticipate for this region. How can we be having merged reads that are 270 bp in length? Any suggestions or insight into what may going on would be greatly appreciated.

Especially with the set displayed in the 2nd / lower figure, would you recommend just using the forward reads since the merged data looks so "wonky"?

Thank you.
Janet

![PlotLengthDist](https://user-images.githubusercontent.com/1120775/59557040-23c3cb80-8f84-11e9-879c-2e580ba06c52.png)

![PlotLengthDist_Enger_6-15-2019](https://user-images.githubusercontent.com/1120775/59557035-07c02a00-8f84-11e9-8b9b-982da9ee6f32.png)

**Comment by benjjneb** [comment]
The most probable explanation is that the unexpected sequence lengths are either off-target amplification. There are also certain kinds of artefacts it might be.

As a quick check, I would inspect the sequence-complexities of the denoised ASVs: `hist(seqComplexity(seqtab), 100)`. Is there any evidence of a low-complexity mode in the data?

Second, I would just go ahead and BLAST some of the low-length sequences to get a sense of what they are. It is totally valid to restrict your data to the expected length distro, but often I like to see what it is I'm getting outside the expected lengths in case it is actually interesting.

The first panel looks pretty clean, the lower-than-expected length stuff is at low frequencies, and restricting to the expected lengths is probably what you'll end up doing. Agree that the bottom two panels look a lot more potentially problematic, since there isn't that abundance peak at the expected lengths. Not sure what I'd do there, but I'd check on the complexities and high/low-lenght BLAST hits and then decide from there probably.

**Comment by janetw** [comment]
Thank you for your help.
I did not see a bimodal distribution with the seqComplexity() (see below) and will next move towards trying to BLAST some of the sequences. 
Thanks again,
Janet
![Histogram_seqComplexity_Sediment](https://user-images.githubusercontent.com/1120775/59580573-7685ac00-9086-11e9-99e9-b757eb2221af.png)
![Histogram_seqComplexity_Enger](https://user-images.githubusercontent.com/1120775/59580597-9026f380-9086-11e9-99bb-08a4646915bf.png)

**Comment by handibles** [comment]
Just to leave a slightly longer breadcrumb trail for the next person. I had a similar problem with variable variation in ASV length on this end (with illumina standard primers) that turned out to be reverse-complemented adapter contamination in _just one of the sample groups_.

This was largely resolved by a mix of `cutadapt` (as below) removal of primers, and manually scrubbing out the ASVs that were clearly not of interest  (`NA`s or organelles) - for this I recommend follwoing the process through and then looking at the taxonomy of the ASVS in the bad range. 

As much as the idea excited me, `seqComplexity` did little to help.

_plot of sequence lengths X abundance:_
![ms__som_16Slength](https://user-images.githubusercontent.com/26572263/113021200-40da8600-917b-11eb-80d8-637a584b8b54.png)

_histogram of seq complexity_
![ms__som_ASV_complexityXlength](https://user-images.githubusercontent.com/26572263/113021688-bf372800-917b-11eb-8d01-85d95bd55a93.png)

_cutadapt command used - remove *reversed & complemented* adapter sequence (tho not adapter seq+primer seq)_

`cutadapt -m 200 -e 0.2 --discard-trimmed -a CTGTCTCTTATACACATCTCCGAGCCCACGAGAC -A CTGTCTCTTATACACATCTGACGCTGCCGACGA -o dirpath/sample_cutad_R1.fastq -p dirpath/sample_cutad_R2.fastq  dirpath/sample_L001_R1.fastq dirpath/sample_L001_R2.fastq`

_final plot of length X abundance post trim_
![ms__som_ASV_deadapted_detax](https://user-images.githubusercontent.com/26572263/113021868-edb50300-917b-11eb-8a9c-677999b1700c.png)



With luck, helpful to someone somewhen.
