### ISSUE TITLE
Keep samples that end with 0 reads after filtering/merging

### ISSUE THREAD

**Issue by kyakimovich** [benjjneb/dada2#818]
Hi,

I've noticed that some of the steps in the dada2 pipeline fail if one or more of the samples ends up with 0 reads, like in the quality filtering steps, or in the read merging step. And I was wondering if there was a way to get it to keep the samples in the final output, even if there are 0 reads. I have a few hundred samples with some controls and treatments interspersed that have low read counts, and some of them don't make it passed filtering or merging, and it would make downstream analysis easier if they were kept in the dada2 ASV table output. I'm sure I could code a solution afterwards in R, but this would be the easiest place to start. Ive had this issue with a couple different data sets now. 

Let me know if there is a work around! I haven't found one pouring over these help tickets.

Thanks

**Comment by benjjneb** [comment]
I believe that they should make it through merging these days as zero read count rows in the sequence table. Can you confirm that you are definitely losing samples in the merging step?

As for filtering, yes zero-read samples are lost in the filtering step, and there is no pretty workaround for it. Basically because filtering outputs a fasta file, and an empty fasta file is not well defined and won't be handled well by other tools, we just don't do it.

The workaround would be at the end, at the sequence table stage, to add those samples back in with zero reads in all cells.
