### ISSUE TITLE
Possible issue with Illumina two color over-confidence in G

### ISSUE THREAD

**Issue by michael-weinstein** [benjjneb/dada2#821]
We are starting to see some evidence of this causing trouble over here.  It seems like when a 2-color system is used, there is a pretty high risk that something that should have been a no-signal N base gets called instead as a high-confidence G base.  This seems to fool the error modeling due to what should be a low/no-confidence base being a high-confidence G instead.  It seems like this is getting some unique amplicons to be detected that don't really exist.

I am going to talk to the rest of the team here and see if I can't find a couple of good examples where this is happening "in the wild" so I can see if there are any patterns to it.

[https://sequencing.qcfail.com/articles/illumina-2-colour-chemistry-can-overcall-high-confidence-g-bases/](url)

**Comment by benjjneb** [comment]
This was a concern for us when the NexSeq came out and I'm not sure it's ever been really resolved, mostly because of a lack of testing data on our end. I had one NexSeq dataset (like a couple samples) and things seemed to work well enough, but I do remember seeing at least some evidence that no-signal G errors were noticeably different.

I'm all ears if you have further observations, especially if there is any shareable data to go along with it. There are various ways to deal with these sorts of error model misspecification issues. One of the easies might be modifying the error-model-fitting function, which is a completely modular part of the algorithm, and in fact can be rewritten in R and provided to the `dada` function (see the `errorEstimationFunction` argument).

**Comment by michael-weinstein** [comment]
We have been seeing that here as well and we have a pretty good volume of data, including several samples where we have evidence of that.  I'm working with the team that has the data to see what it will take to get it shared.

You are going to be at NIST, correct?

**Comment by benjjneb** [comment]
> You are going to be at NIST, correct?

Yes I will be there.

**Comment by cjfields** [comment]
@michael-weinstein the low complexity filter that @benjjneb added recently should address this I believe (I think this is in the trimming step?).  We have seen this with NovaSeq data recently, particularly in samples with low DNA concentration.

**Comment by medinacarolina** [comment]
Dear all, I was wondering if this issue was already solved. I see in my ASV consensus sequences some enrichment for polyG tails> Looing at datasets using other chemistry-based methods I do not seem to see these examples

**Comment by benjjneb** [comment]
@medinacarolina 

The solution that we have in the package is the `rm.lowcomplex` parameter within the `filterAndTrim` function. This allows the removal of reads with regions of low complexity, such as polyG tails, at the filtering stage. To use this approach first inspect the distribution of read complexities in a couple example samples with `plotComplexity("path/to/sample.fastq")`. Then if there is evidence of a bimodal distribution of complexities, the low complexity mode can be filtered out with `filterAndTrim(..., rm.lowcomplex=THRESHOLD)` where the `THRESHOLD` should be chosen based on `plotComplexity` output.
