### ISSUE TITLE
Deep sequencing data and large amount of ASVs called

### ISSUE THREAD

**Issue by serine** [benjjneb/dada2#836]
@benjjneb I have a couple of additional questions, and this is the closest thread, so I figured it's best to re-open this one, rather then opening new issue. Many thanks in advance !

I'm working with soil data set, libraries were generated as per [earch microbiome protocol](http://www.earthmicrobiome.org/protocols-and-standards/16s/), although I don't actually have much info about library preps, PCR and sequencing. I know that it was MiSeq 2X300, but this is mainly learning from the data. I can `grep` for these adaptors in my fastqs

- FWD: GTGCCAGCMGCCGCGGTAA
- REV:  GGACTACHVGGGTWTCTAAT

This is extremely deep sequenced data, e.g

```
Poly-12  800414
Poly-11    621375
P10-T1-D1   337010
P12-T1-D2   333764
P10-T1-D2   321432
C1-T1-D2   311071
```

In short summary there are three conditions:

- `C` control
- `Poly` treatment
- `P` blank (different type of control)

I've tried various ways to analyse this data. For example I've tried `truncQ` 13 vs 2, filtering with `seqtk trim` and taking a sample from the data

``` 
for i in ../v4_treat/*.gz; do seqtk sample -s 123 $i 100000 | gzip - > $(basename $i)&done
```

1. Do you have a sense whether 6000-16000 ASVs is a sensible number for soil microbiome diversity? 

so far I've looked at 3-5 various gut microbiome data and all had around 3000-3500 ASVs and so to me anything bigger then that seem big.

### Individual groups

```
+> readRDS("data_cntrl_sample/seqtab.rds") %>% dim
[1]   12 6461
+> readRDS("data_cntrl_sample/seqtab_nochim.rds") %>% dim
[1]   12 5863
+> readRDS("data_cntrl/seqtab.rds") %>% dim
[1]   12 8247
+> readRDS("data_cntrl/seqtab_nochim.rds") %>% dim
[1]   12 7458
```

```
+> readRDS("data_poly_sample/seqtab.rds") %>% dim
[1]    23 11072
+> readRDS("data_poly_sample/seqtab_nochim.rds") %>% dim
[1]   23 9947
+> readRDS("data_poly/seqtab.rds") %>% dim
[1]    23 13965
+> readRDS("data_poly/seqtab_nochim.rds") %>% dim
[1]    23 12454
```

```
> seq1 <- readRDS("data_cntrl/seqtab_nochim.rds")
> seq2 <- readRDS("data_poly/seqtab_nochim.rds")
> seqtab <- mergeSequenceTables(seq1, seq2)
> seqtab %>% dim
[1]    35 14809
```

2. Should I split my data into control and treatment groups for ASVs detection? 

Above I've shown ASV numbers when I do split into control and treatment, if I keep all samples together and run through [bigdata workflow](https://benjjneb.github.io/dada2/bigdata_paired.html) I get these numbers

```
+> readRDS("data_v4/seqtab.rds") %>% dim
[1]    48 20980
+> readRDS("data_v4/seqtab_nochim.rds") %>% dim
[1]    48 16794
``` 

_there are additional samples, that I haven't looked at the individual level, hence why number don't add up, i.e 12+23 != 48, just FYI_

The number of ASVs don't seem to be that different when I separate the samples, but I'm more worried/interested in what happens at the learning errors step when you separate the data?
I should mention that `poly` samples don't converge after 20 cycles, but if I randomly sample `poly` samples to 100000 depth, they converge after about 12 or so cycles from memory.
I have a funny suspicion that there is something up with errors, either with error modelling or quality filtering the data. 

Could you clarify the use case of these settings please?

- `OMEGA_C`
- `OMEGA_A`
- `maxEE` 
- `truncQ`
- `maxQ`

I've tried running with `maxEE` set down to `c(1,1)`, which reduces number of ASVs (as expected I guess) but only by a little 

I've calculated EE's for some of my samples, shown below. Table is sorted on `min` column. Some samples have particular low EE and other much larger. I'm not too sure what that means and even if this is a useful information, just attempting to figure out what are EEs.  

```
min     max     mean    median
0.007582466683508604    25.376491903242513      1.0654018811665324      0.25489642851411076
0.00852888398163345     24.54626091413149       1.014005710035999       0.23575807527396603
0.008744499622325734    23.56008230821845       1.1877417597967805      0.3546207138753441
0.009002477361252023    22.083507056806784      1.269831433714665       0.3887910433340519
0.011296612559423805    22.85146649323078       1.001014530888708       0.21996776636317578
0.011740458151281847    25.226615392135965      1.018558089405674       0.23111820543141903
0.012611476487730054    25.238851072668748      1.3649389860129177      0.4538428940291807
0.012753427845486293    24.715945631415885      0.9510466821484247      0.21544191389270642
0.012767809561503076    22.37161890781862       1.3016184246065754      0.38479392070193835
0.012767809561503076    22.083507056806784      1.1064811271036383      0.2844538912801049
0.012767809561503076    28.327471363244204      1.3107668882074364      0.4151284075163132
0.014076761027722746    22.083507056806784      1.1086632042293376      0.26921897721316124
0.01684632038270655     24.36506954528173       1.037213415466651       0.24431521889593533
0.017519678214713195    22.083507056806784      0.9546431487140348      0.21482910419698226
0.01829645901781627     28.057925447558272      1.0106889981380842      0.2416245643150746
0.01838783838663132     22.083507056806784      1.0417875440856936      0.25675448621009916
0.018397009559618507    24.320347550972155      1.0059538766794616      0.2355566565600435
0.019365633826264484    22.16232861668771       1.2754935508183929      0.3931545149171715
0.020972930287366773    23.507994254380737      1.51701422343911        0.5674238563475302
0.02232818696765856     22.083507056806784      1.9202237537947169      0.9851906490869845
0.023443914692403554    26.36895836132371       1.541104201526153       0.5882502524592065
0.027466240527134044    24.796843308873157      1.2683555619315585      0.4225953717880908
0.02775775402206691     22.831163208537923      1.082188359433929       0.28342031591092953
```

I think what I really need to tweak is `OMEGA` A and/or C. My understanding is that `OMEGA_A` controls when new ASV will get formed. So in my case to reduce total number of ASVs I should make `OMEGA_A` larger, but how large?  In #315  you point to your paper and suggest to make a p-values histogram. I think it's this table that has all the info right?

```  
sequence                             abundance    n0    n1  nunq  pval birth_type birth_pval birth_fold birth_ham birth_qave
   <chr>                                    <int> <int> <int> <int> <dbl> <fct>           <dbl>      <dbl>     <int>      <dbl>
 1 GTAGGGGGCAAGCGTTGTCCGGAATCACTGGGCGT…      1535 17662  2888  2242     0 I                  NA  NA               NA       NA  
 2 CAGCACCCCGAGTGGTCGGGACGTTTATTGGGCCT…      2250 15513  2132  1556     0 A                   0   9.55e185        66       36.9
 3 GTAGGGCGCAAGCGTTATCCGGAATTATTGGGCGT…       757 12577  1786  1494     0 A                   0   2.19e131        48       37.1
 4 AGAGGTCTCAAGCGTTGTTCGGATTCATTGGGCGT…      2749 12036  1683  1402     0 A                   0   4.73e128        47       36.9
 5 GGAGGGGGCTAGCGTTGTTCGGAATTACTGGGCGT…      1216 11486  1777  1543     0 A                   0   5.20e118        44       37.0
 6 GTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGT…       913 11034  1843  1646     0 A                   0   4.32e 99        37       37.1
 7 GTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGT…      1050 10252  1658  1519     0 A                   0   1.59e 17         7       36.3
 8 GTAGGGGGCTAGCGTTGTCCGGATTTATTGGGCGT…       636  7298  1045  1002     0 A                   0   1.65e130        47       37.0
 9 CAGCACCCCGAGTGGTCGGGACGTTTATTGGGCCT…       537  7221  1019   870     0 A                   0   3.44e  5         2       36.5
10 GTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGT…       464  5842  1044  1004     0 A                   0   1.71e  7         3       37 
```

However I couldn't find any information on the column names and how to use them for diagnostics..? 

what are all the birth columns? 
Does the pvalue column there corresponds to `OMEGA_A` ? and I should plot histogram of those values? 

```
> dadaFs[[1]]$clustering$pval %>% summary
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.000e+00 0.000e+00 0.000e+00 3.207e-43 0.000e+00 1.834e-39 
```

This is a rather lengthy question (took me a couple of days to write it lol, mainly because I was testing several things out), in short summary any advise will be appreciated ! 

Thanks !

p.s

### Control errFs plot

![err_plt_cntl](https://user-images.githubusercontent.com/6700099/64141719-81153d80-ce4c-11e9-8fe6-d9eccd309210.png)

### Poly errFs plot

![errors_plt](https://user-images.githubusercontent.com/6700099/64141741-938f7700-ce4c-11e9-9ca7-3d83e4d00c40.png)

## References

- #315 
- #571
- #546  
- #77

**Comment by benjjneb** [comment]
> 1. Do you have a sense whether 6000-16000 ASVs is a sensible number for soil microbiome diversity?
> so far I've looked at 3-5 various gut microbiome data and all had around 3000-3500 ASVs and so to me anything bigger then that seem big.

It's always hard to give hard number guidelines on the number of ASVs to expect, since it depends so much on the specific environment sampled and the depth of sequencing. However, you should generally see more ASVs in soil samples than in gut samples at the same depth, as soil is typically more diverse. So the numbers you are seeing seem sensible to me.

> 2. Should I split my data into control and treatment groups for ASVs detection?

Typically, as long as the control and treatment groups were processed with the same PCR protocol and on the same sequencing run, it is not necessary to separate them for DADA2 processing. The algorithm is modeling the errors, so as long as the error process is consistent it is fine to keep the sample groups together.

> The number of ASVs don't seem to be that different when I separate the samples, but I'm more worried/interested in what happens at the learning errors step when you separate the data?
> I should mention that poly samples don't converge after 20 cycles, but if I randomly sample poly samples to 100000 depth, they converge after about 12 or so cycles from memory.

Error learning from very diverse samples like soil is harder, and it is more likely that the algorithm will take longer to converge. In general, this is not a major concern though, the error model just needs to be pretty good, not perfect. It also makes sense that convergence might happen faster when subsampling samples, as this effectively reduces diversity a bit.

> Could you clarify the use case of these settings please?
>
>OMEGA_C
>OMEGA_A
>maxEE
>truncQ
>maxQ

`maxEE`, `truncQ`, and `maxQ` are all filtering parameters that throw out reads that fail to meet their conditions (or truncate them in the case of `truncQ`). In general, the only one of these you need is `maxEE`. The others are included largely for use with non-Illumina sequencing technologies.

`OMEGA_C` controls the balance between correcting errors identified byt he algorithm, and throwing away errors identified by the algorithm. If you have strong feelings about one behavior or the other you can modify it by this parameter, but otherwise I probably wouldn't bother messing with it.

`OMEGA_A` controls the sensitivity of the algorithm by setting the p-value threshold at which new ASVs are inferred. You can increase sensitivity by making `OMEGA_A` less stringent than its default value of `1E-40` at the cost of some increase in spurious ASVs.

> So in my case to reduce total number of ASVs I should make OMEGA_A larger, but how large? In #315 you point to your paper and suggest to make a p-values histogram.

Unfortunately this doesn't work very well in real data due to the presence of chimeras. Chimeras are introduced by a different error process than the PCR/sequencing errors the DADA2 algorithm is modeling, and show up all over the p-value distribution, making it hard to pick out a clear break in the distribution.

> Does the pvalue column there corresponds to OMEGA_A ? and I should plot histogram of those values?

Yes the pvalue column corresponds to `OMEGA_A`.

> what are all the birth columns?

These are diagnostics about each ASV that is inferred, recorded at the time of its "birth". `birth_ham` is the hamming distance to the other ASV this one was split off from, `birth_fold` is the fold-times more abndant that ASV was than expected under the error model, and `birth_qave` is the average quality scores at the positions from which that ASV differed from the one it was split off from.

The most useful are `birth_qave`: are there a lot of low `birth_qave` values? If so the error model may be struggling to appropriately model low qualities. And `birth_ham`: Are there a high fraction of `birth_ham=1` values? That may suggest the error model is struggling to accurately identify single-nucleotide variants.

**Comment by serine** [comment]
@benjjneb thanks so much for taking the time to respond. 

I figure that soil samples could be more diverse. Something that I didn't, I wrote out `uniquesToFasta()` ASVs and blasted them against  `16SMicrobial.tar.gz` _Bacterial and Archaeal 16S rRNA sequences from BioProjects 33175 and 33117_ , which I got from NCBI database (ftp://ftp.ncbi.nlm.nih.gov/blast/db/) and I simply counted unique entries, which roughly gives me 5000 unique "species". This is the figure I was working towards, but I get double or triple that, hence why I wanted to look at it a bit closer.  

I tried fiddling with `OMEGA_A` and `C` but that didn't result in much change in ASVs. I guess expected.

Hamming distance looks skewed towards low numbers

### Control group

![birth_ham_plt_cntrl](https://user-images.githubusercontent.com/6700099/64306508-50f9a600-cfd6-11e9-8cbf-3baeb82eb5a0.png)

### Treatment group

![birth_ham_plt_treat](https://user-images.githubusercontent.com/6700099/64306500-44754d80-cfd6-11e9-8fe9-c4580e011aa0.png)
 
One other thing that seems odd that I also don't fully get is during `dada` step, 

```
dadaFs <- dada(derepFs,
               err=errF,
               pool=TRUE,
               verbose = TRUE,
               OMEGA_C = omega_c,
               OMEGA_A = omega_a,
               MIN_FOLD = 1,
               multithread = multithread)
```

I see these numbers 

```
Convergence after  8  rounds.
12 samples were pooled: 2015151 reads in 298090 unique sequences.
12 samples were pooled: 2015151 reads in 417067 unique sequences.
```

I'm pretty sure second round of dada meant to have fewer unique sequences not more. I don't have these numbers for any of my previous runs, but when I filter data with `truncQ=13` I get these numbers

```
Convergence after  8  rounds.
12 samples were pooled: 741885 reads in 100321 unique sequences.
12 samples were pooled: 741885 reads in 85228 unique sequences.
```

but the hamming dist histogram doesn't change shape

**Comment by serine** [comment]
I forgot to add last night `birth_qave` plots. and also ask how small are are too small?

### Control

![birth_qave_plt_cntrl](https://user-images.githubusercontent.com/6700099/64392072-8235ad00-d08e-11e9-8ea9-b8ccdb0c1d30.png)

### Treatment

![birth_qave_plt_teat](https://user-images.githubusercontent.com/6700099/64392059-78ac4500-d08e-11e9-88e3-79297e7702d9.png)

Thanks!

**Comment by benjjneb** [comment]
Looking at these diagnostics they all look normal to me. 

On `birth_qave`, a warning sign would be if their was a second mode in the distro at low Q scores. There is not in your data, this looks very normal and consistent with with algorithm working as expected. 

On `birth_hamming`, a warning sign would be a big spike at `birth_ham==1`. Although that is not separated out in your data, it does not appear from what you have posted that there is one. It is expected that most `birth_ham` will be low due to the way the algorithm works (before "birthing" a new ASV, the sequences is associated to the most similar ASV already created, thus the distances when birthed tend to be low).

Also, on your convergence, that also looks normal. There is some pretty random variation in the number of steps needed for full convergence, and you are well within the normal range.

**Comment by serine** [comment]
@benjjneb Thanks a lot for spending time looking into this. I guess all normal then :). Like I said this was the first time I've analysed soil samples, so I was confused a bit at the start. Having talked to several people it sounds like each microbiome can be very different depending on the sample source, which makes sense.

thanks again !
