### ISSUE TITLE
learnErros matrix is null with default parameters

### ISSUE THREAD

**Issue by olivierrue** [benjjneb/dada2#858]
Hello,
I have an error with the learnErrors function:
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.
By changing the parameter nbases to 1e10, I have no more errors. 
My dataset contains 500 million databases at the beginning. Does this mean that 1e8 bases would not be enough to learn the error rates?
Thank you for your help

**Comment by benjjneb** [comment]
I don't know, and its hard to diagnose from the information given here.
What are the exact commands you are running to produce this error?
It seems yo have a working workaround... does the output of `plotErrors` look reasonable? If so you can probably just proceed.

**Comment by olivierrue** [comment]
Here are my commands:
```
library(dada2)
packageVersion("dada2")
[1] ‘1.12.1’

input_dir <- "/path/to/my/fastq"
output_dir <- "/path/to/my/outdir"
fnFs <- sort(list.files(input_dir, pattern = "_R1.fastq.gz", full.names = TRUE))
fnRs <- sort(list.files(input_dir, pattern = "_R2.fastq.gz", full.names = TRUE))
fnFs.filtN <- file.path(output_dir, "filtN", basename(fnFs))
fnRs.filtN <- file.path(output_dir, "filtN", basename(fnRs))
filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = TRUE)
cutFs <- sort(list.files(file.path(output_dir, "filtN"), pattern = "_R1.fastq.gz", full.names = TRUE))
cutRs <- sort(list.files(file.path(output_dir, "filtN"), pattern = "_R2.fastq.gz", full.names = TRUE))
filtFs <- file.path(output_dir, "filtered", basename(cutFs))
filtRs <- file.path(output_dir, "filtered", basename(cutRs))

get.sample.name <- function(fname) paste(strsplit(basename(fname), "_R")[[1]][1],collapse="_")
sample.names <- unname(sapply(cutFs, get.sample.name))
out <- filterAndTrim(cutFs, filtFs, cutRs, filtRs, maxN = 0, maxEE = c(2, 2), 
    truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = TRUE)  # on windows, set multithread = FALSE
errF <- learnErrors(filtFs, multithread = TRUE, nbases=1e12)
100856429 total bases in 403420 reads from 6 samples will be used for learning the error rates.
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.

```

I can't run plotErrors because errF is not built. Here is the output of plotQualityProfile which looks good to me. I have 10 samples of 100,000 reads approximatively (2x250 bp).

![Sélection_290](https://user-images.githubusercontent.com/39589330/66809085-efa9e880-ef2c-11e9-9f55-5099293e0116.png)


I was wrong, increasing the nbases option doesn't change anything for this dataset.
What else can I check? 
Thanks in advance for your help

**Comment by benjjneb** [comment]
The `plotQualityProfile` output looks pretty unusual.
Is this real data, or simulated data?

**Comment by olivierrue** [comment]
Simulated data, generated with grinder (-mutation_ratio 98.6 1.4).
Some simulated datasets with same parameters worked fine, this one not.

**Comment by benjjneb** [comment]
I'm not sure, sometimes weird things can happen with simulated data because it violates some of the assumptions `learnErrors` makes about real data (e.g. a spread of quality scores) but usually grinder simulated data works fine.

Can you share a sample, ideally one that causes this error when `learnErrors` is run on it?

**Comment by olivierrue** [comment]
You can find the archive containing the datasets here : http://genome.jouy.inra.fr/~orue/Archive.tar.gz
Thanks

**Comment by benjjneb** [comment]
The issue here is that in the simulated data, only 2 quality scores exist, 10 and 30. The default error estimation method uses loess smoothing over the quality scores to estimates the error rates, and it is failing on this data with just two quality scores.

One way to deal with this is to simulate a more realistic mixture of quality scores. Another way would be to either replace the error estimation methods (see `?learnErrors`), or to just define the error model yourself (it's just a matrix). It depends on what your goals are with this simulated data.

**Comment by olivierrue** [comment]
It is the default behaviour of grinder to have only too values of quality scores. Another track I'm exploring is the fact that my simulated reads are very little identical. I'll try to obtain more "realistic" reads.
Thanks again
