### ISSUE TITLE
Analyzing paired/related samples

### ISSUE THREAD

**Issue by FunkyCells** [benjjneb/dada2#864]
Dear Dr. Callahan,

It is with great pleasure that I have made the transition to DADA2 for my 16S rRNA analysis. I have recently re-read your online tutorial and fell upon your description about pooling and pseudo-pooling (https://benjjneb.github.io/dada2/pseudo.html#Pseudo-pooling). Indeed, I'm having a bunch of human fecal samples where the samples are either from the same donor at different time points or from the same donor at the same time point but having undergone different experimental protocols. Logically it would make sens to pool samples that are somehow related/paired. However, I have several different donor stools where I have multiple samples that are thus paired. My question is: Does DADA2 have a parameter that permits to define which samples it should consider related/paired, so that pooling is not complete, but rather specific based on sample origin? 
Best Regards,
Martin LARSEN

**Comment by benjjneb** [comment]
Yep, completely agree that your idea of pooling related samples, rather than all samples. In fact, we have an open feature request on this issue: #604 

However, right now this is not implemented automatically. However, it can be done quite easily by hand in R. See this comment: https://github.com/benjjneb/dada2/issues/604#issuecomment-436364661
