### ISSUE TITLE
documentation mergePairs

### ISSUE THREAD

**Issue by bernt-matthias** [benjjneb/dada2#870]
Seems that the documentation for mergePairs still suggests derep objects as input, e.g. here https://bioconductor.org/packages/release/bioc/manuals/dada2/man/dada2.pdf. 

I'm just updating the Galaxy wrappers and was just wondering if there is still a use case for the depep function or if I can drop the function?

**Comment by benjjneb** [comment]
In the help, it does specify that a list of fastq files can be provided instead. The name of the variable s(i.e. `derepF` and `derepR`) is somewhat misleading at this point, but has remained because the ability to handle fastq files directly was added later, and we don't want to break previous code by changing the variable names in functions.

> I'm just updating the Galaxy wrappers and was just wondering if there is still a use case for the depep function or if I can drop the function?

The whole pipeline can now be run without ever calling `derepFastq` directly, and the recommended way to run it is not to just operate on the fastq files direclty as this keeps memory usage lower. There is a small value in `derepFastq` still in that it gives diagnostic information on the number of unique sequences in the total reads, but this is not needed in most cases, and can be left out of the Galaxy wrappers without much harm.
