### ISSUE TITLE
how to perform strain-level assignment for Pacbio FL 16S sequences 

### ISSUE THREAD

**Issue by wangzlab** [benjjneb/dada2#880]
Dear all, 

I have one question regarding strain-level assignment for Pacbio FL 16S sequences using dada2. If I understand correctly, in all three cases in the dada2 Pacbio NAR paper, ASVs of interest were first classified into strain-level bins based on the copy number and integral ratio of 16S genes in the same genome. Then the strain level taxonomy was assigned using a common best-hit type approach by BLASTing all ASVs in the bin against nt database.

My question is - do I always have to find and assign such strain-level bins first in order to confidently assign strain-level taxonomy to ASV? Alternatively, if I just BLAST one individual ASV against nt database and get one single strain as best-hit with exact 100% match, can I confidently assign that ASV to the corresponding strain? What is the right way to assign strain-level taxonomy for ASVs? It seems not always possible to find strain-level bins in real data which can be much noiser than mock runs.

Thanks very much for any kind input and help!

Best wishes,
Zhang

**Comment by benjjneb** [comment]
> My question is - do I always have to find and assign such strain-level bins first in order to confidently assign strain-level taxonomy to ASV? 

No.

> Alternatively, if I just BLAST one individual ASV against nt database and get one single strain as best-hit with exact 100% match, can I confidently assign that ASV to the corresponding strain?

This is a valid approach to classify based on a single ASV. However, remember that just because only 1 strain in the database exactly matched your sequence, doesn't mean there aren't other "strains" out there that would also exactly match it. That exact match provides a likely assignment, but the strain in your sample isn't exactly the same as that strain (this goes to the ambiguous definition of "strain").

> What is the right way to assign strain-level taxonomy for ASVs? It seems not always possible to find strain-level bins in real data which can be much noiser than mock runs.

For taxa of high interest, it is worth trying to identify genome bins of the ASVs by hand. Unforunately this is not an automated process yet though, so that will only be possible for a small number of high-interest taxa/ASVs. As suggested above, performing classification on the ASVs individually is fine as well -- you just might not be able to get as powerful sub-species classifications with single ASVs as you potentially could with the full genomic complement of ASVs.

**Comment by wangzlab** [comment]
Thanks very much Ben. This makes perfect sense. I'll try if it's possible to identify genome bins in my data by hand following your protocol. Thanks again.

**Comment by wangzlab** [comment]
> > My question is - do I always have to find and assign such strain-level bins first in order to confidently assign strain-level taxonomy to ASV?
> 
> No.
> 
> > Alternatively, if I just BLAST one individual ASV against nt database and get one single strain as best-hit with exact 100% match, can I confidently assign that ASV to the corresponding strain?
> 
> This is a valid approach to classify based on a single ASV. However, remember that just because only 1 strain in the database exactly matched your sequence, doesn't mean there aren't other "strains" out there that would also exactly match it. That exact match provides a likely assignment, but the strain in your sample isn't exactly the same as that strain (this goes to the ambiguous definition of "strain").
> 
> > What is the right way to assign strain-level taxonomy for ASVs? It seems not always possible to find strain-level bins in real data which can be much noiser than mock runs.
> 
> For taxa of high interest, it is worth trying to identify genome bins of the ASVs by hand. Unforunately this is not an automated process yet though, so that will only be possible for a small number of high-interest taxa/ASVs. As suggested above, performing classification on the ASVs individually is fine as well -- you just might not be able to get as powerful sub-species classifications with single ASVs as you potentially could with the full genomic complement of ASVs.

Thanks very much Ben. This makes perfect sense. I'll try if it's possible to identify genome bins in my data by hand following your protocol. Thanks again.
