### ISSUE TITLE
Trimming and Filtering with cutadapt (or alike) prior to dada2

### ISSUE THREAD

**Issue by Piplopp** [benjjneb/dada2#881]
Hello,
I finished the tutorial on 16S data and I have a small question, I see that the filtering and trimming steps is done the same for every sample and that each read is truncated at the same length. I usually trim my reads by quality with cutadapt for each sample, this leading in length variation (small though) in and between samples. 

Can I still perform the trimming and filtering steps with cutadapt prior to the dada2 algorithm and on each sample individually or is there a reason for it to being this way other than convenience ?

Thank you for your help

**Comment by benjjneb** [comment]
The reason for a constant trimming length is so that ASVs arent separated just based on their different lengths because one read was trimmed shorter than the other.

That said, if you are merging at the end, your merged sequences should span the same region (from forward to reverse primer) so it will be mostly fine.

Truncating to the same length within a sample is still desirable though, as it help a bit with detecting rarer variants.

**Comment by Piplopp** [comment]
Thank you for the quick answer and great work on this library !
