### ISSUE TITLE
 removeBimeraDenovo 

### ISSUE THREAD

**Issue by reyt1** [benjjneb/dada2#886]
Dear All,

I have an issue regarding  **removeBimeraDenovo**. I have a 12 and 34 sequencing, the first one came from Illumina MiSeq platform, 2x250bp with 5 million raw paired-end reads per sample, and the second one come from Illumina MiSeq platform, 2x250bp with ~50,000 raw pair-end reads/sample. Now, I am doing the the work flow with dada2 version 1.12.1 in PC with a windows intel core i5 7th generation and 16 GB of RAM. I was following all the step for obtain a matrix ASV, however when I did and script  `**removeBimeralDenovo**´ in R ( x64 3.6.1)

seqtabNoC <- removeBimeraDenovo(seqtabAll)

 it takes 70 hours and still the machine is thinking, all the previous step are doing well.  Are there some problems with my system or the dada2 crash ?

thanks a lot
Reynaldo

**Comment by benjjneb** [comment]
Chimera removal is compute intensive on large sequence tables, so it may just be taking a while. What is the size of the sequence table you are processing? `dim(seqtabNoC)`? The first thing to try though is turning on multithreading, which will speed up this step close to linearly in the number of cores/threads you have:

```
seqtabNoC <- removeBimeraDenovo(seqtabAll, multithread=TRUE)
```

The other thing I would check on is if you are hitting memory limit issues. If the memory being used by R during this command exceeds your physical memory (16GB), execution can become dramatically slower due to the need to swap memory into disk space.

**Comment by reyt1** [comment]
Dear Benji,

Still I waiting for the result so the dimension for SeqtabAll is 23 x 330033.
I know about multithreading, but I know that part of the function works on Linux and Mac, Is it possible to turning on Windows OS?

On the other hand, Rstudio take a 30% of the CPU, 315,6 Mb of memory and 6.3 of GPU 

Thanks a lot for your help  

![image](https://user-images.githubusercontent.com/22963355/68631109-3fe27f00-04c8-11ea-8dee-bb94fbbbb26b.png)

**Comment by benjjneb** [comment]
> the dimension for SeqtabAll is 23 x 330033.

This is a pretty big tables (in number of ASVs) so it is probably just taking a while.

> I know about multithreading, but I know that part of the function works on Linux and Mac, Is it possible to turning on Windows OS?

Yep, just turn on multithreading as described above.
