### ISSUE TITLE
How to import ASV table back in R for dada2 analysis?

### ISSUE THREAD

**Issue by kuldeepmore10** [benjjneb/dada2#904]
I am currently running a test analysis using pipeline outlined at https://benjjneb.github.io/dada2/tutorial.html

Yesterday, I constructed ASV table using this pipeline and I had to shut down my R. Before doing that, I exported my ASV table in csv format. Today I imported table using command read.csv and started further analysis. When I tried to remove chimeras using "seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=FALSE, verbose=TRUE) I received an error message 

"Error in removeBimeraDenovo(sebtab, method = "consensus", multithread = FALSE,  : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns."

It seems like my imported ASV table is not compatible with this command! What should I do?

**Comment by dswan** [comment]
The error you're seeing and the command you have used do not match. If this is a direct cut and paste of your error, you have a typo "sebtab" is not "seqtab"

**Comment by kuldeepmore10** [comment]
Actually it is not a typo and my ASV table is indeed named sebtab and not seqtab. In R, I had corrected the "seqtab" to sebtab before executing the command. I copy pasted command from tutorial just for the reference here. 

I still dont get why I am getting that error.

**Comment by benjjneb** [comment]
What is the result of `storage.mode(sebtab)`?

**Comment by jgrzadziel** [comment]
I think the problem is while you are importing csv file using default settings.
You need simply type
`seqtab = read.csv("seqtab.csv", row.names = 1)`

**Comment by kuldeepmore10** [comment]
jgrzadziel, Thank you! I will try "seqtab = as.matrix(seqtab)" and I will let you know here

**Comment by benjjneb** [comment]
A suggestion for the future: If you are saving R objects to be reimported back into R later, I highly recommend using the `saveRDS`/`readRDS` functions. This will get you back the exact same R object you had before. 

Saving to file formats like with `write.csv`/`read.csv` is not guaranteed to get you exactly what you had before, in part because of various options, but also because the data formats can change when reading back in text files (e.g. from character objects to factor objects).
