### ISSUE TITLE
Issue in creating phylogenetic tree

### ISSUE THREAD

**Issue by Joishy-T** [benjjneb/dada2#913]
Hello,
I am new in this field and having trouble in analysing my data. Can anyone please suggest me what exactly is wrong in creating tree. As m getting this error after 20th days :
> fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE,
+         rearrangement = "stochastic", control = pml.control(trace = 0))
Error in optim(par = lbf, fn = fn, gr = NULL, method = "Nelder-Mead",  :
  function cannot be evaluated at initial parameters
In addition: There were 48 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In optimize(f = fn, interval = c(0.1, 500), lower = 0.1,  ... :
  NA/Inf replaced by maximum positive value
2: In optimize(f = fn, interval = c(0.1, 500), lower = 0.1,  ... :
  NA/Inf replaced by maximum positive value

Please suggest.

**Comment by benjjneb** [comment]
I'd suggest reposting this at the Issues page for the F1000 workflow paper: https://github.com/spholmes/F1000_workflow/issues

This is because the issue you are encountering is not related to the dada2 package, but to subsequent tree-building using phangorn. When reposting, please also include information on your sequencing library, and the size of the ASV table you are working with (e.g. # of ASVs).

**Comment by Joishy-T** [comment]
Dear Benjjneb,
I have reposted it in mentioned link. Please suggest.
