### ISSUE TITLE
LearnErrors based on known invariant subsequence?

### ISSUE THREAD

**Issue by jessicaaudreylee** [benjjneb/dada2#915]
Greetings! I'm hoping to use dada2 as part of a pipeline for analyzing data from an experiment using microbial cells carrying a plasmid with a 20-mer barcode that helps us distinguish cell lineages or strains. We're using Illumina to sequence the barcode and some of the surrounding plasmid sequence, and using the barcode sequences, rather than genomic DNA, to track community dynamics. Since our sequence data include a sizeable segment of the plasmid backbone, which is a known, invariant sequence, it seems that we should be able to use the sequence data covering the backbone segment to calculate error rates directly, rather than using the dada2 algorithm to estimate them... and then apply those error rates in doing sample inference on the barcode segments. Does that make sense? Would it give us any improvement in terms of either accuracy or efficiency? If so, can you recommend a way of doing it within the dada2 package, or should we plan on writing a new script of my own to generate an error rates matrix?

**Comment by benjjneb** [comment]
> Would it give us any improvement in terms of either accuracy or efficiency?

Yes it would probably give a small improvement, simply because it is typically easier to estimate the error rates in lower diversity samples than in (potentially very) high diversity barcode regions.

> If so, can you recommend a way of doing it within the dada2 package, or should we plan on writing a new script of my own to generate an error rates matrix?

The easiest way to do this would be to use a trimmed version of the sequence data that includes only the invariant sequence as the input to `learnErrors`. If simple trimming/truncating can achieve that, e.g. the invariant sequence falls in the first XX nts of the reads, then you can use `filterAndTrim` fo achieve that. Otherwise, you would probably need to use an external program to trim down to the invariant sequence.

**Comment by jessicaaudreylee** [comment]
That sounds like a very simple solution! Many thanks.
