### ISSUE TITLE
'Calloc' could not allocate memory

### ISSUE THREAD

**Issue by Debora6991** [benjjneb/dada2#920]
Hi,
I encountered this problem with the 'derepFastq' command:
Error in add(bin) : 
  'Calloc' could not allocate memory (33218645 of 1 bytes)

No problems with the forward reads, only with the Reverse ones.

Thanks in advance for the reply.

**Comment by benjjneb** [comment]
Can you give us more information on your system and dataset?

```
R.version`
packageVersion("dada2")
```

would help. Also, what kind of data is this (e.g. 2x250 Miseq V3V4)? How large (# of reads) is the sample you are trying to load into memory when it fails?

**Comment by Debora6991** [comment]
+ > > packageVersion("dada2")
[1] ‘1.12.1’
> R.version
               _
platform       x86_64-w64-mingw32
arch           x86_64
os             mingw32
system         x86_64, mingw32
status
major          3
minor          6.0
year           2019
month          04
day            26
svn rev        76424
language       R
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree

I have 88 samples (2x250 MiSeq V3V4)  with an average read number of 80000.


Il giorno gio 16 gen 2020 alle ore 18:37 Benjamin Callahan <
notifications@github.com> ha scritto:

**Comment by benjjneb** [comment]
> os             mingw32

The issue is here. You are using the 32 bit version of mingw, which is therefore restricted to addressing ~3GB of memory. This was insufficient to load your dereplicated data into memory.

The best long-term solution would be to upgrade to a 64-bit system. In most places 32-bit systems have been deprecated or defunct for years now.

If that is difficult to do, you could see if this dataset will run despite the 32-bit mode when you omit the `derepFastq` step, and simply run the commands on the file names instead (see current version of the tutorial). This will stream samples into memory, rather than loading them all at once, and could be enough to get by in this case.

If that doesn't work, you'll have to find a 64-bit system to work on though.

**Comment by Debora6991** [comment]
Thankyou for your prompt reply.
 I'll try what you suggested.

Debora

Il giorno ven 17 gen 2020 alle ore 13:27 Benjamin Callahan <
notifications@github.com> ha scritto:

**Comment by naurasd** [comment]
Hey guys,

I am kinda new to R and bioinformatics and am facing exactly the same issue as Deborah. Have been trying for hours now to find a solution. Why is R using wingw32 instead of mingw64 in the first place? I mean I have installed R default-wise for 32- and 64-bit and am running it on a 64-bit system. Both mingw32 and mingw64 files can be found in R's win library. Is there anyway I can manually make R run on the alternative to mingw32? Or could you share how you managed to upgrade if you were succesful, @Debora6991 ?

thanks so much
Nauras

**Comment by Debora6991** [comment]
I faced the same problem,  I tried to change mingw32 to mingw64 but I
failed.
My solution was to move to a computer with a bigger RAM. I believe that the
problem, at least for me, is not due to mingw but solely to the scarce RAM
memory.

Debora

**Comment by naurasd** [comment]
Ah okay. Thanks for the quick reply. I have 16 GB of RAm, actually thought this would be enough.

Cheers
Nauras
