### ISSUE TITLE
Obtain huge numbers of ASVs after Merge paired reads

### ISSUE THREAD

**Issue by dreamerfuwei** [benjjneb/dada2#921]
Hi, Benjamin:

I have encountered a problem that has been bothering me for days. I am using DADA2 to deal with some SSU data sequenced with Miseq PE300, after **Sample inference** I have dozens of sequence variants per sample (meet my expectations), but after the**Merge paired reads** and **Construct sequence table** the ASVs number increased to thousands and tens of thousands, highly out of my expectations. I have some experience in analyzing 16S and ITS data using DADA2, but I cannot figure out what is wrong with my process, please help me.

Package version: 1.14.0;
Data: paired-end sequencing data of SSU;
Expected ASVs: 100~200
Note: non-overlaping reads using mergePairs(..., justConcatenate = TRUE)

dadaFs:
![dadaFs](https://user-images.githubusercontent.com/46585709/72554047-e5eda380-38d4-11ea-9caa-f1ef738632f1.jpg)
dadaRs:
![dadaRs](https://user-images.githubusercontent.com/46585709/72554056-e84ffd80-38d4-11ea-98f7-ca867e8a713f.jpg)
dim(seqtab)
![dimseqtab](https://user-images.githubusercontent.com/46585709/72554061-ea19c100-38d4-11ea-9751-30c80bdb8ee8.jpg)

All the best wishes,
Wei Fu

**Comment by benjjneb** [comment]
What is the output of `table(colSums(seqtab>0))`? (the number of samples each merged ASV appears in).
And of `table(rowSums(seqtab>0))`? (the number of merged ASVs in each sample).

Also, have you tried running chimiera removal on this table, and if so what was the outcome in terms of ASVs/reads removed?

**Comment by dreamerfuwei** [comment]
Thank you very much for your reply!
I have run the functions you listed, both for the forward reads and paired-end merged reads. Here are the results:

**For the forward reads only:**
![forward reads](https://user-images.githubusercontent.com/46585709/72629631-a930b380-398b-11ea-8a9a-231ed769a944.jpg)

**For the paired-end merged reads:**
![Paired-end](https://user-images.githubusercontent.com/46585709/72629661-b8176600-398b-11ea-9484-7323b948a823.jpg)

You can see that the paired-end reads produced 33477 ASVs within 24 samples, but more than half of them are chimieras. However, for the forward reads, it only produced 774 ASVs and most of them are kept after chimiera removal. Moreover, both methods produced huge numbers of ASVs appear in only 1 sample. I don't know exactly the logic behind merging reads but merging has a huge effect on chimiera removal. Is non-overlapping merging decreases the accuracy of sequences? and how can sequences merge without an overlap (also for shorter ones)?

All the best wishes, and thank you very much for helping me! 

Wei Fu

**Comment by benjjneb** [comment]
What I see there is definitely cause for concern, there are too many 1-sample merged ASVs, and way too many merged reads being removed as chimeric. Since the forward reads don't show those patterns, the first thing I would do is to double-check the reverse reads for the presence of chimeras. Alternatively you could run just the reverse reads through the pipeline and examine the same output as above to see if they show patterns like the forward reads, or like the merged reads.

Merging w/o overlap can lead to more spuriuos sequences, because it lacks the enforcement of perfect overlap between the reads and just concatenates them regardless. In some cases this can yield much higher levels of spurious concatenated ASVs, although in my experience something else has gone wrong as well for that to happen (e.g. low complexity infiltrates or missed primers or something). What is the primer set used here?

I would keep open the possibility of proceeding with just the forward reads if this pattern can't be satisfactorily resolved. Usually losing a bit of resolution w/ the shorter total sequence length is preferable to introducing lots of spurious variation via some yet unresolved process.

**Comment by dreamerfuwei** [comment]
Thank you very much for your kind reply! 

I think the reason that my data have so many chimeras is that I used nested PCR (Common procedure to exclude other fungi in the first PCR) in the amplification (Although I used Phusion polymerase).  I rechecked the primer length against the database, I use WANDA/AML2 primers to study arbuscular mycorrhizal fungi,  this primer generating a 550±5 bp (with primer) fragment of the SSU rRNA region. So in this case, I will have enough overlap to merge the reads. 

I have tried the reverse reads and the results are in the blew:
![Reverse reads](https://user-images.githubusercontent.com/46585709/72672201-b0da8000-3a91-11ea-863c-876df74ea6c9.jpg)
you see the reverse reads have little more chimieras, but relatively few ASVs compared to the forward reads.

I use mergePairs(...minOverlap = 20) to merge the forward and reverse reads (I have  tightened the maxEE because I cannot truncation the reads):
Reads quality:
![Rplot](https://user-images.githubusercontent.com/46585709/72672649-234e5e80-3a98-11ea-83c9-47c1a1bc01a3.jpeg)
Results:
![minoverlap20](https://user-images.githubusercontent.com/46585709/72672466-7b379600-3a95-11ea-92db-f938ee748ee2.jpg)
There are 5598 chimeras out of 6800 ASVs, and about 32% of reads are chimeras. Because I have removed the primers and barcode, the target fragment length is 480-490, seqtab[ ,nchar(colnames(seqtab)) %in% 480:490] could be used to obtain the fragment.

Still, I am not sure in my case so many merged reads being removed as chimeric is appropriate for downstream analysis?

Thank you again, and all the best wishes!
Wei Fu

**Comment by microb123** [comment]
Hi,

I ran through the same issue of high number of ASVs after merged paired reads. Normally we do not used to see such high number. All sample expect one (~70%) has more than 90% of merged sequence reads retained as nonchimeric. I am wondering is there anything wrong going through my sample as it is showing high number of ASVs?
Also, would you please help me to understand the table generated by table(colSums(seqtab>0))? If this code gives the number of samples each merged ASV appear in, then since I have 131 samples that means there should be at least one merged sequence in 131 samples, but the table has only upto 129 (last column of the table).

Thank you

<img width="1448" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/104597614/165886422-4a5ac9ff-686d-4630-bf79-760bc4596622.png">
<img width="1455" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/104597614/165886441-0ec611a0-bebb-4f3c-ac25-bf972e960fd6.png">

**Comment by microb123** [comment]
Hi,

I ran through the same issue of high number of ASVs after merged paired reads. Normally we do not used to see such high number. All sample expect one (~70%) has more than 90% of merged sequence reads retained as nonchimeric. I am wondering is there anything wrong going through my sample as it is showing high number of ASVs?
Also, would you please help me to understand the table generated by table(colSums(seqtab>0))? If this code gives the number of samples each merged ASV appear in, then since I have 131 samples that means there should be at least one merged sequence in 131 samples, but the table has only upto 129 (last column of the table).

Thank you

<img width="1448" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/104597614/165887279-f2879192-1f99-4f6d-9f35-e47445c89294.png">
<img width="1455" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/104597614/165887292-801856ff-7a66-4c93-9633-a94371e31e57.png">

**Comment by microb123** [comment]
Hi,

I ran through the same issue of high number of ASVs after merged paired reads. Normally we do not used to see such high number. All sample expect one (~70%) has more than 90% of merged sequence reads retained as nonchimeric. I am wondering is there anything wrong going through my sample as it is showing high number of ASVs?
Also, would you please help me to understand the table generated by table(colSums(seqtab>0))? If this code gives the number of samples each merged ASV appear in, then since I have 131 samples that means there should be at least one merged sequence in 131 samples, but the table has only upto 129 (last column of the table).
We are sequencing V3-V4 16S rRNA using a illumina MiSeq generating 300bp paired end reads.

Thank you
<img width="1448" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/104597614/165887762-3d53fdcc-d769-405f-af61-e74548d4850f.png">
<img width="1455" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/104597614/165887775-9f58d1ef-294a-49ae-8446-f3693d19c3e4.png">

**Comment by microb123** [comment]
Hi Wei,

I have fewer fecal samples this time than the previous. Regarding per samples ASV, I think we can't compare between two experiment as this time mice were under antibiotics and different diet as compare to previous where we didn't manipulated any of those things. While I was working with output, I notice more than the half of the ASVs were actually present one per sample. 
Removing those ASVs that were present only in single sample now I have around 2200 ASVs which I think is similar to what we used to see previously. 

<img width="589" alt="Screen Shot 2022-05-03 at 4 27 55 PM" src="https://user-images.githubusercontent.com/104597614/167045950-57f6ba5b-6499-4ad2-8d36-f26bb0c3ee50.png">

Thank you once again Wei for your input in my query.

**Comment by microb123** [comment]
Hi Wei,

I have fewer fecal samples this time than the previous. Regarding per samples ASV, I think we can't compare between two experiment as this time mice were under antibiotics and different diet as compare to previous where we didn't manipulated any of those things. While I was working with output, I notice more than the half 
<img width="556" alt="Screen Shot 2022-05-03 at 4 27 55 PM" src="https://user-images.githubusercontent.com/104597614/167047496-cbcd07ce-6711-48bb-a9a7-0763c8d2e76a.png">
of the ASVs were actually present one per sample. Removing those ASVs that were present only in single sample now I have around 2200 ASVs which I think is similar to what we used to see previously.
Thank you for your input in my query.

**Comment by microb123** [comment]
Hi Wei,

I have fewer fecal samples this time than the previous. Regarding per samples ASV, I think we can't compare between two experiment as this time mice were under antibiotics and different diet as compare to previous where we didn't manipulated any of those things. While I was working with output, I notice more than the half of the ASVs were actually present one per sample.
Removing those ASVs that were present only in single sample now I have around 2200 ASVs which I think is similar to what we used to see previously.

Thank you for your input in my query.

<img width="556" alt="Screen Shot 2022-05-03 at 4 27 55 PM" src="https://user-images.githubusercontent.com/104597614/167047877-e753b634-611d-4d8a-86cc-e3629650bbc5.png">

**Comment by dreamerfuwei** [comment]
Hi there,

I don't think simply removing the singletons is a good solution. I don't know if you analyze the faecal samples together with the previous ones, if you are not, then I suggest you analyze the data together and compare the results afterwards. I am not an expert on gut microbial communities, is there any theory that can explain your results? For example, the antibiotic treatment would decline the abundant taxon in the community that releases the rare species out of the competitive environment. Another approach is that you can analyze your data using other pipelines, for example, UPARSE, and then compare the results with DADA2. If you obtain similar results from UPARSE and DADA2, I think this is not a matter of the methods.

All the best, 
Wei
