### ISSUE TITLE
Declining read lengths resulting in V poor merging

### ISSUE THREAD

**Issue by justingdbyrne** [benjjneb/dada2#942]
Hello, 

I am working with 16S  paired-end MiSeq V600 sequencing with 515F-806R primers. The files have been de-multiplexed in MetaBeat, I think I have indicated that there should be no automatic trimming in the query map. Then run thorough DADA2. 

I got this declining read length and got worried.  I thought the issue may be to do with poor primer removal (not all primers were removed by metabeat so I took out that step in metabeat. Now I have re-run it and removed the primers with cutadapt and that helped a little, but the declining read length remains. This makes me think that the problem isn't to do with cutadapt.

From your experience, what do quality profiles like this indicate? 

Might it be an issue with the library setup? The MiSeq run? The metabeat processing?

The quality scores seem fine up to the 200 mark, is that a clue for something...

I have analysed the data that exists, it's 16S bacterial, all what is expected. I just lose half of my reads in mergeing and so worry about how this will affect the biodiversity measures of my samples.

[16_Squalityplots.pdf](https://github.com/benjjneb/dada2/files/4185466/16_Squalityplots.pdf)

**Comment by jgrzadziel** [comment]
@justingdbyrne 
What were the analysis parameters ?
How many bases have you trimmed (especially from the right) ?

In my experience, using 2x300PE technology has no benefit over 2x250PE. 

That is because the last 50 bases are usual poor quality and have to be trimmed. Using 2x250 I usually trim 5-10 last bases, but mostly there is no such need.

Based on your quality plot, I would try to trim forward reads to 230 and reverse reads to 200 bp and then run the analysis.

Additionally, there is no need to use cutadapt to remove primers, in your sequencing. It would be enough to trim them, like in tutorial.

**Comment by justingdbyrne** [comment]
I have adapted the script from the ITS one as I thought the issue may have been poor primer removal. I don't think I am doing any other trimming yet. When I ran the default DADA2 bacterial protocol things were a little worse. 

This is how I filter and trim: 
```
filterAndTrim(fnFs, fnFs.filtN, fnRs,
              fnRs.filtN, maxN = 0, multithread = TRUE)
```
this is how I am running cutadapt:
```
FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)
# Trim FWD and the reverse-complement of REV off of R1 (forward reads)
R1.flags <- paste("-g", FWD, "-a", REV.RC) 
# Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
R2.flags <- paste("-G", REV, "-A", FWD.RC) 
# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2("cutadapt", args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                               "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                               fnFs.filtN[i], fnRs.filtN[i])) # input files
}
```

I am comfortable deciding a trim length.

My issue is why my read length is so short in half of the samples? Why this steady decline?
Is this what has caused me losing 50% of my reads at merging? Why would it look like this when 515F and 806R should not be a very variable read length region?

Does anyone have any advice as to what might be causing this? Has anyone seen anything like it before?


> @justingdbyrne
> What were the analysis parameters ?
> How many bases have you trimmed (especially from the right) ?
> 
> In my experience, using 2x300PE technology has no benefit over 2x250PE.
> 
> That is because the last 50 bases are usual poor quality and have to be trimmed. Using 2x250 I usually trim 5-10 last bases, but mostly there is no such need.
> 
> Based on your quality plot, I would try to trim forward reads to 230 and reverse reads to 200 bp and then run the analysis.
> 
> Additionally, there is no need to use cutadapt to remove primers, in your sequencing. It would be enough to trim them, like in tutorial.

**Comment by benjjneb** [comment]
> Does anyone have any advice as to what might be causing this? Has anyone seen anything like it before?

It's almost certainly caused by the MetaBeat step, which is probably doing some truncating of the reads by default based on a quality threshold. The Readme indicates that it will be truncating reads by default based on certain quality score cues: https://github.com/HullUni-bioinformatics/metaBEAT

You can confirm this by looking at the quality score/length distro prior to MetaBeat processing, where you will probably see everything is the same length.

**Comment by justingdbyrne** [comment]
Thanks @benjjneb I'll look into that as soon as I can. Have you seen anything like this before?

> > Does anyone have any advice as to what might be causing this? Has anyone seen anything like it before?
> 
> It's almost certainly caused by the MetaBeat step, which is probably doing some truncating of the reads by default based on a quality threshold. The Readme indicates that it will be truncating reads by default based on certain quality score cues: https://github.com/HullUni-bioinformatics/metaBEAT
> 
> You can confirm this by looking at the quality score/length distro prior to MetaBeat processing, where you will probably see everything is the same length.
