### ISSUE TITLE
Set default minLen=50 to match assignTaxonomy

### ISSUE THREAD

**Issue by and3k** [benjjneb/dada2#955]
Hi!

IMHO, it would make sense to increase the [default value of `minLen`](https://github.com/benjjneb/dada2/blob/82f4660b450038413e169a5a8e6a8b103fa0e067/R/filter.R#L291) in `filterAndTrim` to `50`, as this is the [minimum sequence length required by `assignTaxonomy`](https://github.com/benjjneb/dada2/blob/963f4e023023bc528177a2c04ab7f1ae5332461c/src/taxonomy.cpp#L182).

Keep up the great work! :)

Thanks!
Bela

**Comment by benjjneb** [comment]
Would it be better yet to be more graceful about how short sequences are dealt with by `assignTaxonomy`?

In particular, it seems preferable for `assignTaxonomy` to just skip assignment (with a message) on short sequences, rather than stopping the `assignTaxonomy` process entirely with a hard error as we do now.

**Comment by and3k** [comment]
Yes, that would work too. :)

**Comment by and3k** [comment]
Excellent, thanks!
