### ISSUE TITLE
assignTaxonomy failing

### ISSUE THREAD

**Issue by kiti15237** [benjjneb/dada2#99]
Hello!

I'm trying to use dada2 in conjunction with picrust, which means when assigning taxonomy I want to assign OTU ids (1380474) rather than names(k__Archaea;p__Euryarchaeota;c__Methanobacteria). I have a fasta file from the greengenes database that maps the ids to reads, but when I try to run assignTaxonomy() using this file, the process freezes and never finishes.

File that does work from dada2 tutorial page:    gg_13_8_train_set_97.fa.gz
File that does NOT work from green genes: gg_13_8_97_otus.fasta

They are both about the same size, and I have tried running on a cluster with loads of memory, with the same result. 

Any idea where the issue could lie?

Thanks so much,
Christine

**Comment by benjjneb** [comment]
The assignTaxonomy function isn't designed for making a single best assignment to a GG OTU. I also believe that Picrust is built on the GG 13.5 release, rather than 13.8.

The best course of action would be to output the sequence variants inferred by dada2, and then use either blast or something like uclust to assign them to GG OTUs. The `uniquesToFasta` function will help with this:

```{r}
uniquesToFasta(seqtab, "my_dada2_sequence.fasta")
```
